### ISSUE TITLE
Downloading pictures directly to RAM instead of disk?

### ISSUE THREAD

**Issue by nah0y** [gphoto/gphoto2#101]
Hello,

Is there such a feature available?
That would be pretty useful for different scenarios where we just want to send back the image somewhere via a web server or other things for example.
It would just skip writing to disk and the reading from disk, which can be slow...

Thanks!

**Comment by msmeissn** [comment]
The library loads it to RAM first unless you use the fd method?

For the commandline tool ... you can use --stdout for output, otherwise how would you get it out of the ram?

**Comment by nah0y** [comment]
I don't know how I could get it out of the ram :)
But stdout looks exactly what I need, I didn't saw that before!

I'll give it a try thanks!

**Comment by nah0y** [comment]
Yes this is working great, thanks :)
