### ISSUE TITLE
Difference between --get-raw-data and --get-file?

### ISSUE THREAD

**Issue by nah0y** [gphoto/gphoto2#102]
Hello,

I just don't really understand what's the difference between getting a file or getting it's raw data?
I mean... a picture is already raw data?
Plus when I use get-raw-data or get-file I have the same result.

Thanks.

**Comment by msmeissn** [comment]
This method was largely for cameras which had non-JPEG image storage and some form of RAW format. These days just use get-file for modern cameras.
