### ISSUE TITLE
Failed to load driver: file not found. But the file is here...

### ISSUE THREAD

**Issue by nah0y** [gphoto/gphoto2#103]
Hello,

Whenever I display the debug log, I can see these 3 logs:
```
0.170047 gp_abilities_list_load_dir  (2): Failed to load '/usr/lib/libgphoto2/2.5.10/ax203': file not found.
0.623183 gp_abilities_list_load_dir  (2): Failed to load '/usr/lib/libgphoto2/2.5.10/st2205': file not found.
0.677297 gp_abilities_list_load_dir  (2): Failed to load '/usr/lib/libgphoto2/2.5.10/tp6801': file not found.
```

But 10-20 logs before, I have this:
```
0.113992 foreach_func                (2): Found '/usr/lib/libgphoto2/2.5.10/ax203'.
0.159247 foreach_func                (2): Found '/usr/lib/libgphoto2/2.5.10/st2205'.
0.161887 foreach_func                (2): Found '/usr/lib/libgphoto2/2.5.10/tp6801'.
```

So first it says it found the files, and then it says the file is not found :/
Plus yes, the files are really there.

And I think this particular thing is taking a lot of time and slow down my entire processes, because the logs goes from 0.67s to 2.05s for the next entry:
```
0.170047 gp_abilities_list_load_dir  (2): Failed to load '/usr/lib/libgphoto2/2.5.10/ax203': file not found.
0.623183 gp_abilities_list_load_dir  (2): Failed to load '/usr/lib/libgphoto2/2.5.10/st2205': file not found.
0.677297 gp_abilities_list_load_dir  (2): Failed to load '/usr/lib/libgphoto2/2.5.10/tp6801': file not found.
2.051357 gp_port_info_list_count     (2): Counting entries (10 available)...
```

So I would really like to fix this :p

Thanks!

**Comment by msmeissn** [comment]
what does:

ls /usr/lib/libgphoto2/2.5.10/ax203*

show for type of ax203 files?

**Comment by nah0y** [comment]
root@OpenWrt:~# ls /usr/lib/libgphoto2/2.5.10/ax203*
/usr/lib/libgphoto2/2.5.10/ax203.so

**Comment by msmeissn** [comment]
what does ldd /usr/lib/libgphoto2/2.5.10/ax203.so
report.... it seems the driver file is there, but is not loadable for some reason

**Comment by nah0y** [comment]
root@OpenWrt:~# ldd /usr/lib/libgphoto2/2.5.10/ax203.so 
Segmentation fault

**Comment by msmeissn** [comment]
sorry for not replying, but this looks like a disk corruption issue.

i hope it fixed itself, sorry for not following up
