### ISSUE TITLE
capturetarget not found in the configuration tree

### ISSUE THREAD

**Issue by mrcmbr** [gphoto/gphoto2#104]
Hello,

i'm trying to build a remote timelapse camera project. I hoocked up my sony a7rII to a raspberry pi, which will control it. What i would like to do is take pictures and have them automatically uploaded via FTP or othe protocols to my server. What i would like to accomplish with gphoto2 is taking the picture and having the files stored in a folder in the raspberry pi untill it gets uploaded to the server. My plan is to write a python script once i find out how i can make the bash commands work.

I see that gphoto2 recognises the camera and is able to take pictures but when i run 
`gphoto2 --list-files`
it returns that there's no file in folder ´/´.

And when i run 
`gphoto2 -get-config capturetarget`
it returns: capturetarget not found in the configuration tree

Do you have any idea how i can have the pictures stored in a local folder?

Thank you in advance for your help!

Marco

**Comment by msmeissn** [comment]
There is no capturetarget setting for Sony, as it onyl supports capture to SDRAM for immediate download.

gphoto2 --capture-image-and-download   

for immediate download here.

**Comment by mrcmbr** [comment]
thank yo so much, i have another question. Apparently the camera is naming each capture with the same name so when i take a second picture it asks me if i want to overwrite the previous one. 
I checked the camera but the filenaming options are disabled when the usb mode is set to "PC"
Again, thank you so much for your help and work :)

**Comment by mrcmbr** [comment]
I solved this in my python script, thanks!

**Comment by msmeissn** [comment]
there is a --filename option which can give out timebased filenames for instance. not optimal, but its good you found a solution!

**Comment by dast7484** [comment]
> I solved this in my python script, thanks!

How did you solve this? I am having the same issue.

**Comment by ma12-co** [comment]
hello @dast7484 , [this is how i solved it ](https://github.com/ma12-co/remote-timelapse-camera/blob/master/timelapse.py)!
hope it helps

Marco

**Comment by dast7484** [comment]
Thank you! @ma12-co
