### ISSUE TITLE
Sony alpha-6000 Could not detect any camera  *** Error (-105: 'Unknown model') *** 

### ISSUE THREAD

**Issue by gbonjovi** [gphoto/gphoto2#105]
Hello：
Could not detect any camera，
my system is Raspbian GNU/Linux 8.0 (jessie)
Linux raspberrypi 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l GNU/Linux

below display debug log：

0.000800 main                        (2): ALWAYS INCLUDE THE FOLLOWING LINES WHEN SENDING DEBUG MESSAGES TO THE MAILING LIST:
0.000889 main                        (2): gphoto2 2.5.15
0.000979 main                        (2): gphoto2 has been compiled with the following options:
0.001009 main                        (2):  + gcc (C compiler used)
0.001034 main                        (2):  + popt (mandatory, for handling command-line parameters)
0.001058 main                        (2):  + exif (for displaying EXIF information)
0.001082 main                        (2):  + no cdk (for accessing configuration options)
0.001106 main                        (2):  + no aa (for displaying live previews)
0.001129 main                        (2):  + no jpeg (for displaying live previews in JPEG format)
0.001154 main                        (2):  + no readline (for easy navigation in the shell)
0.001272 main                        (2): libgphoto2 2.5.16
0.001312 main                        (2): libgphoto2 has been compiled with the following options:
0.001356 main                        (2):  + all camlibs
0.001397 main                        (2):  + gcc (C compiler used)
0.001418 main                        (2):  + ltdl (for portable loading of camlibs)
0.001437 main                        (2):  + no EXIF (for special handling of EXIF files)
0.001503 main                        (2): libgphoto2_port 0.12.0
0.001562 main                        (2): libgphoto2_port has been compiled with the following options:
0.001592 main                        (2):  + iolibs: disk ptpip serial
0.001614 main                        (2):  + gcc (C compiler used)
0.001658 main                        (2):  + ltdl (for portable loading of iolibs)
0.001700 main                        (2):  + no USB (for USB cameras)
0.001744 main                        (2):  + serial (for serial cameras)
0.001777 main                        (2):  + no resmgr (serial port access and locking)
0.001815 main                        (2):  + no ttylock (serial port locking)
0.001859 main                        (2):  + no lockdev (serial port locking)
0.001884 main                        (2): CAMLIBS env var not set, using compile-time default instead
0.001934 main                        (2): IOLIBS env var not set, using compile-time default instead
0.001955 main                        (2): invoked with following arguments:
0.001997 main                        (2):   --debug
0.002016 main                        (2):   -L
0.002256 load_settings               (2): Creating gphoto config directory ('/root/.gphoto')
0.002408 verify_settings             (2): Can't open settings file '/root/.gphoto/settings' for reading.
0.002465 load_settings               (2): Loading settings from file '/root/.gphoto/settings'.
0.002523 load_settings               (2): Can't open settings file '/root/.gphoto/settings' for reading.
0.002552 load_settings               (2): Creating gphoto config directory ('/root/.gphoto')
0.002640 verify_settings             (2): Can't open settings file '/root/.gphoto/settings' for reading.
0.002693 load_settings               (2): Loading settings from file '/root/.gphoto/settings'.
0.002735 load_settings               (2): Can't open settings file '/root/.gphoto/settings' for reading.
0.003322 main                        (2): The user has not specified both a model and a port. Try to figure them out.
0.003384 gp_port_info_list_load      (2): Using ltdl to load io-drivers from '/usr/local/lib/libgphoto2_port/0.12.0'...
0.003742 foreach_func                (2): Called for filename '/usr/local/lib/libgphoto2_port/0.12.0/disk'.
0.004740 gp_port_library_list        (2): found fstab fsname proc
0.004792 gp_port_library_list        (2): found fstab fsname /dev/mmcblk0p1
0.004877 gp_port_library_list        (2): found fstab fsname /dev/mmcblk0p2
0.005260 gp_port_library_list        (2): found mtab fsname /dev/root
0.005319 gp_port_library_list        (2): found mtab fsname devtmpfs
0.005360 gp_port_library_list        (2): found mtab fsname sysfs
0.005392 gp_port_library_list        (2): found mtab fsname proc
0.005426 gp_port_library_list        (2): found mtab fsname tmpfs
0.005493 gp_port_library_list        (2): found mtab fsname devpts
0.005531 gp_port_library_list        (2): found mtab fsname tmpfs
0.005594 gp_port_library_list        (2): found mtab fsname tmpfs
0.005664 gp_port_library_list        (2): found mtab fsname tmpfs
0.005749 gp_port_library_list        (2): found mtab fsname cgroup
0.005786 gp_port_library_list        (2): found mtab fsname cgroup
0.005819 gp_port_library_list        (2): found mtab fsname cgroup
0.005853 gp_port_library_list        (2): found mtab fsname cgroup
0.005886 gp_port_library_list        (2): found mtab fsname cgroup
0.006020 gp_port_library_list        (2): found mtab fsname cgroup
0.006056 gp_port_library_list        (2): found mtab fsname cgroup
0.006091 gp_port_library_list        (2): found mtab fsname systemd-1
0.006125 gp_port_library_list        (2): found mtab fsname mqueue
0.006158 gp_port_library_list        (2): found mtab fsname debugfs
0.006240 gp_port_library_list        (2): found mtab fsname configfs
0.006324 gp_port_library_list        (2): found mtab fsname fusectl
0.006360 gp_port_library_list        (2): found mtab fsname /dev/mmcblk0p1
0.006425 gp_port_library_list        (2): found mtab fsname tmpfs
0.006499 gp_port_library_list        (2): found mtab fsname gvfsd-fuse
0.006665 foreach_func                (2): Loaded '' ('^disk:') from '/usr/local/lib/libgphoto2_port/0.12.0/disk'.
0.006700 foreach_func                (2): Called for filename '/usr/local/lib/libgphoto2_port/0.12.0/ptpip'.
0.007537 foreach_func                (2): Loaded 'PTP/IP Connection' ('ptpip:') from '/usr/local/lib/libgphoto2_port/0.12.0/ptpip'.
0.007577 foreach_func                (2): Loaded '' ('^ptpip:') from '/usr/local/lib/libgphoto2_port/0.12.0/ptpip'.
0.007607 foreach_func                (2): Called for filename '/usr/local/lib/libgphoto2_port/0.12.0/serial'.
0.008604 foreach_func                (2): Loaded 'Serial Port 0' ('serial:/dev/ttyS0') from '/usr/local/lib/libgphoto2_port/0.12.0/serial'.
0.008645 foreach_func                (2): Loaded 'Serial Port Device' ('serial:') from '/usr/local/lib/libgphoto2_port/0.12.0/serial'.
0.008677 foreach_func                (2): Loaded '' ('^serial:') from '/usr/local/lib/libgphoto2_port/0.12.0/serial'.
0.008758 gp_port_info_list_count     (2): Counting entries (6 available)...
0.008785 gp_port_info_list_count     (2): 3 regular entries available.
0.008862 gp_abilities_list_load_dir  (2): Using ltdl to load camera libraries from '/usr/local/lib/libgphoto2/2.5.16'...
0.011260 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/adc65'.
0.011340 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/agfa_cl20'.
0.011369 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/aox'.
0.011395 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/ax203'.
0.011421 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/barbie'.
0.011446 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/canon'.
0.011472 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/casio_qv'.
0.011497 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/clicksmart310'.
0.011523 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/digigr8'.
0.011548 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/digita'.
0.011573 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/dimagev'.
0.011599 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/dimera3500'.
0.011625 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/directory'.
0.011649 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/enigma13'.
0.011675 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/fuji'.
0.011700 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/gsmart300'.
0.011725 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/hp215'.
0.011750 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/iclick'.
0.011775 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/jamcam'.
0.011800 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/jd11'.
0.011825 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/jl2005a'.
0.011851 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/jl2005c'.
0.011876 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/kodak_dc120'.
0.011900 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/kodak_dc210'.
0.011926 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/kodak_dc240'.
0.011951 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/kodak_dc3200'.
0.011977 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/kodak_ez200'.
0.012002 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/konica'.
0.012027 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/konica_qm150'.
0.012052 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/largan'.
0.012077 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/lg_gsm'.
0.012102 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/mars'.
0.012126 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/mustek'.
0.012151 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/panasonic_coolshot'.
0.012177 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/panasonic_dc1000'.
0.012203 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/panasonic_dc1580'.
0.012228 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/panasonic_l859'.
0.012254 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/pccam300'.
0.012279 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/pccam600'.
0.012304 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/pentax'.
0.012329 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/polaroid_pdc320'.
0.012354 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/polaroid_pdc640'.
0.012379 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/polaroid_pdc700'.
0.012404 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/ptp2'.
0.012429 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/ricoh'.
0.012454 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/ricoh_g3'.
0.012479 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/samsung'.
0.012504 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/sierra'.
0.012529 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/sipix_blink2'.
0.012554 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/sipix_web2'.
0.012579 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/smal'.
0.012604 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/sonix'.
0.012629 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/sony_dscf1'.
0.012654 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/sony_dscf55'.
0.012679 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/soundvision'.
0.012705 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/spca50x'.
0.012730 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/sq905'.
0.012755 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/st2205'.
0.012780 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/stv0674'.
0.012805 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/stv0680'.
0.012829 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/sx330z'.
0.012854 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/topfield'.
0.012879 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/toshiba_pdrm11'.
0.012904 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/tp6801'.
0.012952 gp_abilities_list_load_dir  (2): Found 64 camera drivers.
0.106420 gp_port_info_list_count     (2): Counting entries (6 available)...    
0.106488 gp_port_info_list_count     (2): 3 regular entries available.
0.106504 gp_port_new                 (2): Creating new device...
0.106541 gp_port_info_list_get_info  (2): Getting info of entry 0 (6 available)...
0.107061 gp_port_set_settings        (2): Setting settings...
0.107087 gp_port_info_list_get_info  (2): Getting info of entry 1 (6 available)...
0.107367 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.107382 gp_port_set_settings        (2): Setting settings...
0.107399 gp_port_info_list_get_info  (2): Getting info of entry 2 (6 available)...
0.107650 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.107665 gp_port_set_settings        (2): Setting settings...
0.107685 gp_port_free                (2): Freeing port...
0.107698 gp_port_close               (2): Closing port...
0.107726 gp_port_serial_close [unix.c:465](0): Invalid parameters: 'path' is NULL/FALSE.
0.107779 load_settings               (2): Creating gphoto config directory ('/root/.gphoto')
0.107819 verify_settings             (2): Can't open settings file '/root/.gphoto/settings' for reading.
0.107833 load_settings               (2): Loading settings from file '/root/.gphoto/settings'.
0.107852 load_settings               (2): Can't open settings file '/root/.gphoto/settings' for reading.
0.107867 load_settings               (2): Creating gphoto config directory ('/root/.gphoto')
0.107891 verify_settings             (2): Can't open settings file '/root/.gphoto/settings' for reading.
0.107904 load_settings               (2): Loading settings from file '/root/.gphoto/settings'.
0.107922 load_settings               (2): Can't open settings file '/root/.gphoto/settings' for reading.
0.107939 gp_camera_init              (2): Initializing camera...
0.107953 gp_camera_init              (2): Neither port nor model set. Trying auto-detection...
0.107977 gp_abilities_list_load_dir  (2): Using ltdl to load camera libraries from '/usr/local/lib/libgphoto2/2.5.16'...
0.109151 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/adc65'.
0.109169 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/agfa_cl20'.
0.109183 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/aox'.
0.109196 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/ax203'.
0.109209 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/barbie'.
0.109222 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/canon'.
0.109234 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/casio_qv'.
0.109247 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/clicksmart310'.
0.109259 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/digigr8'.
0.109272 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/digita'.
0.109284 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/dimagev'.
0.109297 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/dimera3500'.
0.109310 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/directory'.
0.109322 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/enigma13'.
0.109335 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/fuji'.
0.109347 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/gsmart300'.
0.109360 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/hp215'.
0.109372 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/iclick'.
0.109385 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/jamcam'.
0.109397 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/jd11'.
0.109410 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/jl2005a'.
0.109423 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/jl2005c'.
0.109435 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/kodak_dc120'.
0.109448 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/kodak_dc210'.
0.109460 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/kodak_dc240'.
0.109473 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/kodak_dc3200'.
0.109486 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/kodak_ez200'.
0.109498 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/konica'.
0.109511 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/konica_qm150'.
0.109523 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/largan'.
0.109536 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/lg_gsm'.
0.109548 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/mars'.
0.109560 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/mustek'.
0.109573 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/panasonic_coolshot'.
0.109585 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/panasonic_dc1000'.
0.109598 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/panasonic_dc1580'.
0.109611 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/panasonic_l859'.
0.109624 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/pccam300'.
0.109636 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/pccam600'.
0.109649 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/pentax'.
0.109661 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/polaroid_pdc320'.
0.109674 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/polaroid_pdc640'.
0.109687 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/polaroid_pdc700'.
0.109700 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/ptp2'.
0.109713 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/ricoh'.
0.109725 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/ricoh_g3'.
0.109738 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/samsung'.
0.109750 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/sierra'.
0.109763 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/sipix_blink2'.
0.109776 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/sipix_web2'.
0.109788 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/smal'.
0.109801 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/sonix'.
0.109813 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/sony_dscf1'.
0.109826 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/sony_dscf55'.
0.109838 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/soundvision'.
0.109851 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/spca50x'.
0.109863 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/sq905'.
0.109876 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/st2205'.
0.109888 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/stv0674'.
0.109901 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/stv0680'.
0.109913 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/sx330z'.
0.109926 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/topfield'.
0.109938 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/toshiba_pdrm11'.
0.109951 foreach_func                (2): Found '/usr/local/lib/libgphoto2/2.5.16/tp6801'.
0.109971 gp_abilities_list_load_dir  (2): Found 64 camera drivers.
0.171022 gp_port_info_list_load      (2): Using ltdl to load io-drivers from '/usr/local/lib/libgphoto2_port/0.12.0'...
0.171260 foreach_func                (2): Called for filename '/usr/local/lib/libgphoto2_port/0.12.0/disk'.
0.171808 gp_port_library_list        (2): found fstab fsname proc
0.171839 gp_port_library_list        (2): found fstab fsname /dev/mmcblk0p1
0.171888 gp_port_library_list        (2): found fstab fsname /dev/mmcblk0p2
0.172171 gp_port_library_list        (2): found mtab fsname /dev/root
0.172212 gp_port_library_list        (2): found mtab fsname devtmpfs
0.172244 gp_port_library_list        (2): found mtab fsname sysfs
0.172272 gp_port_library_list        (2): found mtab fsname proc
0.172302 gp_port_library_list        (2): found mtab fsname tmpfs
0.172352 gp_port_library_list        (2): found mtab fsname devpts
0.172386 gp_port_library_list        (2): found mtab fsname tmpfs
0.172421 gp_port_library_list        (2): found mtab fsname tmpfs
0.172476 gp_port_library_list        (2): found mtab fsname tmpfs
0.172536 gp_port_library_list        (2): found mtab fsname cgroup
0.172554 gp_port_library_list        (2): found mtab fsname cgroup
0.172581 gp_port_library_list        (2): found mtab fsname cgroup
0.172605 gp_port_library_list        (2): found mtab fsname cgroup
0.172622 gp_port_library_list        (2): found mtab fsname cgroup
0.172728 gp_port_library_list        (2): found mtab fsname cgroup
0.172747 gp_port_library_list        (2): found mtab fsname cgroup
0.172764 gp_port_library_list        (2): found mtab fsname systemd-1
0.172781 gp_port_library_list        (2): found mtab fsname mqueue
0.172797 gp_port_library_list        (2): found mtab fsname debugfs
0.172863 gp_port_library_list        (2): found mtab fsname configfs
0.172930 gp_port_library_list        (2): found mtab fsname fusectl
0.172960 gp_port_library_list        (2): found mtab fsname /dev/mmcblk0p1
0.173013 gp_port_library_list        (2): found mtab fsname tmpfs
0.173053 gp_port_library_list        (2): found mtab fsname gvfsd-fuse
0.173152 foreach_func                (2): Loaded '' ('^disk:') from '/usr/local/lib/libgphoto2_port/0.12.0/disk'.
0.173169 foreach_func                (2): Called for filename '/usr/local/lib/libgphoto2_port/0.12.0/ptpip'.
0.173508 foreach_func                (2): Loaded 'PTP/IP Connection' ('ptpip:') from '/usr/local/lib/libgphoto2_port/0.12.0/ptpip'.
0.173528 foreach_func                (2): Loaded '' ('^ptpip:') from '/usr/local/lib/libgphoto2_port/0.12.0/ptpip'.
0.173544 foreach_func                (2): Called for filename '/usr/local/lib/libgphoto2_port/0.12.0/serial'.
0.174041 foreach_func                (2): Loaded 'Serial Port 0' ('serial:/dev/ttyS0') from '/usr/local/lib/libgphoto2_port/0.12.0/serial'.
0.174062 foreach_func                (2): Loaded 'Serial Port Device' ('serial:') from '/usr/local/lib/libgphoto2_port/0.12.0/serial'.
0.174078 foreach_func                (2): Loaded '' ('^serial:') from '/usr/local/lib/libgphoto2_port/0.12.0/serial'.
0.174109 gp_port_info_list_count     (2): Counting entries (6 available)...
0.174122 gp_port_info_list_count     (2): 3 regular entries available.
0.174134 gp_port_new                 (2): Creating new device...
0.174153 gp_port_info_list_get_info  (2): Getting info of entry 0 (6 available)...
0.174377 gp_port_set_settings        (2): Setting settings...
0.174394 gp_port_info_list_get_info  (2): Getting info of entry 1 (6 available)...
0.174648 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.174664 gp_port_set_settings        (2): Setting settings...
0.174680 gp_port_info_list_get_info  (2): Getting info of entry 2 (6 available)...
0.174929 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.174944 gp_port_set_settings        (2): Setting settings...
0.174958 gp_port_free                (2): Freeing port...
0.175008 gp_port_close               (2): Closing port...
0.175030 gp_port_serial_close [unix.c:465](0): Invalid parameters: 'path' is NULL/FALSE.
0.176276 gp_context_error            (0): Could not detect any camera

*** Error ***              
Could not detect any camera
*** Error (-105: 'Unknown model') ***       

0.177543 gp_camera_free              (2): Freeing camera...
0.177557 gp_port_free                (2): Freeing port...
0.177576 gp_filesystem_reset         (2): resetting filesystem
0.177587 gp_filesystem_lru_clear     (2): Clearing fscache LRU list...
0.177599 gp_filesystem_lru_clear     (2): fscache LRU list already empty
0.177611 delete_all_folders          (2): Internally deleting all folders from '/'...
0.177624 lookup_folder               (2): Lookup folder '/'...
0.177636 lookup_folder               (2): Found! / is 0x1106b20
0.177648 recurse_delete_folder       (2): Recurse delete folder 0x1106b20//

How to solve，cloud anybody help me.

**Comment by msmeissn** [comment]
0.001700 main (2): + no USB (for USB cameras)
there is no USB support built in.

You need to build libgphoto2 with libusb 1 development headers installed.
