### ISSUE TITLE
gphoto2 with the Sony A99, not possible keep the pictures or only the ARW on Camera

### ISSUE THREAD

**Issue by zahu69** [gphoto/gphoto2#108]
Hello
I have a Problem with my Sony A99. I can only remote control the Camera when i make the setting in the menue "USB-Connection=PC-Remotecontrol". In this case the raspberry PI, from where i send the command gphoto2 --capture-image-and-donwload, downloads the jpg and the arw - file. capt0000.jpg and capt0000.arw. When i send the command the second time, then it ovwerwrites both of the files again with capt0000.jpg and capt0000.arw. the next problem When i send only the command --capture-image, then it says, that the Pictures are stored on the camera. But when i remove the SD-Card, the Card ist empty. This ist i think the reason that the command --Keep-Raw does not work with my camera. I found a similar thread, and hoped, that the command "gphoto2 --set-config capturetarget=1" would be the solutioon too for my Problem. But my A99 does not have the Parameter capturetarget. Does any Person has a hint for my, what kann i do, that it works with my camera too?
 Many thanks at all! :-) zahu69

**Comment by msmeissn** [comment]
yes, this is a limitation of the sony capture firmware, it has only ram capture and does not allow keeping it on the card.

if you notice the windwos software allowing this, please report it to us.
