### ISSUE TITLE
Canon EOS 1200D and eosremoterelease=5

### ISSUE THREAD

**Issue by piMyHome** [gphoto/gphoto2#11]
Hi Marcus,

First of all: Thank you for such a great tool! Please let me know how I can donate to the project.

A few days ago, I set up a webcam with a Canon 1200D and a Raspi at the restaurant of my daughter's boyfriend family (ladarsena.it/webcam). SInce a webcam doesn't need to adjust the focus, I use eosremoterelease=5 to capture the image immediately. I use exactly this command:

```
gphoto2 --force-overwrite --set-config imageformat=3 --set-config iso=0 --set-config eosremoterelease=5 --capture-image-and-download --filename image.jpg
```
Usually it works perfect, but once in a while I get an error. In the night the error persists, then I have to change "-capture-image-and-download" to  "--wait-event-and-download=35s". This works until the next morning, then the same error occurs and I have to switch back to "-capture-image-and-download" to get it running.

Debug log attached. Any ideas?

Thanks
Peter

[debug.zip](https://github.com/gphoto/gphoto2/files/66834/debug.zip)

**Comment by msmeissn** [comment]
We might run in the eos capture timeout of 60 seconds during the night.
What exposure times do you have in those images?

Usually you would not mix the capture-image-and-download and eosremote release options, you could try:

eosremoterelease=5 --wait-event-and-download=100s --set-config eosremoterelease=4  
(4 = Release Full)

**Comment by piMyHome** [comment]
The max. exposure time is about 15sec, it's quite illuminated in the night (http://www.ladarsena.it/webcam/hd/webcam_20151218-0250.jpg).  So a timeout might not be the problem here.

Sorry, i mixed something up in my first issue post above: "--capture-image-and-download" is working in the night but not in the day. It worked flawless before I changed from 2.5.8 to 2.5.9.

**Comment by piMyHome** [comment]
Thanks a lot Marcus,
I did what you suggested and since then I had no more problems, using:
--eosremoterelease=5 --wait-event-and-download=45s --set-config eosremoterelease=4

But I guess it's more the 45 seconds than eosremoterelease=4

I have a feature request: something like **--wait-event-string=**
Instead of waiting for a certain amount of events or a certain time in seconds, we can wait for a string like **--wait-event-string="Saving file as"**. This would help to wait exactly for a specific event.
```
...
UNKNOWN PTP Property d1af changed
UNKNOWN PTP Property d102 changed
UNKNOWN PTP Property d101 changed
UNKNOWN PTP Property d103 changed
UNKNOWN unhandled EOS event StorageInfoChanged (size 12)
UNKNOWN PTP Property d11b changed
UNKNOWN unhandled EOS event StorageInfoChanged (size 12)
Saving file as image.jpg              ## <- That's the event I am waiting for
UNKNOWN ObjectRemoved
UNKNOWN unhandled EOS event StorageInfoChanged (size 12)
UNKNOWN PTP Property d11b changed
```

Oh, and where do I find the donation button?

Thanks,
Peter

**Comment by msmeissn** [comment]
I missed this last entry.

--wait-event  can wait for strings as they are output. for downloaded files wait for "FILEADDED" 

--wait-event-and-download=FILEADDED

(we are not set up for monetary donations at this time. I had two camera donations from companies who wanted stuff fixed for them. But I do not lack money, more I lack time and knowledge :)

**Comment by piMyHome** [comment]
Thanks for the update Marcus!

So get some time and the knowledge how to set up a Paypal donation button and/or an Amazon wishlist :-)
