### ISSUE TITLE
Question: Most efficient compiling workflow?

### ISSUE THREAD

**Issue by haysclark** [gphoto/gphoto2#113]
@msmeissn I have been experimenting with the various configuration option in _libgphoto2_ and I was curious if I must fully recompile _gphoto2_ for each change iteration? I wasn't sure if _libgphoto2_ is a library dependency that is compiled into _gphoto2_, or if _libgphoto2_ is used as a run-time library.

Workflow steps:
1) build _libgphoto2_
2) build _gphoto2_ (output says libgphoto2 is used.
3) tweak _libgphoto2_ and rebuild _libgphoto2_
4) rebuild _gphoto2_ -> Can I just run ```make && make install``` and reuse the previous configuration or is ```./configure``` still required?

Also, please let me know if this line of questions would be more appropriate in the developer listserve?

Thank you!

**Comment by msmeissn** [comment]
you do not need to do step 4 unless you change libgphoto2 external apis and use them in gphoto2, so you can loop on step 3.

**Comment by haysclark** [comment]
@msmeissn Thank you!
