### ISSUE TITLE
libgphoto2 makes darktable hang with webdav directory

### ISSUE THREAD

**Issue by mabod** [gphoto/gphoto2#114]
Hi,
I found a weird behaviour in darktable 2.4.0 which might be caused by /usr/lib/libgphoto2_port/0.12.0/disk.so.

I have my magentacloud mounted with webdav to /mnt/magentacloud. When I copy a file to this directory with dd, the directory is blocked for the duration of the file transfer. Not even an "ls" command is working for it until dd is finished.

When darktable is running at that time and I want to exit darktable, it is not doing so. Instead it sits and waits until the dd file transfer is done and then it exists.

strace shows that darktable is accessing all mounted folders in /mnt incl. /mnt/magentacloud:
```
4969  stat("/mnt/magentacloud/DCIM",  <unfinished ...>
4969  stat("/mnt/magentacloud/dcim", 0x7ff6b7ff0330) = -1 ENOENT (No such file or directory)
4969  stat("/mnt/zstore/DCIM", 0x7ff6b7ff0330) = -1 ENOENT (No such file or directory)
4969  stat("/mnt/zstore/dcim", 0x7ff6b7ff0330) = -1 ENOENT (No such file or directory)
4969  stat("/mnt/zstore/BENCHMARK/DCIM", 0x7ff6b7ff0330) = -1 ENOENT (No such file or directory)
4969  stat("/mnt/zstore/BENCHMARK/dcim", 0x7ff6b7ff0330) = -1 ENOENT (No such file or directory)
```
So it looks like darktable is waiting for the reply of   stat("/mnt/magentacloud/DCIM",  <unfinished ...> before it is able to exit.

This looks like gphoto2 activity. With the help of the darktable developers I created a gdb backtrace which shows that /usr/lib/libgphoto2_port/0.12.0/disk.so is active at that time.

Can somebody here please shed some light on this? Is this indeed gphoto2 behaviour and if yes, why is it doing that an how can I stop it from doing it?

Matthias

**Comment by houz** [comment]
The "why" is easy to answer: darktable tries to detect all connected cameras on startup:

https://github.com/darktable-org/darktable/blob/master/src/common/camera_control.c#L705-L716

The question is, can that be done without blocking? Or can the call be canceled somehow?

**Comment by msmeissn** [comment]
its coming over the directory driver, which looks over all mountpoints for a "DCIM" directory.

**Comment by msmeissn** [comment]
what fstype is in use for mounting this? I tried to filter out all network filesystems

**Comment by mabod** [comment]
The file system is davfs. I use the following fstab entry to mount the cloud:

`https://webdav.magentacloud.de /mnt/magentacloud davfs _netdev,nodev,user,rw,uid=1000,gid=1000,noauto 0 0`

**Comment by msmeissn** [comment]
you could temporary remove / move away the disk.so port driver to avoid this

**Comment by luzpaz** [comment]
Sorry to necrobump, but is this issue still relevant ?

**Comment by mabod** [comment]
No, I dont think so. I quickly gave it a try and darktable starts and stops normally even with a big file transfer to /mnt/magentacloud. I will close this issuee now.
