### ISSUE TITLE
fatal error: gphoto2/gphoto2-camera.h: No such file or directory

### ISSUE THREAD

**Issue by mccodesurfer** [gphoto/gphoto2#115]
I'm trying to install libgphoto2 and gphoto2 in my @HOME/Dev directory to make sure it doesn't conflict with an allready installed gphoto2 - part of StellarMate OS product. libgphoto2 installs ok but I get the above error when I try to install gphoto2. My configure command was

stellarmate@stellarmategb:~/Dev/gphoto2.git/trunk$ ./configure --prefix=$HOME/Dev --with-libgphoto2=$HOME/Dev

As you might guess, I'm new to linux development. I'm trying to modify libgphoto2 for improved pentax support. I searched the trunk and could not find the file mentioned. What can I do? thanks

**Comment by mccodesurfer** [comment]
PS: I checked out the repository using SVN

**Comment by msmeissn** [comment]
gphoto2-camera.h comes from libgphoto2 ... the include directory seems not correctly specified

**Comment by mccodesurfer** [comment]
Thanks! I'll try doing a normal install and see how it goes.

**Comment by mccodesurfer** [comment]
I did a standard install in to /usr/local and everything worked fine. Thanks!

**Comment by LaCamargoSimoes** [comment]
did you fix it... im having the same problem
