### ISSUE TITLE
Canon EOS1100D - 

### ISSUE THREAD

**Issue by meeximum** [gphoto/gphoto2#118]
Hi, 

I want to run gphoto2 on my AllWinner A20 Cubietruck with armbian running on it.
Installation finished without any errors.

auto-detect finds the right camera modell

but when I try to capture I got an error with debug
`*** Error ***
Sorry, your camera does not support generic capture
0.516903 gp_camera_capture [gphoto2-camera.c:1340](0): 'camera->functions->capture (camera, type, path, context)' failed: -6
ERROR: Could not capture image.
ERROR: Could not capture.
*** Error (-6: 'Unsupported operation') ***
`

any help would be great, kind regards
[my-logfile.txt](https://github.com/gphoto/gphoto2/files/1752923/my-logfile.txt)

**Comment by msmeissn** [comment]
libgphoto2 2.5.15 is buggy here., please upgrade to 2.5.16.

**Comment by meeximum** [comment]
great!! I installed the dev version, now it works :-)
