### ISSUE TITLE
Mailing lists are unreachable

### ISSUE THREAD

**Issue by labre** [gphoto/gphoto2#119]
I just wanted to note, that at least the gphoto-user mailing list is down. I get mailer daemons trying to reach gphoto-user@sf.net
gphoto-user@sourceforge.net and
gphoto-user-owner@sourceforge.net

If this is a sourceforge server error, please mark this issue as wontfix (and change the list server, if the problem persists), otherwise please try to find the root cause and fix it.

Should this be an issue on my side, excuse me. I have no indications for that, though. Remote MTA and MUA seem to work properly in all other cases.

Here is the log:
> <gphoto-user-owner@lists.sourceforge.net>: host
>     mx.sourceforge.net[216.105.38.6] said: 550 unknown user (in reply to RCPT
>     TO command)
> 
> Reporting-MTA: dns; mout01.posteo.de
> X-Postfix-Queue-ID: BB32720FB5
> X-Postfix-Sender: rfc822; labre@posteo.de
> Arrival-Date: Mon, 26 Feb 2018 16:32:57 +0100 (CET)
> 
> Final-Recipient: rfc822; gphoto-user-owner@lists.sourceforge.net
> Original-Recipient: rfc822;gphoto-user-owner@lists.sourceforge.net
> Action: failed
> Status: 5.0.0
> Remote-MTA: dns; mx.sourceforge.net
> Diagnostic-Code: smtp; 550 unknown user
> 
> Return-Path: <labre@posteo.de>
> Received: from mout01.posteo.de (unknown [10.0.0.65])
> 	by mout01.posteo.de (Postfix) with ESMTPS id BB32720FB5
> 	for <gphoto-user-owner@lists.sourceforge.net>; Mon, 26 Feb 2018 16:32:57 +0100 (CET)
> Received: from submission-encrypt01.posteo.de (unknown [10.0.0.76])
> 	by mout01.posteo.de (Postfix) with ESMTPS id 71ABD20F44
> 	for <gphoto-user-owner@lists.sourceforge.net>; Mon, 26 Feb 2018 16:32:57 +0100 (CET)
> DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=posteo.de; s=2017;
> 	t=1519659177; bh=2Gw9b5nJOeBs/c32YooTjb9o+E7at3DSgfNV9YRhy2M=;
> 	h=From:To:Subject:Date:From;
> 	b=c6yvffi/7lvApUWmdUsSynDiGANTvsWaV0tjBIBg4/GtnjR1aHeBNri3C7Ot3Kqoy
> 	 qBPohIU9/J8TeK0Qd5lAS1ROWoQ4JDJjoh7WiAX8Y27CLcIZ3ZHPdhgXbDDLQA6pzL
> 	 fZQgPV6ziNJvdxwF87tI1SSkY+VtMEJrpbbtJItCjSpD+JIYxPRg8LyXUcI+O9XBO+
> 	 pr+TBi8x6V1mbcC1ru07gqOkZiNI+AGijQ1zQgLmX5t3p+cMuWd9sSpCxXlo1JgnMd
> 	 OVtqK/VZqaqGO15zUf9CbH8xD4WlHgjCIhg+XrXhDheZ+KP5CgIG205rZkMY2fOfBP
> 	 c+c6mH2hY2UFw==
> Received: from customer (localhost [127.0.0.1])
> 	by submission (posteo.de) with ESMTPSA id 3zqm6t3qggz9rxX
> 	for <gphoto-user-owner@lists.sourceforge.net>; Mon, 26 Feb 2018 16:32:54 +0100 (CET)
> From: Manuel Ullmann <labre@posteo.de>
> To: gphoto-user-owner@lists.sourceforge.net
> Subject: Mail to gphoto-user list is not delivered
> Date: Mon, 26 Feb 2018 16:32:48 +0100
> Message-ID: <87y3jfrckf.fsf@posteo.de>
> User-Agent: Gnus/5.13 (Gnus v5.13) Emacs/25.3 (gnu/linux)
> MIME-Version: 1.0
> Content-Type: text/plain; charset=utf-8
> Content-Transfer-Encoding: quoted-printable
> Posteo-User: removed
> Posteo-DKIM: ok

Thanks,
Manuel

**Comment by msmeissn** [comment]
this is not intended. seems breakage on sf side

**Comment by labre** [comment]
> this is not intended. seems breakage on sf side
Thanks for the info. Would you prefer to leave this open until it is
fixed or close it as wontfix? I would appreciate being notified of it
though.

**Comment by msmeissn** [comment]
lets keep it open until resolved

**Comment by msmeissn** [comment]
https://sourceforge.net/p/forge/site-support/16705/

**Comment by labre** [comment]
According to ticket and a test, it is fixed. Closing…
