### ISSUE TITLE
tethering blocks shooting

### ISSUE THREAD

**Issue by under-score** [gphoto/gphoto2#134]
With some older Nikon D3 and the most recent gphoto2 I monitor the camera
`gphoto2 --capture-tethered`
Works nice but whenever I try to shoot in second terminal (from a webserver)
`gphoto2 --capture-image-and-download`
this command is blocked. It works when  the camera is not being tethered.
Bug, feature or any misunderstanding?

**Comment by under-score** [comment]
thank you! When running
`kill -USR1 $PID`
it tells me "user defined signal 1:" and dies silently under OSX 10.7.5 without shooting.
Maybe I need that as also other options like --keep-raw did not work here.

**Comment by msmeissn** [comment]
hmm, i was mistaken
gphoto2 --capture-tethered does not handle -USR1

hmm, 
gphoto2 --capture-image-and-download -I -1 -F 1000 
-1 for inerval means waiting for SIGUSR1 
thjis will however not report the events inbetween. 

this might need some improvements to the wait-event code, or your own code.

In libgphoto2/examples/sample-photobooth.c I hjave written such an example, with eventchceking loop and SIGUSR1 for triggering a capture.

**Comment by under-score** [comment]
Thank you so much. Unfortunately I cannot compile the sample code
```
sample-photobooth.c:224:9: error: duplicate case value 'GP_EVENT_FILE_ADDED'
                        case GP_EVENT_FILE_CHANGED:
                             ^
sample-photobooth.c:202:9: note: previous case defined here
                        case GP_EVENT_FILE_ADDED: {
```

**Comment by msmeissn** [comment]
very weird, these are distinct enum values and so this should not appear. :/ i dont see how this can happen...

**Comment by under-score** [comment]
any chance for an update here? I am still fiddling around here either with `gphoto2 --capture-tethered` or `gphoto2 --capture-image-and-download`

**Comment by msmeissn** [comment]
lost track of this, sorry :/ i hope either solved or worked around now
