### ISSUE TITLE
Canon 13000D is not supported in 2.5.15 but working in 2.5.9

### ISSUE THREAD

**Issue by rakeshbhatt10** [gphoto/gphoto2#136]
Hi,

I ran code to remote display canon 1300d using gphoto2 and sockets. I written code in 2.5.9 in java used project https://github.com/mvmn/gphoto2-jna as java wrapper

I was successful in transmitted live stream but stream is quite disconnected after 2 min code started to throw errors while capturing photo from Canon.

 I updated gphto2 to 2.5.15 but now it is showing unsupported (error -6) on gp_camera_capture_preview

While gphoto2 shows it still support it
http://gphoto.org/proj/libgphoto2/support.php

Please help

**Comment by rakeshbhatt10** [comment]
No it shows Cannon EOS 1300D

**Comment by rakeshbhatt10** [comment]
[capture.log](https://github.com/gphoto/gphoto2/files/1982658/capture.log)

I had attached capture logs

**Comment by msmeissn** [comment]
Judging from the logfile it seems to have worked for a single image?

The libgpoto2 2.5.15 release was buggy in regards to EOS series, use 2.5.18 or so.

**Comment by msmeissn** [comment]
can you recheck with 2.5.22 and reopen if not fixed?
