### ISSUE TITLE
General camera support for --capture-tethered

### ISSUE THREAD

**Issue by joshbg2k** [gphoto/gphoto2#139]
Not a bug, but also not sure where else to ask this question. When determining whether a camera supports `--capture-tethered`, do any of the properties in the Additional Abilities column of the Supported Cameras page ([http://gphoto.sourceforge.net/proj/libgphoto2/support.php](http://gphoto.sourceforge.net/proj/libgphoto2/support.php)) indicate tethered capture support, or is there another way to find out without actually trying every camera?

**Comment by msmeissn** [comment]
usally this tethered capture is there along with regular capture support, but not necessary.

Nikon and Canon DSLR all can do it for instance.
