### ISSUE TITLE
[EOS 200D] --get-config iso keeps returning Unknown value 0001

### ISSUE THREAD

**Issue by saiiro** [gphoto/gphoto2#145]
Hi, I've noticed a weird behavior with the canon 200D (aka SL2). 
[getiso.txt](https://github.com/gphoto/gphoto2/files/2063864/getiso.txt)
[setiso.txt](https://github.com/gphoto/gphoto2/files/2063865/setiso.txt)

Although the set-config DOES change the value of the iso on the camera, the get-config keeps saying that the current value is unknown. 

I'm attaching the debug logs output for both the set-config and the get-config. 

Thanks !

$ gphoto2 --set-config iso=400
$ gphoto2 --get-config iso
Label: ISO Speed
Readonly: 0
Type: RADIO
Current: Unknown value 0001
Choice: 0 Auto
Choice: 1 100
Choice: 2 200
Choice: 3 400
Choice: 4 800
Choice: 5 1600
Choice: 6 3200
Choice: 7 6400
Choice: 8 12800
Choice: 9 25600
Choice: 10 Unknown value 0001
END
$ gphoto2 --set-config iso=200
$ gphoto2 --get-config iso
Label: ISO Speed
Readonly: 0
Type: RADIO
Current: Unknown value 0001
Choice: 0 Auto
Choice: 1 100
Choice: 2 200
Choice: 3 400
Choice: 4 800
Choice: 5 1600
Choice: 6 3200
Choice: 7 6400
Choice: 8 12800
Choice: 9 25600
Choice: 10 Unknown value 0001
END
$

**Comment by msmeissn** [comment]
The OLC record decoding is failing and providing the incorrect value here. The OLC binary format seems to have changed :/

**Comment by msmeissn** [comment]
could you try current git of libgphoto2? I added some code there to help

**Comment by saiiro** [comment]
Looks like it works !!! 
Thanks again Marcus. 
Should i close this issue ?

**Comment by msmeissn** [comment]
yes. fixed by commit 3b1c6e825947c671064acfbb3edb99d28b893bc6 and commit 96e13a131863e082c056cd045e4ecca2703f3a77
