### ISSUE TITLE
Installing gphoto2 onLinkit Smart 7688

### ISSUE THREAD

**Issue by rad82** [gphoto/gphoto2#15]
Hi,

Im just getting started with installing ghpoto2 on a Linkit Smart DUO (http://www.seeedstudio.com/wiki/LinkIt_Smart_7688_Duo) which is essentially seeedstudio's version of the Arduino Yun running OpenWRT. I have installed all the dependencies without hassle,but since the DUO is a different architecture to the YUN, I am stuck having to compile from scratch.

In the docs online, the slide "Configure, Making, Installing" basically says "Write Me :-P"

Can someone please walk me through configuring, making, installing. I tried simply running $ ./configure.ac after using "$git clone" to download lipgphoto2 and gphoto2 sources. But no luck... "./configure.ac: line 1: syntax error: unexpected word (expecting ")")"

Thanks in advance!

**Comment by msmeissn** [comment]
on github, you would need 
- autoreconf -i -f
- ./configure    --prefix=/usr/   (or whatever target path)
- make
- make install    (or sudo make install if you build as user)

If autoreconf is not available, you could e.g. start with the tarballs, available from http://sf.net/projects/gphoto/ where you would start with the configure step.

**Comment by rad82** [comment]
Thanks! Its gotten me off to some kind of start. 

I installed GCC, and it seems the work:
$gcc -v 
and prints:

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/tmp/run/mountd/mmcblk0p1/usr/bin/../lib/gcc/mipsel-openwrt-linux-uclibc/4.8.3/lto-wrapper
Target: mipsel-openwrt-linux-uclibc
Configured with: /home/buildbot/slave-local/ramips_mt7688/build/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/gcc-4.8.3/configure --target=mipsel-openwrt-linux --host=mipsel-openwrt-linux --build=x86_64-linux-gnu --program-prefix= --program-suffix= --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls --build=x86_64-linux-gnu --host=mipsel-openwrt-linux-uclibc --target=mipsel-openwrt-linux-uclibc --enable-languages=c,c++ --with-bugurl=https://dev.openwrt.org/ --with-pkgversion='OpenWrt GCC 4.8.3' --enable-shared --disable-__cxa_atexit --enable-target-optspace --with-gnu-ld --disable-nls --disable-libmudflap --disable-multilib --disable-libgomp --disable-libquadmath --disable-libssp --disable-decimal-float --disable-libstdcxx-pch --with-host-libstdcxx=-lstdc++ --prefix=/usr --libexecdir=/usr/lib --with-float=soft
Thread model: posix
gcc version 4.8.3 (OpenWrt GCC 4.8.3) 



Going on to configure etc
$./configure --prefix=/usr/

Gives me some hassle, one thing I did notice is a call to gcc -V which should actually be a lower case otherwise it dies:

root@mylinkit:/tmp/run/mountd/mmcblk0p1/libgphoto2-2.5.8# ./configure --prefix=/
usr/ 
checking for a BSD-compatible install... auto-aux/install-sh -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... auto-aux/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking whether make supports nested variables... (cached) no
checking for POSIX sh $() command substitution... yes
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/Media/SD-P1/libgphoto2-2.5.8':
configure: error: C compiler cannot create executables
See `config.log' for more details

The output of config.log is as follows/attached:

[config.log.txt](https://github.com/gphoto/gphoto2/files/84067/config.log.txt)

Thanks!

**Comment by msmeissn** [comment]
configure:3760: gcc    conftest.c  >&5
conftest.c:1:0: internal compiler error: Illegal instruction

i think the compiler is not generating code for your architecture . it might need to be a cross compile? 

I have however no clue about this kind of setup :/

**Comment by msmeissn** [comment]
no reply
