### ISSUE TITLE
Issue with Olympus TG-5

### ISSUE THREAD

**Issue by cemfcelebi** [gphoto/gphoto2#151]
Hi,

We are developing a photo capturing system with using Raspberry Pi 3, gphoto2 and Olympus TG-5. 

When the Olympus TG-5 is connected in MTP mode, the camera is detected by gphoto2

pi@raspberrypi:~ $ gphoto2 --auto-detect
Model                          Port
----------------------------------------------------------
Olympus E-M5                   usb:001,009

pi@raspberrypi:~ $ lsusb
Bus 001 Device 009: ID 07b4:012f Olympus Optical Co., Ltd
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp. SMC9514 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Is there any possibility to capture and trigger image although Olympus TG-5 is not in the supported devices list?

Thanks in advance,
Cem

**Comment by msmeissn** [comment]
I think it is not implemented in the firmware of this Olympus Model.

Th E-M5 Mark 2 allows remote controlled capture and is supported in 2.5.19 and newer
