### ISSUE TITLE
Sony Alpha 7R2 - Capture image issue

### ISSUE THREAD

**Issue by MikeTough** [gphoto/gphoto2#153]
Hi guys,

After a 6 month break in my project I've recently updated to current versions of gphoto2 & libphoto2 and have come across some odd issues with basic image capture and differences between command line and shell mode that were not present in the older version.

`
pi@raspberrypi:~ $ gphoto2 --auto-detect
Model                          Port                                            
----------------------------------------------------------
Sony Alpha-A7r II (Control)    usb:001,014  
pi@raspberrypi:~ $ gphoto2 --set-config capturemode="Single Shot"
pi@raspberrypi:~ $ gphoto2 --get-config capturemode                            
Label: Still Capture Mode                                                      
Readonly: 0
Type: RADIO
Current: Single Shot
Choice: 0 Single Shot
Choice: 1 Burst
Choice: 2 Continuous Low Speed
Choice: 3 Selftimer 2s
Choice: 4 Selftimer 5s
Choice: 5 Selftimer 10s
Choice: 6 Selftimer 10s 3 Pictures
Choice: 7 Selftimer 10s 5 Pictures
Choice: 8 Selftimer 5s 3 Pictures
Choice: 9 Selftimer 5s 5 Pictures
Choice: 10 Selftimer 2s 3 Pictures
Choice: 11 Selftimer 2s 5 Pictures
Choice: 12 Bracketing C 0.3 Steps 3 Pictures
Choice: 13 Bracketing C 0.3 Steps 5 Pictures
Choice: 14 Bracketing C 0.3 Steps 9 Pictures
Choice: 15 Bracketing C 0.5 Steps 3 Pictures
Choice: 16 Bracketing C 0.5 Steps 5 Pictures
Choice: 17 Bracketing C 0.5 Steps 9 Pictures
Choice: 18 Bracketing C 0.7 Steps 3 Pictures
Choice: 19 Bracketing C 0.7 Steps 5 Pictures
Choice: 20 Bracketing C 0.7 Steps 9 Pictures
Choice: 21 Bracketing C 1.0 Steps 3 Pictures
Choice: 22 Bracketing C 1.0 Steps 5 Pictures
Choice: 23 Bracketing C 1.0 Steps 9 Pictures
Choice: 24 Bracketing C 2.0 Steps 3 Pictures
Choice: 25 Bracketing C 2.0 Steps 5 Pictures
Choice: 26 Bracketing C 3.0 Steps 3 Pictures
Choice: 27 Bracketing C 3.0 Steps 5 Pictures
Choice: 28 Bracketing S 0.3 Steps 3 Pictures
Choice: 29 Bracketing S 0.3 Steps 5 Pictures
Choice: 30 Bracketing S 0.3 Steps 9 Pictures
Choice: 31 Bracketing S 0.5 Steps 3 Pictures
Choice: 32 Bracketing S 0.5 Steps 5 Pictures
Choice: 33 Bracketing S 0.5 Steps 9 Pictures
Choice: 34 Bracketing S 0.7 Steps 3 Pictures
Choice: 35 Bracketing S 0.7 Steps 5 Pictures
Choice: 36 Bracketing S 0.7 Steps 9 Pictures
Choice: 37 Bracketing S 1.0 Steps 3 Pictures
Choice: 38 Bracketing S 1.0 Steps 5 Pictures
Choice: 39 Bracketing S 1.0 Steps 9 Pictures
Choice: 40 Bracketing S 2.0 Steps 3 Pictures
Choice: 41 Bracketing S 2.0 Steps 5 Pictures
Choice: 42 Bracketing S 3.0 Steps 3 Pictures
Choice: 43 Bracketing S 3.0 Steps 5 Pictures
Choice: 44 Bracketing WB Lo
Choice: 45 Bracketing WB Hi
Choice: 46 Bracketing DRO Lo
Choice: 47 Bracketing DRO Hi
END
pi@raspberrypi:~ $ gphoto2 --capture-image
New file is in location /capt0000.arw on the camera                            
pi@raspberrypi:~ $ gphoto2 -L
There is no file in folder '/'. 
`
Using command line, the capture image does not appear in the folder. This did work under the older version.

However, using the shell commands, everything appears to function as expected.

`
pi@raspberrypi:~ $ gphoto2 --shell
gphoto2: {/home/pi} /> capture-image                                           
New file is in location /capt0000.arw on the camera                            
gphoto2: {/home/pi} /> ls
capt0000.arw        
gphoto2: {/home/pi} /> 
`
In addition, attempting to alter the capturemode in shell does not appear to function.

`
gphoto2: {/home/pi} /> set-config capturemode="Bracketing C 1.0 Steps 3 Pictures"
gphoto2: {/home/pi} /> get-config capturemode
Label: Still Capture Mode
Readonly: 0
Type: RADIO
Current: Single Shot
Choice: 0 Single Shot
Choice: 1 Burst
Choice: 2 Continuous Low Speed
Choice: 3 Selftimer 2s
Choice: 4 Selftimer 5s
Choice: 5 Selftimer 10s
Choice: 6 Selftimer 10s 3 Pictures
Choice: 7 Selftimer 10s 5 Pictures
Choice: 8 Selftimer 5s 3 Pictures
Choice: 9 Selftimer 5s 5 Pictures
Choice: 10 Selftimer 2s 3 Pictures
Choice: 11 Selftimer 2s 5 Pictures
Choice: 12 Bracketing C 0.3 Steps 3 Pictures
Choice: 13 Bracketing C 0.3 Steps 5 Pictures
Choice: 14 Bracketing C 0.3 Steps 9 Pictures
Choice: 15 Bracketing C 0.5 Steps 3 Pictures
Choice: 16 Bracketing C 0.5 Steps 5 Pictures
Choice: 17 Bracketing C 0.5 Steps 9 Pictures
Choice: 18 Bracketing C 0.7 Steps 3 Pictures
Choice: 19 Bracketing C 0.7 Steps 5 Pictures
Choice: 20 Bracketing C 0.7 Steps 9 Pictures
Choice: 21 Bracketing C 1.0 Steps 3 Pictures
Choice: 22 Bracketing C 1.0 Steps 5 Pictures
Choice: 23 Bracketing C 1.0 Steps 9 Pictures
Choice: 24 Bracketing C 2.0 Steps 3 Pictures
Choice: 25 Bracketing C 2.0 Steps 5 Pictures
Choice: 26 Bracketing C 3.0 Steps 3 Pictures
Choice: 27 Bracketing C 3.0 Steps 5 Pictures
Choice: 28 Bracketing S 0.3 Steps 3 Pictures
Choice: 29 Bracketing S 0.3 Steps 5 Pictures
Choice: 30 Bracketing S 0.3 Steps 9 Pictures
Choice: 31 Bracketing S 0.5 Steps 3 Pictures
Choice: 32 Bracketing S 0.5 Steps 5 Pictures
Choice: 33 Bracketing S 0.5 Steps 9 Pictures
Choice: 34 Bracketing S 0.7 Steps 3 Pictures
Choice: 35 Bracketing S 0.7 Steps 5 Pictures
Choice: 36 Bracketing S 0.7 Steps 9 Pictures
Choice: 37 Bracketing S 1.0 Steps 3 Pictures
Choice: 38 Bracketing S 1.0 Steps 5 Pictures
Choice: 39 Bracketing S 1.0 Steps 9 Pictures
Choice: 40 Bracketing S 2.0 Steps 3 Pictures
Choice: 41 Bracketing S 2.0 Steps 5 Pictures
Choice: 42 Bracketing S 3.0 Steps 3 Pictures
Choice: 43 Bracketing S 3.0 Steps 5 Pictures
Choice: 44 Bracketing WB Lo
Choice: 45 Bracketing WB Hi
Choice: 46 Bracketing DRO Lo
Choice: 47 Bracketing DRO Hi
END
gphoto2: {/home/pi} /> 
`
Whereas in command line it does work.
`
pi@raspberrypi:~ $ gphoto2 --set-config capturemode="Bracketing C 1.0 Steps 3 Pictures"
pi@raspberrypi:~ $ gphoto2 --get-config capturemode                            
Label: Still Capture Mode                                                      
Readonly: 0
Type: RADIO
Current: Bracketing C 1.0 Steps 3 Pictures
Choice: 0 Single Shot
Choice: 1 Burst
Choice: 2 Continuous Low Speed
Choice: 3 Selftimer 2s
Choice: 4 Selftimer 5s
Choice: 5 Selftimer 10s
Choice: 6 Selftimer 10s 3 Pictures
Choice: 7 Selftimer 10s 5 Pictures
Choice: 8 Selftimer 5s 3 Pictures
Choice: 9 Selftimer 5s 5 Pictures
Choice: 10 Selftimer 2s 3 Pictures
Choice: 11 Selftimer 2s 5 Pictures
Choice: 12 Bracketing C 0.3 Steps 3 Pictures
Choice: 13 Bracketing C 0.3 Steps 5 Pictures
Choice: 14 Bracketing C 0.3 Steps 9 Pictures
Choice: 15 Bracketing C 0.5 Steps 3 Pictures
Choice: 16 Bracketing C 0.5 Steps 5 Pictures
Choice: 17 Bracketing C 0.5 Steps 9 Pictures
Choice: 18 Bracketing C 0.7 Steps 3 Pictures
Choice: 19 Bracketing C 0.7 Steps 5 Pictures
Choice: 20 Bracketing C 0.7 Steps 9 Pictures
Choice: 21 Bracketing C 1.0 Steps 3 Pictures
Choice: 22 Bracketing C 1.0 Steps 5 Pictures
Choice: 23 Bracketing C 1.0 Steps 9 Pictures
Choice: 24 Bracketing C 2.0 Steps 3 Pictures
Choice: 25 Bracketing C 2.0 Steps 5 Pictures
Choice: 26 Bracketing C 3.0 Steps 3 Pictures
Choice: 27 Bracketing C 3.0 Steps 5 Pictures
Choice: 28 Bracketing S 0.3 Steps 3 Pictures
Choice: 29 Bracketing S 0.3 Steps 5 Pictures
Choice: 30 Bracketing S 0.3 Steps 9 Pictures
Choice: 31 Bracketing S 0.5 Steps 3 Pictures
Choice: 32 Bracketing S 0.5 Steps 5 Pictures
Choice: 33 Bracketing S 0.5 Steps 9 Pictures
Choice: 34 Bracketing S 0.7 Steps 3 Pictures
Choice: 35 Bracketing S 0.7 Steps 5 Pictures
Choice: 36 Bracketing S 0.7 Steps 9 Pictures
Choice: 37 Bracketing S 1.0 Steps 3 Pictures
Choice: 38 Bracketing S 1.0 Steps 5 Pictures
Choice: 39 Bracketing S 1.0 Steps 9 Pictures
Choice: 40 Bracketing S 2.0 Steps 3 Pictures
Choice: 41 Bracketing S 2.0 Steps 5 Pictures
Choice: 42 Bracketing S 3.0 Steps 3 Pictures
Choice: 43 Bracketing S 3.0 Steps 5 Pictures
Choice: 44 Bracketing WB Lo
Choice: 45 Bracketing WB Hi
Choice: 46 Bracketing DRO Lo
Choice: 47 Bracketing DRO Hi
END
`

There is also some strange behaviour when capturing mulitple images (this behaviour was apparent in the older versions), where the file name gets confused. The first two images always appear to be named the same resulting in the first image not being available to download. Is this a bug in gphoto or a bug in the Sony firmware?

`
pi@raspberrypi:~ $ gphoto2 --shell
gphoto2: {/home/pi} /> get-config capturemode                                  
Label: Still Capture Mode
Readonly: 0
Type: RADIO
Current: Bracketing C 1.0 Steps 3 Pictures
Choice: 0 Single Shot
Choice: 1 Burst
Choice: 2 Continuous Low Speed
Choice: 3 Selftimer 2s
Choice: 4 Selftimer 5s
Choice: 5 Selftimer 10s
Choice: 6 Selftimer 10s 3 Pictures
Choice: 7 Selftimer 10s 5 Pictures
Choice: 8 Selftimer 5s 3 Pictures
Choice: 9 Selftimer 5s 5 Pictures
Choice: 10 Selftimer 2s 3 Pictures
Choice: 11 Selftimer 2s 5 Pictures
Choice: 12 Bracketing C 0.3 Steps 3 Pictures
Choice: 13 Bracketing C 0.3 Steps 5 Pictures
Choice: 14 Bracketing C 0.3 Steps 9 Pictures
Choice: 15 Bracketing C 0.5 Steps 3 Pictures
Choice: 16 Bracketing C 0.5 Steps 5 Pictures
Choice: 17 Bracketing C 0.5 Steps 9 Pictures
Choice: 18 Bracketing C 0.7 Steps 3 Pictures
Choice: 19 Bracketing C 0.7 Steps 5 Pictures
Choice: 20 Bracketing C 0.7 Steps 9 Pictures
Choice: 21 Bracketing C 1.0 Steps 3 Pictures
Choice: 22 Bracketing C 1.0 Steps 5 Pictures
Choice: 23 Bracketing C 1.0 Steps 9 Pictures
Choice: 24 Bracketing C 2.0 Steps 3 Pictures
Choice: 25 Bracketing C 2.0 Steps 5 Pictures
Choice: 26 Bracketing C 3.0 Steps 3 Pictures
Choice: 27 Bracketing C 3.0 Steps 5 Pictures
Choice: 28 Bracketing S 0.3 Steps 3 Pictures
Choice: 29 Bracketing S 0.3 Steps 5 Pictures
Choice: 30 Bracketing S 0.3 Steps 9 Pictures
Choice: 31 Bracketing S 0.5 Steps 3 Pictures
Choice: 32 Bracketing S 0.5 Steps 5 Pictures
Choice: 33 Bracketing S 0.5 Steps 9 Pictures
Choice: 34 Bracketing S 0.7 Steps 3 Pictures
Choice: 35 Bracketing S 0.7 Steps 5 Pictures
Choice: 36 Bracketing S 0.7 Steps 9 Pictures
Choice: 37 Bracketing S 1.0 Steps 3 Pictures
Choice: 38 Bracketing S 1.0 Steps 5 Pictures
Choice: 39 Bracketing S 1.0 Steps 9 Pictures
Choice: 40 Bracketing S 2.0 Steps 3 Pictures
Choice: 41 Bracketing S 2.0 Steps 5 Pictures
Choice: 42 Bracketing S 3.0 Steps 3 Pictures
Choice: 43 Bracketing S 3.0 Steps 5 Pictures
Choice: 44 Bracketing WB Lo
Choice: 45 Bracketing WB Hi
Choice: 46 Bracketing DRO Lo
Choice: 47 Bracketing DRO Hi
END
gphoto2: {/home/pi} /> capture-image
New file is in location /capt0000.arw on the camera                            
New file is in location /capt0000.arw on the camera                            
New file is in location /capt0001.arw on the camera                            
gphoto2: {/home/pi} /> ls
capt0000.arw        capt0001.arw        
gphoto2: {/home/pi} /> 

`
The camera takes all 3 images, but the first two are named capt0000.arw, resulting in the first image being "lost".

I'd be greatful if you guys could take a look at these issues. I'm more than happy to provide more information if necessary.

**Comment by MikeTough** [comment]
HI,

I've run a few more tests and now think I have a better understanding of the issues.

First, it may be helpful if I explain what I'm trying to achieve.

I'm running ghoto2 in a rpi2/python environment.
My camera is a Sony Alpha 7R II.
I'm using gphoto2 v2.5.17 and libphoto2 v2.5.19 (updated today)
My project will run gphoto2 through Jim Easterbrook's python/ghhoto2 API interface.

My objective/progress is to:
- Connect to camera (completed and working)
- Adjust camera settings (completed and working - with minor warnings thrown by gphoto2)
- Focus camera and retrieve focus complete signal (completed and working)
- Capture several bursts of **bracketed** images to camera RAM (working, BUT gphoto2 issues)
- Download images & delete from camera RAM (gphoto2 issues)

I'm really close (but no cigar) on the last two issues. There appear to be several issues/bugs within gphoto.

First, I am receiving a couple of inconvenient error/warning messages from gphoto when accessing the camera config list. These do not appear to have any detrimental effect (perhaps just warnings), but do need handled in the program. 
Second, following a bracketed bust capture, gphoto appears to create a duplicate filename for the first and second file in each burst, which makes the first file inaccessible to the python interface.
Third, following the capture, gphoto seems to clear the photos from its filelist in some situations, making them inaccessible later in the program. I have a hunch that the photos remain in camera ram but that gphoto cannot access them.


Taking the first issue.
Running gp-camera_get_config from the python interface gives the following warning:

WARNING  (_get_config [config.c:8525]) Type of property 'Bulb Mode' expected: 0x0000 got: 0x0004 (in port_log at line 129)
After throwing the warning, the program continues to run without issue. That said, I am not currently using the bulb mode for my project, so cannot say if there is a deeper underlying issue.

Also, running gp_camera_capture from the python interface throws the following warning:

WARNING  (camera_sony_capture [library.c:4150]) no object found during event polling. try the 0xffffc001 object id (in port_log at line 129)
After throwing the warning the program uses the 0xffffc001 object id and continues without issue.

Given that these are only warnings, I would not normally raise them as an issue. However, if your are taking the time to look at the other (more substantive) issues, then I simply raise this for completeness in the hope that it can be fixed (providing, of course, that it doesn't screw things up for other users)

If you require a debug dump for either of these points, please let me know and I will be happy to provide. 

I'll deal with the main issues in the following posts.

**Comment by MikeTough** [comment]
For my application, I'm using the bracketing **continuous** burst mode on the sony alpha. It is important to me that the bracketed photos are taken as quickly as possible. Also, I first need to capture the photos onto the camera (I understand that these are stored in RAM on the sony), allow my program to do other stuff, then to download (and delete) the files from the camera RAM.

Whilst I recognise this is perhaps not a standard requirement (although it is for HDR users!) in gphoto, gphoto very nearly achieves this (at least for the sony camera I am using).

One of the main problems seems to be the way in which gphoto allocates filenames in its CameraList. 

The first file in the bracketed set gets named capt0000.arw. However the second file in the set also get named (in gphoto) as capt0000.arw. Subsequent photos in the set increment as expected. This duplicate name appears to confuse/corrupt the CameraList and the duplicate file is not (easily?) available from within gphoto.

This can be exemplified as follows (using gphoto2):

pi@raspberrypi:~ $ gphoto2 --capture-image --list-files
New file is in location /capt0000.arw on the camera                            
New file is in location /capt0000.arw on the camera                            
New file is in location /capt0001.arw on the camera                            
There are 2 files in folder '/'.
#1     capt0000.arw                42305 KB    0x0    image/x-sony-arw
#2     capt0001.arw

Here, the camera rapidly takes a burst of 3 bracketed photos, gphoto displays a "download bar" which takes around 9 seconds per image (I'm not sure why this is displayed, nor why this time delay is happening, since no files should be downloaded !!!), before displaying the above output. Note that all three images are identified by gphoto, but the first two are allocated the same name. list-files only identifies two of the images, ignoring the duplicate.

A "--debug-loglevel debug" file is attached (DeBug01)
[DeBug01.txt](https://github.com/gphoto/gphoto2/files/2224196/DeBug01.txt)

Note, the debug file contains the warning "WARNING (camera_sony_capture [library.c:4150]) no object found during event polling. try the 0xffffc001 object id (in port_log at line 129)" mentioned in the previous post.

The debug file shows that gphoto can get the internal filename from the camera ('DSC00017.ARW', etc) and that the camera name appears to be correctly sequences by sony's software. It also appears to show that the files from previous captures are retained on the camera. (After running a few capture tests - without deleting files - the camera locks-up and need to be reset by powering down. I'm assuming this is because it runs out of RAM space).

I've no doubt you'll be able to identify other issues from the log file.

Interestingly 
gphoto2 --capture-image-and-download
WILL capture and download all images (with the appropriate duplicate file/rename dialogue) and 
gphoto2 --filename xxx%03n --capture-image-and-download
also correctly downloads and names the files without the warning dialogue. Unfortunately (for my application) I need to perform other commands between the capture and download.

I've also successfully tried setting the camera to "Single Capture" bracketing and capturing files one by one. However, unfortunately I do need to capture images in rapid succession (even if it takes a while to download).

Again happy to provide more information/debug files if necessary.

More on the list-files issue in the following post. 



.

**Comment by MikeTough** [comment]
So, to the third issue. When using --capture-image (into camera RAM) without downloading or deleting images, --list-files "loses" images in some situations. I'm reasonably sure that these images remain on the camera (see previous post). This is illustrated by the following (using gphoto).

 pi@raspberrypi:~ $ gphoto2 --list-files
There is no file in folder '/'.                                                
pi@raspberrypi:~ $ gphoto2 --capture-image
New file is in location /capt0000.arw on the camera                            
New file is in location /capt0000.arw on the camera                            
New file is in location /capt0001.arw on the camera                            
pi@raspberrypi:~ $ gphoto2 --list-files
There is no file in folder '/'.                                                
pi@raspberrypi:~ $ 

They're gone !!

However

pi@raspberrypi:~ $ gphoto2 --capture-image --list-files
New file is in location /capt0000.arw on the camera                            
New file is in location /capt0000.arw on the camera                            
New file is in location /capt0001.arw on the camera                            
There are 2 files in folder '/'.
#1     capt0000.arw                41740 KB    0x0    image/x-sony-arw
#2     capt0001.arw
pi@raspberrypi:~ $ gphoto2 --list-files
There is no file in folder '/'.                                                
pi@raspberrypi:~ $ 

Now you see them, now you don't !!

Interestingly in shell mode:
pi@raspberrypi:~ $ gphoto2 --shell
gphoto2: {/home/pi} /> ls                                                      
gphoto2: {/home/pi} /> capture-image
New file is in location /capt0000.arw on the camera                            
New file is in location /capt0000.arw on the camera                            
New file is in location /capt0001.arw on the camera                            
gphoto2: {/home/pi} /> ls
capt0000.arw        capt0001.arw 

And with multiple captures ----

pi@raspberrypi:~ $ gphoto2 --shell
gphoto2: {/home/pi} /> ls                                                      
gphoto2: {/home/pi} /> capture-image
New file is in location /capt0000.arw on the camera                            
New file is in location /capt0000.arw on the camera                            
New file is in location /capt0001.arw on the camera                            
gphoto2: {/home/pi} /> ls
capt0000.arw        capt0001.arw        
gphoto2: {/home/pi} /> capture-image
New file is in location /capt0001.arw on the camera                            
New file is in location /capt0002.arw on the camera                            
New file is in location /capt0003.arw on the camera                            
gphoto2: {/home/pi} /> capture-image
New file is in location /capt0002.arw on the camera                            
New file is in location /capt0004.arw on the camera                            
New file is in location /capt0005.arw on the camera                            
ls
gphoto2: {/home/pi} /> capt0000.arw        capt0001.arw        capt0002.arw        capt0003.arw        
capt0004.arw        capt0005.arw        
gphoto2: {/home/pi} /> 

Apart from the file naming issue, this is close to what is expected (and wanted).  This does not work outside shell mode (see below), where two consecutive capture-image's looses the first capture files.

pi@raspberrypi:~ $ gphoto2 --capture-image --list-files
New file is in location /capt0000.arw on the camera                            
New file is in location /capt0000.arw on the camera                            
New file is in location /capt0001.arw on the camera                            
There are 2 files in folder '/'.
#1     capt0000.arw                41736 KB    0x0    image/x-sony-arw
#2     capt0001.arw
pi@raspberrypi:~ $ gphoto2 --capture-image --list-files
New file is in location /capt0000.arw on the camera                            
New file is in location /capt0000.arw on the camera                            
New file is in location /capt0001.arw on the camera                            
There are 2 files in folder '/'.
#1     capt0000.arw                41736 KB    0x0    image/x-sony-arw
#2     capt0001.arw

Ideally, when using capture-image and retaining files on camera RAM, **all** files on the camera should be identified by --list-images and not just the files from the current "session". This would make the files available in gphoto and allow them to be downloaded (and deleted) as required.

I'm reasonably sure that this was the behaviour in an earlier version of gphoto/libphoto. I'll roll-back my versions, give it a try and report back.

**Comment by MikeTough** [comment]
Seems I have a cranial memory leak :) Earlier version (gphoto 2.5.15, libphoto 2.5.16) DO exhibit the same behaviour.

**Comment by doisyg** [comment]
> pi@raspberrypi:~ $ gphoto2 --capture-image --list-files
> New file is in location /capt0000.arw on the camera
> New file is in location /capt0000.arw on the camera
> New file is in location /capt0001.arw on the camera
> There are 2 files in folder '/'.
> #1 capt0000.arw 41740 KB 0x0 image/x-sony-arw
> #2 capt0001.arw
> pi@raspberrypi:~ $ gphoto2 --list-files
> There is no file in folder '/'.
> pi@raspberrypi:~ $

Experiencing the same behavior with a Sony Alpha 6300 (last dev version of gphoto2 and Ubuntu 16.04)

**Comment by parismorton** [comment]
I have an A7RII and cant seem to change the capture target to the SD card I put in. Do you know how to fix this?

**Comment by msmeissn** [comment]
SD card capture is not possible with the Sony Alpha cameras. This is a camera limitation currently.

**Comment by msmeissn** [comment]
So, the loss of images on close is due to the fact we need to download the images immediately to libgphoto2 RAM. So if you close the libgphoto2 program, the images will be gone.

I fixed the "Adding images named capt0000 twice" bug now in commit 2ff21c7b2cad90b19f681429f50ad1c42f5928e2 (libgphoto2 git)

That they vanish from the virtual filesystem within gphoto2 I need to review

**Comment by jordansissel** [comment]
I have a Sony a7iii and it _can_ do tethered capture to the camera's SD card.

`Menu> Setup4 > PC Remote Settings > Still Img Save Dest`

Setting this to "PC+Camera" will cause the camera to save to the SD card the images captured while tethering.

**Comment by ltraveler** [comment]
I have the same problem. I just bought a new gimbal for my sony A7RII. Gimball is connected to the camera by PC Connection method. The gimbal has his own buttons to record video and take pictures from the camera but I can only start a video recording using the button on the gimbal. When I am trying to take a photo camera can only focus on the object but not taking a picture. Is that any chance to avoid this limitation? I think on A7RIII sony have added an option where to save pictures    to the menu system. But probably there is a firmware hack that can change default behaviour of the camera like to save picture only on PC or only on the SD card. I really want to make my gimbal work properly.

**Comment by msmeissn** [comment]
good to hear that sony now allows that in newer cameras.

**Comment by msmeissn** [comment]
There is not much more for libgphoto2 to help here I am afraid.

**Comment by Construkted-Reality** [comment]
@MikeTough 

> HI,
> 
> I've run a few more tests and now think I have a better understanding of the issues.
> 
> First, it may be helpful if I explain what I'm trying to achieve.
> 
> I'm running ghoto2 in a rpi2/python environment.
> My camera is a Sony Alpha 7R II.
> I'm using gphoto2 v2.5.17 and libphoto2 v2.5.19 (updated today)
> My project will run gphoto2 through Jim Easterbrook's python/ghhoto2 API interface.
> 
> My objective/progress is to:
> 
> * Connect to camera (completed and working)
> * Adjust camera settings (completed and working - with minor warnings thrown by gphoto2)
> * Focus camera and retrieve focus complete signal (completed and working)
> * Capture several bursts of **bracketed** images to camera RAM (working, BUT gphoto2 issues)
> * Download images & delete from camera RAM (gphoto2 issues)
> 
> I'm really close (but no cigar) on the last two issues. There appear to be several issues/bugs within gphoto.

Hey @MikeTough 
Can you share how you achieved step 2 (Focus camera and retrieve focus complete signal) ?

I'm having a hard time figuring out how to focus the camera and obtain confirmation.

**Comment by 0ut5ider** [comment]
> HI,
> 
> I've run a few more tests and now think I have a better understanding of the issues.
> 
> First, it may be helpful if I explain what I'm trying to achieve.
> 
> I'm running ghoto2 in a rpi2/python environment.
> My camera is a Sony Alpha 7R II.
> I'm using gphoto2 v2.5.17 and libphoto2 v2.5.19 (updated today)
> My project will run gphoto2 through Jim Easterbrook's python/ghhoto2 API interface.
> 
> My objective/progress is to:
> 
> * Connect to camera (completed and working)
> * Adjust camera settings (completed and working - with minor warnings thrown by gphoto2)
> * Focus camera and retrieve focus complete signal (completed and working)
> * Capture several bursts of **bracketed** images to camera RAM (working, BUT gphoto2 issues)
> * Download images & delete from camera RAM (gphoto2 issues)
> 
> I'm really close (but no cigar) on the last two issues. There appear to be several issues/bugs within gphoto.

Hey @MikeTough 
Can you share how you achieved step 2 (Focus camera and retrieve focus complete signal) ?

I'm having a hard time figuring out how to focus the camera and obtain confirmation.
