### ISSUE TITLE
Canon EOS 600D slow capture

### ISSUE THREAD

**Issue by Pfluppe** [gphoto/gphoto2#155]
When the camera is set to manual mode 'M' and I use `--capture-image-and-download` it takes about 2 seconds until the camera takes the picture whereas when I have the camera set to the full automatic mode 'P' it triggers without any delay.
Please help!

**Comment by Pfluppe** [comment]
I'm running gphoto2 on a Raspberry Pi 3 Model B. Thanks in advance!
These are the logs:

[debug-automatic-mode.txt](https://github.com/gphoto/gphoto2/files/2237910/debug-automatic-mode.txt)
[debug-manual-mode.txt](https://github.com/gphoto/gphoto2/files/2237911/debug-manual-mode.txt)

**Comment by msmeissn** [comment]
in libgphoto2 2.5.12 we still had a loop of 2 seconds length waiting for focusing ... this was changed in 2.5.14 and later, so can you update libgphoto2 to a newer version, at least 2.5.14?

**Comment by Pfluppe** [comment]
Thanks for the advice. I updated everything but still there is the mentioned delay.
Here are the debug files, maybe they help:

[debug-automatic-mode-updated.txt](https://github.com/gphoto/gphoto2/files/2237958/debug-automatic-mode-updated.txt)
[debug-manual-mode-updated.txt](https://github.com/gphoto/gphoto2/files/2237959/debug-manual-mode-updated.txt)

**Comment by msmeissn** [comment]
We were still running into the 2 second wait, as no events were delivered for some reason.

I have now cut the default wait of manual focusing to 0.1 seconds in he "half-press => full press" transition.

**Comment by Pfluppe** [comment]
Thanks a lot, now it works flawlessly!

**Comment by Txtscr** [comment]
Hi, 
I have a very similar issue. I'm using the latest gphoto2 (I think 2.5.20) on a raspberry and a Canon 700D. No matter if I use 'P' or 'M' and setting auto focus to off - the delay is always around 0.5s. I've only set gphoto2 to save the photos on the camera card. Are there additional settings at the camera or additional config parameters for gphoto2 to reduce the delay?

**Comment by msmeissn** [comment]
check if you hve lates libgphoto2 using gphoto2 --version

**Comment by Txtscr** [comment]
I used the gphoto2 updater:
gphoto2 2.5.17 gcc, popt(m), exif, no cdk, no aa, no jpeg, no readline
libgphoto2 2.5.19 all camlibs, gcc, ltdl, EXIF
libgphoto2_port 0.12.0 iolibs: disk ptpip serial usb usbdiskdirect usbscsi, gcc, ltdl, USB, serial without locking

**Comment by Txtscr** [comment]
I have attached the debug file.

[debug-manual-no-autofocus.txt](https://github.com/gphoto/gphoto2/files/2636820/debug-manual-no-autofocus.txt)

there seems to be a long time gap from 30ms to 480ms at these commands:
0.038884 gp_abilities_list_load_dir  (2): Found 64 camera drivers.
0.482102 gp_port_info_list_count     (2): Counting entries (7 available)...

If this can't be changed then there might be an alternative way to reduce the delay:
Is there a gphoto2 command for half-pressing the button? Maybe the capture command is faster then.

Thanks!

**Comment by msmeissn** [comment]
you can use the "eosremoterelease" option to control the shutter button manually, so including half and full press / releases.

this delay you describe seems long, but I do not see it in the logfile you attached.

**Comment by MBoaretto25** [comment]
How can i use eosremoterelease?

I have a Canon 1200D, and whenever I set the eosremotereleasevalue it does not change.

gphoto2 --set-config eosremoterelease=3

**Comment by msmeissn** [comment]
it has multiple states, you also need to run wait-event to wait for its result.

This option causes "shutter button" action , so it is "write only", it cannot be read out.

gphoto2 --get-config eosremoterelease
only shows the button states available.

**Comment by MBoaretto25** [comment]
Thanks for the quick answer @msmeissn.

**Comment by msmeissn** [comment]
@Txtscr  as for 0.48 second delay ... the raspberry pi is just slow. You can remove some not needed drivers.

**Comment by crisodanniel** [comment]
Hi Marcus Im also having delay trigger and when tryinig to perform simultaneous trigger it doesnt do it simultaneous, it has a lag between the cameras, especially when shooting with flash on, im using 4 cannon T6 plugged into a powered usb hub, any advice to reduce the lag and make it real simultaneous trigger

**Comment by msmeissn** [comment]
Best way software side would have to use programs already being run and trigger them.

e.g. launch 
gphoto2 --camera "x" --port usb:Y --capture-image -F 1000 -I -1   
for all cameras / ports, note down the PIDs of gphoto2 and then use the SIGUSR 1 signal to trigger them with "kill -USR1 <PID>"

Or write a program that opens and inits all cameras, and then waits for the condition and runs gp_trigger_capture(...) for them?

There still be small delays, (hard to say how much ) ... 
The only real concurrent triggering will only be possible with hardware.
