### ISSUE TITLE
LiveView support for Sony Alpha 7 (ILCE-7)

### ISSUE THREAD

**Issue by norru** [gphoto/gphoto2#156]
Hello,

I am attempting to set up my Alpha 7 for tethering using DarkTable as the host program for GPhoto2. I am able to take captures but LiveView doesn't seem to be supported. All tethering support in DT is provided by GPhoto2.

Is there any reason for the feature being implemented for A7S or A7 III but not for the original first series? There are commercial packages which implement it for the ILCE-7 so it must be possible.

Many thanks!
Nico

**Comment by msmeissn** [comment]
can you try:
 gphoto2 --capture-preview 
and see if that works?

**Comment by norru** [comment]
```
env LANG=C gphoto2 --debug --debug-logfile=gphoto2-logfile.txt --capture-preview
                                                                               
*** Error ***              
PTP Timeout

*** Error ***              
An error occurred in the io-library ('Timeout reading from or writing to the port'): No error description available
*** Error (-10: 'Timeout reading from or writing to the port') ***    
```

**Comment by norru** [comment]
[gphoto2-logfile.txt](https://github.com/gphoto/gphoto2/files/2342465/gphoto2-logfile.txt)

**Comment by msmeissn** [comment]
The logfile shows only follow up hangs, sorry... can you take one after plugging the camrea in fresh?

If you look into it, it should not fail at
16.029197 camera_init [library.c:8236](0): 'ptp_opensession (params, sessionid)' failed: PTP Timeout (0x02fa)

That said, the Alpha 7 might not expose liveview to the remote host, it started only a bit later

**Comment by rektide** [comment]
@msmeissn I'm attaching a log for `gphoto2 --debug --capture-preview`, on an a7 ii:
[gphoto2-preview-log.txt](https://github.com/gphoto/gphoto2/files/2730194/gphoto2-preview-log.txt)

**Comment by msmeissn** [comment]
libgphoto2 2.5.10 is too old. We added liveview support in 2.5.13, so upgrade to a newer one ...

**Comment by VictorLamoine** [comment]
@msmeissn are you sure about this?
http://www.gphoto.org/proj/libgphoto2/support.php does not list `Sony Alpha-A7 (Control)` with LiveView.

I experience the same error, my libgphoto2 seems recent enough:
```bash
||/ Name                                      Version                   Architecture              Description
+++-=========================================-=========================-=========================-========================================================================================
un  libgphoto2-2-dev                          <none>                    <none>                    (no description available)
ii  libgphoto2-6:amd64                        2.5.16-2                  amd64                     gphoto2 digital camera library
ii  libgphoto2-dev:amd64                      2.5.16-2                  amd64                     gphoto2 digital camera library (development files)
ii  libgphoto2-l10n                           2.5.16-2                  all                       gphoto2 digital camera library - localized messages
un  libgphoto2-port10                         <none>                    <none>                    (no description available)
ii  libgphoto2-port12:amd64                   2.5.16-2                  amd64                     gphoto2 digital camera port library
```

---

```bash
sudo gphoto2 --debug --debug-logfile=my-logfile.txt --capture-preview
                                                                               
*** Error ***              
PTP Timeout

*** Error ***              
An error occurred in the io-library ('Timeout reading from or writing to the port'): No error description available
*** Error (-10: 'Timeout reading from or writing to the port') ***       
```
[my-logfile.txt](https://github.com/gphoto/gphoto2/files/4365868/my-logfile.txt)

**Comment by msmeissn** [comment]
I went and checked ... The older A7 just does not support liveview capture, it was introduced in newer models. Sorry, there is nothing we ca do here.
