### ISSUE TITLE
A7 III - Seconds Behind Schedule

### ISSUE THREAD

**Issue by SUPER-DAN** [gphoto/gphoto2#157]
When I do a simple command so the Sony A7 III captures 10 frames with interval of 2 seconds : gphoto2 --capture-image -F 10 -I 2 , there is always a message "2 seconds behind schedule" and not only that, it's for real taking 4 to 5 seconds between shots...

Once the shot is capture, I can see "Download progress bar".. but I don't understand what it's downloading and where as I am not specifying to capture and download the image locally and even there, I have the most expensive SD card UII that can write at 100MB+ per seconds.  I think it has to do with this progress bar reading, probably a checksum by Gphoto2 or something, but since the files are 49MB each, could we have a debug option so the image is not checked and just the action of triggering is sent to the camera.  I don't have this problem with an intervalometer, but I have written scripts (Raspberry Pi 3) for every moment of the day (fast cloud, sunrise, highway car lights at night).. all kind of scenario and this is where gphoto2 is more handy.

- Version of Gphoto2 : 2.5.17.1
- Autofocus is off
- AWB is custom
- ISO is manual
- Aperture is manual
- Shutter is manual
- Single-shot (capture mode)

Or any other reason why it's doing this?

**Comment by msmeissn** [comment]
The problem is it always needs to download the image , as the camrea only capture to its RAM for immediate download.

So card based speeds are not reachable :/
