### ISSUE TITLE
A7RII capturetarget setting not working

### ISSUE THREAD

**Issue by parismorton** [gphoto/gphoto2#158]
Hi,

Recently, I plugged in my A7RII to my RPI to remotely take photos. 

The issue is that instead of saving photos to the SD card, it's saving it to the RPI's RAM which is pretty bad considering its a 42 megapixel raw file. If I try to use the --get-config=capturetarget command, it says that capture target is not found in the configuration tree. What should I do? I'd appreciate any help.

Thanks.

**Comment by msmeissn** [comment]
this is a camera side limitation currently, so we can not support it.
