### ISSUE TITLE
Setting Max Focal Length Does Not Match to True Value

### ISSUE THREAD

**Issue by amadson** [gphoto/gphoto2#162]
The max focal length value set by gphoto2 does not correspond to the actual max value (when disconnected from the USB port). The camera is still capable of an increased focal length, but gphoto2 won't go beyond its "max" value.

I have seen [this](https://sourceforge.net/p/gphoto/mailman/message/34309868/) thread about the same issue. I have tried the suggestions at the end of that thread. 

"""
/main/other/5008
Label: Focal Length
Type: MENU
Current: 10500
Choice: 0 3500
Choice: 1 4600
Choice: 2 5300
Choice: 3 6100
Choice: 4 7300
Choice: 5 8600
Choice: 6 10500

This is the undecoded value (mm length * 100)

can you try if this moves the lens in the expected ranges:

gphoto2 --set-config 5008=4500
gphoto2 --set-config 5008=13500
"""

5008 only allows ints 0 - 6 and their corresponding values (3500, 4600, ...). When trying 'gphoto2 --set-config 5008=13500' it spits out an error and doesn't like the value... Below.

"""
*** Error ***              
The property 'Focal Length' / 0x5008 was not set (0x201c: PTP Invalid Device Prop Value).
"""

Thoughts on how to get the full zoom?

Outputs from --summary and --list-all-config are below.

Camera summary:                                                                
Manufacturer: Nikon Corporation
Model: S9700
  Version: COOLPIX S9700V1.0
  Serial Number: 000030044883
Vendor Extension ID: 0xa (1.0)
Vendor Extension Description: microsoft.com: 1.0; microsoft.com/DeviceServices:1.0;

Capture Formats: JPEG
Display Formats: Undefined Type, Association/Directory, Script, DPOF, MS Wave, Apple Quicktime, Defined Type, JPEG, JFIF

Device Capabilities:
	File Download, File Deletion, File Upload
	Generic Image Capture, No Open Capture, Nikon Capture 3

Storage Devices Summary:
store_00010001:
	StorageDescription: None
	VolumeLabel: None
	Storage Type: Removable RAM (memory card)
	Filesystemtype: Digital Camera Layout (DCIM)
	Access Capability: Read-Write
	Maximum Capability: 15468593152 (14752 MB)
	Free Space (Bytes): 15421669376 (14707 MB)
	Free Space (Images): 1920

Device Property Summary:
Battery Level(0x5001):(read only) (type=0x2) Enumeration [2,5,25,50,65,80,100] value: 100% (100)
Compression Setting(0x5004):(read only) (type=0x2) Enumeration [0,1,2] value: JPEG Fine (2)
F-Number(0x5007):(read only) (type=0x4) Enumeration [340,630] value: f/5.3 (530)
Focal Length(0x5008):(readwrite) (type=0x6) Enumeration [3500,4600,5300,6100,7300,8600,10500] value: 105 mm (10500)
Focus Mode(0x500a):(read only) (type=0x4) Enumeration [1,32784,32785,32786,32787] value: AF-S (32784)
Flash Mode(0x500c):(readwrite) (type=0x4) Enumeration [1,2,3,4] value: Flash off (2)
Exposure Program Mode(0x500e):(read only) (type=0x4) Enumeration [1,2,3,4,32784,32790,32792,32848,32849] value: P (2)
Date & Time(0x5011):(readwrite) (type=0xffff) '20180913T073959'
Property 0xd002:(readwrite) (type=0x6) Enumeration [2,3,4,5,6,7,8] value: 7
Property 0xd280:(read only) (type=0x2) 3
Live View AF Area(0xd05d):(read only) (type=0x2) Range [0 - 1, step 2] value: 2
Lens Sort(0xd0e1):(read only) (type=0x2) Range [0 - 1, step 1] value: 1
Nikon Exposure Time(0xd100):(read only) (type=0x6) Enumeration [65596] value: 65596
Live View Status(0xd1a2):(read only) (type=0x2) Range [0 - 1, step 1] value: No (0)
Live View Prohibit Condition(0xd1a4):(read only) (type=0x6) 0
Property 0xd1ac:(read only) (type=0x2) Enumeration [1,2] value: 1
Property 0xd24f:(readwrite) (type=0xffff) '0011223344556677'
Property 0xd250:(read only) (type=0xffff) '---'
Property 0xd251:(read only) (type=0xffff) '---'
Property 0xd407:(read only) (type=0x6) 1
Property 0xd303:(read only) (type=0x2) 1

/main/actions/autofocusdrive                                                   
Label: Drive Nikon DSLR Autofocus
Type: TOGGLE
Current: 0
/main/actions/controlmode
Label: Set Nikon Control Mode
Type: TEXT
Current: 0
/main/actions/viewfinder
Label: Nikon Viewfinder
Type: TOGGLE
Current: 0
/main/actions/opcode
Label: PTP Opcode
Type: TEXT
Current: 0x1001,0xparam1,0xparam2
/main/settings/datetime
Label: Camera Date and Time
Type: DATE
Current: 1536849655
Printable: Thu 13 Sep 2018 07:40:55 PDT
Help: Use 'now' as the current time when setting.

/main/settings/guid
Label: WLAN GUID
Type: TEXT
Current: 0011223344556677
/main/settings/fastfs
Label: Fast Filesystem
Type: TOGGLE
Current: 1
/main/settings/capturetarget
Label: Capture Target
Type: RADIO
Current: Internal RAM
Choice: 0 Internal RAM
Choice: 1 Memory card
/main/settings/autofocus
Label: Autofocus
Type: RADIO
Current: On
Choice: 0 On
Choice: 1 Off
/main/status/serialnumber
Label: Serial Number
Type: TEXT
Current: 000030044883
/main/status/manufacturer
Label: Camera Manufacturer
Type: TEXT
Current: Nikon Corporation
/main/status/cameramodel
Label: Camera Model
Type: TEXT
Current: S9700
/main/status/deviceversion
Label: Device Version
Type: TEXT
Current: COOLPIX S9700V1.0
/main/status/vendorextension
Label: Vendor Extension
Type: TEXT
Current: microsoft.com: 1.0; microsoft.com/DeviceServices:1.0;
/main/status/Battery Level
Label: Battery Level
Type: TEXT
Current: 100%
/main/capturesettings/flashmode
Label: Flash Mode
Type: RADIO
Current: Flash off
Choice: 0 Automatic Flash
Choice: 1 Flash off
Choice: 2 Fill flash
Choice: 3 Red-eye automatic
/main/capturesettings/f-number
Label: F-Number
Type: RADIO
Current: (null)
Choice: 0 f/3.4
Choice: 1 f/6.3
/main/capturesettings/imagequality
Label: Image Quality
Type: RADIO
Current: JPEG Fine
Choice: 0 JPEG Basic
Choice: 1 JPEG Normal
Choice: 2 JPEG Fine
/main/capturesettings/focallength
Label: Focal Length
Type: RANGE
Current: 105
Bottom: 35
Top: 105
Step: 1
/main/capturesettings/focusmode
Label: Focus Mode
Type: RADIO
Current: AF-S
Choice: 0 Manual
Choice: 1 AF-S
Choice: 2 AF-C
Choice: 3 AF-A
Choice: 4 Unknown value 8013
/main/capturesettings/expprogram
Label: Exposure Program
Type: RADIO
Current: P
Choice: 0 M
Choice: 1 P
Choice: 2 A
Choice: 3 S
Choice: 4 Auto
Choice: 5 Night Landscape
Choice: 6 Automatic (No Flash)
Choice: 7 Unknown value 8050
Choice: 8 Unknown value 8051
/main/capturesettings/shutterspeed2
Label: Shutter Speed 2
Type: RADIO
Current: 1/60
Choice: 0 1/60
/main/capturesettings/liveviewafmode
Label: Live View AF Mode
Type: RADIO
Current: Unknown value 0002
Choice: 0 Face-priority AF
Choice: 1 Unknown value 0002
/main/other/5001
Label: Battery Level
Type: MENU
Current: 100
Choice: 0 2
Choice: 1 5
Choice: 2 25
Choice: 3 50
Choice: 4 65
Choice: 5 80
Choice: 6 100
/main/other/5004
Label: Compression Setting
Type: MENU
Current: 2
Choice: 0 0
Choice: 1 1
Choice: 2 2
/main/other/5007
Label: F-Number
Type: MENU
Current: 530
Choice: 0 340
Choice: 1 630
/main/other/5008
Label: Focal Length
Type: MENU
Current: 10500
Choice: 0 3500
Choice: 1 4600
Choice: 2 5300
Choice: 3 6100
Choice: 4 7300
Choice: 5 8600
Choice: 6 10500
/main/other/500a
Label: Focus Mode
Type: MENU
Current: 32784
Choice: 0 1
Choice: 1 32784
Choice: 2 32785
Choice: 3 32786
Choice: 4 32787
/main/other/500c
Label: Flash Mode
Type: MENU
Current: 2
Choice: 0 1
Choice: 1 2
Choice: 2 3
Choice: 3 4
/main/other/500e
Label: Exposure Program Mode
Type: MENU
Current: 2
Choice: 0 1
Choice: 1 2
Choice: 2 3
Choice: 3 4
Choice: 4 32784
Choice: 5 32790
Choice: 6 32792
Choice: 7 32848
Choice: 8 32849
/main/other/5011
Label: Date & Time
Type: TEXT
Current: 20180913T074055
/main/other/d002
Label: PTP Property 0xd002
Type: MENU
Current: 7
Choice: 0 2
Choice: 1 3
Choice: 2 4
Choice: 3 5
Choice: 4 6
Choice: 5 7
Choice: 6 8
/main/other/d280
Label: PTP Property 0xd280
Type: TEXT
Current: 3
/main/other/d05d
Label: Live View AF Area
Type: RANGE
Current: 2
Bottom: 0
Top: 1
Step: 2
/main/other/d0e1
Label: Lens Sort
Type: MENU
Current: 1
Choice: 0 0
Choice: 1 1
/main/other/d100
Label: Nikon Exposure Time
Type: MENU
Current: 65596
Choice: 0 65596
/main/other/d1a2
Label: Live View Status
Type: MENU
Current: 0
Choice: 0 0
Choice: 1 1
/main/other/d1a4
Label: Live View Prohibit Condition
Type: TEXT
Current: 0
/main/other/d1ac
Label: PTP Property 0xd1ac
Type: MENU
Current: 1
Choice: 0 1
Choice: 1 2
/main/other/d24f
Label: PTP Property 0xd24f
Type: TEXT
Current: 0011223344556677
/main/other/d250
Label: PTP Property 0xd250
Type: TEXT
Current: ---
/main/other/d251
Label: PTP Property 0xd251
Type: TEXT
Current: ---
/main/other/d407
Label: PTP Property 0xd407
Type: TEXT
Current: 1
/main/other/d303
Label: PTP Property 0xd303
Type: TEXT
Current: 1

**Comment by msmeissn** [comment]
the camera reports those values to us, so if its not correct, the camera is incorrect here.

the error above is from the camera itself. you could try some other values around it, but if it reports only this range it seems to stay in it.

not sure why they did not report the full range

**Comment by amadson** [comment]
I have tried many other values around those that are listed. All of which end in the above error. 

Thanks for a prompt response.
