### ISSUE TITLE
update to latest version.

### ISSUE THREAD

**Issue by jaykim445** [gphoto/gphoto2#169]
Hello.
I have exactly same issue with this one #155 
and also wanted to upgrade latest version of libgphoto2 which is released on 27th oct.
I been searching like 10hours how to upgrade the this gphotos, but I just got stucked middle of somewhere.

Imported applications by ssh, `sudo apt-get install gphoto2` and
1) `sudo apt-get upgrade update' only gets gphoto2 for "2.5.11-1" version. 
libgphoto2 "2.5.12-1" version.
not getting any near to latest version.

2) uploading it filezilla.
downloaded zip file from homepage and directly uploaded by filezilla
and did `./configure` `make` `make install`
but at `make` stage it shows errors with this lines.

```
WARNING: 'aclocal-1.16' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <https://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <https://www.gnu.org/software/autoconf>
         <https://www.gnu.org/software/m4/>
         <https://www.perl.org/>
Makefile:545: recipe for target 'aclocal.m4' failed
```
Im new to this raspberry Pi, and sorry for my English skill..

All I want to do is just reduce 2seconds of delay when taking shots with M(Manual) mode on my Canon 600D.

**Comment by msmeissn** [comment]
I cant help with the raspberry build issue. you can check out a helper tool:

https://github.com/gonzalo/gphoto2-updater
