### ISSUE TITLE
Sony A5100 live view problem

### ISSUE THREAD

**Issue by jbonnett92** [gphoto/gphoto2#170]
Hi,
I can't seem to get live view to work:
```
$ gphoto2 --camera="Sony Alpha-A5100 (Control)" --capture-movie --stdout | ffmpeg -i pipe:0 http://localhost:8081/feed1.ffm
ffmpeg version 3.4.2 Copyright (c) 2000-2018 the FFmpeg developers
  built with Apple LLVM version 9.0.0 (clang-900.0.39.2)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.4.2 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --disable-jack --enable-gpl --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Capturing preview frames as movie to 'stdout'. Press Ctrl-C to abort.
ERROR: Movie capture error... Exiting.
Movie capture finished (0 frames)
```
It doesn't error until I visit the url `http://localhost:8081/feed1.ffm`.

**Comment by msmeissn** [comment]
does it capture a movie without this pipe?
or single previews?

**Comment by jbonnett92** [comment]
@msmeissn No it doesn't, it just times out

**Comment by jbonnett92** [comment]
`gphoto2 --camera="Sony Alpha-A5100 (Control)" --capture-preview --debug --debug-logfile=First.txt` [First.txt](https://github.com/gphoto/gphoto2/files/2596492/First.capture.preview.txt)

The screen had the live preview although I did not get any preview on the computer.
Without disconnecting the camera or turning it off I ran the same command and got a different error:

`gphoto2 --camera="Sony Alpha-A5100 (Control)" --capture-preview --debug --debug-logfile=Second.txt` [Second.txt](https://github.com/gphoto/gphoto2/files/2596505/Second.capture.preview.txt)

And then I did the same with `--capture-movie`:
`gphoto2 --camera="Sony Alpha-A5100 (Control)" --capture-movie --debug --debug-logfile=Third.txt` 
[Third.txt](https://github.com/gphoto/gphoto2/files/2596509/my-logfile-2.txt)

And 
`gphoto2 --camera="Sony Alpha-A5100 (Control)" --capture-movie --debug --debug-logfile=Fourth.txt` [Fourth.txt](https://github.com/gphoto/gphoto2/files/2596510/my-logfile-3.txt)

**Comment by msmeissn** [comment]
Sorry for losing track of this issue.

The getobject call is emitted and seems to never return, either it confused or crashed parts of the camera firmware.

I googled a bit and there is one report of using updated firmware making it better, but all others seem to imply there is no liveview on the 5100

**Comment by msmeissn** [comment]
so you can try to get the latest firmware and see if that brings help, but otherwise I think we are out of luck regarding liveview.

**Comment by msmeissn** [comment]
a friend of mine runs: http://www.storch-bleckmar.de/  wth a 5100, he has the firmware updated

**Comment by jbonnett92** [comment]
Sorry I don't actually have the A5100 anymore, I have the A6300.

**Comment by msmeissn** [comment]
ah ok. for this it works I assume? ;)

**Comment by jbonnett92** [comment]
Not sure I'll give it a try later :)

**Comment by msmeissn** [comment]
ok! open a new ticket if it does not work :)
