### ISSUE TITLE
some confusing code

### ISSUE THREAD

**Issue by WarmDay** [gphoto/gphoto2#171]
static GPContextFeedback
ctx_cancel_func (GPContext __unused__ *context, void __unused__ *data)
{
        if (glob_cancel) {
                return (GP_CONTEXT_FEEDBACK_CANCEL);
                glob_cancel = 0;
        } else
                return (GP_CONTEXT_FEEDBACK_OK);
}

why glob_cancel = 0 is behind return?

**Comment by msmeissn** [comment]
it has been this way for quite a while, but I flipped the two lines now
