### ISSUE TITLE
huge liveview speed difference on two different but similarly specced computers

### ISSUE THREAD

**Issue by notnot** [gphoto/gphoto2#172]
I am developing an application that controls a Sony a5100 camera. So far it all works well. I have liveview working in 1024x680 @ 25 Hz on one machine, and much to my surprise, the frame rate is only 4 to 5 Hz on another, slightly more powerful machine. 

```
---- machine: guru (25 Hz liveview) ------------------------------------------------------------------

ubuntu 16.04 LTS
kernel 4.15.0-39-generic

gphoto2         2.5.17         gcc, popt(m), exif, no cdk, no aa, jpeg, no readline
libgphoto2      2.5.19         all camlibs, gcc, ltdl, EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi, gcc, ltdl, USB, serial without locking

---- machine: airtist (5 Hz liveview) ---------------------------------------------------------------

ubuntu 18.04 LTS
kernel 4.15.0-20-generic

gphoto2         2.5.15         gcc, popt(m), exif, cdk, aa, jpeg, readline
libgphoto2      2.5.16         all camlibs, gcc, ltdl, EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi, gcc, ltdl, USB, serial without locking
```

So the two machines have slightly different software versions of some components. Could this explain the huge speed difference i am seeing? Capturing and downloading a full resolution photo is about equally fast on both machines. 

I will install a more recent libgphoto2 on the 'slow' machine soon.

**Comment by notnot** [comment]
After upgrading the slower computer to libgphoto2 version 2.5.20, it is up to speed. Thanks for the great work on this project!

**Comment by msmeissn** [comment]
good to hear! thank you :)
