### ISSUE TITLE
Failed to capture a photo via Sony A7R II camera.

### ISSUE THREAD

**Issue by juj** [gphoto/gphoto2#18]
Built libgphoto2 and gphoto2 on the following system

```
clb@giada:~$ uname -a
Linux giada 3.19.0-42-generic #48~14.04.1-Ubuntu SMP Fri Dec 18 10:24:49 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
clb@giada:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty
```

and connected Sony A7R II camera via usb, and ran `USB_DEBUG=1 gphoto2 --debug --capture-image --port usb:003,090`, which yielded the following log: http://pastebin.com/W6YyMnL4

In particular the errors: 

```
0.343502 gp_port_write               (3): Writing 16 = 0x10 bytes to port...
0.343738 gp_port_write               (3): Wrote   0 = 0x0 out of 16 bytes to port: (empty hexdump of empty buffer)
0.343752 ptp_usb_sendreq [usb.c:106] (0): PTP_OC 0x1002 sending req failed: wrote only 0 of 16 bytes
0.344426 gp_context_error            (0): PTP I/O Error

*** Error ***              
PTP I/O Error
0.344442 gp_port_close               (2): Closing port...
0.344496 gp_context_error            (0): An error occurred in the io-library ('I/O problem'): No error description available
```

Any ideas?

The camera was set to the "PC Remote" usb mode, which was tested to work and remote capture on Windows when using the Sony Remote Capture program, and the camera screen was showing "Connecting..." and "USB" text on it.

**Comment by juj** [comment]
Hmm, nuked the build and followed instructions at https://github.com/gonzalo/gphoto2-updater/blob/master/gphoto2-updater.sh, and now I got it working!

Notable differences are that the script from above uses libusb 1.0 instead of libusb 0.1, and there are some magic files that were written to `/etc/udev/rules.d/` and `/etc/udev/hwdb.d/` that I don't know if `sudo make install` did(?), but that got me going now.

Perhaps libusb 0.1 was too old to function? Or perhaps errors resulting from the magic files being missing are not detected?

**Comment by msmeissn** [comment]
This error is consistent with the GVFS slave of GNOME accessing the camera in parallel. (Only one program can access the camera at once, and gvfs grabs it as soon as it is plugged in.)

as the updater script removes the system libgphoto2 the gvfs gphoto2 monitor  probably not working anymore after running the script.

also ubuntu should switch the system one to usb 1.0 too, but this is probably unrelated.

**Comment by msmeissn** [comment]
was a blocked by gvfs issue
