### ISSUE TITLE
Capture movie setting not available for Nikkon D5000

### ISSUE THREAD

**Issue by MrGiskard** [gphoto/gphoto2#183]
Greetings,

I've been trying to capture video with a Nikkon D5000 but the "movie" setting does not come up in the list of configuration settings - I only get a "moviesound" setting which I presume merely configures whether the movie will have sound or not. The "movie" setting is available on a Nikkon D5100 and movie capture works without any issue. I would like to know, is there any way to capture video with a Nikkon D5000?

**Comment by msmeissn** [comment]
the d5000 does not have the movierecord option, sorry
