### ISSUE TITLE
Regarding gPhoto2 Detect On-Camera Setting Change Manually

### ISSUE THREAD

**Issue by sakibnaz** [gphoto/gphoto2#185]
Hi All.

Firstly I like to thank you for this great tool gPhoto2.

I am testing it with a Nikon D5100. Here I can control the Camera Settings over gPhoto2 CLI Commands. I like to know, is there any way to detect by gPhoto2 if any Camera Settings (like Shutter, F-Number, ISO etc) change On-Camera by user manually?

Regards.

**Comment by msmeissn** [comment]
--wait-event would report changed properties. these are not translated automatically, but --get-config would be updating itself

**Comment by bhjghjbhbfghfhfg** [comment]
> 大家好。
> 
> 首先，我要感谢 gPhoto2 这个很棒的工具。
> 
> 我正在用尼康 D5100 对其进行测试。在这里，我可以通过 gPhoto2 CLI 命令控制相机设置。我想知道，是否有任何方法可以通过 gPhoto2 检测是否有任何相机设置（如快门、F 值、ISO 等）由用户手动更改相机上的设置？
> 
> 问候。


Hello, I am trying to reset my Nikon D750 camera shutter times, can you add your contact information, my email address is 514130142@qq.com, thank you, I want to ask you, camera enthusiast!

**Comment by msmeissn** [comment]
original issue is meanwhile solved, wait-event reports also decoded names now.

what do you mean shutter times?  
for shutterspeed you can use the respective config variables named shutterspeed or shutterspeed2.

number of shutter counter release times? this is not possible with gphoto2.
