### ISSUE TITLE
Nikon Coolpix P80 "PTP Invalid Object Handle" when downloading image

### ISSUE THREAD

**Issue by toxygen** [gphoto/gphoto2#187]
Can't download any image from Nikon Coolpix P80. Neither via -P  nor --capture-image-and-download. See attached logs for details. Camera does take picture when commanded via gphoto.

[capture.txt](https://github.com/gphoto/gphoto2/files/2716888/capture.txt)
[download.txt](https://github.com/gphoto/gphoto2/files/2716889/download.txt)

**Comment by toxygen** [comment]
Actually the camera is Nikon Coolpix l14 misidentified as P80

**Comment by msmeissn** [comment]
its strange. we can query the objectinfo just fine, but the final download reports this error :/

if you want to test:

can you remove |PTP_NIKON_BROKEN_CAP from the line in:
libgphoto2/camlibs/ptp2/  
?
library.c:      {"Nikon:Coolpix P80 (PTP mode)",  0x04b0, 0x016b, PTP_CAP|PTP_NIKON_BROKEN_CAP},

This will swi tch it to event based image detection, which according to your logfile works... 

(That P80 and L14 are confused is not a problem.)

**Comment by toxygen** [comment]
No luck. See attachment.
[capture.txt](https://github.com/gphoto/gphoto2/files/2752260/capture.txt)

**Comment by msmeissn** [comment]
the access pattern is okay, the GetObjectInfo (0xe0004) returns valid and good data, but the GetObject(0xe0004); does not .
we even wait for capturecomplete event (0x400d) before accessing.

This are the very basic PTP access methods that always should work. :/

I am afraid the camera is just a bit buggy :/

**Comment by toxygen** [comment]
I tried to read the pictures on the camera and it didn't work either. It turns out the SD card filesystem was corrupted. Once formatted, it works alright!

**Comment by msmeissn** [comment]
good to hear it works! :)
