### ISSUE TITLE
Camera Quits Responding After Taking Photos

### ISSUE THREAD

**Issue by nickjdunn** [gphoto/gphoto2#19]
I'm rather new to gphoto and I have an issue that I hope someone can help me troubleshoot.  I have a Nikon S6200 which works in PTP mode and have wrote a script for a photo booth for a friends wedding.  It seems after shooting approximately 15 photos the camera just quits responding.  To make sure it wasn't an error somewhere else in the Photo booth program I wrote a script to only capture and downloads images one after another and about 15 photos in it snaps a picture and then just hangs there not downloading anything.  Also the camera remains on so I know it hasn't automatically powered down.  Any help diagnosing would be appreciated.

**Comment by msmeissn** [comment]
can you grab some form of debug trace? add --debug --debug-logfile=xx.log  to the gphoto2 commandline. you might need to strip out the larger image data blobs

**Comment by msmeissn** [comment]
no response :/
