### ISSUE TITLE
How to remove delay after downloading image?

### ISSUE THREAD

**Issue by minw428** [gphoto/gphoto2#190]
Hello,
First of all, following is the version table
gphoto2         2.5.11         gcc, popt(m), exif, cdk, aa, jpeg, readline
libgphoto2      2.5.12         all camlibs, gcc, ltdl, EXIF
libgphoto2_port 0.12.0         gcc, ltdl, USB, serial without locking

I'm facing a strange problem that the --capture-image command takes about 6 secs.
[gphoto2.log.zip](https://github.com/gphoto/gphoto2/files/2730297/gphoto2.log.zip)

As I see, file creation was done about 2 secs later.
1.919491 lookup_folder_file          (2): Lookup folder / file capt0000.jpg
1.919503 lookup_folder               (2): Lookup folder '/'...
1.919515 lookup_folder               (2): Found! / is 0x5f4b20

But freeing camera is much more later..
5.226341 gp_camera_free              (2): Freeing camera...

How can I speed up this?

**Comment by msmeissn** [comment]
The gphoto2 commandline tool is wairting 3 seconds for a potential secondary image here. 
we would either need to find out if capture is completed in another form, or somehow detect we will not need to download a secondary image. :/

**Comment by msmeissn** [comment]
gphoto2/main.c   
        waittime = 3000;

**Comment by minw428** [comment]
> gphoto2/main.c
> waittime = 3000;

Is there any problem if I set lower value such as 100?
Actually I tested with 100, but encountered following problem..

*** Error ***              
An error occurred in the io-library ('Could not lock the device'): Camera is already in use.
*** Error (-60: 'Could not lock the device') ***

**Comment by minw428** [comment]
> changing it to 100 is fine.
> 
> this camera in use is likely a different problem, where gvfs grabs the camera or similar. remove the gvfs gphoto parts

Actually, It was not even there is nothing related gvfs.

But, one strange thing, If I enter ps aux command, I can see the gphoto2 capture command which is still on process.. So I'll test with original 3000 delay value.

**Comment by msmeissn** [comment]
changing it to 100 is fine.

this camera in use is likely a different problem, where gvfs grabs the camera or similar. remove the gvfs gphoto parts

**Comment by msmeissn** [comment]
"S" means "sleep" so it is still running and waiting for something

**Comment by minw428** [comment]
I think there were some missing(or ignored by camera) command such as press shutter or something else.
