### ISSUE TITLE
Powershot G5X can't capture, lens not extracting

### ISSUE THREAD

**Issue by unix0r** [gphoto/gphoto2#191]
Hey guys,

trying to get the current gphoto2 and libgphoto2 version running with a raspberry pi and my Canon Powershot G5X.
```
pi@photobox:~ $ gphoto2 -v
gphoto2 2.5.20

Copyright (c) 2000-2018 Lutz Mueller and others

gphoto2 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of gphoto2 under the terms of the GNU General Public
License. For more information about these matters, see the files named COPYING.

This version of gphoto2 is using the following software versions and options:
gphoto2         2.5.20         gcc, popt(m), exif, no cdk, no aa, jpeg, no readline
libgphoto2      2.5.22         all camlibs, gcc, ltdl, no EXIF
libgphoto2_port 0.12.0         gcc, ltdl, USB, serial without locking

```

The camera is connected via usb and gphoto finds it:

```
pi@photobox:~ $ gphoto2 --auto-detect
Model                          Port                                            
----------------------------------------------------------
Canon PowerShot G5X            usb:001,011
```
As soon as the USB is connected, the camera switches to the view mode (last image is displayed in the display).
Turning on the capture mode does not work for me with:
`gphoto2 --set-config capture=on`

The camera just does nothing.
Trying to capture something ends with:
```

pi@photobox:~ $ gphoto2 --capture-image
                                                                               
*** Error ***              
Canon EOS M Full-Press failed (0x2019: PTP Device Busy)
ERROR: Could not capture image.
ERROR: Could not capture.
*** Error (-110: 'I/O in progress') ***       

For debugging messages, please use the --debug option.
Debugging messages may help finding a solution to your problem.
If you intend to send any error or debug messages to the gphoto
developer mailing list <gphoto-devel@lists.sourceforge.net>, please run
gphoto2 as follows:

    env LANG=C gphoto2 --debug --debug-logfile=my-logfile.txt --capture-image

Please make sure there is sufficient quoting around the arguments.
```
The mylog file from the debug run:
[my-logfile.txt](https://github.com/gphoto/gphoto2/files/2730783/my-logfile.txt)

Any ideas how images can be captured with my camera?

Thank you :-)

**Comment by call-me-matt** [comment]
Oh, good to see that I am not the only one trying this. With the help of @msmeissn and a lot of try and error I achieved to retract the lenses and shoot and transfer a picture! Unfortunately the camera freezes afterwards.
More information here: https://github.com/gphoto/libgphoto2/issues/344

**Comment by call-me-matt** [comment]
Good news, I found the comment that crashes the operation, see the linked issue above.
Maybe someone knows how to integrate this into gphoto2?

**Comment by unix0r** [comment]
fixed together with: https://github.com/gphoto/libgphoto2/issues/344
