### ISSUE TITLE
Regarding Change Camera Mode by CLI

### ISSUE THREAD

**Issue by sakibnaz** [gphoto/gphoto2#194]
Hi All.

Is it possible to change the Camera Mode over gPhoto2 CLI? I understand Mode (Auto, Manual, Av, Tv,  Bulb) needs physical knob dial on the Camera Body. But just wondering if there any way to do by CLI in Camera Software Level.

Thanks in advance.

Regards.

**Comment by msmeissn** [comment]
That depends on the camera mostly ... I think some allow it, but not all.

**Comment by sakibnaz** [comment]
Thank you for reply.
