### ISSUE TITLE
Cannot find viewfinder (release the mirror) on Canon S3 IS?

### ISSUE THREAD

**Issue by sdaau** [gphoto/gphoto2#195]
On http://www.gphoto.org/doc/remote/ it is stated:

> Camera Name | Libgphoto2 capture support | Controllable aspects | Megapixel | Notes
> ...
> Canon PowerShot S3 IS | Yes | All, Viewfinder | 6 | confirmed by Canon

So, I'm trying the S3 IS, connected via USB on Ubuntu 18.04. Turn on the camera, then unmount the "Canon Digital Camera" that appears. Then I do:

```
$ env LANG=C gphoto2 --debug --debug-logfile=my-logfile1.txt --capture-preview
Saving file as capture_preview.jpg 
```

Here, the camera extends the lens, and I guess, as they call it "raises mirror"; it snaps the photo, and the `capture_preview.jpg` is fine/as expected.

Now, I want to do [How to release the mirror after capture-preview shell command? · Issue #165 · gphoto/gphoto2 · GitHub](https://github.com/gphoto/gphoto2/issues/165) (via [gp_camera_capture_preview locks the mirror (EOS 750d) · Issue #121 · gphoto/gphoto2 · GitHub](https://github.com/gphoto/gphoto2/issues/121)), which mentions `set-config viewfinder=0`. So I try:

```
$ env LANG=C gphoto2 --debug --debug-logfile=my-logfile2.txt --set-config viewfinder=0
                                                                               
*** Error ***              
viewfinder not found in configuration tree.
*** Error (-1: 'Unspecified error') ***       
```

Is it possible to get access to `viewfinder` for Canon S3 IS, and if so, how? If not, is there an alternative command that will let me close the viewfinder/release the mirror on Canon S3 IS?

The logfiles from the above commands are attached:

[my-logfile1.txt](https://github.com/gphoto/gphoto2/files/2786676/my-logfile1.txt)
[my-logfile2.txt](https://github.com/gphoto/gphoto2/files/2786677/my-logfile2.txt)

**Comment by msmeissn** [comment]
--set-config capture=0 

should retract the lens

**Comment by sdaau** [comment]
Many thanks @msmeissn:

> --set-config capture=0
>
> should retract the lens

Indeed, it does! Thanks a lot, I guess I can close this now.
