### ISSUE TITLE
autoreconf fails: couldn't open directory 'm4m'

### ISSUE THREAD

**Issue by pauledd** [gphoto/gphoto2#2]
Hi there, 
I tried to install gphoto2 only, from its directory. Steps I did:
(libgphoto2 is already installed)
"svn checkout svn://svn.code.sf.net/p/gphoto/code/trunk gphoto-code"
"cd gphoto-code/gphoto2"
The README in there tells me to run:
"autoreconf -is"
and I get the error:
"aclocal-1.15: error: couldn't open directory 'm4m': Datei oder Verzeichnis nicht gefunden (not found)
autoreconf-2.69: aclocal failed with exit status: 1"
What am I doing wrong?

**Comment by msmeissn** [comment]
this means the svn externals were not resolved. can you run "svn up" in the gphoto-code subdirectory?

btw, current development happens here at github, so you clone gphoto from here.

**Comment by pauledd** [comment]
Ok thank you, from now on I clone from github. I just tried it and it works. 
greets
Paul
PS:
For the sake of completeness here is what I get when doing svn up from that old clone:

>paul@Wurst ~/build/gphoto-code $ svn up
Updating '.':
Redirecting to URL 'https://svn.code.sf.net/p/gphoto/code/trunk/m4':
Fetching external item into 'gphoto-suite/m4m':
External at revision 15513.
Redirecting to URL 'https://svn.code.sf.net/p/gphoto/code/trunk/m4':
Fetching external item into 'gphotofs/m4m':
External at revision 15513.
Fetching external item into 'libgphoto2/m4m':
External at revision 15513.
Redirecting to URL 'https://svn.code.sf.net/p/gphoto/code/trunk/m4':
Fetching external item into 'obsolete/gphoto-suite-all/m4m':
External at revision 15513.
Redirecting to URL 'https://svn.code.sf.net/p/gphoto/code/trunk/m4':
Fetching external item into 'gphoto2-manual/m4m':
External at revision 15513.
Redirecting to URL 'https://svn.code.sf.net/p/gphoto/code/trunk/libgphoto2':
Fetching external item into 'gphoto-suite/src/libgphoto2':
Fetching external item into 'gphoto-suite/src/libgphoto2/libgphoto2_port/m4':
External at revision 15513.
Fetching external item into 'gphoto-suite/src/libgphoto2/m4m':
External at revision 15513.
At revision 15513.
Redirecting to URL 'https://svn.code.sf.net/p/gphoto/code/trunk/gphoto2':
Fetching external item into 'gphoto-suite/src/gphoto2':
svn: warning: W000111: Unable to connect to a repository at URL 'https://svn.gphoto.sf.net/p/gphoto/code/trunk/m4'
At revision 15513.
Redirecting to URL 'https://svn.code.sf.net/p/gphoto/code/trunk/bindings/libgphoto2-sharp':
Fetching external item into 'gphoto-suite/src/libgphoto2-sharp':
Redirecting to URL 'https://svn.code.sf.net/p/gphoto/code/trunk/m4':
Fetching external item into 'gphoto-suite/src/libgphoto2-sharp/m4m':
External at revision 15513.
At revision 15513.
Redirecting to URL 'https://svn.code.sf.net/p/gphoto/code/trunk/gphotofs':
Fetching external item into 'gphoto-suite/src/gphotofs':
Redirecting to URL 'https://svn.code.sf.net/p/gphoto/code/trunk/m4':
Fetching external item into 'gphoto-suite/src/gphotofs/m4m':
External at revision 15513.
At revision 15513.
Redirecting to URL 'https://svn.code.sf.net/p/gphoto/code/trunk/bindings/libgphoto2-python':
Fetching external item into 'gphoto-suite/src/libgphoto2-python':
Redirecting to URL 'https://svn.code.sf.net/p/gphoto/code/trunk/m4':
Fetching external item into 'gphoto-suite/src/libgphoto2-python/m4m':
External at revision 15513.
At revision 15513.
Fetching external item into 'obsolete/gphoto-suite-all/src/libusb':
External at revision 661.
Redirecting to URL 'https://svn.code.sf.net/p/gphoto/code/trunk/gphoto2':
Fetching external item into 'obsolete/gphoto-suite-all/src/gphoto2':
svn: warning: W000111: Unable to connect to a repository at URL 'https://svn.gphoto.sf.net/p/gphoto/code/trunk/m4'
At revision 15513.
Redirecting to URL 'https://svn.code.sf.net/p/gphoto/code/trunk/libgphoto2':
Fetching external item into 'obsolete/gphoto-suite-all/src/libgphoto2':
Fetching external item into 'obsolete/gphoto-suite-all/src/libgphoto2/libgphoto2
_port/m4':
External at revision 15513.
Fetching external item into 'obsolete/gphoto-suite-all/src/libgphoto2/m4m':
External at revision 15513.
At revision 15513.
Redirecting to URL 'https://svn.code.sf.net/p/gphoto/code/trunk/gphotofs':
Fetching external item into 'obsolete/gphoto-suite-all/src/gphotofs':
Redirecting to URL 'https://svn.code.sf.net/p/gphoto/code/trunk/m4':
Fetching external item into 'obsolete/gphoto-suite-all/src/gphotofs/m4m':
External at revision 15513.
At revision 15513.
Redirectin to URL 'https://svn.code.sf.net/p/gphoto/code/trunk/gphoto2-manual':
Fetching external item into 'obsolete/gphoto-suite-all/src/gphoto2-manual':
Redirecting to URL 'https://svn.code.sf.net/p/gphoto/code/trunk/m4':
Fetching external item into 'obsolete/gphoto-suite-all/src/gphoto2-manual/m4m':
External at revision 15513.
At revision 15513.
Redirecting to URL 'https://svn.code.sf.net/p/gphoto/code/trunk/gtkam':
Fetching external item into 'obsolete/gphoto-suite-all/src/gtkam':
Redirecting to URL 'https://svn.code.sf.net/p/gphoto/code/trunk/m4':
Fetching external item into 'obsolete/gphoto-suite-all/src/gtkam/m4m':
External at revision 15513.
At revision 15513.
Redirecting to URL 'https://svn.code.sf.net/p/gphoto/code/trunk/m4':
Fetching external item into 'bindings/libgphoto2-sharp/m4m':
External at revision 15513.
svn: warning: W200000: Error handling externals definition for 'gphoto2/m4m':
svn: warning: W000111: Unable to connect to a repository at URL 'https://svn.gphoto.sf.net/p/gphoto/code/trunk/m4'
Redirecting to URL 'https://svn.code.sf.net/p/gphoto/code/trunk/m4':
Fetching external item into 'gtkam/m4m':
External at revision 15513.
Redirecting to URL 'https://svn.code.sf.net/p/gphoto/code/trunk/m4':
Fetching external item into 'bindings/libgphoto2-python/m4m':
External at revision 15513.
Fetching external item into 'libgphoto2/libgphoto2_port/m4':
External at revision 15513.
At revision 15513.
svn: E205011: Failure occurred processing one or more externals definitions
