### ISSUE TITLE
I/O Problem with Canon EOS 350D /Raspberry Pi 3/

### ISSUE THREAD

**Issue by schoeberlt** [gphoto/gphoto2#20]
Hello!

I installed gphoto2 using this script: [https://github.com/gonzalo/gphoto2-updater/](url) on my Raspberry Pi 3 (distro is the newest Rasbian).
I connected my Canon EOS 350D camera with the standard USB cable, and tried to --capture-image but I got the following message:

> *** Error ***              
> An error occurred in the io-library ('I/O problem'): No error description available
> ERROR: Could not capture image.
> ERROR: Could not capture.
> 
> *** Error ***              
> An error occurred in the io-library ('I/O problem'): No error description available

--auto-detect works:

> Model                          Port                                            
> ----------------------------------------------------------
> Canon Digital Rebel XT (normal mode) usb:001,004     

--list-config does not:

> *** Error ***              
> An error occurred in the io-library ('I/O problem'): No error description available
> *** Error (-7: 'I/O problem') ***       
> 
> For debugging messages, please use the --debug option.
> Debugging messages may help finding a solution to your problem.
> If you intend to send any error or debug messages to the gphoto
> developer mailing list <gphoto-devel@lists.sourceforge.net>, please run
> gphoto2 as follows:
> 
>     env LANG=C gphoto2 --debug --debug-logfile=my-logfile.txt --list-config
> 
> Please make sure there is sufficient quoting around the arguments.

I attached the logfile.
[my-logfile.txt](https://github.com/gphoto/gphoto2/files/170413/my-logfile.txt)

(Camera is in normal mode because it does not support in PTP.)

Please help!

**Comment by msmeissn** [comment]
0.168851 gp_libusb1_open [libusb1.c:375](0): 'libusb_open (port->pl->d, &port->pl->dh)' failed: Access denied (insufficient permissions) (-3)

not sure how the permission handling on raspi works, the camera node in /dev/bus/usb/xxx/yyy need to be accessible for the user.

udev or hwdb rules are used in modern Linux distributions

**Comment by MaximilianBrunner** [comment]
You have to google "gphoto2 usb permission".
But for now just kill all processes with the letters "fs" in them before starting gphoto.

**Comment by schoeberlt** [comment]
Well, it works! I ran the commands with sudo and just works! (shame that I did not figure this out before, I'm newbie with linux...)

**Comment by msmeissn** [comment]
nice to hear that it helped :)

**Comment by mctobiaso123** [comment]
Hi,
same Problem with I/O here. 
Nice to hear that it is working!
Which commands solved your Problem #schoeberlt?
Thx a lot!

**Comment by schoeberlt** [comment]
As I remember, I use every gphoto command with "sudo", but for the very first time I get an error message, but after that it works. I'll check as soon as I get home and give more details.

**Comment by mctobiaso123** [comment]
Hi,
Unfortunately (e.g.) sudo gphoto2 --capture-image haven´t worked, too. I got same Error again, caused by I/O.
I hope you used another "trick".
Thanks for help so far!

**Comment by mctobiaso123** [comment]
Hi,
sudo gphoto2 --capture-image leads to I/O-Problem again.
Maybe you used another command?
Thanks for helping!

**Comment by schoeberlt** [comment]
Hi,
have you tried changing the camera mode? Which EOS do you have? I don't remember exactly but (hopefully ;) ) I'll try the system this afternoon.

**Comment by mctobiaso123** [comment]
Yes, i already changed from PTP-Mode to PC Connection, this should be ok.
Canon EOS 350D, so it should work the same way as your system does.

**Comment by schoeberlt** [comment]
Look, I don't have my camera with me, I gotta get it tomorrow. [http://www.gphoto.org/doc/remote/](This doc is very useful.) Some thing you can try: 1. Set the camera mode to PTP-Mode. I'm not sure but I think that's the way I used it. 2. Go through these config commands you find in the doc. e.g: --list-config
Again, I remember that when I connect it to the Pi, for the very first time I get an error but the second try it succeeds. Good luck, I'll write the exact way I use it tomorrow afternoon

**Comment by mctobiaso123** [comment]
It´s working!
I forgot to update gphoto2 2.5.10

$ wget https://raw.githubusercontent.com/gonzalo/gphoto2-updater/master/gphoto2-updater.sh && chmod +x gphoto2-updater.sh && sudo ./gphoto2-updater.sh

Afterwards the commands sudo gphoto2 --capture-image and sudo gphoto2 --capture-image-and-download worked!

Thank you very much vor helping!!!

**Comment by schoeberlt** [comment]
Nice to hear that it works! I was just setting up the Pi and the Camera, but then I'm glad to hear that it works.
Have fun!

**Comment by andi34** [comment]
Got the report someone using my OpenSource Photobooth Project had the same issue.

We've got it solved by adding the following to the udev rules:

```
SUBSYSTEM=="usb", ATTRS{idVendor}=="04a9", ATTRS{idProduct}=="30ee", GROUP="plugdev", MODE="0666"
```

**Comment by msmeissn** [comment]
this fix just gives out permissions , which it should have done already before
