### ISSUE TITLE
geotagging photos

### ISSUE THREAD

**Issue by pdeman** [gphoto/gphoto2#200]
Hi,

is there a possibility to geotag photos directly using gphoto ?
using the gps of the camera or using gps coordinate from another device ?

Regards,

**Comment by msmeissn** [comment]
This is not possible currently. 

So far I dont know a camera that gives back its GPS location except in the images themselves as EXIF.

For external tagging a script or other tool should be used I think.

**Comment by amirhosseingholami** [comment]
Hi 
Is there a new possibility to geotag photos directly using gphoto2 ?
Best regards

**Comment by msmeissn** [comment]
no, we also do not plan to add this functionality at this time.

it could be done with wrapper scripts or wrapper tooling around gphoto2.
