### ISSUE TITLE
--get-config  capturetarget canon 

### ISSUE THREAD

**Issue by maxbcn** [gphoto/gphoto2#201]
Hello Marcus
-today I am working with a canon 600D

gphoto 2.5.20
libgphoto2 2.5.4
I am doing this comand and the results is :

pi@raspberrypi:~$ gphoto2 --get-config  capturetarget
gphoto2: symbol lookup error: gphoto2: undefined symbol: gp_camera_get_single_config

I can not change the capturetarget.
Can you help me with this , please

Thank you

**Comment by msmeissn** [comment]
you are using a too old not maching libgphoto2, you need to install a newer one.

**Comment by maxbcn** [comment]
Hello
each time to try to reinstall libgphoto2 , a new version , it reinstall 2.5.4 by default
I can not get the way to install new version of it

**Comment by chalmersb** [comment]
@maxbcn I'm not sure if you're still having this problem, but I see that you're using a raspberry pi. If you have a Raspbian operating system, the old version of libgphoto2 comes already installed. You have to remove the old libgphoto2 for the new libgphoto2 to work. 

Type this into the terminal:
dpkg --list | grep gphoto2

This will let you see all of the packages that came with the system with the string "gphoto2" in it. You should see libgphoto2-6 and libgphoto2-port12. If the names of libgphoto2 and libgphoto2-port have different numbers or anything, you should use that name to remove them.

To get rid of the old libgphoto2, type this into the terminal:
sudo apt-get --purge remove libgphoto2-6
sudo apt-get --purge remove libgphoto2-port12

Try gphoto2 --version, and hopefully now the new version of libgphoto2 will be listed.

**Comment by msmeissn** [comment]
Hopefully fixed now, nothing we can directly help with.
