### ISSUE TITLE
I/O Problem on MacBook Pro Late 2013 (El Capitan OSX)

### ISSUE THREAD

**Issue by prasojo** [gphoto/gphoto2#21]
Firstly, i would like to say thank you for this great effort to make this cool stuff, this is exactly what i need to play with my camera :+1:

this component runs smoothly on iMac late 2013 (use Yosemite), but still got no luck when i try to run gphoto2 commands on my MacBook Pro Late 2013 (use OSX El Capitan). both computer use MacPorts to install gphoto2.

any help will be appreciated, thanks :)

below is log from my attempt to run  `gphoto2 --capture-image` on MBP

[capture_image.txt](https://github.com/gphoto/gphoto2/files/171513/capture_image.txt)

**Comment by msmeissn** [comment]
It fails to send anything to the camera and times out during write. It is not obvious why ... :/ The PTPCamera process is not blocking the camera?

**Comment by prasojo** [comment]
i'm not sure it's blocked. PTPCamera has stopped before gphoto2 command calls, the error would be `...'Could not claim the USB device'...` if PTPCamera process is running. 

been succeed to built gphoto2 and libgphoto2 from source and install it, but the result still the same.

this might not be a good approach, but i'm planning to do a clean install on my computer before run another test, i'll let you know the result if you want.
