### ISSUE TITLE
get-config viewfinder not returning correct value

### ISSUE THREAD

**Issue by JamesG-J** [gphoto/gphoto2#210]
After setting viewfinder with `--set-config viewfinder=1`, and reading with `--get-config viewfinder`, gphoto returns:
```
Label: Canon EOS Viewfinder                                                    
Readonly: 0
Type: TOGGLE
Current: 2
END
```

Same behaviour with different values for viewfinder and different cameras (Canon T6i, T7i/750D, 80D)

gphoto2         2.5.17         gcc, popt(m), exif, no cdk, no aa, jpeg, no readline
libgphoto2      2.5.18         all camlibs, gcc, ltdl, EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi, gcc, ltdl, USB, serial without locking

**Comment by msmeissn** [comment]
This was currently not implemented , as we can set it with a command, but not really query it from the camera. Hmm. Perhaps i can return the internal state here.
