### ISSUE TITLE
Sony a5100 capture and download command does not terminate

### ISSUE THREAD

**Issue by Brechtjeu** [gphoto/gphoto2#216]
**Describe the bug**

Running a simple python script:
```import time
from os import system
ID = 0;
for ID in range(0,500):
        system("gphoto2 --capture-image-and-download --debug --debug-logfile=debug.log --force-overwrite --filename images/"+ str(ID).zfill(4) + ".jpg")
        print("captured image: " + str(ID).zfill(4))
        time.sleep(2)`
```
after some time this results in a call that never terminates. The linux terminal reports 'Deleting file /capt0000.jpg' as it's last line, which is completely normal, only it does never terminate the process afterwards. The problem is kind of resolved when i press ctrl+c, then the terminal reports 

>cancelling...

or

> cancelling... 
*** Error ***              
PTP Cancel Request

and the program happily continuous. I have not yet found a way to do this in code, the resetting. Although it should probably just not occur. Now it seems to occur once every 50 images or so.

It might be related to issue #133 but I'm not quite sure, I have experienced the same problem with autofocus, where the camera is to slow to focus and the whole camera gets messed up, although that's another problem where i will try to collect data for on another occasion.

EDIT: #192 seems to be the same issue, altough my logfiles contain date I provided them none the less. I can no update to the latest git release of  libgphoto2 as it doesn't seem to terminate the proccess ever, as in every picture has a problem similar to what i'm discribing here

**Name the camera**
Sony Alpha-A5100 (Control)     usb:001,044

**libgphoto2 and gphoto2 version**
gphoto2         2.5.20         gcc, popt(m), exif, no cdk, no aa, no jpeg, no readline
libgphoto2      2.5.22         all camlibs, gcc, ltdl, EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb usbdiskdirect usbscsi, gcc, ltdl, USB, serial without locking

**To Reproduce**
run a similar script that keeps capturing an downloading images until the sony camera gets stuck

[logs](https://drive.google.com/file/d/1ziEEaNhl0mH5QQbrSuL-ExuoRCrtmpX_/view?usp=sharing)

warning, huge log file, the first one is about 200mb, where it got stuck on the last photo. the second one is 1.6gb, it got stuck about 3 times (last one was around the 115-116 picture, near the end of the file probably) where I used the cancel trick each time to 'reset' the process and let my program continue. in zip it is about 800 mb

**Comment by msmeissn** [comment]
One thing this shows out tha tyou build with libusb0 and not libusb1.

Please build libgphoto2 against libusb1, it has better asynchronous event handling.

The stall you see might be related to that, one endpoint might be stalled and not making progress.

**Comment by Brechtjeu** [comment]
Thanks for the quick responce!
How does one go about building libgphoto2 against libusb1? I'm fairly new to the world of linux and building things, and I assume i wouldn't be the only one who has done this.  I think I used [gphoto-updater](https://github.com/gonzalo/gphoto2-updater) this time around

**Comment by msmeissn** [comment]
depending on distribution can you install libusb-1_0-devel , libusb1-dev or similary named development package?

If he distribution allows searching for packages, check that for thiose names.

Afetrwards run the gphoto updater again
