### ISSUE TITLE
Python hook script 

### ISSUE THREAD

**Issue by robertiii** [gphoto/gphoto2#217]
Sorry going to probably show ignorance here, but is it possible to use a python script as the hook script for a tethered capture?

**Comment by msmeissn** [comment]
The hook script is basically just a script that gets executed, it can be any form of program including a python script.

**Comment by robertiii** [comment]
Ok cool! How would I get the variables that are passed?

**Comment by msmeissn** [comment]
these are just environment variables, so use the standard env variable funcrtionality of python
