### ISSUE TITLE
how to set default filename pattern and download directory for images taken with gphoto2

### ISSUE THREAD

**Issue by uliwest** [gphoto/gphoto2#218]
Hi,
I'm working on a time lapse camera and trying to find a way to set a default filename pattern and download directory for images taken with gphoto2, 
currently I use the following:
`gphoto2 --filename '/home/pi/Desktop/shots/%Y-%m-%d %H-%M-%S %f.%C' --capture-image-and-download`
It works perfectly in terminal , but strangely not when I add it to crontab. This is the code I use in Crontab:
`0,10,20,30,40,50 * * * * gphoto2 --filename '/home/pi/Desktop/shots/%Y-%m-%d %H-%M-%S %f.%C' --capture-image-and-download`
When I leave the filename part out it works in crontab:
`0,10,20,30,40,50 * * * * gphoto2 --capture-image-and-download`
, but the images don't get downloaded to the pi, they stay in the camera instead.
I would prefer to set this filename pattern and download directory as default, so I don't have to add this each time I take a picture. 
I have been searching for hours, but couldn't figure out where and how to set these as defaults. I read that default values can be specified in the `~/.gphoto/settings file`, but I can't find this file. Do I have to create it? Or is it hidden somewhere?
I'm a complete newbie, just spend around 1 month with gphoto2, any help or hint is appreciated.
I'm using a canon 550d and a raspberry pi 3b running 2018-11-13-raspbian-stretch-lite
Thanks!

**Comment by uliwest** [comment]
Figured it out: :)
open terminal, type: sudo apt-get install leafpad

open filebrowser - view - check: show hidden

navigate to /home/pi/.gphoto , open settings file with leafpad
add: 
`gphoto2=filename=/home/pi/Desktop/shots/%Y-%m-%d %H-%M-%S %f.%C`

**Comment by seanasimpson** [comment]
Clever! I was looking for a way to have filenames numbered as they're saved instead of asking to overwrite the previous photos. Forcing the filename to be unique based on the time the image was captured is s very smart way to make sure pictures aren't overwritten. 
It would be nice if gphoto2 would number the photos sequentially by default, but this is a nice workaround. Thank you!

**Comment by msmeissn** [comment]
--filename should also work in cronjob, but cron itself is  using  % characters.
You need to use \%  I think.

see: man 5 crontab

**Comment by msmeissn** [comment]
\\%  ... backslash percent

**Comment by jamie-mint** [comment]
can verify escaping percent like @msmeissn said works:

`0,10,20,30,40,50 * * * * gphoto2 --filename '/home/pi/Desktop/shots/\%Y-\%m-\%d \%H-\%M-\%S \%f.\%C' --capture-image-and-download`

**Comment by msmeissn** [comment]
-> solved
