### ISSUE TITLE
A way to capture-tethered and not automatically download image

### ISSUE THREAD

**Issue by robertiii** [gphoto/gphoto2#219]
Is there a way to run capture tethered and not download the files. I want to use it to run a hook script but not download files

**Comment by msmeissn** [comment]
gphoto2 --wait-event=2000s     would do the function, but currently it would not hook the events received...

you could however run it in a pipe and parse the output, looking for FILEADDED events or so

**Comment by msmeissn** [comment]
question probably answered -> if there is more feedback please reopen
