### ISSUE TITLE
New single configuration set/get in 2.5.10

### ISSUE THREAD

**Issue by Nic2012** [gphoto/gphoto2#22]
According to release notes of new version 2.5.10, its recommended to use new single configuration set/get if possible. Are there any examples how we have to handle new syntax?

Best regards,
Nic

**Comment by Nic2012** [comment]
Thats meant internally using new methods from libgphoto in CLI code.

**Comment by msmeissn** [comment]
? why did you close.

int gp_camera_list_config        (Camera *camera, CameraList *list,
                                  GPContext *context);
int gp_camera_get_single_config  (Camera *camera, const char *name, CameraWidget **widget,
                                  GPContext *context);
int gp_camera_set_single_config  (Camera *camera, const char *name, CameraWidget  *widget,
                                  GPContext *context);


in examples/config.c i am using get_single and set_single config for instance. the list_config gives you a flat list

**Comment by Nic2012** [comment]
Because I am using only gphoto2 CLI not libgphoto. So is there any new syntax of set/get-config beside <get-config propname> etc...? Is "get_single or set_single" published in cmd line gp2?

BTW I found some bugs in gphoto2 when using a Nikon D700, but I will add new ticket for this.

**Comment by msmeissn** [comment]
You dont need to worry about these details when using the gphoto2 cli. I already use these calls in the gphoto2 cli for the regular calls inside.

**Comment by msmeissn** [comment]
... and yu will note that if you use the names in their short form, it will be faster. e.g. --get-config "iso"   / --set-config iso=xxx   ... will use the single faster methods

**Comment by Nic2012** [comment]
Well that was the reason why I have closed the issue, because in gphoto2 cli there are no new methods published. The release notes describes internal changes, that wasn't clear before.
