### ISSUE TITLE
Canon EOSM100 *** Error (-60: 'Could not lock the device')

### ISSUE THREAD

**Issue by Heinnn** [gphoto/gphoto2#220]
Please Help

pi@raspberrypi:~ $ gphoto2 --auto-detect
Model                          Port                                            
----------------------------------------------------------
Canon EOS M100                 usb:001,009     
pi@raspberrypi:~ $ gphoto2 --capture-image
                                                                               
*** Error ***              
An error occurred in the io-library ('Could not lock the device'): Camera is already in use.
ERROR: Could not capture image.
ERROR: Could not capture.
*** Error (-60: 'Could not lock the device') ***       

For debugging messages, please use the --debug option.
Debugging messages may help finding a solution to your problem.
If you intend to send any error or debug messages to the gphoto
developer mailing list <gphoto-devel@lists.sourceforge.net>, please run
gphoto2 as follows:

    env LANG=C gphoto2 --debug --debug-logfile=my-logfile.txt --capture-image

Please make sure there is sufficient quoting around the arguments.

-----------------------------------------------------------------------------------------
pi@raspberrypi:~ $ gphoto2 --version
gphoto2 2.5.20

Copyright (c) 2000-2018 Lutz Mueller and others

gphoto2 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of gphoto2 under the terms of the GNU General Public
License. For more information about these matters, see the files named COPYING.

This version of gphoto2 is using the following software versions and options:
gphoto2         2.5.20         gcc, popt(m), exif, no cdk, no aa, no jpeg, no readline
libgphoto2      2.5.22         all camlibs, gcc, ltdl, EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb usbdiskdirect usbscsi, gcc, ltdl, USB, serial without locking

**Comment by msmeissn** [comment]
This means another program is using it, likely gvfs.

**Comment by Heinnn** [comment]
So I tried renaming the following files, And it's work. I don't know why.
Reference https://www.raspberrypi.org/forums/viewtopic.php?t=70049#p665262

/usr/share/dbus1/services/org.gtk.Private.GPhoto2VolumeMonitor.service
/usr/share/gvfs/mounts/gphoto2.mount 
/usr/share/gvfs/remote-volume-monitors/gphoto2.monitor
/usr/lib/gvfs/gvfs-gphoto2-volume-monitor

Thanks
