### ISSUE TITLE
Canon 1300D won't focus when eosremoterelease=1

### ISSUE THREAD

**Issue by welander071290** [gphoto/gphoto2#221]
Hello.

I have a application where i would like to imitate the functionality of my cameras shutter button.
I would like to make a "half press" in advance of taking the picture.
The purpose is to achieve as constant a delay as possible, from when i send the --capture-image-and-download command, to the actual piture is taken.

From what i understand, I should be able to use the --set-config -eosremoterelease=1. And then when i'm ready, I can send the capture and download command.
I haven't figured the complete command out yet, but my main problem is with the first command: --set-config -eosremoterelease=1. I would expect this to make the camrea focus. But it does nothing, except releasing the flash if it's dark.

Do i have to enable some stuff in order for this to work? I have tried searching for an answer, but without luck.

Any help will be greatly appreciated.
Thanks in advance
. Anders

**Comment by msmeissn** [comment]
on EOS you can always call --set-config autofocusdrive=1     to run autofocus once

**Comment by msmeissn** [comment]
i tried with my EOS 750D ... 

With half press as option it does not work, but 
"Press 1" does autofocus.
gphoto2 --get-config eosremoterelease

**Comment by welander071290** [comment]
Brilliant! -That was exactly what i was looking for. 
I didn't know about that option.

If anybody in the future is struggling with something similar, here is what i ended up dooing in my application.
I'm controlling the camera from a python script, where i send subprocess calls to the terminal.

`Some python code`
`subprocess.call([gphoto2 --set-config eosremoterelease=6 &],  shell=True)#the "&" ignores the output from the terminal`
`Some other python code`
`subprocess.call([gphoto2 --set-config eosremoterelease=2 --wait-event-and-download=1s --filename image01.jpg &],  shell=True)`

As far as I have testet, this will work for me.
Please tell me if you see anything that i should change.
