### ISSUE TITLE
Canon T7i Wrong Aperture Reading

### ISSUE THREAD

**Issue by sepehrhm** [gphoto/gphoto2#222]
I am using gphoto2 cli to set the aperture on my camera to different values. However, after I get the same config, it is always at the same value (5).

When I take a picture, and read the exif information, aperture is set to the desired value.

**Camera Model**

Canon EOS Rebel T7i 

**libgphoto2 and gphoto2 version**
```
gphoto2 2.5.17

Copyright (c) 2000-2018 Lutz Mueller and others

gphoto2 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of gphoto2 under the terms of the GNU General Public
License. For more information about these matters, see the files named COPYING.

This version of gphoto2 is using the following software versions and options:
gphoto2         2.5.17         gcc, popt(m), exif, no cdk, no aa, jpeg, no readline
libgphoto2      2.5.18         all camlibs, gcc, ltdl, EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi, gcc, ltdl, USB, serial without locking
```
**To Reproduce**
```
$ gphoto2 --set-config aperture=10
$ gphoto2 --get-config aperture
Label: Aperture
Readonly: 0
Type: RADIO
Current: 5
Choice: 0 5
Choice: 1 5.6
Choice: 2 6.3
Choice: 3 7.1
Choice: 4 8
Choice: 5 9
Choice: 6 10
Choice: 7 11
Choice: 8 13
Choice: 9 14
Choice: 10 16
Choice: 11 18
Choice: 12 20
Choice: 13 22
Choice: 14 25
Choice: 15 29
Choice: 16 32
Choice: 17 36
END
$ gphoto2 --capture-image-and-download
New file is in location /capt0000.jpg on the camera
Saving file as capt0000.jpg
Deleting file /capt0000.jpg on the camera
$ exiftool -aperture capt0000.jpg
Aperture                        : 10.0
```
As for the debug log, I obtained it via this command:
`gphoto2 --set-config aperture=10 --debug --debug-logfile=aperture.log`
[aperture.log](https://github.com/gphoto/gphoto2/files/3154650/aperture.log)

I also think this is more of a `libgphoto2` issue, since I have developed my own frontend, and it suffers from this issue as well.

**Comment by msmeissn** [comment]
Please update to a newer version of libgphoto2 , e.g. 2.5.25.

Problem is that the "OLC Info" read code needs some offsets adjusted for newer EOS cameras, otherwise it would report aperture 0.
