### ISSUE TITLE
When in shell mode, directories and files are cached

### ISSUE THREAD

**Issue by gorangajic** [gphoto/gphoto2#235]
When you enter in shell mode and take a picture using the camera shutter, a new picture will not be available after listing. Also, you can unplug the camera and you will still be able to navigate and list files.

**libgphoto2 and gphoto2 version**
gphoto2         2.5.20         clang, popt(m), no exif, no cdk, no aa, jpeg, readline
libgphoto2      2.5.23         all camlibs, clang, ltdl, no EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi, clang, ltdl, USB, serial without locking

**To Reproduce**
connect camera 
```
g2photo --shell
```
```
ls /store_00020001/DCIM/100CANON
```
take a picture
```
ls /store_00020001/DCIM/100CANON
```

**Comment by msmeissn** [comment]
the shell probably needs to do some event polling on its own.

you can use 

wait-event 1s

and then the file should be visible

**Comment by gorangajic** [comment]
Great that will work for me, thanks
