### ISSUE TITLE
Wrong return code

### ISSUE THREAD

**Issue by HKHH** [gphoto/gphoto2#238]
**Describe the bug**
I can trigger my Canon EOS 5D Mark IV over USB and wifi. When the focus is okay both return code is 0.
USB command ->    gphoto2 --auto-detect --trigger-capture
Wifi command ->      gphoto2 --port ptpip:192.168.1.2  --trigger-capture --set-config capturetarget=card

If the camera can not adjust the focus (eg: too close), then I get via a USB connection the return code 1. About the wifi connection, however, I get back to 0, although an error is issued. The return code should also be 1.

**Name the camera**
Canon EOS 5D Mark IV

**libgphoto2 and gphoto2 version**
gphoto2 2.5.23
libgphoto2 2.5.23

**To Reproduce**
Hold a camera so close something the focus can not be set and than
gphoto2 --port ptpip:192.168.1.2  --trigger-capture --set-config capturetarget=card

**Comment by msmeissn** [comment]
I think you can put the --set-config capturetarget=card (which will usually succeed) in a seperate command.

If you have --trigger-capture last  it will report error on both wifi and usb,
