### ISSUE TITLE
support XDG_CONFIG_HOME & XDG_DATA_HOME

### ISSUE THREAD

**Issue by legrostdg** [gphoto/gphoto2#249]
It would be great if gphoto2 could support `XDG_CONFIG_HOME` and `XDG_DATA_HOME`.

`~/.gphoto/settings` probably belongs to `$XDG_CONFIG_HOME/gphoto/settings`

See http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html for the reference.

Not high priority, though :).

**Comment by BeatLink** [comment]
I would also like to see this change as well

**Comment by Un1q32** [comment]
bump

**Comment by ndim** [comment]
This is definitely an issue for the libgphoto2 library.

**Comment by ndim** [comment]
Wait a minute... what did you think XDG_DATA_HOME was appropriate for?

**Comment by legrostdg** [comment]
@ndim I'm not sure of what files (lib)gphoto2 uses. On my computer, I just have `~/.gphoto/settings`, which should go to `XDG_CONFIG_HOME`

**Comment by ndim** [comment]
@legrostdg That is what I thought, but I wanted to make sure. Thanks you!

We handle the settings file as part of libgphoto2, so this issue can be closed again.
