### ISSUE TITLE
gphoto2 2.5.10 Error: undefined symbol: gp_camera_get_single_config

### ISSUE THREAD

**Issue by amitpate** [gphoto/gphoto2#25]
Hi,
I installed the latest stable versions:
 - gphoto2-2.3.10.tar.bz2
 - libgphoto2-2.5.10.tar.bz2
 - libusb-1.0.20.tar.bz2

Capture & Save photo is working; but when I try to get or set the config it shows me this error.

`$ gphoto2 --get-config capturetarget `
`gphoto2: symbol lookup error: gphoto2: undefined symbol: gp_camera_get_single_config`

I`m trying to use only the gpoto2 CLI.

**Comment by msmeissn** [comment]
ypu probably have an older libgphnoto2 2.5.x version installed in the system, while 2.5.10 was instaleld ot /usr/local/.

what does
gphoto2 --version

report

**Comment by amitpate** [comment]
Thanks Marcus,

I only installed the libgphoto2 2.5.10 but don`t know why the 2.5.4 version was active.

`$ sudo gphoto2 --version`
```
gphoto2 2.5.10

Copyright (c) 2000-2016 Lutz Mueller and others

gphoto2 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of gphoto2 under the terms of the GNU General Public
License. For more information about these matters, see the files named COPYING.

This version of gphoto2 is using the following software versions and options:
gphoto2         2.5.10         gcc, popt(m), exif, no cdk, no aa, no jpeg, no readline
libgphoto2      2.5.4          all camlibs, gcc, ltdl, EXIF
libgphoto2_port 0.12.0         gcc, ltdl, USB, serial without locking
```

Well I removed this libgphoto2 2.5.4 version by:
`sudo apt-get remove libgphoto2-port10`

Now the get / set config is working and gphoto2 version shows:
`$ sudo gphoto2 --version`
```
gphoto2 2.5.10

Copyright (c) 2000-2016 Lutz Mueller and others

gphoto2 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of gphoto2 under the terms of the GNU General Public
License. For more information about these matters, see the files named COPYING.

This version of gphoto2 is using the following software versions and options:
gphoto2         2.5.10         gcc, popt(m), exif, no cdk, no aa, no jpeg, no readline
libgphoto2      2.5.10         all camlibs, gcc, ltdl, EXIF
libgphoto2_port 0.12.0         gcc, ltdl, USB, serial without locking
```

Thanks again :100:
