### ISSUE TITLE
Fujifilm gfx100 support

### ISSUE THREAD

**Issue by enginefuture** [gphoto/gphoto2#256]
Fill in fields below. If you don't know how, leave it free.

**Name of the camera*
Fujifim GFX100
Use the Marketing name.
Fujifim GFX100
**USB IDs**
e.g. by running:   lsusb 
Bus 001 Device 016: ID 04cb:02de Fuji Photo Film Co., Ltd
**camera summary output**
run

  gphoto2 --summary > summary.txt

attach summary.txt here
[summary.txt](https://github.com/gphoto/gphoto2/files/3723843/summary.txt)

**camera configuration output**

gphoto2 --list-all-config > list-all-config.txt

and attach list-all-config.txt here
[list-all-config.txt](https://github.com/gphoto/gphoto2/files/3723844/list-all-config.txt)

**test capture**

test if capture perhaps already works:

  gphoto2 --capture-image-and-download
 work
  gphoto2 --capture-preview
*** Error (-6: 'Unsupported operation') ***

**Comment by msmeissn** [comment]
i have added the id... what libgphoto2 is used? I added preview suppor tfor fuji in 2.5.19.

**Comment by msmeissn** [comment]
no reply, assuming ok
