### ISSUE TITLE
fujifim xt2 --trigger-capture error -110

### ISSUE THREAD

**Issue by enginefuture** [gphoto/gphoto2#257]
**Describe the bug**

1.339431 ptp_usb_getresp [usb.c:514] (0): PTP_OC 0x100e receiving resp failed: PTP Device Busy (0x2019)
1.339446 camera_trigger_capture [library.c:5410](0): 'ptp_initiatecapture(params, 0x00000000, 0x00000000)' failed: 'PTP Device Busy' (0x2019)
1.339467 gp_context_error            (0): PTP Device Busy

*** Error ***              
PTP Device Busy
1.339512 gp_camera_trigger_capture [gphoto2-camera.c:1369](0): 'camera->functions->trigger_capture (camera, context)' failed: -110
ERROR: Could not trigger capture.
*** Error (-110: 'I/O in progress') ***       

1.340494 gp_camera_free              (2): Freeing camera...
1.340512 gp_camera_exit              (2): Exiting camera ('Fuji Fujifilm X-T2')...

**Name the camera**
fujifim xt2

**libgphoto2 and gphoto2 version**
gphoto2         2.5.20         gcc, popt(m), exif, cdk, aa, jpeg, readline
libgphoto2      2.5.22         all camlibs, gcc, ltdl, EXIF
libgphoto2_port 0.12.0 

**To Reproduce**
gphoto2 --trigger-capture

If its a camera misbehavior, attach debug output using  --debug --debug-logfile=debug.log   (if considered useful).

**Comment by msmeissn** [comment]
Could you try the attached patch or current git master branch?

**Comment by msmeissn** [comment]
no response ... hopefully fixed
