### ISSUE TITLE
2 Canon EOS RP connection by usb port failed

### ISSUE THREAD

**Issue by Patrick-Lascombe** [gphoto/gphoto2#259]
Hello again,

I'm trying to connect to 2 Canon EOS RP simultaneously by providing the correct usb port (usb:xxx,xxx). But frequently my program is not connecting to the provided usb port. Instead it is connecting to the other camera.

Does this problem already occurred ? 

Thank you for your help

**Comment by msmeissn** [comment]
if you have the wrong port, it might happen. do you use --camera   too?

A debug logfile would be good
