### ISSUE TITLE
folders rights are wrong

### ISSUE THREAD

**Issue by Shura0** [gphoto/gphoto2#26]
Hi!

I have got:

- gphoto2         2.5.4          gcc, popt(m), exif, cdk, no aa, jpeg, readline
- libgphoto2      2.5.4          all camlibs, gcc, ltdl, EXIF
- libgphoto2_port 0.10.0         gcc, ltdl, no USB, serial lockdev locking

I use gphoto to get photos from my cam via Wi-Fi, command looks like:
`gphoto2 --port ptpip:$ip --quiet --skip-existing --new --get-all-files --filename=$MEDIA_DIR/$FILENAME_FORMAT;`

$FILENAME_FORMAT is _%Y/%m/%d/%f.%C_, so it creates new folder every day and it looks like '2016/05/11'
**Issue:** I've noted it creates new folder with wrong rights:
drwx------ 2 shura shura 4096 May 11 20:24 11/
i.e. it's 700, but by fact it should be 775 (my umask is 002)

Could you please fix it? My wife cannot access the photos!

Best regards,
Alexander

**Comment by msmeissn** [comment]
i adjusted this in current git for the next release

**Comment by Shura0** [comment]
Thank you
