### ISSUE TITLE
gphoto2 does not see Sony cameras

### ISSUE THREAD

**Issue by pavelber** [gphoto/gphoto2#266]
I compiled and installed the last gphoto2 version  2.5.23 on Ubuntu
I have 3 Sony cameras: Nex-6, A7II and A6000

gPhoto2 autodetect does not see  A7II and A6000 and sees Nex-6 as "Mass Storage"

**Comment by msmeissn** [comment]
nex6 is only mass storage.

for the others check that you built with USB support, see "gphoto2 --version"

**Comment by ShingoYasu** [comment]
pavelber, I had initially similar issues with my SONY RX100V, though mine was listed among the gphoto2-compatible cameras.  Among your list, at least A7II and A6000 seems to be also listed.

Here's what I did on my camera.

On the camera side, you check the USB setting.  Usually, with SONY cameras, you push the 'menu' button and go to the toolbox tab.  Maybe, USB connection setting will be there.  You can select between 'Mass Storage' and 'PC Remote'.  I selected 'PC Remote', and gphoto2 started to recognize my camera.

**Comment by msmeissn** [comment]
no further reply received from original reporter ..
