### ISSUE TITLE
GoPro conncetion not possible because of i/o error

### ISSUE THREAD

**Issue by sbi1911** [gphoto/gphoto2#267]
After connecting the Raspberry 3 to a GoPro (4 or 5), "gphoto2 --auto-detect" can be executed, but when entering "gphoto2 --trigger-caputure", an i/o error appears and the camera cannot be addressed.

Is there a solution?

Thank you very much for your help.

**Comment by msmeissn** [comment]
currently the gopros do not seem to allow remote triggering over USB, only over WLAN.

**Comment by msmeissn** [comment]
There is nothing we can do right now, sorry.
