### ISSUE TITLE
Issues with EOS 1200D in timelapse mode

### ISSUE THREAD

**Issue by GioMac** [gphoto/gphoto2#27]
When capturing single image - no problems occur, when using timelapse (-I and -F options) - there are problems (always reproducible) with first image:

> [root@localhost]# gphoto2 --debug --debug-logfile=logfile.txt --capture-image-and-download -I 3 -F 2 --force-overwrite
> Time-lapse mode enabled (interval: 3s).
> Capturing frame #1/2...
> ERROR: Could not capture image.
> ERROR: Could not capture.
> not sleeping (57 seconds behind schedule)
> Capturing frame #2/2...
> New file is in location /capt0000.jpg on the camera
> Saving file as capt0000.jpg
> Deleting file /capt0000.jpg on the camera

gphoto info:
[logfile.txt.gz](https://github.com/gphoto/gphoto2/files/286403/logfile.txt.gz)

> 0.000087 main                        (2): gphoto2 2.5.10
> 0.000102 main                        (2): gphoto2 has been compiled with the following options:
> 0.000114 main                        (2):  + gcc (C compiler used)
> 0.000125 main                        (2):  + popt (mandatory, for handling command-line parameters)
> 0.000135 main                        (2):  + exif (for displaying EXIF information)
> 0.000145 main                        (2):  + no cdk (for accessing configuration options)
> 0.000155 main                        (2):  + no aa (for displaying live previews)
> 0.000164 main                        (2):  + jpeg (for displaying live previews in JPEG format)
> 0.000174 main                        (2):  + readline (for easy navigation in the shell)
> 0.000190 main                        (2): libgphoto2 2.5.10
> 0.000203 main                        (2): libgphoto2 has been compiled with the following options:
> 0.000217 main                        (2):  + all camlibs
> 0.000228 main                        (2):  + gcc (C compiler used)
> 0.000238 main                        (2):  + ltdl (for portable loading of camlibs)
> 0.000248 main                        (2):  + EXIF (for special handling of EXIF files)
> 0.000262 main                        (2): libgphoto2_port 0.12.0
> 0.000275 main                        (2): libgphoto2_port has been compiled with the following options:
> 0.000286 main                        (2):  + gcc (C compiler used)
> 0.000296 main                        (2):  + ltdl (for portable loading of camlibs)
> 0.000325 main                        (2):  + USB (libusb1, for USB cameras)
> 0.000339 main                        (2):  + serial (for serial cameras)
> 0.000350 main                        (2):  + no resmgr (serial port access and locking)
> 0.000360 main                        (2):  + no ttylock (serial port locking)
> 0.000369 main                        (2):  + lockdev (serial port locking)
> 0.000380 main                        (2): CAMLIBS env var not set, using compile-time default instead
> 0.000389 main                        (2): IOLIBS env var not set, using compile-time default instead
> 0.000399 main                        (2): invoked with following arguments:
> 0.000409 main                        (2):   --debug
> 0.000419 main                        (2):   --debug-logfile=logfile.txt
> 0.000429 main                        (2):   --capture-image-and-download
> 0.000439 main                        (2):   -I
> 0.000448 main                        (2):   3
> 0.000458 main                        (2):   -F
> 0.000467 main                        (2):   2
> 0.000476 main                        (2):   --force-overwrite
> 

log file attached

Note: Applicable for gphoto2-2.5.9 and gphoto2-2.5.10, not tested with previous versions

**Comment by msmeissn** [comment]
i applied a fix for libgphoto2 in the libgphoto2 git ... i hope it helps

**Comment by GioMac** [comment]
Thanks
I will check and update you...

**Comment by GioMac** [comment]
Fix confirmed - issue solved!
