### ISSUE TITLE
Sony Alpha-A9 (Control) can not get files by command gphoto2 --list-files

### ISSUE THREAD

**Issue by CBrother** [gphoto/gphoto2#270]
[my-logfile.txt](https://github.com/gphoto/gphoto2/files/3916205/my-logfile.txt)

i can not get files from my camera Sony Alpha-A9 (Control)

![image](https://user-images.githubusercontent.com/23162258/70045840-c7bb3500-15ff-11ea-9b4c-01c82eb13a43.png)

**Comment by msmeissn** [comment]
yes, the camera is only doing remote control in this mode.

It wont access the sd card 

not sure why sony designed it that way, sorry.
