### ISSUE TITLE
Capture and download JPEG+RAW download only JPG on NikonD5300

### ISSUE THREAD

**Issue by trik84** [gphoto/gphoto2#273]
Hi, 

This may not be a bug, but only a configuration issue. When I run:
`gphoto2 --capture-image-and-download --keep-raw`
on my raspberry connected to Nikon D5300 configured whit Image quality 4 (NEF+Basic) and capture target to 1 (MemoryCard), only the JPEG file is download.

What is the corret way to download both JPEG+NEF file  ?

Many thanks

Luca

**Comment by msmeissn** [comment]
to download both, just leave out --keep-raw   ... so just "--capture-image-and-download"

**Comment by trik84** [comment]
Thanks, if I remove --keep-raw option it works, but in my application I need to download both files and leave a copy of each one on the camera memory card, as a backup. Is it possible ?

Yet many thanks

Luca

**Comment by rocketBeagle** [comment]
To achieve that you can use **--keep** instead of --keep-raw I think

**Comment by msmeissn** [comment]
yes, --keep should work.
