### ISSUE TITLE
Canon M50 crash after a few usage

### ISSUE THREAD

**Issue by AlexandreMagnat** [gphoto/gphoto2#274]
**Describe the bug**
After somes usage of a Canon M50, the device stop respond. I ran the command:

 /usr/bin/gphoto2 --capture-image-and-download --filename test.jpg

And the result is:
*** Erreur ***
Canon EOS M Full-Press failed (0x2019: PTP Device Busy)
Erreur : Acquisition d'image impossible.
Erreur : Acquisition impossible.
*** Erreur (-110 : « I/O in progress ») ***

If I reboot the Camera, the device work again perfectly. But, after some times of use, the problem come back again ... I

**Name the camera**
Canon EOS M50                  usb:001,012

**libgphoto2 and gphoto2 version**
gphoto2         2.5.23         gcc, popt(m), no exif, no cdk, no aa, no jpeg, no readline
libgphoto2      2.5.22         all camlibs, gcc, ltdl, EXIF
libgphoto2_port 0.12.0         gcc, ltdl, USB, serial without locking

**To Reproduce**
Steps to reproduce the behavior: I haven't find the way to reproduce the problem ...

If its a camera misbehavior, attach debug output using  --debug --debug-logfile=debug.log   (if considered useful).

[debug_gphoto2.log](https://github.com/gphoto/gphoto2/files/3985347/debug_gphoto2.log)

**Comment by AlexandreMagnat** [comment]
Hi, I complete this post.
When I do a preview, the first time, the preview works correctly
The second time, there is an error: *** Erreur (-1 : « Erreur indéfinie ») ***

Here, you can find the logfile
[debug_preview.log](https://github.com/gphoto/gphoto2/files/3987629/debug_preview.log)

**Comment by msmeissn** [comment]
see https://github.com/gphoto/libgphoto2/issues/440
