### ISSUE TITLE
Canon Rebel t7i/EOS 800D cannot save image to computer in python

### ISSUE THREAD

**Issue by slampants** [gphoto/gphoto2#276]
Raspbery Pi 3B running Buster
Canon Rebel t7i (EOS 800D according to auto-detect)
gphoto2 version 2.5.20
libgphoto2 version 2.5.22

I'm attempting to download a file from the memory card of my camera to a directory on my raspberry pi, and running into an unspecified gphoto2 error.

**To Reproduce**
I'm currently doing a slightly more complicated version of this in a series of modules I'm running, but was able to reproduce the issue using the following line-by-line commands in a Python shell (running on 2.7.16):

```
>>> import gphoto2 as gp
>>> import os
>>> camera = gp.Camera()
>>> camera.init()
>>> folder, name = os.path.split('/store_00020001/DCIM/100CANON/IMG_0146.CR2')
>>> camera_file = gp.check_result(gp.gp_camera_file_get(camera, folder, name, gp.GP_FILE_TYPE_NORMAL))
>>> gp.check_result(gp.gp_file_save(camera_file,'/home/pi/images/bursts'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python2.7/site-packages/gphoto2/result.py", line 157, in check_result
    raise gphoto2.GPhoto2Error(error)
gphoto2.GPhoto2Error: [-1] Unspecified error
```

I do not have any issues saving individual files, or all files, to a directory on the pi from the command line tool, just in Python.

**Comment by msmeissn** [comment]
perhaps ask over in the https://github.com/jim-easterbrook/python-gphoto2 repo for pyhton binding help,  @jim-easterbrook

**Comment by jim-easterbrook** [comment]
Is `/home/pi/images/bursts` a directory? You need to supply a filename to `gp_file_save`.

**Comment by slampants** [comment]
Ah, sorry about that @msmeissn. @jim-easterbrook , thanks for that. I see now that I missed the os.path.join call earlier in the example script I was working off of.
