### ISSUE TITLE
build error: ‘GP_EVENT_FILE_CHANGED’ undeclared (with solution, but why?)

### ISSUE THREAD

**Issue by calocedrus** [gphoto/gphoto2#277]
Hello,

I've just discovered libgphoto2 and gphoto2 and these are simply incredible pieces of code, I'm just getting started.
I'm building ligphoto2 and gphoto2 (cloned from the git repo, master branch) in a local folder rather than the default, by specifying that location with --prefix (for libgphoto2: 
./configure --prefix=/home/ludovic/libs/libgphoto2_sandbox).
libgphoto2 appears to be installed correctly, but upon make, gphoto2 throws an error:
```
actions.c:1262:8: error: ‘GP_EVENT_FILE_CHANGED’ undeclared 
```
Afer deciding to dive into the code and try to find a solution before writing, I have found out that gphoto2 compiles only if I remove all reference to gphoto2/ in the includes of the .h files located gphoto2/gphoto2: actions.h, main.h, etc... 
That is I changed:
```
#include <gphoto2/gphoto2-camera.h>
#include <gphoto2/gphoto2-context.h>
```
to
```
#include <gphoto2-camera.h>
#include <gphoto2-context.h>
```
etc...

Then gphoto2 builds fine and I can use it.
So it looks like the libgphotos .h files couldn't be properly located with the default code, which seems strange to me (in the sense: I likely did something unusual). 

So: what am I doing wrong so that I would have to do these changes? Is there a particular directory structure to respect for libgphoto2 and gphoto2 installations?

Some info: end result of ./configure for gphoto2:
```
Configuration (gphoto2 2.5.23.1):

  Build
    Source code location:          .
    Compiler:                      gcc

  Features
    Use translations:              yes
    libgphoto2:                    yes
    pthread support:               yes (-lpthread)
    Interactive config support:    no (http://dickey.his.com/cdk/cdk.html)
    JPEG support:                  yes
    libexif:                       yes
    Text preview support:          no (http://www.sourceforge.net/projects/aa-project)
    use popt library:              yes
    popt libs:                     -L/usr/ -lpopt
    popt cppflags:                 -I/usr/include
    Readline support:              yes (doesn't require explicit -lncurses)

You may run "make" and "make install" now.

```
Error message after make (gphoto2), before the modifications mentioned in the .h files above:

```
gcc -DHAVE_CONFIG_H -I. -I..  -DLOCALEDIR=\"/usr/local/share/locale\" -D_GPHOTO2_INTERNAL_CODE  -I.. -I../gphoto2 -I/home/ludovic/libs/libgphoto2/include/gphoto2 -I/usr/include/libexif -DLOCALEDIR=\"/usr/local/share/locale\" -D_GPHOTO2_INTERNAL_CODE    -I/usr/include/libexif  -I/usr/include -g -O2 -Wall -Wmissing-declarations -Wmissing-prototypes -g -MT gphoto2-actions.o -MD -MP -MF .deps/gphoto2-actions.Tpo -c -o gphoto2-actions.o `test -f 'actions.c' || echo './'`actions.c
actions.c: In function ‘action_camera_upload_metadata’:
actions.c:133:6: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   fn = path+5;
      ^
actions.c: In function ‘action_camera_wait_event’:
actions.c:1133:13: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
    wp.u.str = arg;
             ^
actions.c:1262:8: error: ‘GP_EVENT_FILE_CHANGED’ undeclared (first use in this function); did you mean ‘GP_EVENT_FILE_ADDED’?
   case GP_EVENT_FILE_CHANGED:
        ^~~~~~~~~~~~~~~~~~~~~
        GP_EVENT_FILE_ADDED

```

**Comment by msmeissn** [comment]
It is picking up an older system libgphoto2 development installation during build if you see this error.

Remove or replace it (e.g. install directly to /usr/ instead of /usr/locale as a shortcut)

**Comment by calocedrus** [comment]
Lightning fast reply!
I had done an export to where the pkg-config of libgphoto2 is installed locally:
```
export PKG_CONFIG_PATH=/home/ludovic/libs/libgphoto2/lib/pkgconfig/
```
So is it still as you suggest?

**Comment by msmeissn** [comment]
But for some reason the includes are probably still fetched from the wrong location :/

**Comment by calocedrus** [comment]
You are right. 
I have found the correct way to get rid of the build error related to the include, not by using the proposed solution above (which isn't in any way a correct approach) but by using the configure option:
```
--with-libgphoto2=/path/to/libgphoto2_gphoto2
```
Then the error mentioned above is gone (no need to export PKG_CONFIG_PATH, the error is gone even without setting this environment variable).
But then a linking error arises:
```/usr/bin/ld: gphoto2-actions.o: undefined reference to symbol 'gp_log@@LIBGPHOTO2_5_0'
/home/ludovic/libs/libgphoto2_gphoto2/lib/libgphoto2_port.so.12: error adding symbols: DSO missing from command line
```
This is another issue so I'll close the present one and discuss the new one in a new comment.
