### ISSUE TITLE
Timelapse capture fails or is inconsistent - Sony A5000

### ISSUE THREAD

**Issue by davidharpe** [gphoto/gphoto2#28]
Hi there,
I know this has been talked about in the mailing list but didn't see a bug posted here. Symptoms are various Sony cameras will take pictures in timelapse mode just fine for quite some time then stop capturing. 

I've also experienced a timelapse set for say - a 20 second interval - will take no photos for 40 seconds then two photos in quick succession. Debug log shows "no object found during event polling. try the 0xffffc001 object id" when this happens. 

Let me know if I can help with debugging.

**Comment by wtgee** [comment]
@davidharpe Does your port change? I am experiencing the same thing on a Canon but it is because of usb port resets. Not sure if related but I've been trying to figure out.

**Comment by msmeissn** [comment]
the sony event polling during capture is occasionaly a bit buggy and might lose events. ... I so far have not been able to pinpoint the reason(s)

**Comment by pascaldorland** [comment]
any news on this ancient issue?? :)

**Comment by msmeissn** [comment]
we did some fixes for alpha capture end of 2016. best to try with the current release
