### ISSUE TITLE
Sony nex 3n

### ISSUE THREAD

**Issue by pepcampas** [gphoto/gphoto2#280]
Hi, 
Is compatibility with the Sony Nex 3n camera planned? It is a very good mirrorless with possibilities in astrophotography but it does not work through Indi / Kstars: ___ (

Thank you very much

Pep

**Comment by msmeissn** [comment]
So far we only know that the Sony Alpha series are capture capable, previous NEX versions were not remote capture capable.

Can you attach  both text files from

gphoto2 --summary  --debug --debug-logfile=summary.log.txt > summary.txt

**Comment by msmeissn** [comment]
as of now it seems the NEX series is not remote capture capable.
