### ISSUE TITLE
Number of supported cameras: 0 on raspbian stretch

### ISSUE THREAD

**Issue by avisecag** [gphoto/gphoto2#281]
When installing the latest development version on raspbian stretch through gphoto2-updater script, no cameras are detected anymore, and when I run gphoto2 --list-cameras it says there are no supported cameras.

Interesting things about this:
This *used* to work. I have done this several times a few months ago, and it wasn't an issue (same gphoto-installer script, so that can't be the issue either).
It works on my laptop. But on raspbian stretch, the behaviour is consistent (tested several pis with several disks).
Latest stable works without issue.

Quite honestly, I'm at a bit of a loss here about what to do to fix the situation.

**Comment by msmeissn** [comment]
can you check if there were any errors during build?

can you check if the "stable" version still works?

**Comment by avisecag** [comment]
stable version still works, as mentioned.
I haven't seen any errors during the build, but I'll build again and shove the stdout into a file to take a closer look.

**Comment by msmeissn** [comment]
there is a change with the lumix camera driver which is new, which might vcause this ... but starting fresh , with autoreconf etc should not give issues :/

**Comment by avisecag** [comment]
I *do* have an error related to lumix.c when building libgphoto2:
```
lumix/lumix.c:29:10: fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>
          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [lumix/lumix_la-lumix.lo] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1
```
It's good that you mention lumix, because while I saw this a while ago, it happens on both the Pi and my laptop (and the final build there works), compilation proceeds regardless, and the libgphoto2 version at the end of the build is correct (2.5.23.1). But there's nothing else around that looks like an error, so maybe this is it. 
Maybe worth mentioning: My laptop did have 2.5.23.1 installed before, while the Pis don't, maybe that has an influence on why it works on the ubuntu laptop but not on the pis.
You mention starting fresh, and quite honestly, I don't think I do. All cases so far had a pre-existing version of gphoto2. In my experience this is no problem at all with gphoto-updater, is it possible this is messing something up? Then how would I best go about cleaning everything out?
In the meantime, I'll try a direct install of the latest dev version on a clean slate and see if that makes a difference...

Attached below are the output of the gphoto-updater, as well as a different file with the complete output of all the processes called by it, just in case this reveals anything more.

[gphoto-updater-output.txt](https://github.com/gphoto/gphoto2/files/4035598/gphoto-updater-output.txt)
[process-log.txt](https://github.com/gphoto/gphoto2/files/4035599/process-log.txt)

**Comment by avisecag** [comment]
Just to let you know, situation is the same with a clean install on a fresh system.

**Comment by msmeissn** [comment]
this bad include is likely the reason.

do you have curl development libraries installed?

i thought my autoconf checks would capture this and avoid it

**Comment by avisecag** [comment]
I now ran a build of an older commit of ligphoto2 (https://github.com/gphoto/libgphoto2/commit/098af2ae205b0210790347b20258a0ded3ed6f71), somewhere around the time when I did this the last time, and it works. So it's definitely a change down the tree that causes the behaviour. Whether it is an issue that needs to be fixed in libgphoto2 or in the updater is up to you to decide.

**Comment by avisecag** [comment]
Just FYI, installing libcurl-dev doesn't fix the problem. I guess I'd have to make a link to curl.h from the proper folder, but for now I can live with the older build.

**Comment by msmeissn** [comment]
weird, configure checks for presence ... do you have "config.log" somewhere still?

**Comment by msmeissn** [comment]
hmm i can reproduce it, something in the logic is incorrect

**Comment by msmeissn** [comment]
just fixed this in current GIT hopefully

**Comment by avisecag** [comment]
I can confirm that the problem is fixed. :)
