### ISSUE TITLE
Sony RX0 II Unable to Capture Consistently

### ISSUE THREAD

**Issue by jeffav** [gphoto/gphoto2#286]
Image capture on the Sony RX0 II camera works intermittently using gphoto2 CLI.

Using 'gphoto2 --capture-image-and-download' may take an image, but the command never exits. Often the command will pause with no feedback.
[capture-image-and-download.txt](https://github.com/gphoto/gphoto2/files/4083710/capture-image-and-download.txt) (and the end of this command, I had to Ctrl+c twice to exit it.

Using 'capture-preview' seems to work more consistently, but still produces errors.
[capture-preview.txt](https://github.com/gphoto/gphoto2/files/4083709/capture-preview.txt)

The camera is in PC control mode.

Similar issues: #133 #216 #419

**Name the camera**

Model                          Port                                            
Sony DSC RX0 II (PC Control)   usb:001,011  

**libgphoto2 and gphoto2 version**
gphoto2 2.5.23.1

Copyright (c) 2000-2020 Marcus Meissner and others

gphoto2 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of gphoto2 under the terms of the GNU General Public
License. For more information about these matters, see the files named COPYING.

This version of gphoto2 is using the following software versions and options:
gphoto2         2.5.23.1       gcc, popt(m), exif, no cdk, no aa, no jpeg, no readline
libgphoto2      2.5.23.1       all camlibs, gcc, ltdl, EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi, gcc, ltdl, USB, serial without locking

**To Reproduce**
Set the camera to PC Control mode.
Connect the camera.
Use `gio mount -s gphoto2` to free the camera. (Fixes "cannot unlock device" error)
Run `gphoto2 --capture-image-and-download` multiple times until error.

**Comment by msmeissn** [comment]
the capture-image-and-download.txt is kind of short, did you wait just 3 seconds before ctrl-c? Or did it completelyx hang?

It might be that it uses libusb0 still, which does not work for Sony.

Can you rm /usr/local/lib/libgphoto2_port/0.12.0/usb.so to make sure that libusb1 is used?

**Comment by jeffav** [comment]
Thank you for your reply. Unfortunately I returned the camera when I couldn’t find a way to solve this issue. I won’t be able to test it.

**Comment by msmeissn** [comment]
sorry for late reply :(

**Comment by BeebBenjamin** [comment]
@msmeissn I just rm `/usr/local/lib/libgphoto2_port/0.12.0/usb.so` and this works why does this work?

**Comment by msmeissn** [comment]
usb.so is the libusb0 driver ... (we use the libusb1 driver by default)
the libusb0 driver has no asynchronous interrupt handling method, which we need for the sony.

Without async interrupt handling the device stalls its USB communications.

**Comment by BeebBenjamin** [comment]
Why does deleting it from the 0.12.0 folder work if libusb1 is also present in the same directory and supposed to be the default?

**Comment by msmeissn** [comment]
it is loaded alphabetically, for some reason both were built.
