### ISSUE TITLE
Reading PTP event failed when using capture-image.py (sony alpha a6000)

### ISSUE THREAD

**Issue by gadoo2020** [gphoto/gphoto2#288]
ubuntu 18.04 LTS
Python 2.7.17
i installed python-gphoto2 from https://github.com/jim-easterbrook/python-gphoto2

when i tried to capture image from my sony camera this error appears :

WARNING: gphoto2: (ptp_usb_event [usb.c:587]) Reading PTP event failed: Timeout reading from or writing to the port (-10)
WARNING: gphoto2: (ptp_usb_event [usb.c:587]) Reading PTP event failed: Timeout reading from or writing to the port (-10)
WARNING: gphoto2: (ptp_usb_event [usb.c:587]) Reading PTP event failed: Timeout reading from or writing to the port (-10)
WARNING: gphoto2: (ptp_usb_event [usb.c:587]) Reading PTP event failed: Timeout reading from or writing to the port (-10)
WARNING: gphoto2: (ptp_usb_event [usb.c:587]) Reading PTP event failed: Timeout reading from or writing to the port (-10)
WARNING: gphoto2: (ptp_usb_event [usb.c:587]) Reading PTP event failed: Timeout reading from or writing to the port (-10)
WARNING: gphoto2: (ptp_usb_event [usb.c:587]) Reading PTP event failed: Timeout reading from or writing to the port (-10)
WARNING: gphoto2: (ptp_usb_event [usb.c:587]) Reading PTP event failed: Timeout reading from or writing to the port (-10)
WARNING: gphoto2: (ptp_usb_event [usb.c:587]) Reading PTP event failed: Timeout reading from or writing to the port (-10)
WARNING: gphoto2: (ptp_usb_event [usb.c:587]) Reading PTP event failed: Timeout reading from or writing to the port (-10)
WARNING: gphoto2: (ptp_usb_event [usb.c:587]) Reading PTP event failed: Timeout reading from or writing to the port (-10)

**Comment by msmeissn** [comment]
can you try with the commandline tool and also get a logfile?

gphoto2 --capture-image-and-download --debug --debug-logfile=capture.log

abnd attach capture.log here?

**Comment by msmeissn** [comment]
no reply received ... closing for now. Please just comment if you get back to it and we can reopen.

**Comment by LeaKess** [comment]
I have the same problem. I have also used the example programme capture-image.py .
Every time I tried to capture image from my sony alpha R2 (Sony ILCE-7M2) this waring appears:
WARNING: gphoto2: (ptp_usb_event [usb.c:588]) Reading PTP event failed: Timeout reading from or writing to the port (-10)
WARNING: gphoto2: (ptp_usb_event [usb.c:588]) Reading PTP event failed: Timeout reading from or writing to the port (-10)
WARNING: gphoto2: (ptp_usb_event [usb.c:588]) Reading PTP event failed: Timeout reading from or writing to the port (-10)
WARNING: gphoto2: (ptp_usb_event [usb.c:588]) Reading PTP event failed: Timeout reading from or writing to the port (-10)


gphoto2         2.5.28.1       gcc, popt(m), exif, no cdk, no aa, jpeg, no readline
libgphoto2      2.5.27         standard camlibs, gcc, ltdl, EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi, gcc, ltdl, EXIF, USB, serial without locking

The capture.log is here:
  GNU nano 5.4                                           capture.log                                                    
0.000999 main                        (2): BITTE IMMER FOLGENDE ZEILE EINFÜGEN WENN DEBUG MESSAGES AN DIE MAILINGLISTE G>0.001227 main                        (2): gphoto2 2.5.28.1
0.001281 main                        (2): gphoto2 wurde mit den folgenden Optionen übersetzt:
0.001317 main                        (2):  + gcc (C compiler used)
0.001350 main                        (2):  + popt (mandatory, for handling command-line parameters)
0.001383 main                        (2):  + exif (for displaying EXIF information)
0.001415 main                        (2):  + no cdk (for accessing configuration options)
0.001446 main                        (2):  + no aa (for displaying live previews)
0.001478 main                        (2):  + jpeg (for displaying live previews in JPEG format)
0.001510 main                        (2):  + no readline (for easy navigation in the shell)
0.001548 main                        (2): libgphoto2 2.5.27
0.001583 main                        (2): libgphoto2 wurde mit den folgenden Optionen übersetzt:
0.001622 main                        (2):  + standard camlib set (ax203 canon digigr8 dimagev directory docupen jl2005a>0.001654 main                        (2):  + gcc (C compiler used)
0.001686 main                        (2):  + ltdl (for portable loading of camlibs)
0.001718 main                        (2):  + EXIF (for special handling of EXIF files)
0.001755 main                        (2): libgphoto2_port 0.12.0
0.001790 main                        (2): libgphoto2_port wurde mit den folgenden Optionen übersetzt:
0.001823 main                        (2):  + iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi
0.001855 main                        (2):  + gcc (C compiler used)
0.001886 main                        (2):  + ltdl (for portable loading of iolibs)
0.001918 main                        (2):  + EXIF (for vusb)
0.001950 main                        (2):  + USB (libusb1, for USB cameras)
0.001981 main                        (2):  + serial (for serial cameras)
0.002013 main                        (2):  + no resmgr (serial port access and locking)
0.002044 main                        (2):  + no ttylock (serial port locking)
