### ISSUE TITLE
Nikon DS-Qi2 Support

### ISSUE THREAD

**Issue by hzarei4** [gphoto/gphoto2#292]
Hi, 

I just want to know that the gphoto2 package can support Nikon microscope cameras? Like the Nikon DS-Qi2 camera with USB 3.0 interface.

Thanks!

**Comment by msmeissn** [comment]
We have not yet heard reports of such devices.

- It is unlikely to be already supported by libgphoto2. (likelyness < 10%)
- It might be just a USB Video device, supported by video4linux tooling
- Or it might be a third party protocol which is so far not known.

Without getting info from a device it is however hard to say.

**Comment by msmeissn** [comment]
if someone has such a device, please report details... closing for now
