### ISSUE TITLE
gPhoto2 - Forward LiveView over WiFi to an App

### ISSUE THREAD

**Issue by sakibnaz** [gphoto/gphoto2#293]
Hello There.

I like to forward the LiveView of my DSLR to an Android App over WiFi. I am using Raspberry Pi to run the gPhoto2 Application.

I know gPhoto2-Server have LiveView feature over web. But I don't wanted to use Web. Can anyone advise the best possible way to forward LiveView over WiFi?

Thanks.

Regards.

**Comment by ttbek** [comment]
Isn't that what it does by default?  I assume that here by WiFi you mean on a local wireless network and by 'Web' you mean the WAN or Internet.  Is this: https://mvmn.wordpress.com/2015/06/03/gphoto2-server-web-interface-for-gphoto2/ not what you're looking for?

**Comment by sakibnaz** [comment]
Hi, yes "gp2sev" is an option. However, later I find its also possible to stream LiveView over HTTP localhost using gPhoto2 itself.

Thanks.
