### ISSUE TITLE
SONY DSLR-A350 "No Image Capture"

### ISSUE THREAD

**Issue by tricktresor** [gphoto/gphoto2#298]
Hi there!
I just thought, I bought the perfect camera for my photo booth: A very cheap SONY DSLR-A350.
I ensured that this camera is listed in "supported cameras".

Unfortunately gphoto2 tells me at --summary: "No Image Capture".
In the mentioned outdated detailed list, I can also see that Image Capture seems not to be supported.

Until now I thought that any camera supporting PTP mode can be used for taking pictures...

> Cameras capable of MTP, PTP or PictBridge are supported without needing to be specifically listed here.

Is there really no chance to let the A350 take pictures with gphoto2?

Thanks
Enno

**Comment by msmeissn** [comment]
"supported" usually means for downloading images as baseline.

Our records so far indidcate this camera as non-capture capable.

It predates the Sony Alpha cameras that started to support capture.

Is there any specific menu entry on camera for selcting "PC ControL" as USB Mode?

**Comment by tricktresor** [comment]
Hey Marcus,
thanks for incredible fast response!
camera only has modes "PTP" and "mass storage".

**Comment by msmeissn** [comment]
Does not sound promising sadly.

can you run:

gphoto2 --summary --debug --debug-logfile=summary.log    and attach the summary.log here?

**Comment by tricktresor** [comment]
[summary.log](https://github.com/gphoto/gphoto2/files/4333065/summary.log)

**Comment by tricktresor** [comment]
[summary.log](https://github.com/gphoto/gphoto2/files/4333067/summary.log)

**Comment by msmeissn** [comment]
It really only has basics for downloading images. No vendor opcodes or other indications that would show capture capabilities :(

**Comment by tricktresor** [comment]
It's a pity... 😫
Thanks for investigating!!
