### ISSUE TITLE
Camera capture and download issue

### ISSUE THREAD

**Issue by dungcules** [gphoto/gphoto2#299]
I have two cameras (same type) and I am trying to capture (gp_camera_capture) then download images (gp_camera_file_get) immediately to usb. I used two separate threads for each camera for this process (after detect and initialize for both cameras). If I just leave the cameras capture WITHOUT downloading, they can capture as many images as I want. 

However, if I download the image after capturing, they return error -7 after 490s images for both cameras and the cameras are freeze. The delay between capturing images is 2 seconds. Do you have any idea to help me now of this issue?

**libgphoto2 and gphoto2 version**
gphoto2                 2.5.11         
libgphoto2             2.5.12         
libgphoto2_port     0.12.0

**Comment by msmeissn** [comment]
Just to be clear , it is 1 thread per camera?

Cameras can only be accessed single threadedly, they have no concept of different sessions in parallel.

**Comment by msmeissn** [comment]
closing, as there was no feedback. feel free to reopen / comment
