### ISSUE TITLE
Sony a6300 shuts down after first ghoto2 command in USB-mode MTP from a mac

### ISSUE THREAD

**Issue by burpy** [gphoto/gphoto2#30]
Hi,

first of all I like to thank you for the great tool gphoto2.

I have a problem with my new cam. I connect my Sony a6300 with USB (MTP mode) from the terminal.app and gphoto2 on a Mac. I quit the process "PTPCamera" to prevent "Error (-53: 'Could not claim the USB device')" and type in

`gphoto2 --list-files`

It works and it shows me

```
There is no file in folder '/'.                                                
There is no file in folder '/store_00010001'.
There is 1 file in folder '/store_00010001/2016-06-25'.
#1     C0001.MP4                  rd 63615 KB 1920x1080 application/x-unknown
```

Thats fine! But after one command then the cam shuts off and I have to restart the cam to make a second command. Here is the version that I use and the debug protocol:

gphoto2         2.5.10         clang, popt(m), no exif, no cdk, no aa, jpeg, readline
libgphoto2      2.5.10         all camlibs, clang, ltdl, no EXIF
libgphoto2_port 0.12.0         clang, ltdl, USB, serial without locking

[my-logfile.txt](https://github.com/gphoto/gphoto2/files/333482/my-logfile.txt)

**Comment by burpy** [comment]
I updated now on my raspberry pi too. I have updated from version  2.5.7 to this developer version 

gphoto2         2.5.10.1       gcc, popt(m), exif, no cdk, no aa, jpeg, no readline
libgphoto2      2.5.10.1       all camlibs, gcc, ltdl, EXIF
libgphoto2_port 0.12.0         gcc, ltdl, USB, serial without locking

and the same appears now on the raspberry. The cam (Sony a6300) shuts down after the first command in MTP Mode.

See attached the my-logfile.txt from the raspberry

[my-logfile-from-raspberry.txt](https://github.com/gphoto/gphoto2/files/340480/my-logfile.txt)

**Comment by msmeissn** [comment]
likely fixed these days, 
there were some opcodes sent that changed in the last years

**Comment by starlord1980** [comment]
I think it hasnt been solved. I just happen to have a Sony a6300 and am setting up gphoto2 on raspberry pi, triggering via Octoprint script and am googling this problem. I see now its a known issue.
I'm able to take approx 3-7 photos before it loses connection.

`pi@octopi:~/scripts $ gphoto2 --auto-detect
Model                          Port                                            
----------------------------------------------------------
Sony Alpha-A6300 (Control)     usb:001,023     
pi@octopi:~/scripts $ gphoto2 --capture-image
                                                                               
*** Error ***              
PTP Timeout

*** Error ***              
An error occurred in the io-library ('Timeout reading from or writing to the port'): No error description available
ERROR: Could not capture image.
ERROR: Could not capture.

*** Error ***              
PTP Timeout

*** Error ***              
An error occurred in the io-library ('Timeout reading from or writing to the port'): No error description available
`
