### ISSUE TITLE
Capturetarget not working on Sony Alpha A6000 

### ISSUE THREAD

**Issue by ousim97** [gphoto/gphoto2#302]
Hello,
An issue occurred when I tried the command `gphoto2 --get-config capturetarget`  using a Raspberry pi 3, I get the following error :  
 *** Error ***              
capturetarget not found in configuration tree.

Is there any solution please?

**Comment by msmeissn** [comment]
In earlier Sony Alphas it was not possible to store to card during capture.

New ones (2019+ or so) support selection of target in the camera and we support it there.

The A6000 does not, sorry.

**Comment by ShingoYasu** [comment]
Very useful information.  Thank you.

I also have a similar issue with SONY RX100V digital camera.  I think I purchased it around 2017.

Although 'auto-detect' successfully detects my camera and '--trigger-capture' is able to control the camera, no image is saved in the SD card.

I also have a similar error message to the one with ousim97.  
By typing, "--get-config capturetarget", it returns the error message like, "capturetarget not found in configuration tree."

I am using Raspberry Pi 3, and my gphoto2 version is as follows.

gphoto2 :   2.5.20-3.
libgphoto2-6:  2.5.22-3.
libgphoto2-l10n: 2.5.22-3.
libgphoto2-port12: 2.5.22-3.

I would appreciate your kind advice.

Also, if, like in the response by msmeissn, gphoto2 does not support the function of configuring the save location (SD card), will there be a method to circumvent it, and somehow get the picture take by the camera transferred to Raspberry Pi, or to PC?

Thank you very much in advance.

**Comment by msmeissn** [comment]
in libgphoto2 2.5.24 I added sony capturetarget support for NEW Sony cameras. by "NEW" I think it is 2019+ cameras or so.
the cameras before did not offer the option
