### ISSUE TITLE
Nikon enable liveview failed (0x2019: PTP Device Busy)

### ISSUE THREAD

**Issue by colin-adams** [gphoto/gphoto2#304]
I don't know if this is a fault in the software or in my usage of it or in my camera, but...
I am using my camera as a webcam for Zoom by running the command:
gphoto2 --stdout --capture-movie | gst-launch-1.0 fdsrc ! decodebin3 name=dec ! queue ! videoconvert ! v4l2sink device=/dev/video0

This works fairly well, but periodically the feed fails mid-broadcast with:
Nikon enable liveview failed (0x2019: PTP Device Busy)

I can recover by stopping the video in Zoom, switching off the camera, switching it on again, and re-running the command. But that's a nusiance. If it's not a problem with the camera, then I'd like to eliminate the problem if possible.

**Name the camera**
Nikon DSC D810

**libgphoto2 and gphoto2 version**
gphoto2 2.5.23

Copyright (c) 2000-2019 Marcus Meissner and others

gphoto2 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of gphoto2 under the terms of the GNU General Public
License. For more information about these matters, see the files named COPYING.

This version of gphoto2 is using the following software versions and options:
gphoto2         2.5.23         gcc, popt(m), exif, no cdk, no aa, jpeg, readline
libgphoto2      2.5.23         all camlibs, gcc, ltdl, EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi, gcc, ltdl, USB, serial lockdev locking

**To Reproduce**
As described in the problem. Failure is typically after about 10 minutes, but it's not 100% predictable. When I was first running it a few weeks ago, I got about 10 hours without a failure.

**Comment by msmeissn** [comment]
if this ran better some weeks ago ... did you update libgphoto2  inbetween?

**Comment by colin-adams** [comment]
Not intentionally. It may have happened in a mass dnf update. I don't know.

**Comment by msmeissn** [comment]
Hmm. In a running session this error would only appear if the camera drops out of liveview, which might happen e.g. when the camrea gets too hot.

I added some code to report liveview prohibit conditions to current libgphoto2 git now, to see this better.

**Comment by msmeissn** [comment]
can you test with 2.5.25 release if this still happens and if it reports errors?

**Comment by colin-adams** [comment]
I'll do so as soon as it gets pushed out as a Fedora update.

**Comment by colin-adams** [comment]
As Fedora hasn't shipped anything more recent than 2.5.23, I tried
downloading a zip from github, and compiled it.

But gphoto2 --version now shows:

gphoto2 2.5.23.1

Copyright (c) 2000-2020 Marcus Meissner and others

gphoto2 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of gphoto2 under the terms of the GNU General Public
License. For more information about these matters, see the files named
COPYING.

This version of gphoto2 is using the following software versions and
options:
gphoto2         2.5.23.1       gcc, popt(m), exif, no cdk, no aa, no jpeg,
no readline
libgphoto2      2.5.24         standard camlibs, gcc, ltdl, EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb1 usbdiskdirect
usbscsi, gcc, ltdl, EXIF, USB, serial lockdev locking

NOT 2.5.25

**Comment by colin-adams** [comment]
My mistake - it was libgphoto2 you were talking about.
So I compiled the latter also from source, but gphoto2 --version is still
showing the same information (I did a ./configure/make clean; make; sudo
make install for gphoto2 after installing libgphoto2 ).

I think I must be missing some step.

If I do ls -l /usr/local/lib, this is what I see:

total 708
drwxr-xr-x. 3 root root   4096 Jun  6 12:12 libgphoto2
-rwxr-xr-x. 1 root root    987 Jun  6 12:12 libgphoto2.la
drwxr-xr-x. 3 root root   4096 Jun  6 12:12 libgphoto2_port
-rwxr-xr-x. 1 root root    976 Jun  6 12:12 libgphoto2_port.la
lrwxrwxrwx. 1 root root     25 Jun  6 12:12 libgphoto2_port.so ->
libgphoto2_port.so.12.0.0
lrwxrwxrwx. 1 root root     25 Jun  6 12:12 libgphoto2_port.so.12 ->
libgphoto2_port.so.12.0.0
-rwxr-xr-x. 1 root root 144080 Jun  6 12:12 libgphoto2_port.so.12.0.0
lrwxrwxrwx. 1 root root     19 Jun  6 12:12 libgphoto2.so ->
libgphoto2.so.6.1.0
lrwxrwxrwx. 1 root root     19 Jun  6 12:12 libgphoto2.so.6 ->
libgphoto2.so.6.1.0
-rwxr-xr-x. 1 root root 541096 Jun  6 12:12 libgphoto2.so.6.1.0
drwxr-xr-x. 3 root root   4096 Oct 10  2019 netscape
drwxr-xr-x. 2 root root   4096 Jun  6 12:12 pkgconfig
drwxr-xr-x. 3 root root   4096 Mar 13 15:00 python3.7
drwxr-xr-x. 2 root root   4096 Jun  6 12:12 udev

**Comment by msmeissn** [comment]
can you check with ldd /usr/bin/gphoto2  which libgphoto2 it picks up?

also with gphoto2 --version ?

**Comment by msmeissn** [comment]
depending on your libdir, you can also overwrite the system installation if needed
(not sure if it uses /usr/lib64 for the system libs.)

./configure --prefix=/usr/  --libdir=/usr/lib64    
make clean
make
sudo make install

**Comment by colin-adams** [comment]
Just found out it was an ldconfig issue.

Working now. I'll report next weekend on whether it's cured my issue or not.

**Comment by msmeissn** [comment]
Thank you! I am curious if we see an actual error, or if there is another bug.

**Comment by colin-adams** [comment]
I've just hit this today:

*** Error ***
Nikon enable liveview failed (0x2019: PTP Device Busy)
ERROR: Movie capture error... Exiting.
Movie capture finished (308597 frames)
Got EOS from element "pipeline0".
Execution ended after 1:00:12.303733091
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...

**Comment by msmeissn** [comment]
Its been quite a number of frames....

I will be adding code to ignore busy for some tries during capture-movie. 

(Not very confident it will help.)
