### ISSUE TITLE
Olympus E-M5 Mark2: Extreme delay after capture

### ISSUE THREAD

**Issue by jalpar** [gphoto/gphoto2#305]
"ghoto2 --capture-image" seem working, but there is an extreme delay (more than 1min before ghoto2 exits)

I use it with "Olympus OM-D E-M5 Mark II".
It it recognised by ghoto2 --auto-detect as "Olympus E-M1"

gphoto2 --version says:

gphoto2         2.5.23         gcc, popt(m), exif, no cdk, no aa, jpeg, readline
libgphoto2      2.5.23         standard camlibs, gcc, ltdl, EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi, gcc, ltdl, EXIF, USB, serial without locking

These come from the OpenSuse 15.1 repo. I tried self with a compiled libgphoto2 v2.5.23, with the same result.

"ghoto2 --debug --capture-image" says:

[...]
New file is in location /store_00010001/DCIM/102OLYMP/P4180867.JPG on the camera
3.418006 camera_wait_for_event       (2): waiting for events timeout 3000 ms

[Note that even taking the picture takes more than 3sec]
[Then, the following lines repeats million times]

3.418020 gp_port_get_timeout         (2): Current port timeout is 20000 milliseconds.
3.418033 gp_port_set_timeout         (2): Setting port timeout to 150 milliseconds.
3.418047 gp_port_check_int           (3): Reading 24 = 0x18 bytes from interrupt endpoint...
3.568271 gp_port_check_int           (3): Reading 24 = 0x18 bytes from interrupt endpoint...
3.718532 gp_port_set_timeout         (2): Setting port timeout to 20000 milliseconds.

[And eventually:]

68.514347 gp_port_get_timeout         (2): Current port timeout is 20000 milliseconds.
68.514403 gp_port_set_timeout         (2): Setting port timeout to 3000 milliseconds.
68.514441 gp_port_check_int           (3): Reading 24 = 0x18 bytes from interrupt endpoint...
71.517581 gp_port_check_int           (3): Reading 24 = 0x18 bytes from interrupt endpoint...
74.520758 ptp_usb_event [usb.c:587]   (0): Reading PTP event failed: Timeout reading from or writing to the port (-10)
74.520793 gp_port_set_timeout         (2): Setting port timeout to 20000 milliseconds.
774.521699 gp_camera_free              (2): Freeing camera...
74.521724 gp_camera_exit              (2): Exiting camera ('Olympus E-M1')...
74.521744 gp_port_get_timeout         (2): Current port timeout is 20000 milliseconds.
74.521759 gp_port_set_timeout         (2): Setting port timeout to 150 milliseconds.
74.521774 gp_port_check_int           (3): Reading 24 = 0x18 bytes from interrupt endpoint...
74.671993 gp_port_check_int           (3): Reading 24 = 0x18 bytes from interrupt endpoint...
74.822264 gp_port_set_timeout         (2): Setting port timeout to 20000 milliseconds.
74.822317 ptp_usb_sendreq             (2): Sending PTP_OC 0x1003 (Close session) request...
74.822331 gp_port_write               (3): Writing 12 = 0xc bytes to port...
74.822447 gp_port_write               (3): Wrote   12 = 0xc bytes to port: (hexdump of 12 bytes)
0000  0c 00 00 00 01 00 03 10-10 00 00 00              ............    

74.822473 ptp_usb_getresp             (2): Reading PTP_OC 0x1003 (Close session) response...
74.822486 gp_port_read                (3): Reading 1024 = 0x400 bytes from port...
74.823438 gp_port_read                (3): Read    12 = 0xc out of 1024 bytes from port: (hexdump of 12 bytes)
0000  0c 00 00 00 03 00 01 20-10 00 00 00              ....... ....    

74.823492 gp_port_close               (2): Closing port...
74.824611 _close_async_interrupts     (2): canceling transfer 0:0x55b65883eee0 (status 0)
74.824728 _close_async_interrupts     (2): canceling transfer 1:0x55b658882b00 (status 0)
74.824794 _close_async_interrupts     (2): canceling transfer 2:0x55b658824760 (status 0)
74.824850 _close_async_interrupts     (2): canceling transfer 3:0x55b65886a400 (status 0)
74.824909 _close_async_interrupts     (2): canceling transfer 4:0x55b6588447d0 (status 0)
74.824972 _close_async_interrupts     (2): canceling transfer 5:0x55b658881090 (status 0)
74.825032 _close_async_interrupts     (2): canceling transfer 6:0x55b658871500 (status 0)
74.825091 _close_async_interrupts     (2): canceling transfer 7:0x55b6588715e0 (status 0)
74.825144 _close_async_interrupts     (2): canceling transfer 8:0x55b658880e60 (status 0)
74.825194 _close_async_interrupts     (2): canceling transfer 9:0x55b65883e070 (status 0)
74.825258 _cb_irq                     (2): 0x55b65883eee0 with status 3
74.825274 _cb_irq                     (2): Transfer 0x55b65883eee0 should be in LIBUSB_TRANSFER_COMPLETED, but is 3!
74.825300 _cb_irq                     (2): 0x55b658882b00 with status 3
74.825312 _cb_irq                     (2): Transfer 0x55b658882b00 should be in LIBUSB_TRANSFER_COMPLETED, but is 3!
74.825328 _cb_irq                     (2): 0x55b658824760 with status 3
74.825339 _cb_irq                     (2): Transfer 0x55b658824760 should be in LIBUSB_TRANSFER_COMPLETED, but is 3!
74.825358 _cb_irq                     (2): 0x55b65886a400 with status 3
74.825369 _cb_irq                     (2): Transfer 0x55b65886a400 should be in LIBUSB_TRANSFER_COMPLETED, but is 3!
74.825386 _cb_irq                     (2): 0x55b6588447d0 with status 3
74.825397 _cb_irq                     (2): Transfer 0x55b6588447d0 should be in LIBUSB_TRANSFER_COMPLETED, but is 3!
74.825413 _cb_irq                     (2): 0x55b658881090 with status 3
74.825424 _cb_irq                     (2): Transfer 0x55b658881090 should be in LIBUSB_TRANSFER_COMPLETED, but is 3!
74.825440 _cb_irq                     (2): 0x55b658871500 with status 3
74.825451 _cb_irq                     (2): Transfer 0x55b658871500 should be in LIBUSB_TRANSFER_COMPLETED, but is 3!
74.825469 _cb_irq                     (2): 0x55b6588715e0 with status 3
74.825480 _cb_irq                     (2): Transfer 0x55b6588715e0 should be in LIBUSB_TRANSFER_COMPLETED, but is 3!
74.825496 _cb_irq                     (2): 0x55b658880e60 with status 3
74.825507 _cb_irq                     (2): Transfer 0x55b658880e60 should be in LIBUSB_TRANSFER_COMPLETED, but is 3!
74.825524 _cb_irq                     (2): 0x55b65883e070 with status 3
74.825536 _cb_irq                     (2): Transfer 0x55b65883e070 should be in LIBUSB_TRANSFER_COMPLETED, but is 3!
74.825985 gp_filesystem_reset         (2): resetting filesystem
74.826011 gp_filesystem_lru_clear     (2): Clearing fscache LRU list...
74.826023 gp_filesystem_lru_clear     (2): fscache LRU list already empty
74.826038 delete_all_folders          (2): Internally deleting all folders from '/'...
74.826052 lookup_folder               (2): Lookup folder '/'...
74.826065 lookup_folder               (2): Found! / is 0x55b65881ce10
74.826081 recurse_delete_folder       (2): Recurse delete folder 0x55b65881ce10//
74.826112 recurse_delete_folder       (2): Recurse delete folder 0x55b65886c880/store_00010001
74.826129 recurse_delete_folder       (2): Recurse delete folder 0x55b6588598a0/DCIM
74.826145 recurse_delete_folder       (2): Recurse delete folder 0x55b6588751c0/102OLYMP
74.826161 delete_folder               (2): Delete one folder 0x55b6588751c0/102OLYMP
74.826176 delete_all_files            (2): Delete all files in folder 0x55b6588751c0/102OLYMP
74.826192 delete_folder               (2): Delete one folder 0x55b6588598a0/DCIM
74.826204 delete_all_files            (2): Delete all files in folder 0x55b6588598a0/DCIM
74.826217 delete_folder               (2): Delete one folder 0x55b65886c880/store_00010001
74.826229 delete_all_files            (2): Delete all files in folder 0x55b65886c880/store_00010001
74.826242 delete_all_files            (2): Delete all files in folder 0x55b65881ce10//
74.826254 gp_port_free                (2): Freeing port...
74.826266 gp_port_close               (2): Closing port...
74.826774 gp_filesystem_reset         (2): resetting filesystem
74.826798 gp_filesystem_lru_clear     (2): Clearing fscache LRU list...
74.826813 gp_filesystem_lru_clear     (2): fscache LRU list already empty
74.826830 delete_all_folders          (2): Internally deleting all folders from '/'...
74.826844 lookup_folder               (2): Lookup folder '/'...
74.826855 lookup_folder               (2): Found! / is 0x55b65881ce10
74.826869 recurse_delete_folder       (2): Recurse delete folder 0x55b65881ce10//
74.826882 delete_all_files            (2): Delete all files in folder 0x55b65881ce10//

**Comment by ColinSlack** [comment]
Hi, do you have a lot of images on your camera?
 I have an issue whereby on a freshly formatted card executing either a --capture-image OR --capture-images-and-download it takes about 6 seconds to return with the filenames, with each shot after that it slowly takes longer and longer to return control, after 20 odd shots it's now at 10-12 seconds. using the debug It seems to be doing a list of each image on the card, probably to find the last shot taken, I do a lot of timelapse and It gets up to 60 seconds after each shot until the camera puts the images in a new folder on the camera.  
Just thought this might be your problem too.

**Comment by pingutron** [comment]
The same thing happens to me. I don't have a whole lot of images on the card right now. It comes back with the filename reasonably soon after the capture but then it hangs for more than a minute before it signals a PTP timeout.

**Comment by jalpar** [comment]
The same for me. There is no image in the card. The log shows that there is a 3sec timeout and this repeats several times before gphoto gives it up.

It would be great if msmeissn read this post. I would try to fix this bug but I certainly need some initial support for that.

**Comment by mad-marco** [comment]
This looks similar to the issue that I have with my E-M1 Mk2, but in my case it takes a single picture and stores it on the SD card and then hangs until the error message ERROR: Could not capture image is displayed. Did anyone manage to get capture working on an Olympus camera with recent versions of the software?

**Comment by msmeissn** [comment]
I have fixed the OMD capture code in current git to hopefully make this work better and faster.

Can you try current libgphoto2 GIT or 2.5.25 once it is released?

**Comment by pingutron** [comment]
I just tried `gphoto2 --capture-image --debug` on `adcb6e76` (the current HEAD) with my E-M5 II using an otherwise empty SD card and it still behaves substantially like before – after taking the picture it hangs for more than a minute and then times out.

**Comment by msmeissn** [comment]
hmm, can you capture a --debug trace?

gphoto2 --capture-image --debug --debug-logfile=capture.log

**Comment by pingutron** [comment]
Sure, here you are.

[capture.log](https://github.com/gphoto/gphoto2/files/4673805/capture.log)

**Comment by msmeissn** [comment]
There was an unconditional 65 second wait, where it should have waited only the passed in time (3 seconds) at most.

I fixed this now, but it was only after the 2.5.25 release I just did, sorry.

**Comment by pingutron** [comment]
Yep, works now.

**Comment by jalpar** [comment]
> I have fixed the OMD capture code in current git to hopefully make this work better and faster.

It is indeed much better now. But it still takes 15 seconds to run
gphoto2 --capture-image

The capture it taken after around 2-3 seconds.

It there any particular (hopefully fixable) reason for that.

**Comment by msmeissn** [comment]
hmm. can you take another debugtrace now? then we can check timestamps again.

there are 3 second wait at the end potentially too much, but where the other 12 come from is weird.
