### ISSUE TITLE
Unknown model

### ISSUE THREAD

**Issue by Steboss** [gphoto/gphoto2#31]
Hi!

I have install gphoto2 and now I was trying to deal with the python interface
I am trying to detect the camera but  by using a simple code like this: 

```
 gp.check_result(gp.use_python_logging())
    context = gp.gp_context_new()
    camera = gp.check_result(gp.gp_camera_new())
    gp.check_result(gp.gp_camera_init(camera, context))
```

I got an error message "Unknwon model[105]"  when my camera is a Nikon D40, which is in the list

If I use the terminal interface with:

```
gphoto2 --auto-detect
```

the camera is correctly detected

Where is my mistake?

Thank you 

Stefano

**Comment by msmeissn** [comment]
it should work, if no camera is set, one will be autodetect on gp_camera_init and used.

currently no idea what the issue might be

**Comment by msmeissn** [comment]
hopefully fixed, was not clear what the issue was
