### ISSUE TITLE
How to open Nikon z6 z7 Prores raw  Enable_HDMI_RAW_Output

### ISSUE THREAD

**Issue by hanqiushi0808** [gphoto/gphoto2#311]
How to open Nikon z6 z7 Prores raw  Enable_HDMI_RAW_Output？thank you~

**Comment by hanqiushi0808** [comment]
https://www.youtube.com/watch?v=B5hYW_IuyH4
Someone can do it

**Comment by msmeissn** [comment]
I added an option to switch HDMI from 8 to 10 bit, not sure if this was meant here

**Comment by hanqiushi0808** [comment]
> I added an option to switch HDMI from 8 to 10 bit, not sure if this was meant here

It's not 8 bit to switch 10 bit, it's to turn on the HDMI output raw switch. It's hidden by default. The official needs to pay to unlock it, but someone can crack it under PTP

**Comment by hanqiushi0808** [comment]
Is there a way?

**Comment by msmeissn** [comment]
one other article:

https://www.newsshooter.com/2019/12/17/raw-over-hdmi-is-here-we-test-drive-the-nikon-z6-and-prores-raw/

**Comment by msmeissn** [comment]
It seems they either install different firmware or even different hardware to the Nikon Z6.

https://www.nikon.de/de_DE/news-press/press.tag/news/bv-pr-wwa1912-raw-video-output-for-nikon-z7-and-z6.dcr

It seems firmware 2.20 brings it...

**Comment by msmeissn** [comment]
if you have a Z6 wioth 2.20 or higher, can you attach your --summary output here?
I will see if I can upgrade my Z6, but I currently have no card reader to upgrade the firmware.

**Comment by msmeissn** [comment]
The screenshot seems to be code similar to:  https://github.com/simeonpilgrim/nikon-firmware-tools

**Comment by hanqiushi0808** [comment]
It won't use too little public information

**Comment by msmeissn** [comment]
This is a bit above my head. Best way is perhaps to reach out to the Nikon Hacker forum.

https://nikonhacker.com/

**Comment by msmeissn** [comment]
i am afraid this is all I can do currently.
