### ISSUE TITLE
gPhoto2 - LiveView Streaming Issue

### ISSUE THREAD

**Issue by sakibnaz** [gphoto/gphoto2#313]
Hi there.

I am trying to enable Live Preview Streaming over Localhost. I am using gPhoto2 in an ARM Board.

- I have started FFServer by "ffserver -f ffserver.config"

- Then executed Capture-Move by "gphoto2 --capture-movie --stdout | ffmpeg -f mjpeg -re -i pipe:0 http://localhost:8080/feed1.ffm" 

- But when I am trying to access the Preview with URL "http://10.10.10.253:8080/"  over network using the IP of the ARM Board then it reports "File Not Found". 

Can anyone advise please where I am making wrong?

Necessary files attached for your review.

Thanks in advance.

Regards.

[ffserver.config.txt](https://github.com/gphoto/gphoto2/files/4570609/ffserver.config.txt)
![FFServer](https://user-images.githubusercontent.com/6670151/80916327-d27a2180-8d79-11ea-8c56-c44e3b2da8b9.png)
![Capture-movie](https://user-images.githubusercontent.com/6670151/80916330-d443e500-8d79-11ea-8eba-4e6920493b2f.png)
![Web](https://user-images.githubusercontent.com/6670151/80916336-d8700280-8d79-11ea-972a-6c607706c75d.png)

**Comment by msmeissn** [comment]
The howto was not fully correct, adjust to:

gphoto2 --capture-movie --stdout | ffmpeg -re -i pipe:0 -listen 1 -f mjpeg http://localhost:8080/feed.ffm

**Comment by msmeissn** [comment]
OK, this was standalone, not with ffserver ... I need to see how ffserver works

**Comment by msmeissn** [comment]
I dont seem to have ffserver anymore, as ffmpeg dropped it :/ Perhaps someone else can help

**Comment by sakibnaz** [comment]
Hi @msmeissn. Thanks for reply.

However, I made some progress. Attached is the "**_ffserver.conf_**" and I executed the below command.

**_ffserver -f ffserver.conf
gphoto2 --capture-movie --stdout | ffmpeg -f mjpeg -re -i pipe:0 http://localhost:8080/feed1.ffm_**

I can see the web view at "http://10.10.10.253:8080/stat.html" and I can see stream at "http://10.10.10.253:8080/test.mjpg". But the stream is too slow ... it have almost 10 - 12 sec delay.

Any advise please?

Thank you.

Regards.

[ffserver.conf.txt](https://github.com/gphoto/gphoto2/files/4570937/ffserver.conf.txt)
![Web_View](https://user-images.githubusercontent.com/6670151/80919607-b92ea080-8d8c-11ea-9941-ae518b042e7a.png)

**Comment by sakibnaz** [comment]
Tried the standalone version as well with the command you advised.

gphoto2 --capture-movie --stdout | ffmpeg -re -i pipe:0 -listen 1 -f mjpeg http://localhost:8080/feed.ffm

But seems its not streaming and no web view comes.

![image](https://user-images.githubusercontent.com/6670151/80921712-cef69280-8d99-11ea-8832-1801986090d9.png)

Please advise.

Thanks.

**Comment by sakibnaz** [comment]
Hi @msmeissn.

I tried the LiveView steaming as per the command below which mentioned in the web.

**_gphoto2 --capture-movie --stdout | ffmpeg -re -i pipe:0 -listen 1 -f mjpeg http://localhost:8080/feed.jpg_**

But the http web view not connecting. Can you please advise?

Debug log attached for your review.

Thanks in advance.

Regards.

[streamlog.txt](https://github.com/gphoto/gphoto2/files/4581991/streamlog.txt)

**Comment by msmeissn** [comment]
The log shows read errors. can you check if the cable is good.

does gpoto2 --capture-movie=10s   work on its own?

**Comment by sakibnaz** [comment]
Hi @msmeissn. Still am struggling with LiveView streaming.

I tested with a Canon 6D. When Camera in Photo Mode then I run command "gphoto2 --capture-movie=10s" and I can see a file created "movie.mjpg"

![image](https://user-images.githubusercontent.com/6670151/81716901-bbcf7b00-949b-11ea-9459-7b78c519833f.png)

I also put the Camera Dial into Video Mode and tried a Movie Record with below commands and it works Ok.

gphoto2 --set-config capturetarget=1

gphoto2 --set-config viewfinder=1 --set-config movierecordtarget=Card --wait-event=10s --set-config movierecordtarget=None --wait-event-and-download=2s

But when Camera Dial in Photo Mode and I tried to do LiveView Stream by:

gphoto2 --capture-movie --stdout | ffmpeg -re -i pipe:0 -listen 1 -f mjpeg http://localhost:8080/feed.jpg

![image](https://user-images.githubusercontent.com/6670151/81717718-b6befb80-949c-11ea-928a-96ca24c85407.png)

Then web view not connecting. Do I need to run any other 'gphoto2' commands (for 6D) before run the streaming command?

FYI, I am using Chrome Browser and no FFServer is running.

Please advise.

Thanks.
