### ISSUE TITLE
Can someone please figure out small step focussing

### ISSUE THREAD

**Issue by breditter** [gphoto/gphoto2#314]
I'm not linux pro but I definitely can follow some instructions. Small step focus is available on canon EOS utility in the live view mode, so I don't think it is impossible to do it. Implementing it in gphoto2 would be a game-changer in most timelapse situation.

**Comment by msmeissn** [comment]
This is implemented, camera needs to be in liveview mode though.

It is in the config option manualfocusdrive   it has Near 1 / Near 2 / Near 3 / Far 1 / Far 2 / Far 3 

Near 1 and Far 1 are the small step variants, 2 is higher, and 3 is longer
