### ISSUE TITLE
Please support `Remote Control` for Canon EOS 800D

### ISSUE THREAD

**Issue by Aliveing** [gphoto/gphoto2#315]
**Name of the camera**
[EOS Kiss X9i / EOS Rebel T7i / EOS 800D](https://global.canon/en/c-museum/product/dslr853.html)
> This camera has different name when selling of different area

---

Hi, we want use `Canon EOS 800D` to develop, so I don't have the device at this time, and also can't fill the left fields below, sorry.

I search `Canon EOS 800D` in  [Remote Control Overview](http://www.gphoto.org/doc/remote/), this camera not included, but I saw `Canon EOS 750D`, 800D support bigger ISO than 750D, and has new noise reduction algorithm, we more like to use 800D.

So we want `Canon EOS 800D` can support Remote Control, if it already supported, please tell me, I really did't see it.

Thanks and regards.

---

**USB IDs**

**camera summary output**

**camera configuration output**

**test capture**

**Comment by msmeissn** [comment]
the remote control overvie wpage is not regular updated.

We support the EOS 800D already, the USB ID was also added in libgphoto2 2.5.22.

Please just try it out.

**Comment by Aliveing** [comment]
Thanks a lot, we will try it.
