### ISSUE TITLE
gPhoto2 - Thumbnail Picture Resolution

### ISSUE THREAD

**Issue by sakibnaz** [gphoto/gphoto2#316]
Hi.

I tried "--get-all-thumbnails" on my Nikon D5100 and found the thumbnails pic are 160x120 resolution. Is it anyhow possible to change the resolution?

Thanks,

**Comment by msmeissn** [comment]
there is a "large thumbnail" retrieval command, which could be implemented, but currently is not.

I will see if I can quickly add it tomorrow.

**Comment by sakibnaz** [comment]
Thanks @msmeissn. Yes please, that will be great.

**Comment by msmeissn** [comment]
In current libgphoto2 git you can now do:

            gphoto2 --set-config thumbsize=large

For downloading largethumbnails.
(this is user setting on your machine / account in $HOME/.gphoto/settings, not in the camera)

**Comment by sakibnaz** [comment]
Thanks, I'll try it soon.

**Comment by sakibnaz** [comment]
Hi @msmeissn.

I did make of the current libgphoto2 from git as per the INSTALL note. But when making current git gphoto2 then getting below when ./configure and make.

![image](https://user-images.githubusercontent.com/6670151/81507395-f5c74280-931e-11ea-8a99-a0a11acd4c7d.png)

Is the libgphoto2 version on git is older? If so, it will be great if you can release a new version (2.5.25) of libgohoto2 which can work with the latest gphoto2 release with enabled command option "gphoto2 --set-config thumbsize=large".

Thank you.

Regards.

**Comment by msmeissn** [comment]
I plan to release 2.5.25 soonish (perhaps next weekend, lets see)

**Comment by sakibnaz** [comment]
Great. Thanks.

**Comment by sakibnaz** [comment]
Hi @msmeissn ... just a soft-reminder about the next official release of libgphoto2 2.5.25 with "Large Thumbnail" support.

Tentative when we can expect this release?

Thanks.
