### ISSUE TITLE
Camera not showing up.

### ISSUE THREAD

**Issue by SeventhDread** [gphoto/gphoto2#318]
When I run gphoto2 --auto-detect my camera is not appearing and I have tried loads cables

It is a Canon SX620 HS and II am connecting via micro usb to usb.

gphoto2:         2.5.23        
libgphoto2:      2.5.22         
libgphoto2_port: 0.12.0         

I am not sure if you need the --debug response here so I will give it anyway: 

0.000388 main                        (2): ALWAYS INCLUDE THE FOLLOWING LINES WHEN SENDING DEBUG MESSAGES TO THE MAILING LIST:
0.000454 main                        (2): gphoto2 2.5.23
0.000498 main                        (2): gphoto2 has been compiled with the following options:
0.000516 main                        (2):  + gcc (C compiler used)
0.000534 main                        (2):  + popt (mandatory, for handling command-line parameters)
0.000601 main                        (2):  + exif (for displaying EXIF information)
0.000625 main                        (2):  + no cdk (for accessing configuration options)
0.000636 main                        (2):  + no aa (for displaying live previews)
0.000656 main                        (2):  + jpeg (for displaying live previews in JPEG format)
0.000668 main                        (2):  + no readline (for easy navigation in the shell)
0.000690 main                        (2): libgphoto2 2.5.22
0.000718 main                        (2): libgphoto2 has been compiled with the following options:
0.000738 main                        (2):  + all camlibs
0.000749 main                        (2):  + gcc (C compiler used)
0.000763 main                        (2):  + ltdl (for portable loading of camlibs)
0.000776 main                        (2):  + EXIF (for special handling of EXIF files)
0.000794 main                        (2): libgphoto2_port 0.12.0
0.000812 main                        (2): libgphoto2_port has been compiled with the following options:
0.000826 main                        (2):  + iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi
0.000839 main                        (2):  + gcc (C compiler used)
0.000853 main                        (2):  + ltdl (for portable loading of iolibs)
0.000865 main                        (2):  + USB (libusb1, for USB cameras)
0.000877 main                        (2):  + serial (for serial cameras)
0.000889 main                        (2):  + no resmgr (serial port access and locking)
0.000901 main                        (2):  + no ttylock (serial port locking)
0.000914 main                        (2):  + no lockdev (serial port locking)
0.000927 main                        (2): CAMLIBS env var not set, using compile-time default instead
0.000940 main                        (2): IOLIBS env var not set, using compile-time default instead
0.000953 main                        (2): invoked with following arguments:
0.000965 main                        (2):   --debug
0.001015 load_settings               (2): Creating gphoto config directory ('/home/pi/.gphoto')
0.001079 verify_settings             (2): Can't open settings file '/home/pi/.gphoto/settings' for reading.
0.001096 load_settings               (2): Loading settings from file '/home/pi/.gphoto/settings'.
0.001119 load_settings               (2): Can't open settings file '/home/pi/.gphoto/settings' for reading.
0.001135 load_settings               (2): Creating gphoto config directory ('/home/pi/.gphoto')
0.001163 verify_settings             (2): Can't open settings file '/home/pi/.gphoto/settings' for reading.
0.001178 load_settings               (2): Loading settings from file '/home/pi/.gphoto/settings'.
0.001199 load_settings               (2): Can't open settings file '/home/pi/.gphoto/settings' for reading.
0.001465 gp_camera_free              (2): Freeing camera...
0.001483 gp_port_free                (2): Freeing port...
0.001497 gp_filesystem_reset         (2): resetting filesystem
0.001510 gp_filesystem_lru_clear     (2): Clearing fscache LRU list...
0.001521 gp_filesystem_lru_clear     (2): fscache LRU list already empty
0.001532 delete_all_folders          (2): Internally deleting all folders from '/'...
0.001545 lookup_folder               (2): Lookup folder '/'...
0.001556 lookup_folder               (2): Found! / is 0x18d6d60
0.001570 recurse_delete_folder       (2): Recurse delete folder 0x18d6d60//

I am unsure what is happening, weather its hardware e.g the micro-usb cable is not compatible or software where it just doesn't have the drivers.. Please help my I want to use this as my camera for octoprint.

**Comment by msmeissn** [comment]
does:

gphoto2 --list-cameras 

show a lot of cameras?

can you attach output of
gphoto2 --auto-detect --debug

**Comment by SeventhDread** [comment]
Yes, list cameras brings a whole list of cameras, 
[auto_detect_debug.txt](https://github.com/gphoto/gphoto2/files/4606106/auto_detect_debug.txt)
And there the debug for auto detect I copied it into a txt file as I didn't want to flood the chat.

**Comment by msmeissn** [comment]
can you check if it is visible when you run: lsusb   ? 
It should show up in this list.

**Comment by SeventhDread** [comment]
This is what I get: 
Bus 001 Device 019: ID 1997:2433
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp. SMC9514 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
 
I don't see it..

**Comment by msmeissn** [comment]
what camera is it?
so can you check cabling and battery status?
if everything looks good, also "dmesg" output on the Pi if there are USB errors.

**Comment by SeventhDread** [comment]
Well theres the dmesg: 
[dmesg.txt](https://github.com/gphoto/gphoto2/files/4606380/dmesg.txt)
Definitly some errors, and not sure what you mean by check cabling and battery status but I think you mean like the cable is plugged in right which I believe it is there is metal showing but its as far as I am comfortable pushing it in on the camera incase it breaks and the battery its about 50-75% doesn't show exact charge on the camera.

**Comment by msmeissn** [comment]
[ 5295.763437] usb 1-1-port2: Cannot enable. Maybe the USB cable is bad?

So something is weird with the connection...
 
Yes, please do not "force push" anything.

Also one reason of problems on Rasperry Pi is that the powersupply might not provide enough power. DO you use the original powersupply / or one with enough power?

**Comment by SeventhDread** [comment]
Sorry for the delay but yes I believe i am using the power supply that comes in the box 5v 2.5A but once on octoprint it said low power so will try another plug and try again thanks. And dont think its the cable as i was able to transfer files to my computer over it.

**Comment by SeventhDread** [comment]
Just tried another plug and no change..

**Comment by SeventhDread** [comment]
Well I just was messing around desided to unplug my wireless keyboards dongle and plug the cameras usb in that port.. AND IT WOKRED!!! So for some reason the other ports are faulty, but it comes up as 'USB PTP Class Camera' not the actual camera name.. Will it still work?

**Comment by SeventhDread** [comment]
And when I try and use the gphoto2 --capture-image command it gives me this.. : 

*** Error ***
An error occurred in the io-library ('Could not claim the USB device'): Could not claim interface 0 (Device or resource busy). Make sure no other program (gvfs-gphoto2-volume-monitor) or kernel module (such as sdc2xx, stv680, spca50x) is using the device and you have read/write access to the device.
ERROR: Could not capture image.
ERROR: Could not capture.
*** Error (-53: 'Could not claim the USB device') ***

For debugging messages, please use the --debug option.
Debugging messages may help finding a solution to your problem.
If you intend to send any error or debug messages to the gphoto
developer mailing list <gphoto-devel@lists.sourceforge.net>, please run
gphoto2 as follows:

    env LANG=C gphoto2 --debug --debug-logfile=my-logfile.txt --capture-image

Please make sure there is sufficient quoting around the arguments.

Any idea what this is?

**Comment by msmeissn** [comment]
it is blocked by another process, likely gvfs...

try:
gio mount -s gphoto2

to umount the gphoto slaves.

--capture-image might work already, if not you probably need current libgphoto2 GIT or at least 2.5.24 :/

**Comment by SeventhDread** [comment]
Well doing the gio mount made the lense open when I capture image but then the camera just turns off..

**Comment by msmeissn** [comment]
In this case you will need a newer verison of libgphoto2.

IN general the PowerSHOT SX capture is still very fragile.

**Comment by SeventhDread** [comment]
How do I update it? Is there a command?

**Comment by msmeissn** [comment]
a generic updater is at:  
https://github.com/gonzalo/gphoto2-updater

but otherwise it is usually not straigt forward

**Comment by SeventhDread** [comment]
I tried that but didn't work, so I am trying this 

https://i386.com/upgrading-gphoto2-for-raspberry-pi-to-solve-canon-5d-mkiii-issues/

**Comment by SeventhDread** [comment]
Didn't work..

**Comment by SeventhDread** [comment]
Now this: https://pimylifeup.com/raspberry-pi-dslr-camera-control/

**Comment by SeventhDread** [comment]
It just won't update its staying as: 
gphoto2:         2.5.23        
libgphoto2:      2.5.22         
libgphoto2_port: 0.12.0 

Will not update, do you know why?

**Comment by SeventhDread** [comment]
I am going to close this and open a new one as I was able to get the camera to show up which is what I wanted and will open a new one for unable to capture image and other error thank you.
