### ISSUE TITLE
gPhoto2 - EXIF of RAW Image File

### ISSUE THREAD

**Issue by sakibnaz** [gphoto/gphoto2#322]
Hi.

Is it possible to read detail EXIF (Camera Parameter - Shutter, ISO, F-Stop etc) of RAW image via gPhoto2 CLI?

Thanks.

**Comment by msmeissn** [comment]
No, usually gphoto2 is not for reading out file metadata.

For raw files, use "exiftool" ... I just tested with CR2 and NEF.

**Comment by sakibnaz** [comment]
Thanks. Yes, I was also planning to use ExifTool.
