### ISSUE TITLE
gPhoto2 - File Upload Error | PTP Access Denied

### ISSUE THREAD

**Issue by sakibnaz** [gphoto/gphoto2#324]
HI there.

I am getting error when trying to Upload a txt file (in Canon 6D Camera) using below command.

gphoto2 --upload-file test.txt --folder /store_00020001/DCIM/100CANON

It reports Error - PTP Access Denied.

![image](https://user-images.githubusercontent.com/6670151/81969920-7dbf8c00-9640-11ea-96d1-b35373a383f5.png)

![image](https://user-images.githubusercontent.com/6670151/81970093-cc6d2600-9640-11ea-9b9c-781141c31632.png)

Debug log attached.

[upload-logfile.txt](https://github.com/gphoto/gphoto2/files/4630161/upload-logfile.txt)

Please advise.

Thanks.

**Comment by msmeissn** [comment]
The Canons can only upload JPEG, if at all. No other file types.

Nikon do not support file upload at all.

I think we also had this by email.

**Comment by sakibnaz** [comment]
Yes, Thanks a lot @msmeissn.
