### ISSUE TITLE
gPhoto2 - Bulb Capture Time Issue

### ISSUE THREAD

**Issue by sakibnaz** [gphoto/gphoto2#326]
Hello.

Using my Canon EOS 6D I can trying to do a Bulb capture of exact exposure time 3.8s. I am using below command:

gphoto2 --set-config eosremoterelease=Immediate --wait-event=3.8s --set-config eosremoterelease="Release Full" --wait-event-and-download=2s

But when checking the Exposure Time on Camera as well as using ExifTool its 2.9s

Can anyone advise how to get exact Bulb Timing?

Terminal log is attached.

[Bulb_Capture_Log.txt](https://github.com/gphoto/gphoto2/files/4631644/Bulb_Capture_Log.txt)

Thanks.

**Comment by msmeissn** [comment]
Currently it parses integer seconds if you specify it with <number>s, so ---wait-event=3.8s waits 3 seconds.

--wait-event=3800ms     
would work as workraound

I have to think if we parse fractional seconds here.. hmm

**Comment by sakibnaz** [comment]
Thanks.
