### ISSUE TITLE
--frames 1 does not capture 1 frame / image. 

### ISSUE THREAD

**Issue by jacksnodgrass** [gphoto/gphoto2#327]
gphoto2 --capture-image-and-download --frames 1

creates / downloads 4 to 5 images.... I expect it do do 1 image... unless I am not understanding what a frame is.  If 4 to 5 images is ok for --frames 1... then how can I get just 1 image.. that's all I need.. the additional images just slow things down.

**gphoto2 --capture-image-and-download --frames 1**
New file is in location /capt0000.jpg on the camera                            
Saving file as capt0000.jpg
Deleting file /capt0000.jpg on the camera
New file is in location /capt0001.jpg on the camera                            
Saving file as capt0001.jpg
Deleting file /capt0001.jpg on the camera
New file is in location /capt0002.jpg on the camera                            
Saving file as capt0002.jpg
Deleting file /capt0002.jpg on the camera
New file is in location /capt0003.jpg on the camera                            
Saving file as capt0003.jpg
Deleting file /capt0003.jpg on the camera
New file is in location /capt0004.jpg on the camera                            
Saving file as capt0004.jpg
Deleting file /capt0004.jpg on the camera
New file is in location /capt0005.jpg on the camera                            
Saving file as capt0005.jpg
Deleting file /capt0005.jpg on the camera

it takes 5 to 7 seconds

SONY RX100 M4 IV
Sony DSC-RX100M4               usb:001,020 

This version of gphoto2 is using the following software versions and options:
gphoto2         2.5.23         gcc, popt(m), exif, no cdk, no aa, jpeg, readline
libgphoto2      2.5.24         standard camlibs, gcc, ltdl, EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi, gcc, ltdl, EXIF, USB, serial lockdev locking

**Comment by msmeissn** [comment]
it should only take 1, and just trying it here it just takes 1.

Does this also happen with
 gphoto2 --capture-image-and-download
without --frames 1?

Is there some form of bracketing enabled on camera?

**Comment by jacksnodgrass** [comment]
I am not really sure what is going on but NOW when I run: 
**gphoto2 --capture-image-and-download --frames 1**
I get: 
```
New file is in location /capt0000.jpg on the camera                            
Saving file as capt0000.jpg
Deleting file /capt0000.jpg on the camera
```

... the expected behavior... I cut / pasted the command from above where it did 5 images. 

I did upgrade files on my system... but I re-tested the command I was using and got the same results... maybe I needed to logout and log back in to see the changes... 

I updated: 
gphoto2-2.5.23-2.fc32.x86_64

and I installed and played around with: entangle

anyway... 9 hours later... the command works correctly. 

Thanks - jack
