### ISSUE TITLE
Sony a6000 capture interval bug

### ISSUE THREAD

**Issue by AlexisPotvin** [gphoto/gphoto2#33]
Hello, we have been testing the sony a6000 with libgphoto and Gphoto2 .
 When we were using Gphoto2, --capture-image-and-download --interval=1 , the interval stop after 12-30 pictures for 35 seconds and then take a couple of pictures and then an other 35 sec wait and so on. We also tested with an other program using libgphoto and the same problem happen.

**Comment by msmeissn** [comment]
this is sadly one Sony capture issue we are currently having ... occasionaly we do not receive the capturecomplete event and wait for 30 seconds

**Comment by AlexisPotvin** [comment]
Thanks a lot for you feed back! Would it be possible not to wait for the response from the camera? Only send the call to take a picture without waiting for the feedback?

**Comment by msmeissn** [comment]
I had implemented  this for nikon and canon, but not yet for Sony, as it is tricky :/ I can try for the next release :/

**Comment by TominJoseph18** [comment]
Hey .. Is a fix for the Sony available now?

Reply asap. Thanks.

**Comment by AlxStenshin** [comment]
Hello. I am experiencing same issue with sony rx100. 
Here is my capture log:
[capture.txt](https://github.com/gphoto/gphoto2/files/1141651/capture.txt)
 I hope it can be useful.

**Comment by msmeissn** [comment]
The 35 second wait delay should mostly be gone. 

In the trace from the last comment I see continous interval picture retrieval, no more 35 seconds waits.

I have implemented --trigger-capture too, it is enabled since 2.5.11 actually.

**Comment by msmeissn** [comment]
i think this is done.
