### ISSUE TITLE
gPhoto2 - Nikon D3200 Manualfocusdrive Problem

### ISSUE THREAD

**Issue by sakibnaz** [gphoto/gphoto2#331]
Hi there.

I am unable to make "manualfocusdrive" on my Nikon D3200. Please have a look the below. gPhoto reports Error message:

Failed to set new configuration value 1500 for configuration entry manualfocusdrive.
*** Error (-6: 'Unsupported operation') ***

![image](https://user-images.githubusercontent.com/6670151/83365722-22c1bf00-a3cc-11ea-8fd7-deca083d0c8d.png)

My lens is "**_AF-S Nikkor 18-55mm 1:3.5-F5.6G DX VR_**" and I tested manualfocusdrive with this lens and Nikon D5100 before, which worked ok.

Also debug log is attached.

[manualfocusdrive-logfile.txt](https://github.com/gphoto/gphoto2/files/4708712/manualfocusdrive-logfile.txt)

Please advise.

Thanks.

**Comment by msmeissn** [comment]
We add several commands "by guessing" to the D3xx cameras, apparently MfDrive is not supported on it.

**Comment by msmeissn** [comment]
I will remove manualfocusdrive from the list of available commands.

does gphoto2 --set-config autofocus=1  work?

Does on camera movie recording work with:
gphoto2 --set-config movie=1 --wait-event=10s --set-config movie=0 --wait-event-and-download=2s

**Comment by sakibnaz** [comment]
Hi @msmeissn.

Yes, both autofocus=1 and autofocusdrive=1 works but movie=1 gives 
Error: PTP Operation Not Supported.

Thanks.
