### ISSUE TITLE
gPhoto2 - Nikon D3200 Bulb Capture Problem

### ISSUE THREAD

**Issue by sakibnaz** [gphoto/gphoto2#332]
Hi there.

I am unable to make Bulb capture on my Nikon D3200. I have set my Shutterspeed to Bulb Mode and run the below command to Open and Close Bulb Shutter for 5s.

gphoto2 --set-config shutterspeed=52
gphoto2 --set-config bulb=1 --wait-event=5s --set-config bulb=0

But gPhoto reports Error message: **"Failed to set new configuration value 1 for configuration entry bulb"**

![image](https://user-images.githubusercontent.com/6670151/83366008-235b5500-a3ce-11ea-8b28-2ffb7e9c6b8c.png)

Also debug log is attached.

[bulb-logfile.txt](https://github.com/gphoto/gphoto2/files/4708721/bulb-logfile.txt)

Please advise.

Thanks.

**Comment by msmeissn** [comment]
I think it does not support bulb capture.

For the D3xxx we have added "guessed" commands to their initialization, and the guessing here was too optimistic.

**Comment by sakibnaz** [comment]
Noted. Thanks.
