### ISSUE TITLE
One third stop settings - Choice: vs. actual

### ISSUE THREAD

**Issue by theapiarist** [gphoto/gphoto2#334]
**Describe the bug**

The one-third stop scale (gphoto2 --get-config /main/capturesettings/aperture reports choice vs f-stop) but some stops cannot being set. 

Camera operation - aperture priority, lens - 100mm f2.8 

**Name the camera**

Model                          Port                                            
----------------------------------------------------------
Canon EOS 600D                 usb:001,002     

**libgphoto2 and gphoto2 version**
gphoto2 2.5.23

Copyright (c) 2000-2019 Marcus Meissner and others

gphoto2 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of gphoto2 under the terms of the GNU General Public
License. For more information about these matters, see the files named COPYING.

This version of gphoto2 is using the following software versions and options:
gphoto2         2.5.23         gcc, popt(m), exif, no cdk, no aa, jpeg, no readline
libgphoto2      2.5.25         standard camlibs (SKIPPING lumix), gcc, ltdl, EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb usbdiskdirect usbscsi, gcc, ltdl, EXIF, USB, serial without locking

**To Reproduce**

pi@camerapi:~ $ gphoto2 --set-config /main/capturesettings/aperture=0
pi@camerapi:~ $ gphoto2 --get-config /main/capturesettings/aperture
Label: Aperture                                                                
Readonly: 0
Type: RADIO
Current: 2.8
Choice: 0 2.8
Choice: 1 3.2
Choice: 2 3.5
Choice: 3 4
Choice: 4 4.5
Choice: 5 5
Choice: 6 5.6
Choice: 7 6.3
Choice: 8 7.1
Choice: 9 8
Choice: 10 9
Choice: 11 10
Choice: 12 11
Choice: 13 13
Choice: 14 14
Choice: 15 16
Choice: 16 18
Choice: 17 20
Choice: 18 22
Choice: 19 25
Choice: 20 29
Choice: 21 32
END

All above is OK, but ...

pi@camerapi:~ $ gphoto2 --set-config /main/capturesettings/aperture=4
pi@camerapi:~ $ gphoto2 --get-config /main/capturesettings/aperture          
Label: Aperture                                                                
Readonly: 0
Type: RADIO
Current: 4
Choice: 0 2.8
Choice: 1 3.2
Choice: 2 3.5
Choice: 3 4
Choice: 4 4.5
Choice: 5 5
Choice: 6 5.6
Choice: 7 6.3
Choice: 8 7.1
Choice: 9 8
Choice: 10 9
Choice: 11 10
Choice: 12 11
Choice: 13 13
Choice: 14 14
Choice: 15 16
Choice: 16 18
Choice: 17 20
Choice: 18 22
Choice: 19 25
Choice: 20 29
Choice: 21 32
END

Aperture was set at Choice 4 and so should be F4.5, but actually is F4. When I check the EXIF data on the pics photographs are taken at the F stop indicated by "Current:" ... so F2.8 in the first example and F4.0 in the second.

There are several instances through the range of 1/3rd F stops that this can be reproduced - if the config is set to 9 (and it should therefore be F8) the get-config reported is 9 and the photo is taken at F9

--set-config = 11 (so should be F10) ... get-config reports 11 and EXIF reports photo at F11

I'm writing scripts for remote wildlife photography in poor light. I should buy a longer, faster lens, but would prefer not to ;-)

Thanks for all your work on this
 

If its a camera misbehavior, attach debug output using  --debug --debug-logfile=debug.log   (if considered useful).

**Comment by theapiarist** [comment]
I should have added - this might be related to [issue #222](https://github.com/gphoto/gphoto2/issues/222)

**Comment by msmeissn** [comment]
I think here the problem is that "index" and "value" are too common, and the code selects the wrong one.

Can you use 
  gphoto2 --set-config-index aperture=3  
or
 gphoto2 --set-config-value aperture=4
for aperture 4

**Comment by theapiarist** [comment]
That works 👍 
Many thanks for such a quick response.
Have a good weekend.
