### ISSUE TITLE
Impossible to save directly to Sony A7iii SD card (Firm 3.10)

### ISSUE THREAD

**Issue by ManuMCoupe** [gphoto/gphoto2#337]
Fill in fields below. If you don't know how, leave it free.

**Sony A7 M
![Error a7iii](https://user-images.githubusercontent.com/43456883/84534801-e014b680-acea-11ea-8315-fe02bae1f957.png)
ark III*

Use the Marketing name.

**USB IDs**
e.g. by running:   lsusb 

**camera summary output**
run

  gphoto2 --summary > summary.txt

attach summary.txt here

**camera configuration output**

gphoto2 --list-all-config > list-all-config.txt

and attach list-all-config.txt here

**test capture**

test if capture perhaps already works:

  gphoto2 --capture-image-and-download
 
  gphoto2 --capture-preview

**Comment by msmeissn** [comment]
you seem to have an older version of libgphoto2.

Please update to 2.5.25 and see if this makes it work.

**Comment by ManuMCoupe** [comment]
> 
> 
> you seem to have an older version of libgphoto2.
> 
> Please update to 2.5.25 and see if this makes it work.

Thanks. I think it works after updating everything. I'll try this afternoon with octolapse. Thanks

**Comment by ManuMCoupe** [comment]
![Error a7iii Fixed](https://user-images.githubusercontent.com/43456883/84661957-64e61700-af1b-11ea-89eb-594915d30cbb.png)

**Comment by msmeissn** [comment]
and if you set it to gphoto2 --set-config capturetarget="card+sdram" ... does it help?

**Comment by ManuMCoupe** [comment]
> 
> 
> and if you set it to gphoto2 --set-config capturetarget="card+sdram" ... does it help?

Yes, thanks
Problem fixed ^^

**Comment by msmeissn** [comment]
thanks!
