### ISSUE TITLE
Support for Sony A6400 (ILCE-6400)

### ISSUE THREAD

**Issue by EchoUrandom404** [gphoto/gphoto2#338]
**Name of the camera**

Sony A6400 E-mount camera with APS-C Sensor

**USB IDs**

`Bus 005 Device 014: ID 054c:0caa Sony Corp.`

**camera summary output**

[summary.txt](https://github.com/gphoto/gphoto2/files/4773760/summary.txt)

**camera configuration output**

[list-all-config.txt](https://github.com/gphoto/gphoto2/files/4773763/list-all-config.txt)

**test capture**

![capture_preview](https://user-images.githubusercontent.com/22819862/84556248-60c1ca00-ad60-11ea-8a43-bd8e98bd0cca.jpg)
![capt0000](https://user-images.githubusercontent.com/22819862/84556252-61f2f700-ad60-11ea-9b63-161c068b4631.jpg)

It also outputted an .arw file but github won't upload it. The test capture basically works fine though.

**Comment by msmeissn** [comment]
Thanks for the report, looks all good! 

We have the camera already listed in libgphoto2 2.5.24 and newer releases.
