### ISSUE TITLE
Fuji X-T2 and X-T1 - 'Sorry, your camera does not support generic capture' & 'PTP Device Prop Not Supported'

### ISSUE THREAD

**Issue by ACMACMACM** [gphoto/gphoto2#339]
I have just the command line running on the Pi4B, and only the camera connected via USB cable.

gphoto2 --auto-detect
shows the Fuji Fujifilm X-T2 connected on Port usb:001,003

Looking promising..

gphoto2 --summary
tells me: No image capture, No open capture, No vendor specific capture

A little less promising...

gphoto2 --debug-logfile=mylogfile.txt --capture-image
tells me: ERROR
'Sorry, your camera does not support generic capture'

GPhoto version: 2.5.20, libgphoto2: 2.5.24.1, libgphoto2_port 0.12.0

The X-T2 camera was in Bulb mode, connected to the Pi 4B via a working USB cable (it can control the mount no problem) with the LCD screen showing black with 'USB Mode' displayed.

Same happens for both Fuji X-T2 and Fuji X-T1 cameras.

Any help here is very appreciated.

**Comment by ACMACMACM** [comment]
Running v2.0.1 of Astroberry
The current version of KStars 3.4.2
Only a Fuji X-T2 connected via USB cable
Ekos running the camera with the GPhoto CCD driver (GPhoto version: 2.5.20, libgphoto2: 2.5.24.1, libgphoto2_port 0.12.0)

The X-T2 camera was in Bulb mode, connected to the Pi 4B via a working USB cable (it can control the mount no problem) with the LCD screen showing black with 'USB Mode' displayed.

**Comment by ACMACMACM** [comment]
I updated to the latest version fo GPhoto2 (v 2.5.23 and also the libgphoto2 2.5.25 however that still says its on 2.5.24.1 for some reason.  Install of that appeared to be successful.

Logfile attached.
[my-logfile5.txt](https://github.com/gphoto/gphoto2/files/4775912/my-logfile5.txt)

**Comment by msmeissn** [comment]
http://fujifilm-dsc.com/en/manual/x-t2/menu_setup/connection_setting/index.html

Is the USB mode in the camera set to one of the tether modes?

**Comment by ACMACMACM** [comment]
I now set the in camera PC Connection setting to 'USB TETHER SHOOTING AUTO'
I then ran:
gphoto2 --capture-image 

....and 
Its working!!  Thankyou.  

The default PC Connection setting in camera was 'USB CARD READER' and this was where i was having the issue.  

Thanks a million.

**Comment by msmeissn** [comment]
very good to hear!

**Comment by ACMACMACM** [comment]
[Raised subsequent issue.](https://github.com/gphoto/gphoto2/issues/340)
