### ISSUE TITLE
Canon EOS Rebel SL3 Support

### ISSUE THREAD

**Issue by bananemure** [gphoto/gphoto2#343]
Hi, 
Currently Canon EOS Rebel SL3 Support is not supported with gphoto2.
Are you guys planing to add support to it ?
Please.
Thanks

**Comment by msmeissn** [comment]
This already should be done, it is listed as EOS 250D.

Please test and report back!

**Comment by joeySeal** [comment]
Does [remote](http://www.gphoto.org/doc/remote/) control work with the 250D/SL3? I see it is on the compatibility list but not remote control list and was not sure if that mean remote control does not work or nobody has tested it.

**Comment by msmeissn** [comment]
it should work , not sure we got a direct confirmation, but all current EOS / Rebel support capture + liveview.
