### ISSUE TITLE
gPhoto2 - List-Files Not Working After Movie Record

### ISSUE THREAD

**Issue by sakibnaz** [gphoto/gphoto2#344]
Hi there.

I am using Nikon D5100 where after Movie record if I run "--list-files" then it reports only There is no file in folder '/'. My card have files but which are not shown in list.

FYI please have a look the picture below:

![image](https://user-images.githubusercontent.com/6670151/86533901-478ee200-bef6-11ea-935a-8425d8a20f8e.png)

Any advise please?

Thanks in advance.

**Comment by sakibnaz** [comment]
Hi @msmeissn. Any suggestion please?

Thanks.

**Comment by msmeissn** [comment]
its weird ... the second --list-files should also list all files.

if you do 
gphoto2 --set-config movie=1 --wait-event=5s --set-config movie=0 --wait-event=2s      
to see the FILEADDED ? 

or perhaps a debug log of the second empty --list-files

**Comment by sakibnaz** [comment]
Hi @msmeissn ... I tried and FILEADDED is there but still no "list-files" result.

![image](https://user-images.githubusercontent.com/6670151/87185022-dc387c00-c30a-11ea-9a90-d8a09524b865.png)

FYI, debug log is attached for the empty "list-files".

[debug_list-file.txt](https://github.com/gphoto/gphoto2/files/4904690/debug_list-file.txt)
.
Thanks in advance.

Regards.

**Comment by msmeissn** [comment]
I fixed it in GIT I hope, you can also workaround it by doing 
gphoto2 --set-config applicationmode=0   
after movie capture
