### ISSUE TITLE
Nikon D300s locks up randomly

### ISSUE THREAD

**Issue by erikjber** [gphoto/gphoto2#345]
**Describe the bug**

When using gphoto2 to capture and download images via USB, the camera locks up. The operation times out, and all subsequent calls also time out.
The bug appears at random, sometimes after a few captures, sometimes several thousand captures are possible without issue.

Once the bug manifests, the camera is locked in PC mode, with the upload progress bar moving and filling over and over again.

Disconnecting the USB cable does not work. Turning off the camera does not work. The only thing that works is to turn off the camera power, either by disconnecting the power cable or removing the battery.

**Name the camera**
Nikon DSC D300s (PTP mode)     usb:001,006

**libgphoto2 and gphoto2 version**
gphoto2         2.5.23.1       gcc, popt(m), no exif, no cdk, no aa, jpeg, no readline
libgphoto2      2.5.25         standard camlibs (SKIPPING lumix), gcc, ltdl, no EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi, gcc, ltdl, no EXIF, USB, serial without locking

**To Reproduce**

This behaviour is observed on Raspberry Pi, hardvare revision a020d3, Raspbian 9 Stretch, kernel version 4.19.66-v7+.
1. Connect raspberry pi to camera via USB. 
2. Make sure camera battery is fully charged or mains adapter is connected.
3. Execute the following command repeatedly until bug manifests:
    gphoto2 --capture-image-and-download --filename tmp/tmp.jpg --force-overwrite --debug --debug-loglevel debug

If its a camera misbehavior, attach debug output using  --debug --debug-logfile=debug.log   (if considered useful).

Two logs are attached, one from a successful invocation (good.log) and one from the first invocation that fails (bad.log).
[bad.log](https://github.com/gphoto/gphoto2/files/4885931/bad.log)
[good.log](https://github.com/gphoto/gphoto2/files/4885933/good.log)

**Comment by msmeissn** [comment]
I added another safety check in the sdram delettion code... lets see if it helps

**Comment by msmeissn** [comment]
can you try current git of libgphoto2?

**Comment by erikjber** [comment]
Testing it now.

**Comment by erikjber** [comment]
I've now taken 10000 images without any problems whatsoever. Awesome! Thank you so much!

**Comment by msmeissn** [comment]
good to hear it works:)
