### ISSUE TITLE
Folder creation return PTP Access Denied (Canon EOS R2)

### ISSUE THREAD

**Issue by Patrick-Lascombe** [gphoto/gphoto2#351]
Hello,

I'm working on a Canon EOS R2, when using `gphoto2 --mkdir=/store_00020001/DCIM/102CANON` I get the following error : 
```

*** Error ***              
PTP Access Denied
*** Error (-1: 'Unspecified error') ***       

For debugging messages, please use the --debug option.
Debugging messages may help finding a solution to your problem.
If you intend to send any error or debug messages to the gphoto
developer mailing list <gphoto-devel@lists.sourceforge.net>, please run
gphoto2 as follows:

    env LANG=C gphoto2 --debug --debug-logfile=my-logfile.txt --mkdir=/store_00020001/DCIM/102CANON

Please make sure there is sufficient quoting around the arguments.

```

Is there a requirement that I'm missing concerning the folder creation or a configuration that I need to do ?

Thanks

**Comment by msmeissn** [comment]
canon cameras allow only very limited filesystem operations from the host.

as far as I know at most jpeg upload is supported, nothing else. 

so its a camera side limitation.
