### ISSUE TITLE
gPhoto2 - Nikon D3200 Movie Record

### ISSUE THREAD

**Issue by sakibnaz** [gphoto/gphoto2#352]
Hi.

I am not able to do Movie Record in my D3200 ... gPhoto reports "PTP Operation Not Supported" when I run "--set-config movie=1".

![image](https://user-images.githubusercontent.com/6670151/88348964-95b63900-cd70-11ea-9878-caf460eb46de.png)

Debug log is here.

[movie-logfile.txt](https://github.com/gphoto/gphoto2/files/4969595/movie-logfile.txt)

Please advise.

Thanks.

**Comment by msmeissn** [comment]
This kind of movie capture is not supported on D3200, we mistakenly had it in the override list.

**Comment by msmeissn** [comment]
On Thu, Jul 23, 2020 at 04:45:34PM -0700, sakibnaz wrote:
> Hi.
> 
> I am not able to do Movie Record in my D3200 ... gPhoto reports "PTP Operation Not Supported" when I run "--set-config movie=1".
> 
> ![image](https://user-images.githubusercontent.com/6670151/88348964-95b63900-cd70-11ea-9878-caf460eb46de.png)
> 
> Debug log is here.
> 
> [movie-logfile.txt](https://github.com/gphoto/gphoto2/files/4969595/movie-logfile.txt)
> 
> Please advise.

movie recording is not supported on the D3200.

I initially "guessed" some of the hidden opcodes, but it turns out I guessed
too optimistic.

Ciao, Marcus
