### ISSUE TITLE
Cannot get shuttercount on EOS350d 

### ISSUE THREAD

**Issue by aseques** [gphoto/gphoto2#355]
I am using a gphoto2 to obtain data from a Canon EOS 350D, but unfortunately it doesn't work, the version I'm using of gphoto is 2.5.23 from ubuntu 20.04

When in mode PC set at the camera

```
Model                          Port                                            
----------------------------------------------------------
Canon Digital Rebel XT (normal mode) usb:003,003
```
When mode is set to PTP
```
Model                          Port                                            
----------------------------------------------------------
Canon EOS 350D                 usb:003,004     
```
On both cases I see this error in the output
```
*** Error ***              
/main not found in configuration tree.
*** Error (-1: 'Unspecified error') ***       
```
Stil I can get some attributes shown without issue such as `sudo gphoto2 --get-config /main/status/firmwareversion
[ptp.txt](https://github.com/gphoto/gphoto2/files/5047654/ptp.txt)
[pcmode.txt](https://github.com/gphoto/gphoto2/files/5047655/pcmode.txt)

Is there something I'm doing wrong? Thanks

**Comment by msmeissn** [comment]
You do not need to write the full path, you could use gphoto2 --get-config shuttercount

That said, as far as I currently know, the EOS 350D does not export the shuttercount to our knowledge.

**Comment by aseques** [comment]
Thanks for your help anyway
