### ISSUE TITLE
Nikon Z7 capture preview issue

### ISSUE THREAD

**Issue by px4Li** [gphoto/gphoto2#358]
**USB IDs**
by running:   lsusb 
Output:
Bus 002 Device 016: ID 04b0:0442 Nikon Corp. 

**camera summary output**
run

  gphoto2 --summary>summary.txt
[summary.txt](https://github.com/gphoto/gphoto2/files/5056125/summary.txt)

**camera configuration output**

gphoto2 --list-all-config > list-all-config.txt
and attach list-all-config.txt here
[list-all-config.txt](https://github.com/gphoto/gphoto2/files/5056130/list-all-config.txt)

**test capture**

test if capture perhaps already works:

  gphoto2 --capture-image-and-download
It is able to take picture.
Output:
New file is in location /store_00010001/DCIM/101NCZ_7/DSC_0045.JPG on the camera
Saving file as DSC_0045.JPG                                                    
Deleting file /store_00010001/DCIM/101NCZ_7/DSC_0045.JPG on the camera

  gphoto2 --capture-preview
It is not able to get live view.
Output:
*** Error (-6: 'Unsupported operation') ***                                    

For debugging messages, please use the --debug option.
Debugging messages may help finding a solution to your problem.
If you intend to send any error or debug messages to the gphoto
developer mailing list <gphoto-devel@lists.sourceforge.net>, please run
gphoto2 as follows:

    env LANG=C gphoto2 --debug --debug-logfile=my-logfile.txt --capture-preview

Please make sure there is sufficient quoting around the arguments.

and attach my-logfile.txt here
[my-logfile.txt](https://github.com/gphoto/gphoto2/files/5056236/my-logfile.txt)

**Comment by msmeissn** [comment]
you need to update to a more recent libgphoto2 version and this will be fixed. 2.5.16 is from 2017.
