### ISSUE TITLE
Nikon DSC D5200: Liveview cannot start

### ISSUE THREAD

**Issue by Hogfeldt** [gphoto/gphoto2#359]
Hi, I'm getting the following error, when trying to capture video with my Nikon DSC D5200:
```
$ gphoto2 --capture-movie
Capturing preview frames as movie to 'movie.mjpg'. Press Ctrl-C to abort.      

*** Error ***              
Liveview cannot start: code 0x80000000
ERROR: Movie capture error... Exiting.
Movie capture finished (0 frames)
-------------------------------------
```
I'm running the following software:
```
gphoto2               2.5.23 
libgphoto2            2.5.25
libgphoto2_port       0.12.0 
```
Here is some of the output i got from enabling debug: 
```
0.346218 gp_context_error            (0): Liveview cannot start: code 0x80000000
                                                                                               
*** Error ***                                                                                  
Liveview cannot start: code 0x80000000                                                                                                                                                         
0.346257 gp_camera_capture_preview [gphoto2-camera.c:1403](0): 'camera->functions->capture_preview ( camera, file, context)' failed: -1                                                       
ERROR: Movie capture error... Exiting.                                                         
Movie capture finished (0 frames)
0.346334 main                        (2): Uploading file...
*** Error (-1: 'Unspecified error') *** 
```
Is this a bug? Or is there some configuration I have to do for capturing video? I'm able to take photos with gphoto2.

**Comment by msmeissn** [comment]
On Thu, Aug 13, 2020 at 11:50:49AM -0700, Per Høgfeldt wrote:
> Hi, I'm getting the following error, when trying to capture video with my Nikon DSC D5200:
> ```
> $ gphoto2 --capture-movie
> Capturing preview frames as movie to 'movie.mjpg'. Press Ctrl-C to abort.      
> 
> *** Error ***              
> Liveview cannot start: code 0x80000000
> ERROR: Movie capture error... Exiting.
> Movie capture finished (0 frames)
> -------------------------------------
> ```
> I'm running the following software:
> ```
> gphoto2               2.5.23 
> libgphoto2            2.5.25
> libgphoto2_port       0.12.0 
> ```
> Here is some of the output i got from enabling debug: 
> ```
> 0.346218 gp_context_error            (0): Liveview cannot start: code 0x80000000
>                                                                                                
> *** Error ***                                                                                  
> Liveview cannot start: code 0x80000000                                                                                                                                                         
> 0.346257 gp_camera_capture_preview [gphoto2-camera.c:1403](0): 'camera->functions->capture_preview ( camera, file, context)' failed: -1                                                       
> ERROR: Movie capture error... Exiting.                                                         
> Movie capture finished (0 frames)
> 0.346334 main                        (2): Uploading file...
> *** Error (-1: 'Unspecified error') *** 
> ```
> Is this a bug? Or is there some configuration I have to do for capturing video? I'm able to take photos with gphoto2. 

0x80000000 according to the SDK means "The Exposure Program Mode property (...) is set to anything other than P/S/A/M."

Can you check that it is one of the 4 above modes?

Ciao, Marcus

**Comment by Hogfeldt** [comment]
Thank you very much! This solved my problem, had the camera in auto mode.

**Comment by enexusde** [comment]
Same to D3300.

**Comment by DrakoRod** [comment]
same to D5500 thanks!
