### ISSUE TITLE
Sony RX0 M2 ISO and exposure compensation adjustment

### ISSUE THREAD

**Issue by TimRyan99** [gphoto/gphoto2#363]
I have tried setting exposure compensation in Sony RX0 M2 (v2.0 firmware) and ISO in gphoto2 but without success. I see in gphoto2 --config that the ISO and exposure compensation fields are present but greyed out and are not accessible. Also Entangle does not allow these parameters to be changed. I understand Entangle uses libphoto2 library so presume the issue is to do with this library and not gphoto2 or Entangle. Finally I have checked on Windows machine with Sony ImageEdge-Remote and find I am able to make these changes. So looks like this is not a limitation of the camera. Appreciated any assistance. I have posted this same message on the libphoto2 github as the question may be more relevant to the underlying toolbox rather than gphoto2. Appreciate any assistance.

**Comment by msmeissn** [comment]
This is something I will adjust in the next release 2.5.26, the iso and shuttrerspeed and expcomp values are handled there better

**Comment by TimRyan99** [comment]
Tested fix and can now set ISO value of Sony RX0 using gphoto2 - thanks so much for this update. 

Used https://github.com/msmeissn/gphoto2-updater to do the update - worked well

**Comment by msmeissn** [comment]
thx for the feedback!
