### ISSUE TITLE
GoPro HERO 8 PTP I/O Error

### ISSUE THREAD

**Issue by derekseiple** [gphoto/gphoto2#365]
**Describe the bug**

I am unable to get summary information or otherwise interact with the camera.

**Name the camera**
I am using the GoPro HERO 8, but it shows as follows with `--auto-detect`:
```
$ gphoto2 --auto-detect
Model                          Port                                            
----------------------------------------------------------
USB PTP Class Camera           usb:001,008
```

**libgphoto2 and gphoto2 version**
```
$ gphoto2 --version
gphoto2 2.5.20

Copyright (c) 2000-2018 Lutz Mueller and others

gphoto2 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of gphoto2 under the terms of the GNU General Public
License. For more information about these matters, see the files named COPYING.

This version of gphoto2 is using the following software versions and options:
gphoto2         2.5.20         gcc, popt(m), exif, cdk, aa, jpeg, readline
libgphoto2      2.5.22         all camlibs, gcc, ltdl, EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi, gcc, ltdl, USB, serial without locking
```

**To Reproduce**
Simply run `gphoto2 --summary` with the camera plugged in.

Please see attached debug log:
[my-logfile.txt](https://github.com/gphoto/gphoto2/files/5234939/my-logfile.txt)

**Comment by msmeissn** [comment]
it is reporting a storage id of 0x4 .. which is very low (it should have a high bit set)

what kind of stoage is available? is the card plugged in?

**Comment by derekseiple** [comment]
Thank you for your response. Yes, the SD card is plugged in. I can browse the files on the camera. I should note that I ran the above on Debian. I have since also installed `gphoto2` on macOS Catalina and it is working fine there. The problem is that I really need it to work on Debian..

Attached is the (working) debug log from macOS:
[my-logfile.txt](https://github.com/gphoto/gphoto2/files/5239299/my-logfile.txt)

**Comment by msmeissn** [comment]
It is not clear why it happens there, for my Hero 7 it works on openSUSE :/

If have the ability to try a newer libgphoto2, you can try that but I do not think it will.

is there an error in "dmesg" perhaps when this happens?

**Comment by luzpaz** [comment]
@derekseiple ping

**Comment by msmeissn** [comment]
as there was no reaction, lets close.
