### ISSUE TITLE
Sony Alpha A9 detected as Sony Corp. ILCE-6000 by lsusb and not found when running gphoto2 --auto-detect

### ISSUE THREAD

**Issue by henningdekode** [gphoto/gphoto2#370]
**Describe the bug**
Sony Alpha A9 detected as Sony Corp. ILCE-6000 (aka Alpha-6000) in charging mode

When connecting a Sony Alpha A9 to the usb port of a Raspberry Pi Zero W lsusb lists it as 
Bus 001 Device 010: ID 054c:0994 Sony Corp. ILCE-6000 (aka Alpha-6000) in charging mode

**Name the camera**
If this is camera specific, include the camera name as shown by gphoto2 --auto-detect or USB IDs
Camera Name: Sony Alpha A9 - firmware version 6.0 
Listed name by lsusb:
Bus 001 Device 010: ID 054c:0994 Sony Corp. ILCE-6000 (aka Alpha-6000) in charging mode

**libgphoto2 and gphoto2 version**
output of: gphoto2 --version

gphoto2         2.5.26         gcc, popt(m), exif, no cdk, no aa, no jpeg, no readline
libgphoto2      2.5.26         standard camlibs (SKIPPING docupen lumix), gcc, ltdl, EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi, gcc, ltdl, EXIF, USB, serial without locking

**To Reproduce**

Connect a Sony A9 
Run gphoto2 --auto-detect

If its a camera misbehavior, attach debug output using  --debug --debug-logfile=debug.log   (if considered useful).

Output from  gphoto2 --auto-detect -debug --debug-logfile=debug.log

*** Error: No camera found. ***

For debugging messages, please use the --debug option.
Debugging messages may help finding a solution to your problem.
If you intend to send any error or debug messages to the gphoto
developer mailing list <gphoto-devel@lists.sourceforge.net>, please run
gphoto2 as follows:

    env LANG=C gphoto2 --debug --debug-logfile=my-logfile.txt --auto-detect -debug --debug-logfile=debug.log

Please make sure there is sufficient quoting around the arguments.

**Comment by henninghov** [comment]
It turned out to be a cable issue closing.
