### ISSUE TITLE
Displayed version for libgphoto2 wrong?

### ISSUE THREAD

**Issue by groboter** [gphoto/gphoto2#372]
I've just installed the new versions 2.5.26 for both libgphoto2 and gphoto2 on a fresh raspberry pi.

The command `gphoto2 --version` shows only version **2.5.22** instead of 2.5.26 for libgphoto2. Why?
Here is the complete version string from gphoto2:

```
gphoto2 2.5.26

Copyright (c) 2000-2020 Marcus Meissner and others

gphoto2 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of gphoto2 under the terms of the GNU General Public
License. For more information about these matters, see the files named COPYING.

This version of gphoto2 is using the following software versions and options:
gphoto2         2.5.26         gcc, popt(m), exif, no cdk, no aa, no jpeg, no readline
libgphoto2      2.5.22         all camlibs, gcc, ltdl, EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi, gcc, ltdl, USB, serial without locking

```

**Comment by msmeissn** [comment]
This usually means the system libgphoto2 is used instead of the installed libgphoto2.
your build is probably in /usr/local if you did not specify a --prefix during configure

you probably either need to overwrite the system install or remove it and just use the one in /usr/local

**Comment by groboter** [comment]
Thanks for your answer. You were right the build was in /usr/local so I tried to delete the system install but after some point nothing worked and I installed it new according to this [guide](https://pimylifeup.com/raspberry-pi-dslr-camera-control/). But the result is exactly the same:
gphoto2 2.5.26.1
libgphoto2 2.5.22
libgphoto_port 0.12.0

Unfortunately I am a linux beginner and do not understand what to do now?

**Comment by tvaucher** [comment]
Hello,
I don't know if it's relevant to you anymore, but I recently started from a clean astroberry image which has an old version of `libgphoto2` installed as well.

If you followed the guide you linked, you probably still have an old version of `libgphoto2` laying around somewhere which gets linked before the newly installed one.
What's the output of `ldconfig -p | grep libgphoto2` ? You probably will have
```bash
libgphoto2_port.so.12 (libc6,hard-float) =>  /usr/lib/something/libgphoto2_port.so.12
libgphoto2_port.so.12 (libc6,hard-float) => /usr/local/lib/libgphoto2_port.so.12
libgphoto2_port.so (libc6,hard-float) =>  /usr/lib/something/libgphoto2_port.so
libgphoto2_port.so (libc6,hard-float) => /usr/local/lib/libgphoto2_port.so
libgphoto2.so.6 (libc6,hard-float) =>  /usr/lib/something/libgphoto2.so.6
libgphoto2.so.6 (libc6,hard-float) => /usr/local/lib/libgphoto2.so.6
libgphoto2.so (libc6,hard-float) => /usr/lib/something/libgphoto2.so
libgphoto2.so (libc6,hard-float) => /usr/local/lib/libgphoto2.so
```

` /usr/lib/something/` will obviously depend on your system. Once you identified that you can run
```bash
sudo rm -rf  /usr/lib/something/libgphoto*
sudo ldconfig
```

And your new libgphoto2 should be the only version in the linker (check again using `ldconfig -p | grep libgphoto2`)
Hope this helps.

**Comment by groboter** [comment]
First sorry for the long delay!

The solution from tvaucher solved the problem!

Many thanks @tvaucher!
