### ISSUE TITLE
F-number options for Sony Cameras empty / not returned

### ISSUE THREAD

**Issue by henninghov** [gphoto/gphoto2#376]
**Describe the bug**
When running: 
gphoto2 --get-config f-number or 
gphoto2 --get-config /main/capturesettings/f-number

The camera returns no options for the f-number options available for the camera / lens combination. The data returned is: 

Label: F-Number
Readonly: 1
Type: RANGE
Current: 0
Bottom: 0
Top: 655.35
Step: 0.01
END

I expected that the function would return the options supported for the lens attached as options.

Setting f-number values works with value and but with index using --set-cofig
gphoto2 --set-config-value /main/capturesettings/f-number=7.1

OK

Not working: 
gphoto2 --set-config-index /main/capturesettings/f-number=7

*** Error ***
The /main/capturesettings/f-number widget has no indexed list of choices. Use --set-config-value instead.
*** Error (-2: 'Bad parameters') ***

For debugging messages, please use the --debug option.
Debugging messages may help finding a solution to your problem.
If you intend to send any error or debug messages to the gphoto
developer mailing list <gphoto-devel@lists.sourceforge.net>, please run
gphoto2 as follows:

    env LANG=C gphoto2 --debug --debug-logfile=my-logfile.txt --set-config-index /main/capturesettings/f-number=7

Please make sure there is sufficient quoting around the arguments.

**Name the camera**
If this is camera specific, include the camera name as shown by gphoto2 --auto-detect or USB IDs
Tested with:
Sony Alpha-A6000 (Control)     usb:001,002 (firmware 3.20)
Sony Alpha-A9(Control)             usb:001,002 (firmware 6.0) 

I am testing with them individually and not connected simultaneously.

**libgphoto2 and gphoto2 version**
output of: gphoto2 --version

gphoto2         2.5.26         gcc, popt(m), exif, no cdk, no aa, no jpeg, no readline
libgphoto2      2.5.26         standard camlibs (SKIPPING docupen lumix), gcc, ltdl, EXIF
libgphoto2_port 0.12.0

**To Reproduce**

Connect a Sony A9 or Sony A6000 camera
run: 

gphoto2 --auto-detect
sudo chmod a+rw /dev/bus/usb/"port"/"port"
gphoto2 --get-config /main/capturesettings/f-number

Result: 
Label: F-Number
Readonly: 1
Type: RANGE
Current: 0
Bottom: 0
Top: 655.35
Step: 0.01
END

Log file attached.

If its a camera misbehavior, attach debug output using  --debug --debug-logfile=debug.log
[debug.log](https://github.com/gphoto/gphoto2/files/5457682/debug.log)
   (if considered useful).

**Comment by msmeissn** [comment]
I added code that shows an static table of f-numbers. (not all reachabkle, depends on your lens)

this will also allow using --set-config-index again
