### ISSUE TITLE
EOS M6 Mark II locked when --wait-event-and-download

### ISSUE THREAD

**Issue by marczh** [gphoto/gphoto2#378]
**Describe the bug**

I cannot capture-release on a EOS M6 Mark II when I run the following command:

`gphoto2 --set-config remotemode=1 --set-config uilock=0 --wait-event-and-download`

- the TFT goes black, I would assume it to stay on in Remote Mode
- no focussing and no image taken when pressing the camera's capture release button halfway/full

**Name the camera**
Canon EOS M6 Mark II           usb:020,018 

**libgphoto2 and gphoto2 version**
gphoto2         2.5.26         clang, popt(m), no exif, no cdk, no aa, jpeg, readline
libgphoto2      2.5.26         standard camlibs, clang, ltdl, no EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb1, clang, ltdl, no EXIF, USB, serial without locking

**To Reproduce**
- camera connected to MacBook Pro via USB-C Cable
- no PTPCamera process present on MacOS
- switch camera on (normal liveview on camera's TFT appears)

`gphoto2 --set-config remotemode=1 --set-config uilock=0 --wait-event-and-download --debug --debug-logfile=wait-event.log`
- press the shutter release 3 times
- abort with ctrl-c
- TFT shows battery status and Laptop Icon
- still no PTPCamera process running on MacOS

`gphoto2 --list-all-config > 2011-20-1045-config.txt`

[wait-event.log](https://github.com/gphoto/gphoto2/files/5572649/wait-event.log)
[201120-1045-config.txt](https://github.com/gphoto/gphoto2/files/5572669/201120-1045-config.txt)

**Comment by msmeissn** [comment]
I think we solved it in current git :)

**Comment by Buschwiesel** [comment]
for me the issue still exists
[wait-event.log](https://github.com/gphoto/gphoto2/files/6292562/wait-event.log)
[config.txt](https://github.com/gphoto/gphoto2/files/6292563/config.txt)

**Comment by msmeissn** [comment]
0.000874 main                        (2): libgphoto2 2.5.25

you need to build libgphoto2 2.5.27 at least. (not only the gphoto2 commandline tool)

**Comment by Buschwiesel** [comment]
confirmed. 
Tether works with EOS M6 Mark 2 now
