### ISSUE TITLE
Cannot get Camera Serial Number

### ISSUE THREAD

**Issue by ColinSlack** [gphoto/gphoto2#38]
Hi,
I have just updated to 2.5.10 for both gphoto2 and libgphoto2 but now find the --get-config serialnumber returns:
Label: Serial Number
Type: Text
Current: None
This for both a Nikon 610 and Nikon D50, this was working fine in the previous version I was using 2.5.5 and 2.5.5.1
any assistance would be great, I really don't want to go back to the old version if possible.
Thank you
Colin

**Comment by ColinSlack** [comment]
after further testing the D50 does display the Serial Number but not when requesting the serial number - just in the summary, the older D50 has a CCN number,

**Comment by ColinSlack** [comment]
Hi just reinstalled 2.5.9 (both gphoto2 and libgphoto2) and the --get-config serialnumber is working correctly.

**Comment by msmeissn** [comment]
This is a bug n 2.5.10, which will be fixed in 2.5.11 by commit 0c36599145559137c040b1d20ce864451a2d2098

**Comment by ColinSlack** [comment]
Great, thanks for that, I thought it had to be something like that.
