### ISSUE TITLE
Error when compiling in Mac

### ISSUE THREAD

**Issue by nataliahering** [gphoto/gphoto2#381]
**Describe the bug**
When I run ```make``` in mac (Apple clang version is 12.0.0), I get the following error:
```
shell.c:420:21: error: implicit declaration of function 'rl_copy_text' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                current = strdup (rl_copy_text (0, end));
```

**Name the camera**
Not applicable, compilation bug

**libgphoto2 and gphoto2 version**
v2.5.26 with this commit applied https://github.com/gphoto/gphoto2/commit/ae594057b14e4ad8eded87d3f342d95614fc07bb

**To Reproduce**
In a mac environment clone the project and run
```
autoreconf -is
./configure
make
```

**Comment by msmeissn** [comment]
Which readline library version is used there?
Did configure report presence of readline? (Can you attach config.log ? )

**Comment by nataliahering** [comment]
[config.log](https://github.com/gphoto/gphoto2/files/5614306/config.log) Looks like readline is present, if I am not missing anything.
I have version 8.0 installed in my Mac.

**Comment by samarth-robo** [comment]
I faced the same issue. This comment fixes it for me: https://github.com/Proxmark/proxmark3/issues/110#issuecomment-171015752.

The `brew link` command did not run successfully for me, but it printed out a couple of export commands for `LDFLAGS` and `CPPFLAGS`. Running them, configuring `gphoto2` again, and then `make` worked.

**Comment by msmeissn** [comment]
Natalia, did you have chance to try the above?

Sorry I cannot help, I dont have access to a Mac.

**Comment by msmeissn** [comment]
likely fixed by above guidance
