### ISSUE TITLE
Sony A7R II capture-preview JPG & movie MJPG corrupt / strange format

### ISSUE THREAD

**Issue by trishmapow** [gphoto/gphoto2#389]
**Describe the bug**

Camera successfully takes capture-preview but the resulting JPG file cannot be opened by any image viewer except Irfanview on Windows. Same story with capture-movie, only opens in VLC on Windows (not on the Raspberry Pi) and it plays erratically at times. Tested in CLI, Entangle, Ekos etc. Capture-image works with no problems.

Raspberry Pi image viewer fails with "Error interpreting JPEG image file (Unsupported marker type 0x96)", other viewers just don't work at all.

**libgphoto2 and gphoto2 version**
`gphoto2         2.5.26         gcc, popt(m), exif, cdk, aa, jpeg, readline`
`libgphoto2      2.5.26.1       standard camlibs, gcc, ltdl, EXIF`
`libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi, gcc, ltdl, EXIF, USB, serial without locking`

**To Reproduce**
`gphoto2 --capture-preview` or `gphoto2 --capture-movie=10s` and try to open the file.

Full capture-preview log: https://gist.github.com/trishmapow/c2c98c2e2d7a7bc2de558be0c05039e1
'Corrupt' files: https://drive.google.com/drive/folders/19086uiUfHyP2ZAuzCE61GgS6QRh8MIwV?usp=sharing

**Comment by msmeissn** [comment]
The unknown blob at the begin of the preview object contains a spurious FF D8 which we scan for as JPEG marker,.

I added code to avoid that to current GIT if you could try if that will help?

**Comment by trishmapow** [comment]
Oops sorry for reporting in the wrong repo. Thanks for the quick bugfix, I can confirm that capture-preview and capture-movie now both work as expected in CLI and multiple GUIs. Looking forward to using the camera for astrophotography!

**Comment by msmeissn** [comment]
thx for feedback!
