### ISSUE TITLE
sudo apt-get install gphoto2 -> 2.5.4 not 2.5.10

### ISSUE THREAD

**Issue by nanota0** [gphoto/gphoto2#39]
after "sudo apt-get install gphoto2" the output from: "sudo apt-cache show gphoto2" shows the following:

---

Package: gphoto2
Version: 2.5.4-1
Architecture: armhf
Maintainer: Debian PhotoTools Maintainers pkg-phototools-devel@lists.alioth.debian.org
Installed-Size: 802
Depends: libaa1 (>= 1.4p5), libc6 (>= 2.4), libcdk5, libexif12, libgphoto2-6 (>= 2.5.2), libgphoto2-port10 (>= 2.5.2), libjpeg8 (>= 8c), libncurses5 (>= 5.5-5~), libpopt0 (>= 1.14), libreadline6 (>= 6.0)
Suggests: gtkam, gthumb
Homepage: http://www.gphoto.org/proj/gphoto2/
Priority: extra
Section: utils
Filename: pool/main/g/gphoto2/gphoto2_2.5.4-1_armhf.deb

---

There is an alternative way to upgrade gphoto2: https://github.com/gonzalo/gphoto2-updater

is there any other automatic way or a possibility to use "sudo apt-get update && sudo apt-get upgrade"?

**Comment by msmeissn** [comment]
well, apt things ... contact the vendor (Debian? Raspberry Pi provider?)

the gphoto2-updater script can be used, or you can even do it more manually if yu want.

we are not offering debian packages ourselves at this time.
