### ISSUE TITLE
Anyway to check if shutter release is locked on multiple models of camera?

### ISSUE THREAD

**Issue by BeebBenjamin** [gphoto/gphoto2#391]
I noticed that as the battery runs out on some models of Nikon the shutter release gets locked, but `--trigger-capture` is still possible.  I know this is something that doesn't happen with `--capture-image` because it will fail in some way when the battery is this low. Is there any quick check or command that can be done before `--trigger-capture` is done to check if the camera is actually locked?

I thought I could use `--summary` and parse out the battery level to check the likelihood of an imminent failure.  But does anyone have any tricks that could be done.  I wish to maintain the speed that `--trigger-capture` has over `--capture-image`.

**Comment by msmeissn** [comment]
trigger-capture and capture-image use the same methods, so they should fail the same way.

Nikon has reporting prohibit condition via ptp properties for Liveview and Movie Record , but not for regular capture afaik.

Other cameras I currently not recall, they report errors when trying to capture e.g. for Canon EOS.

**Comment by msmeissn** [comment]
It is bit 8 in 0xd1a4 (Liveview Prohibitz Condition only .... its not in movierecprohibit condition I think)

**Comment by BeebBenjamin** [comment]
Hi Marcus thanks for the answer, knowing that `--trigger-capture` and `--capture-image` should throw errors helped me find the problem in my code and not gphoto!  I had a dodgy try, except block that was masking the --trigger-capture error.
