### ISSUE TITLE
Sony Alpha-A7 Liveview support

### ISSUE THREAD

**Issue by ghartma** [gphoto/gphoto2#398]
**Is your feature request related to a problem? Please describe.**
The first gen A7 is missing Liveview support while it seems the later revisions of this camera are supported by gphoto2.

**Describe the solution you'd like**
Would it be possible to add support for this specific model?

**Describe alternatives you've considered**
I would attempt to retrofit the support for later models to the first gen, but I have limited c experience. Supervision would be appreciated.

**Additional context**
Judging my support for later models on this list: http://gphoto.org/proj/libgphoto2/support.php

**Comment by msmeissn** [comment]
the older ones do not support liveview in their firmware
