### ISSUE TITLE
Question Regarding Capture for PowerShots Released After Mid 2009

### ISSUE THREAD

**Issue by magicbycalvin** [gphoto/gphoto2#399]
Greetings,

I have a Canon PowerShot A4000 IS and learned through the gphoto2 documentation that PowerShots released after mid 2009 do not support capture through the Canon SDK. Since this is a camera that was given to me for free, I am thinking about disassembling it and soldering my own control hardware to the camera. However, before taking on that endeavor, I wanted to know whether a software solution is possible. My best guess is that there are limitations in the physical hardware, however if there is a chance that I can get it working through software, I would like to attempt that first.

Should a software solution be possible but nonexistent yet, I would be happy to contribute my findings if they are substantial.

Thank you for your time!

**Comment by msmeissn** [comment]
There is an 3rd party addon software called "CHDK", which can be used also to add remote control.

(we support chdk also to some degree)

https://chdk.fandom.com/wiki/CHDK

**Comment by msmeissn** [comment]
Also, recent (since 2017?) Canon PowerShot series occasionaly have no EOS M style capture support.
