### ISSUE TITLE
--interval option uses too much available drive space

### ISSUE THREAD

**Issue by huaruiwu** [gphoto/gphoto2#4]
Running gphoto2 with interval and capture-image-and-download options causes extra space usage on the hard drive. The space is freed up only after the process exits.

I found this by running gphoto2 on the root partition and --filename option set to a separate data partition. Available space decreased very quickly on the / partition until it was full. Exiting the gphoto2 process freed all the space on root partition that was being used.

**Comment by msmeissn** [comment]
which gphoto2 version?

while it is running, do files appear in the directory where you started gphoto2 from?

**Comment by huaruiwu** [comment]
This is with photo2 2.5.8

Files do not appear in the directory where I started gphoto2 from. They do appear where specified with --filename /path/to/directory/%n.jpg

**Comment by msmeissn** [comment]
ah. I see the problem. I forgot to close filedescriptors, so deleted files kept hanging around.

I commited a fix to git for 2.5.9

**Comment by huaruiwu** [comment]
Thanks for fixing the issue so quickly!
