### ISSUE TITLE
Strange errors while quering for config

### ISSUE THREAD

**Issue by abulak** [gphoto/gphoto2#40]
I run
`gphoto2 --get-config /main/capturesettings/imagequality` 

and besides the correct output (i.e. different choices) I also get
*** Error ***              
Property '/main/capturesettings/imagequality' not found.

(even though the property is clearly there).

`running gphoto2 --list-all-config` produces the whole config without any problems.

(this is not specific to imagequality)

(gphoto-2.5.10, Sony A5000)

**Comment by msmeissn** [comment]
hmm. this is something i did not try buit I think I could have added a bug there.

fwiw you can use "gphoto2 --get-config imagequality" which will be faster even. ;)
