### ISSUE TITLE
Sony A6000 No Download configuration 

### ISSUE THREAD

**Issue by kot0005** [gphoto/gphoto2#402]
Trying to set this up : https://github.com/FormerLurker/Octolapse/wiki/V0.4---Configuring-a-DSLR-With-No-Download

But when i use `gphoto2 --auto-detect --get-config capturetarget
` command, i recieve the following error:
![image](https://user-images.githubusercontent.com/68181325/111067410-39c73d00-8518-11eb-9ded-3eb766e414a8.png)

any ideas on how to resolve this ?

thanks

**Comment by kot0005** [comment]
nvm looks liker this camera does not support it :(

**Comment by msmeissn** [comment]
yes, that a6000 did not support capturetarget / captuzre to SD CARD ...
newer Sony allow selection in the meantime.

**Comment by kot0005** [comment]
> yes, that a6000 did not support capturetarget / captuzre to SD CARD ...
> newer Sony allow selection in the meantime.

Hi! what is the octopi command in SSH to uninstall or remove gphoto2 and all the script changes i did to it ?  iw would like to fresh install because i did a few changes following the above guide.


ALso i found this as an alternative so going to try it out. looks like this method allows for captures to be stored onto SD card.

https://www.youtube.com/watch?v=L9JTPyg2qVU&lc=Ugw9lx4HTyNtvZKGZcN4AaABAg.9KnIuK6xEXd9KqX-UBzztP&ab_channel=thereoughtabe

thankyou!

**Comment by msmeissn** [comment]
i am not familar with octopi, sorry.

**Comment by kot0005** [comment]
> i am not familar with octopi, sorry.

Thinking of getting a A6400, does it support capture/storage to SD card?

**Comment by msmeissn** [comment]
it seems the a6400 has this property, so I think yes.
