### ISSUE TITLE
Adjust settings of Nikon Z6 in video mode

### ISSUE THREAD

**Issue by tmthn** [gphoto/gphoto2#407]
I would like to build a small remote control for my Nikon Z6 and have now encountered the following problem: The Nikon Z6 has two modes, one is the video mode and the other is the still mode. If I now want to set the settings for e.g. the exposure, I can only do this in still mode and not in video mode. 

In the summary I saw that there is each setting additionally with a movie prefix. But the values are not adjustable. How can I change settings in video mode?

**Comment by msmeissn** [comment]
we already have hooked up:

movief-number    config for the aperture
movieshutterspeed for shutterspeed
movieiso for iso

i just added to git also movieexposurecompensation 

That said, if you see them readonly , you need to change to the rotary dial to e.g. "A" if you want to switch f-numbers

**Comment by tmthn** [comment]
Ah I seem to have missed that. I use the camera most of the time in manual mode. Thank you for your help!

**Comment by msmeissn** [comment]
you are weclome!
