### ISSUE TITLE
RX100m7 error

### ISSUE THREAD

**Issue by ammartist** [gphoto/gphoto2#409]
**Describe the bug**
I am using it as a part of octolapse plugin on octoprint on raspberry pi 3B+ following this steps:
https://github.com/FormerLurker/Octolapse/wiki/V0.4---GPhoto2-Installation
https://github.com/FormerLurker/Octolapse/wiki/Configuring-an-External-Camera

gphoto2 detect the camera as below:
`gphoto2 --auto-detect
Model Port USB PTP Class Camera usb:001,007`

However, I am getting errors when I try to take photo. following this command:

`pi@octopi:~/scripts $ /home/pi/scripts/take-snapshot.sh 1 1 "" "/home/pi/scripts" "" "/home/pi/scripts/test.jpg"
Model Port USB PTP Class Camera usb:001,007

*** Error ***
PTP Invalid Object Handle
ERROR: Could not capture image.
ERROR: Could not capture.
The snapshot was not found in the expected directory: '/home/pi/scripts/test.jpg'.`

Hope you can help on sorting out this error

**Name the camera**
SONY RX100m7

**libgphoto2 and gphoto2 version**
gphoto2 --version
gphoto2 2.5.17

Copyright (c) 2000-2018 Lutz Mueller and others

gphoto2 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of gphoto2 under the terms of the GNU General Public
License. For more information about these matters, see the files named COPYING.

This version of gphoto2 is using the following software versions and options:
gphoto2         2.5.17         gcc, popt(m), exif, no cdk, no aa, jpeg, no readline
libgphoto2      2.5.19         all camlibs, gcc, ltdl, EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb usbdiskdirect usbscsi, gcc, ltdl, USB, serial without locking

**To Reproduce**
/home/pi/scripts/take-snapshot.sh 1 1 "" "/home/pi/scripts" "" "/home/pi/scripts/test.jpg"

**Comment by msmeissn** [comment]
can you build with libusb1 ? 

apt-get install libusb-1.0.0-dev or similar, then repeat configure - make - make install steps for libgphtoo2

perhaps also use a more recent libgphoto2

**Comment by ammartist** [comment]
Thanks for pointing this out, 
installing apt-get install libusb-1.0.0-dev and re-installing libgphoto2 did made it work.
