### ISSUE TITLE
GOPRO hero5 Black error

### ISSUE THREAD

**Issue by zammand** [gphoto/gphoto2#413]
**I can't shoot with GOPRO hero5 Black**
Hi, i have a problem with use of Gopro hero 5 black, i search in web and documentation, but don't find solution, would you like help me? 

Terminal :

$ gphoto2 --auto-detect

Model                          Port                                            
----------------------------------------------------------
GoPro HERO5 Black              usb:001,006     

$ gphoto2 --capture-image
                                                                               
*** Error ***              
An error occurred in the io-library ('Could not claim the USB device'): Could not claim interface 0 (Device or resource busy). Make sure no other program (gvfs-gphoto2-volume-monitor) or kernel module (such as sdc2xx, stv680, spca50x) is using the device and you have read/write access to the device.
ERROR: Could not capture image.
ERROR: Could not capture.
*** Error (-53: 'Could not claim the USB device') ***       

For debugging messages, please use the --debug option.
Debugging messages may help finding a solution to your problem.
If you intend to send any error or debug messages to the gphoto
developer mailing list <gphoto-devel@lists.sourceforge.net>, please run
gphoto2 as follows:

    env LANG=C gphoto2 --debug --debug-logfile=my-logfile.txt --capture-image

Please make sure there is sufficient quoting around the arguments.

$ env LANG=C gphoto2 --debug --debug-logfile=my-logfile.txt --capture-image
                                                                               
*** Error ***              
An error occurred in the io-library ('Could not claim the USB device'): Could not claim interface 0 (Device or resource busy). Make sure no other program (gvfs-gphoto2-volume-monitor) or kernel module (such as sdc2xx, stv680, spca50x) is using the device and you have read/write access to the device.
ERROR: Could not capture image.
ERROR: Could not capture.
*** Error (-53: 'Could not claim the USB device') ***   

**Name the camera**
GoPro HERO5 Black              usb:001,006

**libgphoto2 and gphoto2 version**
gphoto   22.5.20
libgphoto2   2.5.22
libgphoto2_port 0.12.0

**To Reproduce**

0.000640 main                        (2): ALWAYS INCLUDE THE FOLLOWING LINES WHEN SENDING DEBUG MESSAGES TO THE MAILING LIST:
0.000892 main                        (2): gphoto2 2.5.20
0.000961 main                        (2): gphoto2 has been compiled with the following options:
0.001008 main                        (2):  + gcc (C compiler used)
0.001046 main                        (2):  + popt (mandatory, for handling command-line parameters)
0.001084 main                        (2):  + exif (for displaying EXIF information)
0.001122 main                        (2):  + cdk (for accessing configuration options)
0.001158 main                        (2):  + aa (for displaying live previews)
0.001195 main                        (2):  + jpeg (for displaying live previews in JPEG format)
0.001232 main                        (2):  + readline (for easy navigation in the shell)
0.001273 main                        (2): libgphoto2 2.5.22
0.001321 main                        (2): libgphoto2 has been compiled with the following options:
0.001359 main                        (2):  + all camlibs
0.001396 main                        (2):  + gcc (C compiler used)
0.001433 main                        (2):  + ltdl (for portable loading of camlibs)
0.001469 main                        (2):  + EXIF (for special handling of EXIF files)
0.001510 main                        (2): libgphoto2_port 0.12.0
0.001556 main                        (2): libgphoto2_port has been compiled with the following options:
0.001595 main                        (2):  + iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi
0.001632 main                        (2):  + gcc (C compiler used)
0.001668 main                        (2):  + ltdl (for portable loading of iolibs)
0.001707 main                        (2):  + USB (libusb1, for USB cameras)
0.001743 main                        (2):  + serial (for serial cameras)
0.001780 main                        (2):  + no resmgr (serial port access and locking)
0.001816 main                        (2):  + no ttylock (serial port locking)
0.001852 main                        (2):  + no lockdev (serial port locking)
0.001895 main                        (2): CAMLIBS env var not set, using compile-time default instead
0.001933 main                        (2): IOLIBS env var not set, using compile-time default instead
0.001969 main                        (2): invoked with following arguments:
0.002006 main                        (2):   --debug
0.002042 main                        (2):   --debug-logfile=my-logfile.txt
0.002079 main                        (2):   --capture-image
0.002241 load_settings               (2): Creating gphoto config directory ('/home/pi/.gphoto')
0.002640 load_settings               (2): Loading settings from file '/home/pi/.gphoto/settings'.
0.002962 main                        (2): The user has not specified both a model and a port. Try to figure them out.
0.003045 gp_port_info_list_load      (2): Using ltdl to load io-drivers from '/usr/lib/arm-linux-gnueabihf/libgphoto2_port/0.12.0'...
0.003720 foreach_func                (2): Called for filename '/usr/lib/arm-linux-gnueabihf/libgphoto2_port/0.12.0/disk'.
0.005519 gp_port_library_list        (2): found fstab fsname proc
0.005664 gp_port_library_list        (2): found fstab fsname PARTUUID=6932ba04-01
0.005765 gp_port_library_list        (2): found fstab fsname PARTUUID=6932ba04-02
0.006168 gp_port_library_list        (2): found mtab fsname /dev/root
0.006253 gp_port_library_list        (2): found mtab fsname devtmpfs
0.006314 gp_port_library_list        (2): found mtab fsname sysfs
0.006369 gp_port_library_list        (2): found mtab fsname proc
0.006425 gp_port_library_list        (2): found mtab fsname securityfs
0.006482 gp_port_library_list        (2): found mtab fsname tmpfs
0.006590 gp_port_library_list        (2): found mtab fsname devpts
0.006647 gp_port_library_list        (2): found mtab fsname tmpfs
0.006744 gp_port_library_list        (2): found mtab fsname tmpfs
0.006845 gp_port_library_list        (2): found mtab fsname tmpfs
0.006968 gp_port_library_list        (2): found mtab fsname cgroup2
0.007093 gp_port_library_list        (2): found mtab fsname cgroup
0.007147 gp_port_library_list        (2): found mtab fsname none
0.007239 gp_port_library_list        (2): found mtab fsname cgroup
0.007295 gp_port_library_list        (2): found mtab fsname cgroup
0.007534 gp_port_library_list        (2): found mtab fsname cgroup
0.007592 gp_port_library_list        (2): found mtab fsname cgroup
0.007647 gp_port_library_list        (2): found mtab fsname cgroup
0.007701 gp_port_library_list        (2): found mtab fsname cgroup
0.007755 gp_port_library_list        (2): found mtab fsname cgroup
0.007816 gp_port_library_list        (2): found mtab fsname cgroup
0.007871 gp_port_library_list        (2): found mtab fsname systemd-1
0.007930 gp_port_library_list        (2): found mtab fsname debugfs
0.008063 gp_port_library_list        (2): found mtab fsname sunrpc
0.008192 gp_port_library_list        (2): found mtab fsname mqueue
0.008250 gp_port_library_list        (2): found mtab fsname configfs
0.008388 gp_port_library_list        (2): found mtab fsname /dev/mmcblk0p1
0.008488 gp_port_library_list        (2): found mtab fsname tmpfs
0.008668 gp_port_library_list        (2): found mtab fsname gvfsd-fuse
0.008735 gp_port_library_list        (2): found mtab fsname fusectl
0.009105 foreach_func                (2): Loaded '' ('^disk:') from '/usr/lib/arm-linux-gnueabihf/libgphoto2_port/0.12.0/disk'.
0.009172 foreach_func                (2): Called for filename '/usr/lib/arm-linux-gnueabihf/libgphoto2_port/0.12.0/ptpip'.
0.010405 foreach_func                (2): Loaded 'PTP/IP Connection' ('ptpip:') from '/usr/lib/arm-linux-gnueabihf/libgphoto2_port/0.12.0/ptpip'.
0.010503 foreach_func                (2): Loaded '' ('^ptpip:') from '/usr/lib/arm-linux-gnueabihf/libgphoto2_port/0.12.0/ptpip'.
0.010548 foreach_func                (2): Called for filename '/usr/lib/arm-linux-gnueabihf/libgphoto2_port/0.12.0/serial'.
0.012138 foreach_func                (2): Loaded 'Serial Port Device' ('serial:') from '/usr/lib/arm-linux-gnueabihf/libgphoto2_port/0.12.0/serial'.
0.012272 foreach_func                (2): Loaded '' ('^serial:') from '/usr/lib/arm-linux-gnueabihf/libgphoto2_port/0.12.0/serial'.
0.012319 foreach_func                (2): Called for filename '/usr/lib/arm-linux-gnueabihf/libgphoto2_port/0.12.0/usb1'.
0.053854 foreach_func                (2): Loaded '' ('^usb:') from '/usr/lib/arm-linux-gnueabihf/libgphoto2_port/0.12.0/usb1'.
0.054038 foreach_func                (2): Loaded 'Universal Serial Bus' ('usb:001,006') from '/usr/lib/arm-linux-gnueabihf/libgphoto2_port/0.12.0/usb1'.
0.054088 foreach_func                (2): Loaded 'Universal Serial Bus' ('usb:001,005') from '/usr/lib/arm-linux-gnueabihf/libgphoto2_port/0.12.0/usb1'.
0.054135 foreach_func                (2): Called for filename '/usr/lib/arm-linux-gnueabihf/libgphoto2_port/0.12.0/usbdiskdirect'.
0.055732 foreach_func                (2): Called for filename '/usr/lib/arm-linux-gnueabihf/libgphoto2_port/0.12.0/usbscsi'.
0.056976 gp_port_info_list_count     (2): Counting entries (8 available)...
0.057088 gp_port_info_list_count     (2): 4 regular entries available.
0.057171 gp_abilities_list_load_dir  (2): Using ltdl to load camera libraries from '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22'...
0.059926 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/adc65'.
0.059981 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/agfa_cl20'.
0.060022 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/aox'.
0.060062 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/ax203'.
0.060101 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/barbie'.
0.060140 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/canon'.
0.060180 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/casio_qv'.
0.060285 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/clicksmart310'.
0.060325 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/digigr8'.
0.060364 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/digita'.
0.060402 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/dimagev'.
0.060441 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/dimera3500'.
0.060479 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/directory'.
0.060517 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/enigma13'.
0.060556 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/fuji'.
0.060594 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/gsmart300'.
0.060632 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/hp215'.
0.060672 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/iclick'.
0.060712 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/jamcam'.
0.060751 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/jd11'.
0.060789 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/jl2005a'.
0.060828 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/jl2005c'.
0.060867 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/kodak_dc120'.
0.060907 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/kodak_dc210'.
0.060947 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/kodak_dc240'.
0.060987 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/kodak_dc3200'.
0.061028 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/kodak_ez200'.
0.061067 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/konica'.
0.061107 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/konica_qm150'.
0.061147 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/largan'.
0.061186 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/lg_gsm'.
0.061226 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/mars'.
0.061265 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/mustek'.
0.061305 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/panasonic_coolshot'.
0.061344 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/panasonic_dc1000'.
0.061382 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/panasonic_dc1580'.
0.061420 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/panasonic_l859'.
0.061458 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/pccam300'.
0.061499 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/pccam600'.
0.061538 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/pentax'.
0.061579 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/polaroid_pdc320'.
0.061618 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/polaroid_pdc640'.
0.061656 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/polaroid_pdc700'.
0.061696 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/ptp2'.
0.061734 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/ricoh'.
0.061807 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/ricoh_g3'.
0.061850 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/samsung'.
0.061890 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/sierra'.
0.061930 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/sipix_blink2'.
0.061970 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/sipix_web2'.
0.062010 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/smal'.
0.062048 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/sonix'.
0.062087 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/sony_dscf1'.
0.062128 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/sony_dscf55'.
0.062168 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/soundvision'.
0.062207 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/spca50x'.
0.062247 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/sq905'.
0.062286 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/st2205'.
0.062325 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/stv0674'.
0.062365 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/stv0680'.
0.062493 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/sx330z'.
0.062546 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/topfield'.
0.062587 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/toshiba_pdrm11'.
0.062626 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/tp6801'.
0.062682 gp_abilities_list_load_dir  (2): Found 64 camera drivers.
0.305485 gp_port_info_list_count     (2): Counting entries (8 available)...
0.305669 gp_port_info_list_count     (2): 4 regular entries available.
0.305713 gp_port_new                 (2): Creating new device...
0.305772 gp_port_info_list_get_info  (2): Getting info of entry 0 (8 available)...
0.306659 gp_port_set_settings        (2): Setting settings...
0.306723 gp_port_info_list_get_info  (2): Getting info of entry 1 (8 available)...
0.307564 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.307614 gp_port_set_settings        (2): Setting settings...
0.307659 gp_port_info_list_get_info  (2): Getting info of entry 2 (8 available)...
0.340119 gp_port_set_timeout         (2): Setting port timeout to 5000 milliseconds.
0.340234 gp_port_set_settings        (2): Setting settings...
0.340291 gp_libusb1_update           (2): (old int=0, conf=-1, alt=-1) port usb:001,006, (new int=0, conf=-1, alt=-1) port usb:001,006
0.340330 gp_libusb1_update           (2): lowlevel libusb1 port not yet opened, no need for libusb changes
0.340370 gp_abilities_list_detect_usb(2): Auto-detecting USB cameras...
0.344170 gp_libusb1_find_device_lib  (2): Looking for USB device (vendor 0x2672, product 0x27)... found.
0.344589 gp_libusb1_find_device_lib  (2): Detected defaults: config 1, interface 0, altsetting 0, inep 82, outep 01, intep 83, class 06, subclass 01
0.344641 gp_abilities_list_detect_usb(2): Found 'GoPro HERO5 Black' (0x2672,0x27)
0.344815 gp_port_info_list_get_info  (2): Getting info of entry 3 (8 available)...
0.379109 gp_port_set_timeout         (2): Setting port timeout to 5000 milliseconds.
0.379240 gp_port_set_settings        (2): Setting settings...
0.379296 gp_libusb1_update           (2): (old int=0, conf=-1, alt=-1) port usb:001,005, (new int=0, conf=-1, alt=-1) port usb:001,005
0.379337 gp_libusb1_update           (2): lowlevel libusb1 port not yet opened, no need for libusb changes
0.379380 gp_abilities_list_detect_usb(2): Auto-detecting USB cameras...
0.385617 gp_libusb1_find_device_by_class_lib(2): Looking for USB device (class 0x29a, subclass, 0xffffffff, protocol 0xffffffff)...
0.390110 gp_libusb1_find_device_by_class_lib(2): Looking for USB device (class 0x6, subclass, 0x1, protocol 0x1)...
0.390430 gp_port_free                (2): Freeing port...
0.390474 gp_port_close               (2): Closing port...
0.391808 gp_camera_set_abilities     (2): Setting abilities ('GoPro HERO5 Black')...
0.391875 gp_setting_set              (2): Setting key 'model' to value 'GoPro HERO5 Black' (gphoto2)
0.391924 save_settings               (2): Saving 3 setting(s) to file "/home/pi/.gphoto/settings"
0.393750 gp_port_info_list_lookup_path(2): Looking for path 'usb:001,006' (8 entries available)...
0.393814 gp_port_info_list_get_info  (2): Getting info of entry 2 (8 available)...
0.393862 gp_camera_set_port_info     (2): Setting port info for port 'Universal Serial Bus' at 'usb:001,006'...
0.426362 gp_port_set_timeout         (2): Setting port timeout to 5000 milliseconds.
0.426499 gp_port_set_settings        (2): Setting settings...
0.426558 gp_libusb1_update           (2): (old int=0, conf=-1, alt=-1) port usb:001,006, (new int=0, conf=-1, alt=-1) port usb:001,006
0.426598 gp_libusb1_update           (2): lowlevel libusb1 port not yet opened, no need for libusb changes
0.426643 gp_setting_set              (2): Setting key 'port' to value 'usb:001,006' (gphoto2)
0.426695 save_settings               (2): Saving 3 setting(s) to file "/home/pi/.gphoto/settings"
0.427771 gp_camera_init              (2): Initializing camera...
0.427941 gp_libusb1_find_device_lib  (2): Looking for USB device (vendor 0x2672, product 0x27)... found.
0.428335 gp_libusb1_find_device_lib  (2): Detected defaults: config 1, interface 0, altsetting 0, inep 82, outep 01, intep 83, class 06, subclass 01
0.428382 gp_camera_init              (2): Loading '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.22/ptp2'...
0.451478 gp_port_open                (2): Opening USB port...
0.451631 gp_libusb1_open             (2): ()
0.451846 gp_libusb1_open             (2): claiming interface 0
0.451917 gp_libusb1_open [libusb1.c:431](0): 'libusb_claim_interface (port->pl->dh, port->settings.usb.interface)' failed: Resource busy (-6)
0.452010 gp_port_set_error [gphoto2-port.c:1190](0): Could not claim interface 0 (Device or resource busy). Make sure no other program (gvfs-gphoto2-volume-monitor) or kernel module (such as sdc2xx, stv680, spca50x) is using the device and you have read/write access to the device.
0.454772 gp_context_error            (0): An error occurred in the io-library ('Could not claim the USB device'): Could not claim interface 0 (Device or resource busy). Make sure no other program (gvfs-gphoto2-volume-monitor) or kernel module (such as sdc2xx, stv680, spca50x) is using the device and you have read/write access to the device.
0.458243 gp_camera_free              (2): Freeing camera...
0.458304 gp_port_free                (2): Freeing port...
0.458343 gp_port_close               (2): Closing port...
0.459665 gp_port_set_error [gphoto2-port.c:1190](0): Could not release interface 0 (Device or resource busy).
0.460582 gp_filesystem_reset         (2): resetting filesystem
0.460637 gp_filesystem_lru_clear     (2): Clearing fscache LRU list...
0.460676 gp_filesystem_lru_clear     (2): fscache LRU list already empty
0.460715 delete_all_folders          (2): Internally deleting all folders from '/'...
0.460755 lookup_folder               (2): Lookup folder '/'...
0.460793 lookup_folder               (2): Found! / is 0x2069d40
0.460833 recurse_delete_folder       (2): Recurse delete folder 0x2069d40//

**Comment by msmeissn** [comment]
two things.
- the hero 5 does not allow remote control or remote capture over USB. 
- Remote control is possible over WIFI, which gphoto2 currently ddoes not support for the GoPro.
- Your above problem is caused by something blocking access to the gopro, likely gvfs or similar.

So not much we can do, at most you can download images.
