### ISSUE TITLE
Sony A7R4 Manual Focus Step near-far

### ISSUE THREAD

**Issue by ispybadguys** [gphoto/gphoto2#416]
Looking over the issues for the Son A7R4 I found a suggestion  for focus control:

gphoto2 "--set-config=/main/actions/manualfocus=7"   

but this produces 

*** Error ***              
/main not found in configuration tree.
*** Error (-1: 'Unspecified error') ***   

Thanks

Kurt

**Comment by msmeissn** [comment]
I made some adjustments in the hope its fixed in current GIT master.

I hope it works now.

**Comment by ispybadguys** [comment]
I am using this on a Mac. How can I install the update?

⁣Get BlueMail for Android ​
