### ISSUE TITLE
Compile on Mac Fails

### ISSUE THREAD

**Issue by ispybadguys** [gphoto/gphoto2#423]
**Describe the bug**
Ld error when compiling photo on Mac OS X 10.15.7

Using GPhoto2.framework @ https://github.com/lnxbil/GPhoto2.framework after a lengthy compile the session ends with:
`echo   > glib-public-headers.txt.tmp && mv glib-public-headers.txt.tmp glib-public-headers.txt
make[6]: Nothing to be done for `install-exec-am'.
Making install in .
  CC       pkg.o
  CC       parse.o
  CC       rpmvercmp.o
  CC       main.o
  CCLD     pkg-config
Undefined symbols for architecture x86_64:
  "_CFRelease", referenced from:
      _find_folder in libglib-2.0.a(libglib_2_0_la-gutils.o)
  "_CFStringGetCString", referenced from:
      _find_folder in libglib-2.0.a(libglib_2_0_la-gutils.o)
  "_CFStringGetCStringPtr", referenced from:
      _find_folder in libglib-2.0.a(libglib_2_0_la-gutils.o)
  "_CFStringGetLength", referenced from:
      _find_folder in libglib-2.0.a(libglib_2_0_la-gutils.o)
  "_CFURLCopyFileSystemPath", referenced from:
      _find_folder in libglib-2.0.a(libglib_2_0_la-gutils.o)
  "_CFURLCreateFromFSRef", referenced from:
      _find_folder in libglib-2.0.a(libglib_2_0_la-gutils.o)
  "_FSFindFolder", referenced from:
      _find_folder in libglib-2.0.a(libglib_2_0_la-gutils.o)
  "_kCFAllocatorSystemDefault", referenced from:
      _find_folder in libglib-2.0.a(libglib_2_0_la-gutils.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [pkg-config] Error 1
make: *** [install-recursive] Error 1`

**Name the camera**
Not camera specific
**libgphoto2 and gphoto2 version**
current version of 

**To Reproduce**

brew install pkg-config  
curl https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.tar.gz -o pkgconfig.tgz
tar -zxf pkgconfig.tgz && cd pkg-config-0.29
./configure && make install  
./configure --with-internal-glib && make install

**Comment by msmeissn** [comment]
outdated, please open new issue if not fixed
