### ISSUE TITLE
Nikon D5600 Refusing Uploads

### ISSUE THREAD

**Issue by sophierahn** [gphoto/gphoto2#427]
Hi!

I'm making a long term time lapse camera controller and so I want to save photos taken on a Nikon D5600 with the proper time stamp. That naming isn't an issue, but the uploading is. I've noticed this with photos that haven't been renamed as well.

This is all done on with the CLI. 

If I run --capture-image the JPG saves to the camera. 
If I run --capture-image-and-download the JPG saves to the camera, saves to the debian machine, then deletes from the camera.
If I add --filename %Y-%m-%d.%H:%M:%S.JPG then it saves the image to the camera _with the default name (INT_xxx.JPG)_, saves the image to the debian machine with the specified name, and deletes the image in its original name from the camera. 

From what I've read, the above is all expected behavior. I included it to prove the camera isn't morally opposed to saving images via gphoto. It's also worth noting i had to changed the capturetarget = 1 instead of its default to get anything to save at all. Before that gphoto "saved it" to the camera but it was nowhere to be seen. I'm not quite sure what the default was doing, but I understand changing the capture target switched to using the SD card. 

So then I thought I could try to brute force it. I captured, downloaded, and renamed the picture as I wanted it, then tried various means of uploading the photo back to the camera. --upload-file, -u, put, you name it, all returns the same error:
*** Error (-1: 'Unspecified error') ***

This is the case with renamed photos as well as default named photos. 

I also noticed that the shell mode commands _also_  produced the above error. I tried running --debug with all of these and the error pops up at the same point regardless of the command:

0.004170 main                        (2):   --debug
0.004493 load_settings               (2): Creating gphoto config directory ('/root/.gphoto')
0.005778 load_settings               (2): Loading settings from file '/root/.gphoto/settings'.
0.008565 main                        (2): Uploading file...
*** Error (-1: 'Unspecified error') ***

Any thoughts on what I'm doing wrong?

libgphoto2 and gphoto2 version:
gphoto2 2.5.23.1

Copyright (c) 2000-2020 Marcus Meissner and others

gphoto2 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of gphoto2 under the terms of the GNU General Public
License. For more information about these matters, see the files named COPYING.

This version of gphoto2 is using the following software versions and options:
gphoto2         2.5.23.1       gcc, popt(m), exif, no cdk, no aa, jpeg, no readline
libgphoto2      2.5.25.1       standard camlibs (SKIPPING lumix), gcc, ltdl, EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb usbdiskdirect usbscsi, gcc, ltdl, EXIF, USB, serial without locking

**Comment by msmeissn** [comment]
You are doing nothing wrong.

I think Nikon does not allow uploading images to the camera, this is a common camera side limitation.

Canon EOS allowed it I think, but only JPEGs.

The capturetarget=0 mode is "SDRAM" capture, the captured image is downloaded immediately, you need to "download" it out of gphoto2, or it will be lost.

**Comment by msmeissn** [comment]
the abilities are static, and actually it is hard to find out even from PTP introspection if a camera supports upload or not (it always suppots the respective PTP SendObject command... but in the Nikon case just for PictBridge print control)
I can try filtering the ability out for Nikon specifically.

**Comment by msmeissn** [comment]
reported better now ... not much more we can do
