### ISSUE TITLE
RX1RII : not capturetarget

### ISSUE THREAD

**Issue by Camilochiang** [gphoto/gphoto2#428]
For documentation:
Imposible to store images in sd card with Sony RX1RII 
 `gphoto2 --get-config capturetarget

*** Error ***              
capturetarget not found in configuration tree.
*** Error (-1: 'Unspecified error') ***  

`
[20210602_RX1RII_gphoto2_output.txt](https://github.com/gphoto/gphoto2/files/6584754/20210602_RX1RII_gphoto2_output.txt)

**Comment by msmeissn** [comment]
i do not see the capturetarget, it is not available for all Sony cameras sadly... apparently not for this one either

**Comment by msmeissn** [comment]
So not much we can do sadly.
