### ISSUE TITLE
Disable Wifi/NFC/Bluetooth options

### ISSUE THREAD

**Issue by Vallevard** [gphoto/gphoto2#429]
Hello, I'm sorry if this is not the right place to ask the next question.
I was wondering if there is an option or it is possible to use gphoto2 to disable the options of Wifi/NFC/Bluetooth?

Its for my place of work, security does not allow Wifi, NFC or Bluetooth.

Thanks.

**Comment by msmeissn** [comment]
This is not handled by gphoto2 in any form ...

if its for your laptop, checkout rfkill 
for cameras, you will need to do that in camera.
