### ISSUE TITLE
Multiple Cameras

### ISSUE THREAD

**Issue by wtgee** [gphoto/gphoto2#43]
It seems that specifying the usb port doesn't work for two cameras of the same model. Is there any current work-around for this?

Specifically, it looks like this has just been left as an open problem on [main.c#L2452](https://github.com/gphoto/gphoto2/blob/master/gphoto2/main.c#L2452)

What would be the preferred way to get this fixed? It seems like gphoto2 assumes there will always only be one camera (with single port settings written to a flat file). 

Thanks!

**Comment by msmeissn** [comment]
It should work, but just not via the "settings" file.

how do you use it/call it?

**Comment by wtgee** [comment]
This might be a problem on our end as we are having some spurious resets on the usb hub, but calling via:

```
# Open shutter
gphoto2 --camera="Canon EOS 100D" --port usb:002,008  \
         --set-config eosremoterelease=Immediate \
         --wait-event=120s --set-config eosremoterelease=4 \
         --wait-event-and-download=2s \
         --filename "${F}"
```

I don't do anything to the settings file but do make the above call twice and each time overwrites what is in the settings.

I'll do some more testing on this next week when I have access to the two cameras again. Thanks!

**Comment by wtgee** [comment]
Can't seem to duplicate reliably with new hardware, so closing. Thanks!
