### ISSUE TITLE
Using the --show-preview switch does not work with gphoto2 cli built for Android.

### ISSUE THREAD

**Issue by laheller** [gphoto/gphoto2#431]
Hi @msmeissn @ndim

I successfully built gphoto2/libgphoto2 (and all the dependecies) from sources for Android aarch64 architecture.
See the related older "issue" [here](https://github.com/gphoto/libgphoto2/issues/335).

For now everything seems to work, when I try gphoto2 cli from Android terminal, like capturing, dirs/files listing, etc.
But when I tried the cli with _--show-preview_ switch, I got following error:

> *** Error (-1: 'Unspecified error') ***                                        

The above error is definitely NOT caused by missing **aalib** dependency because among other I also built and included that library.
Here you can check the whole debug log from the _gphoto2 --show-preview_ call:
https://drive.google.com/file/d/19s3BD19gNs7ENwDPZQd4phPOBBgeanda/view?usp=sharing

BR,

Ladislav

**Comment by msmeissn** [comment]
The error might be more on the gphoto2 / aalib side. A single preview seems to be capture and returned fine.


are aalib sample programs like "bb" running?

is /tmp writeable? (we store a temp file there during aa decoding)

**Comment by msmeissn** [comment]
i changed the code to use in memory only , no need for /tmp

**Comment by laheller** [comment]
Hi @msmeissn 

There is no /tmp on Android systems. The only world writable location is /sdcard but obviously it makes no sense to write and keep there temporary files.
Just noticed that in the meantime you made fix (temp storage in memory), so I am going to grab latest source, create a new build and will let you know the result.

BR,

Ladislav

**Comment by msmeissn** [comment]
i also applied a fix where we only ever showed the first picture on most cameras, as the code had not followed changes in both drivers and ligphoto2 in the last years.

It also quite depends on available terminal size, if the terminal is too small it cannot rescale the jpeg down sufficiently.

**Comment by laheller** [comment]
Hi @msmeissn 

Rebuilt gphoto2 cli and tried again. Now the error is gone, but instead of expected ASCII-art output I got following:

> 1|y2s:/data/local/tmp/gphoto2 # ./gphoto2 --debug --debug-logfile=logfile_show_preview.log --show-preview                                                                                                                                                                     
> Saving file as capture_preview.jpg                                             
> y2s:/data/local/tmp/gphoto2 # 
> 

As you can see, it simply captured a preview photo as a jpeg file.

Again, the logfile is here:
https://drive.google.com/file/d/1yF-XzmWWH0f8EvxoiPgb80WoM8IdOT49/view?usp=sharing

**Comment by msmeissn** [comment]
the line in question:

1.732145 gphoto2                     (2): Screen too small (aa is 160x50, jpeg cinfo is now 132x88.

so it needs at least 88 lines of terminal to show something ... :/

**Comment by laheller** [comment]
Hi @msmeissn 

I did a little research, it is possible to make it work also on Android.
AAlib has a built-in function **aa_parseoptions** which is able to read/parse environment variable AAOPTS, where we can change the terminal size, example:
`AAOPTS="-width 160 -height 90"`

In the gphoto2 code we need only add one more line in the **gphoto2-cmd-capture.c** before aa_autoinit:
```
if (!aa_parseoptions(NULL, NULL, NULL, NULL)) gp_log (GP_LOG_DEBUG, "gphoto2", "[aa_parseoptions] did not work!.");
c = aa_autoinit (&aa_defparams);

```
That's all. For this one line I will not create a PR.
Screenshot from Android terminal:
![kép](https://user-images.githubusercontent.com/5788998/123852866-14224000-d91d-11eb-9bfc-cb4632c19c69.png)

BR,

Ladislav

**Comment by msmeissn** [comment]
i added it ... should be solved now :)
