### ISSUE TITLE
Sony SLT-A55V: Sorry, your camera does not support generic capture

### ISSUE THREAD

**Issue by just-max** [gphoto/gphoto2#439]
**Bug description**

Trying to use `gphoto2 --capture-image` fails with the error message `Sorry, your camera does not support generic capture`.
This is despite the listing for "Sony SLT-A55 (PTP mode)" on the supported cameras list (http://www.gphoto.org/proj/libgphoto2/support.php). (The camera seems to have been added in gphoto/libgphoto2@81cea929f0f28b71f429fbd175410334c9e038f0).

The camera I am using is the "SLT-A55V", however as far as I am aware the only difference to the SLT-A55 is the addition of GPS support.

The "USB Connection" in the camera's settings is set to "PTP" (as opposed to "Mass Storage").

Is there a known reason why this camera won't work?

**Camera Name**
from `gphoto2 --auto-detect`: Sony SLT-A55 (PTP mode)
from `lsusb`: ID 054c:04a3 Sony Corp. SLT-A55V

**libgphoto2 and gphoto2 version**
I have tried with (from the Linux Mint 20 Cinnamon repositories, aka. ubuntu focal https://packages.ubuntu.com/focal/gphoto2)
```
gphoto2 2.5.23

Copyright (c) 2000-2019 Marcus Meissner and others

gphoto2 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of gphoto2 under the terms of the GNU General Public
License. For more information about these matters, see the files named COPYING.

This version of gphoto2 is using the following software versions and options:
gphoto2         2.5.23         gcc, popt(m), exif, cdk, aa, jpeg, readline
libgphoto2      2.5.25         standard camlibs (SKIPPING lumix), gcc, ltdl, EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi, gcc, ltdl, EXIF, USB, serial without locking
```
And built from source:
```
gphoto2 2.5.27

Copyright (c) 2000-2021 Marcus Meissner and others

gphoto2 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of gphoto2 under the terms of the GNU General Public
License. For more information about these matters, see the files named COPYING.

This version of gphoto2 is using the following software versions and options:
gphoto2         2.5.27         gcc, popt(m), exif, no cdk, no aa, no jpeg, readline
libgphoto2      2.5.27         standard camlibs (SKIPPING docupen lumix), gcc, ltdl, EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi, gcc, ltdl, EXIF, USB, serial without locking
```

**To Reproduce**
Use given camera. Run `gphoto2 --capture-image`. If there's anything else I should try please let me know.

Logs (`env LANG=C gphoto2 --debug --debug-logfile=my-logfile.txt --capture-image`):
gphoto2 2.5.23: [log-gphoto2-2.5.23.txt](https://github.com/gphoto/gphoto2/files/6823167/log-gphoto2-2.5.23.txt)
gphoto2 2.5.27: [log-gphoto2-2.5.27.txt](https://github.com/gphoto/gphoto2/files/6823165/log-gphoto2-2.5.27.txt)

**Comment by msmeissn** [comment]
I am afraid it is from before the time where Sony added capture abilities. The SLT A58 was the first I think.

Is there a PC Control USB option?

**Comment by just-max** [comment]
Oh well, that's too bad.
Doesn't look like it. The only options two options under "USB Connection" are the ones I listed above, and I can't see any other relevant options. I also checked that I have the latest camera firmware.
Thanks for the response, though.

**Comment by zungge** [comment]
Hi
I have 2 Japanese devices, which are sony SLT A33 and A55
I used to know there was a hack of these 2 machines on nex-hack, but now the link is dead.
Does anyone still have the A55.2.1jan2.Eng.zip version (https://rapidtrend.com/f/15292852/a55_2_1_jap2eng.html)
Please help me with my application, and send me the download link email: dungmxdk43@gmail.com
Thank you very much
