### ISSUE TITLE
Canon EOS R `--summary` is timing out

### ISSUE THREAD

**Issue by AndreasBilke** [gphoto/gphoto2#446]
**Describe the bug**

I tried to setup the Canon EOS R for video recording on Debian Bullseye. During the setup I tried to capture images / get a summary from gphoto and got a timeout. Also please see [my-logfile.txt](https://github.com/gphoto/gphoto2/files/6945104/my-logfile.txt)

**Name the camera**
If this is camera specific, include the camera name as shown by gphoto2 --auto-detect or USB IDs

```
gphoto2 --auto-detect               
Model                          Port                                            
----------------------------------------------------------
Canon EOS R                    usb:001,016 
```

**libgphoto2 and gphoto2 version**
output of: gphoto2 --version

```
gphoto2 --version
gphoto2 2.5.27

Copyright (c) 2000-2021 Marcus Meissner and others

gphoto2 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of gphoto2 under the terms of the GNU General Public
License. For more information about these matters, see the files named COPYING.

This version of gphoto2 is using the following software versions and options:
gphoto2         2.5.27         gcc, popt(m), exif, cdk, aa, jpeg, readline
libgphoto2      2.5.27         standard camlibs, gcc, ltdl, EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi, gcc, ltdl, EXIF, USB, serial without locking
```

**To Reproduce**

```
gphoto2 --summary
```

**Comment by msmeissn** [comment]
can you try to get a debuglogfile?

gphoto2 --summary --debug --debug-logfile=summary.log     

and attach summary.log here

**Comment by AndreasBilke** [comment]
Hi! Sorry for the delay: [summary.log](https://github.com/gphoto/gphoto2/files/6952601/summary.log)

**Comment by msmeissn** [comment]
super weird. we only send open session and then getdeviceinfo commands, then reading data from camera hangs.

is there any parallel other user of the camera perhaps?

does it always happen, even at first plugin?

can you try to attach it to  a different usb port ?

**Comment by AndreasBilke** [comment]
Very weird. I put the camera into a USB port from my laptop dock and it worked flawlessly. On the other hand putting it in the original usb port it never works.
I would assume this is an issue with my laptop (or whatever) and not gphoto

**Comment by msmeissn** [comment]
it might be some weird lowlevel usb stuff / packet size issue, but i think we handle that correctly ... so i think it probably is hardware related
