### ISSUE TITLE
Please use pkgconfig for libpopt detection

### ISSUE THREAD

**Issue by yarda** [gphoto/gphoto2#448]
**Describe the bug**
It seems gphoto2 hardcodes the libpopt paths in the `gphoto-m4/gp-check-popt.m4` which is not good when e.g. cross-compiling with the `mxe`. In such case it can add: `POP_CFLAGS=-I/usr/include` and `POP_LIBS=-l/usr/lib` which is obviously wrong, because they are host paths, not the cross-compiler paths and causes some "mystic" compilation errors complaining about incompatible types.

It seems libpopt ships the popt.pc, which is configured correctly in the `mxe`.

Also dropping libpopt mandatory requirement should resolve this problem.

**Name the camera**
unrelated to cameras

**libgphoto2 and gphoto2 version**
2.5.27

**To Reproduce**
Rebuild gphoto2 in mxe.

**Comment by msmeissn** [comment]
commit a03b75eb , will be in 2.5.28 release only

**Comment by yarda** [comment]
Great, thanks, I used the latest stable and haven't noticed, closing.
