### ISSUE TITLE
configure time check for readline needs to check for rl_copy_text() function

### ISSUE THREAD

**Issue by ndim** [gphoto/gphoto2#455]
**Describe the bug**

The `gphoto2 --shell` optionally supports using the readline library. The configure checks check for the presence of the functions `rl_completion_append_character` and `rl_completion_matches`. This is sufficient on systems with GNU readline, but not on systems with BSD readline like e.g. OSX. That implementation of readline does not have the `rl_copy_text` function which the gphoto2 code uses, so on OSX, builds will fail at compile time:

  * https://github.com/gphoto/gphoto2/issues/381
  * https://github.com/gphoto/libgphoto2/issues/688#issuecomment-904083401

The workaround on those systems is to either install GNU readline, or compile gphoto2 `--without-readline`.

Running `configure` should check for the presence of `rl_copy_text` and print a useful error message mentioning those workarounds.

**Name the camera**
N/A

**libgphoto2 and gphoto2 version**
gphoto2-2.5.27.1 going back to at least commit fd638fc from 2002-07-28.

**To Reproduce**
To reproduce the behavior, on OSX run

    cd gphoto2
    ./configure
    make

**Comment by msmeissn** [comment]
i added it to configure. the nesting in this check is a bitwild, but well.
