### ISSUE TITLE
Pentax K3II can't capture images, maybe incorrectly detected

### ISSUE THREAD

**Issue by Javier-MH** [gphoto/gphoto2#459]
### **Describe the bug**

Hello. Thanks a lot for your time developing a triggering solution.
I have installed gphoto2/libgphoto 2.5.27. 
I have made the installation on Kubuntu (20.4) and MSYS2 for Windows 10. Same issue on both.
Seems my camera is detected without triggering capabilities, I can get files but I can't trigger the camera.
I have a new USB 3.0 cable (tested with a 2.0 cable too), my operating system detects the camera correctly and I can see the pics on internal SD cards, etc. Camera is in PTP mode (MSC mode does not work).
I think my camera is detected as a generic PTP camera without any triggering capabilities.

### **Name the camera**
Camera is Pentax K3-II, last firmware installed.

.
$ env LANG=C gphoto2 --auto-detect --list-config
Model                          Port

USB PTP Class Camera           usb:002,002
/main/actions/opcode
/main/settings/datetime
/main/status/serialnumber
/main/status/manufacturer
/main/status/cameramodel
/main/status/deviceversion
/main/status/vendorextension
/main/status/batterylevel
/main/other/5001
/main/other/5011
/main/other/d406
/main/other/d407
/main/other/d303

### **libgphoto2 and gphoto2 version**
$ env LANG=C gphoto2 --version
gphoto2 2

Copyright (c) 2000-2021 Marcus Meissner and others

gphoto2 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of gphoto2 under the terms of the GNU General Public
License. For more information about these matters, see the files named COPYING.

This version of gphoto2 is using the following software versions and options:
gphoto2         2.5.27         x86_64-w64-mingw32-gcc, popt(m), exif, no cdk, no aa, jpeg, readline
libgphoto2      2.5.27         standard camlibs (SKIPPING lumix), x86_64-w64-mingw32-gcc, ltdl, EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip usb1, x86_64-w64-mingw32-gcc, ltdl, EXIF, USB, no serial

### **To Reproduce**

Just run:
$ env LANG=C gphoto2 --capture-image

*** Error ***
Sorry, your camera does not support generic capture

ERROR: Could not capture image.
ERROR: Could not capture.
*** Error (-6: 'Unsupported operation') ***

Thanks in advance.

[PentaxK32_capture.txt](https://github.com/gphoto/gphoto2/files/7315960/PentaxK32_capture.txt)

**Comment by msmeissn** [comment]
try to switch it to mass storage mode.

the capture is done over mass storage (via vendor specific USB SCSI commands)

**Comment by msmeissn** [comment]
this is a permission issue ... as workaround you can try this as root user

we have a udev rule which gives out regular permissions to this /dev/sgX device, should hopefully be included if you use an RPM package.

**Comment by Javier-MH** [comment]
Hello again.
My solution for Windows:
I installed VIrtualBox + Guest Additions for USB 3.0 support.
Then imported a Kubuntu VM
Into Kubuntu, I installed gphoto2
I created a shared folder windows<->Kubuntu VM (added user to vboxsf group)
On Windows, I use Capture One, so I enabled and defined the shared folder as a Hot Folder.
On linux, launched gphoto2 with tether capture, file path on the shared folder
That's all. I just fire my camera and, after a couple of seconds, I can view my pic in Capture One.
GREAT.
As a negative  note ( maybe I'll create a new issue ), PEF files generated by using this method are not recognised by any software, but DNG files work fine. PEF files seem to have EXIF info missing, incorrect pixel count... and maybe this is the reason no software can read it.
Regards.

**Comment by Javier-MH** [comment]
Yes, PEF is the RAW format of Pentax cameras. K3-II PEF files are handled by most of the photographic software at present (Capture One, Lightroom, Affinity Photo, etc). The problem is, when this file is generated by using gphoto2 tether mode, this file is created or stored with some kind of corruption, and it's not recognised by any software. If I take a picture with my camera without USB cables, etc, that is, just storing it on the camera's SD card, I can read this PEF file without issue.
If I set my camera to use RAW DNG files, using gphoto2 in tether mode, there is not problem with the created DNG file, it's recognised without issues.
Regards.

**Comment by msmeissn** [comment]
we have some PEF fixup code, originally for the K100D... perhaps this is not working correctly.

I added a check to only use it for the K100D now, please check
