### ISSUE TITLE
Set f-number on Nikkon D80

### ISSUE THREAD

**Issue by MrGiskard** [gphoto/gphoto2#46]
Greetings

I'm running gphoto2 on a Rasberry Pi 2 with a Nikkon D8. I can capture images just fine but I get a "PTP Operation Not Supported" error when trying to set the f-number. From reading the options for the Nikkon D80 on the gphoto2 list of supported cameras I figured that such an operation is supported but I may have understood the description incorrectly. Cam someone confirm whether this operation is supported on this specific camera?

**Comment by msmeissn** [comment]
can youy capture a debug trace for it?

the gphoto2 commandline with the --debug --debug-logfile=xx.log added

**Comment by MrGiskard** [comment]
Hi Marcus,

I discovered that I had a pretty old version of gphoto2 - 2.5.4 to be
exact. I've compiled the 2.5.10 version and the problem has been resolved -
I can now change the f-number without issue

Thanks for the response!
