### ISSUE TITLE
Download from smartphone failed. Reason: Unsupported operation.

### ISSUE THREAD

**Issue by mgoppelt** [gphoto/gphoto2#463]
**Describe the bug**

I uploaded files to my Motorola smartphone with gphoto2. I want to create a backup by downloading the files again to my computer. It works on some files, but not on others. Audio files (mp3) "audio/mpeg" can be downloaded, video files (webm) "application/x-unknown" not.

**Name the camera**

Model                          Port
USB PTP Class Camera           usb:001,003

**libgphoto2 and gphoto2 version**

gphoto2 2.5.27

Copyright (c) 2000-2021 Marcus Meissner and others

gphoto2 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of gphoto2 under the terms of the GNU General Public
License. For more information about these matters, see the files named COPYING.

This version of gphoto2 is using the following software versions and options:
gphoto2         2.5.27         x86_64-pc-linux-gnu-gcc, popt(m), exif, cdk, no aa, no jpeg, readline
libgphoto2      2.5.27         standard camlibs, x86_64-pc-linux-gnu-gcc, ltdl, EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip usb1 usbdiskdirect usbscsi, x86_64-pc-linux-gnu-gcc, ltdl, EXIF, USB, no serial

**To Reproduce**

gphoto2 --list-files --folder /store_00010001/Pictures/_002_neu/010_stereo &> debug_11.txt
gphoto2 --debug -p 1 --folder /store_00010001/Pictures/_002_neu/010_stereo &> debug_12.txt

gphoto2 --list-files --folder /store_00010001/Pictures/_002_neu/011_vid &> debug_21.txt
gphoto2 --debug -p 1 --folder /store_00010001/Pictures/_002_neu/011_vid &> debug_22.txt

0.986844 get_file_func               (2): Getting file '142_odyssey.webm'.
0.986850 gp_filesystem_get_file      (2): Download of '142_odyssey.webm' from '/store_00010001/Pictures/_002_neu/011_vid' (type 1) failed. Reason: 'Unsupported operation'
0.986854 gp_camera_file_get  gphoto2-camera.c:1692 (0): 'gp_filesystem_get_file (camera->fs, folder, file, type, camera_file, context)' failed: -6

**Comment by mgoppelt** [comment]
[debug_11.txt](https://github.com/gphoto/gphoto2/files/7487726/debug_11.txt)

**Comment by mgoppelt** [comment]
[debug_21.txt](https://github.com/gphoto/gphoto2/files/7487738/debug_21.txt)
[debug_22.txt](https://github.com/gphoto/gphoto2/files/7487739/debug_22.txt)

**Comment by mgoppelt** [comment]
debug_12.txt is large (44 MB).

**Comment by msmeissn** [comment]
problem is the device was not known as MTP device, and is not detectable ... and we filter against downloading "undefined" types...

I whitelisted motorola as MTP device, also added the device to the id lists.

**Comment by mgoppelt** [comment]
The phone was in PTP mode. I manually switched to MTP. The files can be downloaded now.

**Comment by mgoppelt** [comment]
There is another problem. I have subfolders with subfolders but no files. The subfolders get treated as files and cannot be listed or downloaded. I will upload the debug output.

**Comment by mgoppelt** [comment]
markus@ryzen ~/tmp/moto_bak $ gphoto2 --list-folders --folder /store_00010001/Pictures/_002_neu/_002_sxtn
There are 0 folders in folder '/store_00010001/Pictures/_002_neu/_002_sxtn'.   
markus@ryzen ~/tmp/moto_bak $ gphoto2 --list-files --folder /store_00010001/Pictures/_002_neu/_002_sxtn
There are 2 files in folder '/store_00010001/Pictures/_002_neu/_002_sxtn'.     
#1     001_Aso                    rd     4 KB application/x-unknown
#2     002_Leben                  rd     4 KB application/x-unknown

**Comment by mgoppelt** [comment]
gphoto2 --debug --list-folders --folder /store_00010001/Pictures/_002_neu/_002_sxtn &> debug_31.txt
gphoto2 --debug --list-files --folder /store_00010001/Pictures/_002_neu/_002_sxtn &> debug_32.txt

**Comment by mgoppelt** [comment]
[debug_31.txt](https://github.com/gphoto/gphoto2/files/7493119/debug_31.txt)
[debug_32.txt](https://github.com/gphoto/gphoto2/files/7493120/debug_32.txt)

**Comment by mgoppelt** [comment]
libmtp had the same problem. The Android version is very old (version 5.1). I fixed the problem by creating new folders and moving the files. The folders were there on the phone, but got represented as files on MTP.
