### ISSUE TITLE
Microsoft LifeCam HD-3000 is not detected

### ISSUE THREAD

**Issue by CrispyPin** [gphoto/gphoto2#473]
**Describe the bug**

Microsoft LifeCam HD-3000 is not detected by gphoto2 --auto-detect

**Name the camera**
Microsoft LifeCam HD-3000
ID 045e:0779

**libgphoto2 and gphoto2 version**
2.5.27

**To Reproduce**
Plug in a Microsoft LifeCam and run gphoto2 --auto-detect, observe it not being in the list

[debug_gphoto2.log](https://github.com/gphoto/gphoto2/files/7739669/debug_gphoto2.log)

**Comment by msmeissn** [comment]
This is probably a webcam, which is served by the kernel usb video driver.
You can try trunning a videoconference program or "cheese" from GNOME to see if it gets detected by it.

If you think this is a "non-webcam" camera  can you attach lsusb -v   ?

**Comment by CrispyPin** [comment]
It is a webcam, are they not supported? And yes other programs do detect it. In OBS Studio I'm able to set some of the parameters like exposure but it's very weird about it (only specific values on the slider work). Though if I set the brightness too that setting is lost outside of OBS.

I was hoping to be able to use gphoto2 to set exposure and brightness/gain since I need 2 different settings profiles and using a script would be helpful.

I attached the output of lsusb -v for this camera:
[lsusb_lifecam.txt](https://github.com/gphoto/gphoto2/files/7740705/lsusb_lifecam.txt)

**Comment by CrispyPin** [comment]
Alright I found a different tool (v4l-utils) that works, I'm still curious why it doesn't work in gphoto though

**Comment by msmeissn** [comment]
webcams and usb connected digital cameras use different usb protocols.

webcams use a more streaming like protocol (USBVIDEO protocol), have no filesystem itself, and cannot be operated disconnected usually. To avoid latency issues the protocol is usually implemented directly in the kernel.

digital cameras that can be disconnecetd, can take single pictures or movies, or can also be fully remote controlled usually. Most speak PTP (Picture Transfer Protocol) these days. As there are no real latency requirements it can and is implemented in userland usually.

I thought about also handling usbvideo cameras in libgphoto2 too, but they already have their own ecosystem ... so it would be duplicated effort and likely not meet latency requirements.
