### ISSUE TITLE
Cannot detect Sony ILCE-6000 

### ISSUE THREAD

**Issue by HlKun** [gphoto/gphoto2#476]
gphoto2 --auto-detect,unable to detect camera;
but lsusb can find the camera;
![eb11587fcf35fe29be62f20c5e0cb6d](https://user-images.githubusercontent.com/46489569/148481612-4ea3b3e1-33f8-48c3-af30-27a0d3da8737.png)

**Comment by msmeissn** [comment]
what does
gphoto2 --version
report?

it might be that you did not build with usb support.

**Comment by HlKun** [comment]
![2022-01-07 18-54-26屏幕截图](https://user-images.githubusercontent.com/46489569/148533822-03ee7907-0b55-412d-9f7d-f75e6a37eb91.png)

**Comment by msmeissn** [comment]
you built libgphoto2 without USB support ...  see the "no USB" in the last line.

before configure-ing libgphoto2, you need to install the libusb1 development package.

**Comment by HlKun** [comment]
thank you,it words now.
