### ISSUE TITLE
build fails: libexif is missing

### ISSUE THREAD

**Issue by Vouivre** [gphoto/gphoto2#479]
The build fails for `gphoto2` version 2.5.28. I get the following error:

```
checking for jpeglib.h... yes
checking for jpeg_read_scanlines in -ljpeg... yes
checking for LIBEXIF... no
configure: error: Package requirements (libexif >= 0.6.9) were not met:

Package 'libexif', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LIBEXIF_CFLAGS
and LIBEXIF_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

I use the following to build `gphoto2`

```
./configure \
    --prefix=/usr \
    --disable-nls
```

`libexif` is not installed on my system and from the documentation I see it's not mandatory to have it as a dependency. I was able to install `gphoto2` 2.5.27 with the same configuration and build command. 

I can also install `libgphoto2` 2.5.28 without problems. 

My system:

```
Linux HOSTNAME 5.7.12 #7 SMP Wed Oct 21 07:21:26 UTC 2020 x86_64 GNU/Linux
```

My linux distribution is based on `musl`, not `glibc`, I don't know if it makes a difference. 

Let me know if you need more information.

**Comment by msmeissn** [comment]
does it proceed? I think gphoto2 will still buikld also without libexif?


@ndim ?

**Comment by ndim** [comment]
Will examine further.

@Vouivre What musl based Linux distro is that, btw? If I set up a VM with a musl based distro, I could very well install the same one you are using and therefore much more closely replicate your environment.

**Comment by ndim** [comment]
Found it. This is unrelated to glibc vs musl, so @Vouivre please disregard my question about your musl based distro.

This is purely an oversight of mine from commit 96dbd34de5393f6da6d402836af4aec1a7d9c573 in conjunction with the earlier commit d21c6a390e26cec8f76570f0d41d8ac7256033fc: `PKG_CHECK_MODULES`, when not given the fourth `[if-not-found]` argument, will abort `configure` if the module has not been found.

Will commit a fix in the next few minutes.

**Comment by Vouivre** [comment]
Thank you very much!

**Comment by Vouivre** [comment]
Sorry to come back with this issue, but I tried to use the following patch:

```
diff --git a/configure.ac b/configure.ac
index f958bfc..e4522ed 100644
--- a/configure.ac
+++ b/configure.ac
@@ -277,7 +277,8 @@ dnl 0.5.3 introduces exif-ifd.h which we use
 dnl 0.6.9 introduces exif-log.h which we use
 PKG_CHECK_MODULES([LIBEXIF], [libexif >= 0.6.9],
                   [AC_DEFINE([HAVE_LIBEXIF], [1],
-                             [whether building with libexif])])
+                             [whether building with libexif])],
+                  [AC_MSG_WARN([building gphoto2 *without* libexif])])
 
 
 dnl ---------------------------------------------------------------------------
```

and it still not compiles. What's wrong ?

**Comment by ndim** [comment]
> Sorry to come back with this issue, but I tried to use the following patch:

You are very welcome to come back with any issue until we have resolved it. Sorry for having messed this up in the first place, and for apparently not having fixed it yet, either.

> and it still not compiles. What's wrong ? 

As I have not seen the actual error message, I can only speculate. The first and as of right now the only thing coming to mind is... Have you re-run `autoreconf` and `configure`?

**Comment by Vouivre** [comment]
> As I have not seen the actual error message, I can only speculate. The first and as of right now the only thing coming to mind is... Have you re-run `autoreconf` and `configure`?

Sorry, you have actually fix it. It's simply that I don't know the build tools very well....

First I get the exact same error as the first time. 

Then, if I understand now correctly, you have fixed `configure.ac`. This file is necessary to generate the `configure` script. So If I only patch `configure.ac` it won't change anything. So I have to patch `configure.ac` and to run `autoreconf` in order to update the `configure` script. 

In the next release of `gphoto2`, it won't be necessary to run `autoreconf`, because `configure` won't give any error if `libexif` is not installed. 

Thank you for correcting me if I'm wrong.

**Comment by ndim** [comment]
> Thank you for correcting me if I'm wrong.

There is nothing to correct here - you are spot on.
