### ISSUE TITLE
Fuji Fujifilm GFX 100S: gphoto2 --capture-preview crashes

### ISSUE THREAD

**Issue by theratty** [gphoto/gphoto2#480]
**Describe the bug**

When I try to capture preview with _gphoto2 --capture-preview_ gphoto crashes.

**Name the camera**
Fuji Fujifilm GFX 100S (2nd) - added in latest release (2.5.28)
I don't have another camera to check if it works on other.

**libgphoto2 and gphoto2 version**
gphoto2              2.5.28
libgphoto2          2.5.28
libgphoto2_port  0.12.0 

**To Reproduce**

gphoto2 --capture-preview

Output:
double free or corruption (out)                                                
Aborted

**Debug Logs**

[capture-preview-debug.log](https://github.com/gphoto/gphoto2/files/7896445/capture-preview-debug.log)

**Comment by msmeissn** [comment]
a memory leak avoidance patch was too greedy and causing double frees ... i fixed it in 2.5.28.1 current GIT of libgphoto2
