### ISSUE TITLE
Canon EOS 850D capture in sd but download empty file

### ISSUE THREAD

**Issue by gentilmente** [gphoto/gphoto2#488]
HI, thanks for this awesome work!
**Describe the bug**

**`--capture-image-and-download`**, downloads empty file
but  **`--capture-image`**  and then **`--get-file <number>`** works fine

**Name the camera**
Canon EOS 850D

`gphoto2 --summary`
Device Capabilities:
        File Download, File Deletion, File Upload
        **No Image Capture**, No Open Capture, _Canon EOS Capture_, Canon EOS Capture 2
        Canon Wifi support

**libgphoto2 and gphoto2 version**
gphoto2         2.5.28         clang, popt(m), exif, no cdk, no aa, jpeg, readline
libgphoto2      2.5.28         standard camlibs, clang, no ltdl, no EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb1, clang, no ltdl, no EXIF, USB, serial without locking

**To Reproduce**
have this camera model and exec those commands

This make me think, why `--capture-image-and-download` doesn't work if I can do both actions one after the other?
And what is Canon EOS Capture listed with `--summary`? how can I use that?
thank you

**Comment by newluhux** [comment]
same issue on Canon EOS 650D :-(

**Comment by msmeissn** [comment]
can you get a debuglogfile of the failing capture?
canons support 2 different capture targets, RAM (usually the /capt0000.jpg ones) and SD-CARD (the DCIM/.../IMG_ paths)
but it should not create empty files.

**Comment by msmeissn** [comment]
no reply received, reopen if you can reproduce and provide a logfile
