### ISSUE TITLE
How to get the status of focus for canon 1500D

### ISSUE THREAD

**Issue by arnozeng** [gphoto/gphoto2#494]
sometimes we need to make sure the focus is clearly before capture the picture, but it seem that gphoto2 can't feed back the status for forcus when try use autofocussdrive command. 

i also try to get the status from gp_camera_wait_for_event function, but can't find this the message we need.

how to get the status of focus? or i miss something? thanks

**Comment by msmeissn** [comment]
if you read the events, there will be a focusinfo event/ config change for the Canon EOS

"focusinfo" property.

looks like:
eosversion=2,size=6000x4000,size2=6000x4000,points={{-455,-455,345,284},{455,455,345,284},{-455,455,345,284},{455,0,345,284},{-455,0,345,284},{0,-455,345,284},{0,455,345,284},{0,0,345,284},{-1017,-455,345,284},{1017,455,345,284},{-1017,455,345,284},{1017,0,345,284},{-1017,0,345,284},{0,-856,345,284},{0,856,345,284},{455,-455,345,284},{1580,0,345,284},{-1580,0,345,284},{1017,-455,345,284}},select={},unknown={0080000000000000000000000000000000ffff}

The property will change and there will be points listed in select={} if these are triggered.

sample from different EOS with points selected:
eosversion=2,size=6960x4640,size2=6960x4640,points={{1672,830,297,291},{1266,830,297,291},{578,1021,297,291},{0,1021,297,291},{-578,1021,297,291},{-1266,830,297,291},{-1672,830,297,291},{-2078,830,297,291},{1266,415,297,291},{578,511,297,291},{0,511,297,291},{-578,511,297,291},{-1266,415,297,291},{-1672,415,297,291},{-2078,415,297,291},{2078,830,297,291},{578,0,297,291},{0,0,297,291},{-578,0,297,291},{-1266,0,297,291},{-1672,0,297,291},{-2078,0,297,291},{2078,415,297,291},{1672,415,297,291},{0,-511,297,291},{-578,-511,297,291},{-1266,-415,297,291},{-1672,-415,297,291},{-2078,-415,297,291},{2078,0,297,291},{1672,0,297,291},{1266,0,297,291},{-578,-1021,297,291},{-1266,-830,297,291},{-1672,-830,297,291},{-2078,-830,297,291},{2078,-415,297,291},{1672,-415,297,291},{1266,-415,297,291},{578,-511,297,291},{2078,-830,297,291},{1672,-830,297,291},{1266,-830,297,291},{578,-1021,297,291},{0,-1021,297,291}},select={3,4,5,7,8,15,16,17,18,20,23,34,35,38,40,42,44,},unknown={ffffffffff1f000000000000000000000000000000000000000000000000000000000000ffff}

**Comment by arnozeng** [comment]
Thank you for your reply。 i will try it.
