### ISSUE TITLE
Canon EOS 100D - capture-movie not work well

### ISSUE THREAD

**Issue by pigbrain** [gphoto/gphoto2#503]
**Describe the bug**
I recorded video like the command below and i got the `movie.mjpg`.  
When i played the movie.mjpg, i got `JPEG error #42`.
Also when I put this file(movie.mjpg) in ffmpeg  I get this error. (No JPEG data found in image / Invalid data found when processing input)

```
gphoto2 --capture-movie=10s
```

**Name the camera**
```
Canon EOS 100D 
```

**libgphoto2 and gphoto2 version**
```
This version of gphoto2 is using the following software versions and options:
gphoto2         2.4.11         gcc, popt(m), exif, no cdk, no aa, no jpeg, no readline
libgphoto2      2.4.13         gcc, ltdl, EXIF
libgphoto2_port 0.8.0          gcc, ltdl, USB (libusb1), serial without locking
```

**To Reproduce**
When i run `gphoto2 --capture-movie=10s`, I always get the same result.

I attatched log file by running `gphoto2  --capture-movie=3s --debug --debug-logfile=log.txt`

[log.txt](https://github.com/gphoto/gphoto2/files/8489359/log.txt)

**Comment by pigbrainfs** [comment]
> 2.4.13 is 10 years old, please update to a more recent version first.

I'll check it again. Thanks!

**Comment by pigbrain** [comment]
> 2.4.13 is 10 years old, please update to a more recent version first.

I'll check it. Thanks!
