### ISSUE TITLE
Canon EOS R6 - Can't change Aperture

### ISSUE THREAD

**Issue by LeMajors** [gphoto/gphoto2#508]
I _can_ change e.g. ISO or shutterspeed but not the aperture. The camera is set to "M" (Manual Settings)
Is this a bug or do I something wrong?

**Name the camera**
Canon EOS R6

**libgphoto2 and gphoto2 version**
gphoto2 2.5.27

**To Reproduce**
**gphoto2 --get-config aperture**
Label: Aperture
Readonly: 0
Type: RADIO
**Current: 6.3**
Choice: 0 6.3
Choice: 1 7.1
Choice: 2 8
Choice: 3 9
Choice: 4 10
Choice: 5 11
Choice: 6 13
Choice: 7 14
Choice: 8 16
Choice: 9 18
Choice: 10 20
Choice: 11 22
Choice: 12 25
Choice: 13 29
END

**gphoto2 --set-config-index aperture=8**
(no output or error message)

**gphoto2 --get-config aperture**
...the same output as above. That means: **Current: 6.3** ...not 16 as expected.

The debug.log is attached: [debug.log](https://github.com/gphoto/gphoto2/files/8756349/debug.log)

Thanks for help,

Marcus

**Comment by msmeissn** [comment]
the EOS R reporting of aperture was not handled correctly in 2.5.27, update to 2.5.29 please and test again...

**Comment by LeMajors** [comment]
Thanks for this info. Unfortunately I don't know much about make, etc. I'm using a Raspi 4B and tried this tutorial:
https://www.e-techno-tutos.com/wp-content/uploads/2021/05/Instructions.pdf

Now the version of gphoto2 is 2.5.28.1, libphoto2 is still 2.5.27...

If you have a noob tutorial for the update-process on the RPI I would be glad to get a link.
Otherwise I will live with this bug until a noob-friendly "apt get install..." is out.

**Comment by msmeissn** [comment]
there is a gphoto2-updater script, but not sure if it would work for you. Otherwise sadly you have to wait  :/

**Comment by LeMajors** [comment]
Yes! That solves all problems. I the script updatet my pi to gphoto2 2.5.28 and livgphoto2 to 2.5.29.1 and now it works!
Many thanks!!
