### ISSUE TITLE
--wait-event does not timeout command, continues to wait

### ISSUE THREAD

**Issue by 19hours** [gphoto/gphoto2#511]
When the camera is slow, I want to timeout the command if it does not respond within x seconds.

I use --wait-event / --wait-event-and-download for this. However, the command does not timeout and stays waiting until the command is executed completely.

For e.g
gphoto2 --summary --wait-event=1s
gphoto2 --set-config eosremoterelease=Immediate --set-config eosremoterelease=Release Full --wait-event-and-download=1s --force-overwrite

**Comment by msmeissn** [comment]
these cancels should be immediate and not cause waits.

what is your libusb 1 version, and your hardware platform?

**Comment by msmeissn** [comment]
probably something in the API on cancellation urbs changed ... :/
