### ISSUE TITLE
Canon EOS M50 gphoto detection

### ISSUE THREAD

**Issue by Jetter1** [gphoto/gphoto2#513]
**Describe the bug**

Gphoto is not detecting my Canon EOS M50. I am trying to use it in conjunction with Octolapse to create timelapes. When I plug the camera in it does not show up in gphoto2 --auto-detect. I have tried many different USB cables, and am sure multiple transfer data.

**Name the camera**
Canos EOS M50

**libgphoto2 and gphoto2 version**

gphoto2         2.5.28         gcc, popt(m), exif, no cdk, no aa, jpeg, no readline
libgphoto2      2.5.28         standard camlibs (SKIPPING docupen lumix), gcc, no ltdl, EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi, gcc, no ltdl, EXIF, USB, serial without locking

**To Reproduce**

If its a camera misbehavior, attach debug output using  --debug --debug-logfile=debug.log   (if considered useful).

Discord: Jetter#2195 if it is easier. Thanks

**Comment by msmeissn** [comment]
is it visible when you run 

lsusb

if not, chek usb cabling and lower level setup.

**Comment by Jetter1** [comment]
https://i.imgur.com/oyb2C3j.png

I tried running lsusb before plugging it and and nothing changed after plugging it in..

I know this USB works for sure as when I plug and unplug my 3D printer it changed in lsusb.

**Comment by Jetter1** [comment]
Issue solved.. I had tape covering the power prong on the USB so it did not power my 3D Printer.. I knew this cable was 100% good for data because it worked with my printer.. what I didn't realize is I would need power & data.

Thanks for the comment msmeissn.
