### ISSUE TITLE
Can't capture video/preview using Ricoh Theta Z1 camera

### ISSUE THREAD

**Issue by jamal-zaghmout** [gphoto/gphoto2#516]
**Describe the bug**

I cannot use the options `--capture-movie` and `--capture-preview` when using gphoto2. So, I can't take videos using the camera.

**Name the camera**
Ricoh Theta Z1 - using `gphoto2 --auto-detect` shows: `USB PTP Class Camera` and `usb:001,003`

**libgphoto2 and gphoto2 version**
gphoto2         2.5.15         gcc, popt(m), exif, cdk, aa, jpeg, readline
libgphoto2      2.5.16         all camlibs, gcc, ltdl, EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi, gcc, ltdl, USB, serial without locking

**To Reproduce**

Run either of the following commands:

`gphoto2 --capture-movie`
_This gives the output:_

> Capturing preview frames as movie to 'movie.mjpg'. Press Ctrl-C to abort.      
> ERROR: Movie capture error... Exiting.
> Movie capture finished (0 frames)

`gphoto2 --capture-preview`
_This gives the output:_

> *** Error (-6: 'Unsupported operation') ***                                    
> 
> For debugging messages, please use the --debug option.
> Debugging messages may help finding a solution to your problem.
> If you intend to send any error or debug messages to the gphoto
> developer mailing list <gphoto-devel@lists.sourceforge.net>, please run
> gphoto2 as follows:
> 
>     env LANG=C gphoto2 --debug --debug-logfile=my-logfile.txt --capture-preview
> 
> Please make sure there is sufficient quoting around the arguments.

If its a camera misbehavior, attach debug output using  --debug --debug-logfile=debug.log   (if considered useful).
The following file was made using `env LANG=C gphoto2 --debug --debug-logfile=my-logfile.txt --capture-preview `:
[my-logfile.txt](https://github.com/gphoto/gphoto2/files/8950572/my-logfile.txt)

**Comment by msmeissn** [comment]
if you want to try something, try
gphoto2 --set-config movie=1 --wait-event=10s --set-config movie=0 --wait-event-and-download=5s

**Comment by jamal-zaghmout** [comment]
> 

Hey. I tried it and it gave me this in the terminal output:

> *** Error ***              
> PTP Device Busy
> 
> *** Error ***              
> Failed to set new configuration value 1 for configuration entry movie.
> Waiting for 10 seconds for events from camera. Press Ctrl-C to abort.
> 
> *** Error ***              
> PTP Invalid Transaction ID
> 
> *** Error ***              
> Failed to set new configuration value 0 for configuration entry movie.
> Waiting for 5 seconds for events from camera. Press Ctrl-C to abort.
