### ISSUE TITLE
Tethered capture issues with Nikon D3200

### ISSUE THREAD

**Issue by domokos** [gphoto/gphoto2#52]
Well this may rather belong to libgphoto. Let me know and I'll move it.

This is on
uname -a
Linux mercury 3.4.39 #1 SMP PREEMPT Mon Oct 12 12:02:29 CEST 2015 armv7l armv7l armv7l GNU/Linux
Opensuse Tumbleweed up-to-date

gphoto-2.5.11-1.1.armv7hl
libgphoto2-6-2.5.12-1.1.armv7hl

My target is to capture in bulb mode with Nikon D3200 (latest Firmware, which is 1.04). I saw copy/paste issues in /camlibs/ptp2/cameras/nikon-d3200.txt also false information e.g. live view does work with D3200.

On the road here's what I hit:

1. Bulb mode capture (gphoto2 -B) does not work. From the debug log it seems to me that D3200 simply does not support this tethered. Anyway I attach a debug log from an attempted bulb capture.

2. Downloading files from the D3200 SD card while capturing in bulb mode. This is probably again an unsupported scenario by Nikon and I suspect that there is a rather serious bug in the Nikon firmware. While the bulb capture is active - using either an intervalometer or keeping the shutter release button pressed down - accessing the file system on the camera causes it to physically close the shutter. I do not think there is anything that can be done in gphoto2, this clearly seems to me a Nikon bug/an unpredictable result of an unsupported scenario - whatever we/they call it.

3. Capture with shutter speeds other than bulb (gphoto2 --capture-image-and-download -F 5 -I 4). This works no problems in both single capture and time lapse mode.

Summarizing 
1. Someone please confirm that the camera does not support this
2. Someone please confirm that the camera does not support this
3. This is not an issue

[log.zip](https://github.com/gphoto/gphoto2/files/714800/log.zip)

**Comment by msmeissn** [comment]
1. i think the nikon dslr series does not support bulb capture over usb
2. no, the nikon dslr can either do capture or filesystem operations, doing stuff in parallel is not possible

**Comment by domokos** [comment]
1. My Nikon Df works fine in bulb capture mode. I also read somewhere that a user had success using his D7100 or D7200 in bulb mode.
2. OK, thank you.
