### ISSUE TITLE
make check failure and Bulb not found on Sony A6000

### ISSUE THREAD

**Issue by justanenduser** [gphoto/gphoto2#53]
Test 21 (Missing port option) failed.
On Sony A6000 "Bulb mode enabled" but "bulb not found in configuration tree" failure.

[test-suite.txt](https://github.com/gphoto/gphoto2/files/732322/test-suite.txt)
[my-logfile.txt](https://github.com/gphoto/gphoto2/files/732323/my-logfile.txt)

**Comment by msmeissn** [comment]
can you run tyhe part of the testcase:   
gphoto2 --camera="Directory Browse" -L ; echo $?
and report the output?

**Comment by msmeissn** [comment]
for the bulb. hmm. it is a bit buggy I think, have to figure that out. can youy try something like:

gphoto2 --set-config capture=1 --wait-event=15s --set-config capture=0 --wait-event-and-download=30s

**Comment by msmeissn** [comment]
(note for marcus: problem is that "capture" and "bulb" associate with 0xd2c1, and the framework can only use one magic value once)

**Comment by justanenduser** [comment]
gphoto2 --camera="Directory Browse" -L ; echo $?
    returns There is no file in folder '/'.

gphoto2 --set-config capture=1 wait-event=10s --set-config capture=0 --wait-event-and-download=30s
    this works and returns a picture

I did not understand that
    --set-config capture=1 "presses" the shutter
    --wait-event=10s is the length of the exposure
    --set-config capture=0 "releases" the shutter

I did find that
    --wait-event-and-download=<some# of seconds> can be set as low as 2s and still yield the photo

gary anderson

**Comment by msmeissn** [comment]
SO make check here fails because you might have had a USB camera or SD card mounted that is found by the test, (instead of not finding anything). This is kind of harmless.  :)

The bulb mode I need to either enhance or improve the documentation, but good to hear if it works for you now :)

**Comment by justanenduser** [comment]
Thanks for your help :-) Apparently my frustration is now with another program (CCDciel) and its inability to work with my A6000 in BULB mode ... oh well ... :-) 

gary
