### ISSUE TITLE
gphoto2 through ffmpeg with VA-API hardware acceleration produces a broken result

### ISSUE THREAD

**Issue by kreaninw** [gphoto/gphoto2#532]
**Describe the bug**

I tried to use gphoto2 with VA-API hardware acceleration with:

```
gphoto2 --stdout --capture-movie | ffmpeg -hwaccel vaapi -c:v mjpeg -i - -vcodec rawvideo -pix_fmt yuv420p -threads 2 -f v4l2 /dev/video14
```

The result streaming to my vl42loopback device, `/dev/video14`, is broken whether I specified the `-c:v mjpeg`, as shown in my screenshot below:

![Screenshot from 2022-08-20 18-34-46](https://user-images.githubusercontent.com/1403194/185769911-c213dedc-ba11-41a4-99b5-8fa4af7ae8db.png)

The acceleration works on my iGPU (UHD 620 - KBL GT2) in i5-8250u, though.

I tested to check whether the ffmpeg (5.1-2.7) in my system (openSUSE Tumbleweed) is broken. I can convert my mp4 file to a mov file without any issue using:

```
ffmpeg -hwaccel vaapi -i input.mp4 -c:v mjpeg output.mov
```

It seems, ffmpeg is working right, the converted video file is not broken, and hardware acceleration works fine also.

If I am not using hardware acceleration, gphoto2 works fine. But the CPU usage would be a lot higher, as shown in the screenshot below:

![Screenshot from 2022-08-20 18-38-05](https://user-images.githubusercontent.com/1403194/185771156-02f608a4-e763-4f0e-8049-637e2489c2bb.png)

**Name the camera**
This is not related to the camera.

**libgphoto2 and gphoto2 version**
output of: gphoto2 --version

```
gphoto2 2.5.28

Copyright (c) 2000-2021 Marcus Meissner and others

gphoto2 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of gphoto2 under the terms of the GNU General Public
License. For more information about these matters, see the files named COPYING.

This version of gphoto2 is using the following software versions and options:
gphoto2         2.5.28         gcc, popt(m), exif, cdk, no aa, jpeg, readline
libgphoto2      2.5.30         standard camlibs (SKIPPING lumix), gcc, no ltdl, EXIF
libgphoto2_port 0.12.1         iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi, gcc, no ltdl, EXIF, USB, serial lockdev locking
```

**To Reproduce**
1. Connect the camera, make sure to unmount the camera in the system.
2. Launch gphoto2 with VA-API hardware acceleration by: `gphoto2 --stdout --capture-movie | ffmpeg -hwaccel vaapi -c:v mjpeg -i - -vcodec rawvideo -pix_fmt yuv420p -threads 2 -f v4l2 /dev/video14`, but at your v4l2loopback device. Mine is `/dev/video14`. You can check this by `v4l2-ctl --list-devices`.
3. Open **VLC > Media > Open Capture Device** to test gphoto2 stream.

**Comment by kreaninw** [comment]
As a workaround for this issue, I found that I can use QSV instead of VA-API for hardware acceleration. The command is:

```
gphoto2 --stdout --capture-movie | ffmpeg -init_hw_device qsv=hw -filter_hw_device hw -c:v mjpeg_qsv -i - -vcodec rawvideo -pix_fmt yuv420p -threads 2 -f v4l2 /dev/video14
```

My v4l2loopback device is `/dev/video14`. You can check yours with `v4l2-ctl --list-devices`.

However, this workaround will not work with AMD guys. Therefore, hardware acceleration with VA-API would be more preferable.

**Comment by kreaninw** [comment]
As another workaround for anyone having this issue and trying to make hardware acceleration work with FFmpeg. Forget about hardware acceleration with FFmpeg. You can use GStreamer instead by:

```
gphoto2 --stdout --capture-movie | gst-launch-1.0 fdsrc ! decodebin3 name=dec ! queue ! videoconvert ! v4l2sink device=/dev/video14
```

I am not able to make VA-API work with GStreamer yet. However, the performance and resource usage with an unaccelerated GStreamer is far better than an accelerated FFmpeg. There's _zero_ latency on my weak iGPU (UHD 620). I recommend everyone to use gPhoto2 through the GStreamer pipeline instead.

**Comment by kreaninw** [comment]
This issue is fixed as of `gphoto2` **v2.5.30-2.1** and `ffmpeg` **v6.0-1699.4.pm.10** on openSUSE Tumbleweed. Now, I can run gphoto2 with VA-API hardware acceleration with:

```
gphoto2 --stdout --capture-movie | ffmpeg -hwaccel vaapi -c:v mjpeg -i - -vcodec rawvideo -pix_fmt yuv420p -threads 2 -f v4l2 /dev/video14
```

**Comment by Cyanic** [comment]
Thanks for all this, using ffmpeg with hardware acceleration thanks to you. Out of curiosity do you know how to stream GStreamer to pipewire? Been struggling with that for a while now. Perhaps you know?

**Comment by archerallstars** [comment]
@Cyanic I can't stream GStreamer to PipeWire. Many people on the internet say they're able to do it, but I can't make it work at all, nor I can find the command that actually works posting anywhere.
