### ISSUE TITLE
Canon EOS M50 Mark II support issue

### ISSUE THREAD

**Issue by obisidianouc** [gphoto/gphoto2#536]
**Describe the bug**

My camera is Canon EOS M50 Mark II, which is shown supported to capture in the list on the website (http://www.gphoto.org/proj/libgphoto2/support.php, Canon EOS M50m2). However, I cannot capture image from this camera when running gphoto2 --capture-image. I connected this camera to the raspberry pi. I tried to add "sudo", but still did not work. Any idea on it ?

output of gphoto2 --capture-image :

This camera can not capture
Error: Could not capture image
Error: Could not capture
*** Error(-6: 'Unspported operation')***

**Name the camera**
`Output of gphoto2 --auto-detect: `

`Model                                            Port`

`-----------------------------------------`
`Mass Storage Camera                    disk:/boot`
`USB PTP Class Camera                   usb:001,007`

output of  lsusb:

Bus 001 Device 007: ID04a9:32f9 Cannon. Inc. Canon Digital Camera
Bus 002 Deviuce 001: ID 1d6b:0003 Linux_Foundation 3.0 root hub

**libgphoto2 and gphoto2 version**

gphoto2 version: 2.5.27
libgphoto2 version: 2.5.27

**Comment by msmeissn** [comment]
the gphoto2 tries to use the Mass Storage camera it finds first. (Probably a mounted camera SD card.)

You can prepend --port usb:   to the gphoto2 calls to select zthe USB camera instead of the disk driver.

**Comment by obisidianouc** [comment]
> the gphoto2 tries to use the Mass Storage camera it finds first. (Probably a mounted camera SD card.)
> 
> You can prepend --port usb: to the gphoto2 calls to select zthe USB camera instead of the disk driver.


Than you for your quick reply. I tried to use gphoto2 --auto-detect --port usb: 007, but it still does not work. Maybe I do not use the command correctly. Could you clarify more about how to use the command to select the USB camera instead of the disk driver? Sorry to ask this simple question.

**Comment by msmeissn** [comment]
e.g. use it for the other commands beside autodetect:

gphoto2 --port usb: --capture-image

**Comment by obisidianouc** [comment]
> e.g. use it for the other commands beside autodetect:
> 
> gphoto2 --port usb: --capture-image

Thank you so much, I think I solve it now!
