### ISSUE TITLE
Error Detect Camera Sony ZV-E10

### ISSUE THREAD

**Issue by xNiza** [gphoto/gphoto2#542]
Hi guys I would like to say that is my first time here and If I go against some rule please don´t report me.

I am configuring my first time octo print and I followed a Youtube Tutorial, my problem was that octo print didn´t detect my camera but It was an error of mine cause I have the "PC conect" 'Off'

-> So When I execute the command `gphoto2` --auto-detect`
It appears:

USB PTP Class Camera usb:001,004

So then I ignore this and i continue configuren octolapse but then it dind´t worked at all.

I checked this list [http://www.gphoto.org/proj/libgphoto2/support.php](url) if Sony ZVE-10 was available to use  

And it appers like Sony ZV-E10 (Control) I don´t knoe what doesn´t mean that control.

I have checked all and reinstalled octoprint so many times and I am so frustrated. Can Anyone help me please?

Thanks for all and Sorry for the admin/moderator if I have made a mistake.

(I don´t know who to debug the error and I´ve tried so many times)

**Comment by msmeissn** [comment]
in the camera there is a USB Mode menu. there it should say "PC Control" 

- can you send us the USB ids in this mode? 
- Install gphoto2 commandline tool
- can you run gphoto2 --summary --debug --debug-logfile=summary.log > summary.txt    and attach both summary.log and summary.txt here?
- check if gphoto2  --capture-image-and-download   works

**Comment by AnthonyOGorman** [comment]
Not sure if this was fixed but I have this exact issue with the Sony ZV-E10.

Running  "gphoto2 --capture-image-and-download" outputs:
ERROR: Could not capture image.
ERROR: Could not capture.

[summary.txt](https://github.com/gphoto/gphoto2/files/10015254/summary.txt)
[summary.log](https://github.com/gphoto/gphoto2/files/10015255/summary.log)

**Comment by AnthonyOGorman** [comment]
Ignore this I was on a old version of libgphoto2, upgrading to 2.5.30 fixed the issue.

**Comment by msmeissn** [comment]
lets consider it solved with 2.5.30 then, thanks for testing!

**Comment by xNiza** [comment]
Still it doesnt work

**Comment by AnthonyOGorman** [comment]
> Still it doesnt work

What is your output for "gphoto2 -v"
