### ISSUE TITLE
Raspberry Pi libgphoto2 symbol lookup error

### ISSUE THREAD

**Issue by BryanWilkins** [gphoto/gphoto2#543]
Hi there,  
I have 2 programs that use libgphoto2 on the raspberry pi.  recently I was setting up a new install and compiled the latest version.  When I run my programs, I get this error.

symbol lookup error: /usr/local/lib/libgphoto2.so: undefined symbol: gp_port_init_localedir, version LIBGPHOTO2_5_0

What could be the problem and howto fix?  

If i revert back to the version right before the last. It works just fine.  I am not understanding something here.  Please help.

**Comment by msmeissn** [comment]
You probably have a mix of old and new libgphoto2_port and libgphoto2.
e.g. it tries to use an old libgphoto2_port ... perhaps from /usr/lib/ somewhere, 

remove this old libgphoto2_port 

(ldd /usr/local/lib/libgphoto2.so    should show where it loads it from)

**Comment by BryanWilkins** [comment]
Thank you so much for this...  I was a little stuck.  It worked just like you said.  I deleted all old files and recompiled everything and it is working now perfectly.  the ldd trick DID work and I didn't think of that.  like I said THANK YOU!
