### ISSUE TITLE
Nikon DSLR: get step size from auto focus for the manual focus (question/feature)

### ISSUE THREAD

**Issue by tokiAi** [gphoto/gphoto2#554]
Is it possible to get the steps (x) that the motor made in the lens during auto focus, so that I could use these steps in manual focus and focus on the same spot/plane with `--set-config manualfocusdrive=x`?

**Additional context**
I'm working on a focus stacking algorithm and this feature would be helpful.
I have a method that use auto focus ( `--set-config autofocusdrive=1`) and then manually executes the steps of the motor up to the "limit Error". (something like` for-loop with --set-config manualfocusdrive=-1`) but it is slow.

**Comment by msmeissn** [comment]
I have so far not seen that reported.
With the modern ultrasound motors there is also no direct physical drive that even could report this back.

**Comment by tokiAi** [comment]
Thank you. Now I know that this is a camera side limitation.
