### ISSUE TITLE
RAW format for --capture-preview possible?

### ISSUE THREAD

**Issue by mviereck** [gphoto/gphoto2#558]
**Is your feature request related to a problem? Please describe.**

I make heavy use of `--capture-preview` along with EOSzoom to capture photos with a Canon EOS 1000D mounted on a microscope. (I found that 'EOSzoom 10x' gives the same resolution as a regular capture, just restricted to a small area.)

The images I get with `--capture-preview` are in 8bit jpg format. The jpg format causes compression artefacts and does not store the full range of information that the sensor could provide.

**Describe the solution you'd like**
Is it possible to get the preview images in RAW format?  If not yet, would it be possible at all?
Or, at least, a lossless format like TIF with 16bit for greater color range?

**Comment by msmeissn** [comment]
The preview is delivered via special commandpipeline and is I think always JPEG. have not seen this otherwise yet.
you would need to do full capture to get RAW.

**Comment by mviereck** [comment]
Thank you for your answer!
Do I understand right that the conversion to JPEG is done within the camera and not by gphoto2?

I would prefer not do do full captures in my setup, because it involves several hundred captures in each session (hard time for the camera mechanic) and I would only need that small preview area. However, there might not be an immediate way for this.

Or is it possible to get a full capture without triggering the mechanic?

**Comment by msmeissn** [comment]
yes, the preview is sent as jpeg by the camera already. (I think the mirror based cameras have a secondary sensor for that even.)

i fear you will need to go mirrorless if you want your requirements :/
