### ISSUE TITLE
Multiple actions at the same time gphoto2

### ISSUE THREAD

**Issue by CikaLaza** [gphoto/gphoto2#56]
Hi,

Is there any way to do multiple actions at the same:
Live view and capture for example? I have tried something similar but it does not work....
I have tried i one thread to do the live streaming and it works, but when I try to do same action (capture for example) it fails, and streaming breaks.
Is this restriction of libgphoto2 or usb library? 

Regards,
Miroslav

**Comment by msmeissn** [comment]
There can only be 1 connection over USB, so accessing the same device from multiple threads or processes is not possible.

This needs to happen in the same thread/process  and you somehow need to program / multiplex the access in that.

so capture previews in a loop and on a trigger run capture_image in the middle.

**Comment by CikaLaza** [comment]
Ok, thank you for your fast reply.
