### ISSUE TITLE
Fuji XT-3 unable to use camera shutter release when tethered

### ISSUE THREAD

**Issue by RampantPanda** [gphoto/gphoto2#570]
**Describe the bug**

When tethered to computer, my camera's shutter release (or any other button) doesn't work

**Name the camera**
Fuji Fujifilm X-T3 

**libgphoto2 and gphoto2 version**
gphoto2 2.5.28

Copyright (c) 2000-2021 Marcus Meissner and others

gphoto2 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of gphoto2 under the terms of the GNU General Public
License. For more information about these matters, see the files named COPYING.

This version of gphoto2 is using the following software versions and options:
gphoto2         2.5.28         gcc, popt(m), exif, no cdk, no aa, jpeg, readline
libgphoto2      2.5.30         standard camlibs, gcc, no ltdl, EXIF
libgphoto2_port 0.12.1         iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi, gcc, no ltdl, EXIF, USB, serial without locking

**To Reproduce**

I used the troubleshooting guide from https://docs.darktable.org/usermanual/4.0/en/tethering/troubleshooting/
1. Connect camera via tetherpro USB 3.0 cable
2. (Unmount automounted PTP via file manager)
3. Open terminal and give command: `λ env LANG=C gphoto2 --port usb: --capture-image-and-download` The camera is unresponsive. I ctrl-C to cancel the command.

Here is the terminal output: https://bin.garudalinux.org/?948cd8572bf7f768#4RBHvFRhY1pqdX3BYMiY9kFtYYFqoeZLeyoFUtbk5jxe
Here is the debug log: https://bin.garudalinux.org/?ba00beea94868ed0#5goWM4WnawZAChsWxcWdqRMxiFoVKdYkNVfqnzKRN43V
I tried this with camera set to capture 1) RAW+jpeg 2) RAW only and 3)jpeg only, with same results.
Autofocus was on.
Camera set to "USB tether shooting auto" in connection settings.

Computer is dell xps 13 with garuda linux. More info on computer here: https://bin.garudalinux.org/?e91ddf701b5634a5#VT3xEpFUrY5mZwh48v1a2qg7RmaAQFyWLBrP61PN3VX

**Comment by bocajnotnef** [comment]
I'm experiencing similar behavior on the XT-4. I'm also unable to update any of the camera's configuration while the tethered session is active.

I first noticed this behavior in Darktable, which uses gphoto2 as it's connection library under the hood. Notably, triggering a capture via gphoto (or Darktable) works (`gphoto --capture-image-and-download`), so it seems like everything is working... except for the camera not being able to release the shutter itself.

**Comment by aeewhite** [comment]
I'm also experiencing this behavior on my Fuji X-T3. The camera is set to "USB Tether Shooting Auto" mode and connected via USB. I can also report that single shot methods like `--capture-image-and-download` work for me most of the time as well, only locks up consistently when running `--capture-tethered`

Here's a debug log output from running `sudo gphoto2 --capture-tethered --debug --debug-logfile=debug.log`
[debug.log](https://github.com/gphoto/gphoto2/files/13255596/debug.log)

```
gphoto2 2.5.28

Copyright (c) 2000-2021 Marcus Meissner and others

gphoto2 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of gphoto2 under the terms of the GNU General Public
License. For more information about these matters, see the files named COPYING.

This version of gphoto2 is using the following software versions and options:
gphoto2         2.5.28         clang, popt(m), exif, no cdk, no aa, jpeg, readline
libgphoto2      2.5.31         standard camlibs, clang, no ltdl, EXIF
libgphoto2_port 0.12.2         iolibs: disk ptpip serial usb1, clang, no ltdl, EXIF, USB, serial without locking
```

**Comment by bocajnotnef** [comment]
@aeewhite it looks like this is an issue within libgphoto2. There's an active thread in that repo: https://github.com/gphoto/libgphoto2/issues/653

**Comment by msmeissn** [comment]
please check if it works better now in git.
i set the priperty during wait to 0x0001 and during capture to 0x0002

**Comment by aeewhite** [comment]
Just built the latest in git and looks to be working reliably with my X-T3 now. Thanks so much for everyone's help!
