### ISSUE TITLE
Description how to Use Fuji X-E3

### ISSUE THREAD

**Issue by boyi01** [gphoto/gphoto2#571]
I found that my Fuji X-E3 shoud have a basic support: http://www.gphoto.org/proj/libgphoto2/support.php

Image Capture, Liveview, Configuration

But i have no idea how to get them... yan you give any advice?

**Comment by boyi01** [comment]
the camera has 2 modes... USB-Cardreader or USB RAW-CONV...
in both i get a a -1 Error...
[my-logfile.txt](https://github.com/gphoto/gphoto2/files/10980962/my-logfile.txt)

**Comment by boyi01** [comment]
Nobody can help me?

**Comment by msmeissn** [comment]
The Fuji X-E series to our knowledge is not remote controllable. So you will only be able to download images from its card, but not more.

The series Fuji X-T, X-Pro, GFX, are remotre controllable
