### ISSUE TITLE
EOS R6 - Display off after --list-all-config

### ISSUE THREAD

**Issue by LeMajors** [gphoto/gphoto2#587]
Recently, my setup has been behaving differently than before - and I don't know what caused it.

I connected a Raspi4 to a Canon EOS R6 via USB. Although I work with Python, I can reproduce the problem via console commands.

So far, after connecting the camera via USB, the display with the viewfinder image was visible - even after various gphoto2 commands. Now it is the case that after connecting the camera, the viewfinder image is visible, but after e.g. the command "gphoto2 --list-all-config" it disappears and does not come back. Only the icons of the battery and a PC are visible. If it had always been like this, I wouldn't be surprised, but it was different before. My project (360° shots via gimbal, controlled by the Raspi) require settings on the camera. **How do I get the viewfinder image back without reconnecting the USB cable?**

(gphoto2 --reset didn't help.)

Camera: Canon EOS R6
gphoto2 2.5.28

- Connect Camera via USB to Raspi - the camera display still shows viewfinder image.
- Command: gphoto2 --auto-detect - the viewfinder image is still there.
- Command: gphoto2 --list-all-config - the display shows only the icons that say "connected to PC"
- Command: gphoto2 --reset - the display still shows only the icons.

[debug.log](https://github.com/gphoto/gphoto2/files/11778720/debug.log)

**Comment by hfiguiere** [comment]
> 0.001494 main                        (2): libgphoto2 2.5.27

I'm not sure which came first: this version of libgphoto2 or the camera. We are at 2.5.30 currently.

**Comment by msmeissn** [comment]
we flipped this behaviuour back and forth with the releases, so the last release should have it as unlocked (display enabled).
