### ISSUE TITLE
Sony SLT-a58 is recognized, but I can not capture a picture with gphoto2

### ISSUE THREAD

**Issue by ttsoris** [gphoto/gphoto2#59]
Hi there,
I've downloaded and compiled the latest versions of gphoto2 and libgphoto2 from this repository.
When I connect my SONY STL-a58 camera on my laptop and run the following command:
`LD_LIBRARY_PATH=/usr/local/lib env LANG=C /usr/local/bin/gphoto2 --abilities`
I get the following response:
`Abilities for camera             : Sony SLT-A58 (Control)                      
Serial port support              : no
USB support                      : yes
Capture choices                  :
                                 : Image
                                 : Trigger Capture
Configuration support            : yes
Delete selected files on camera  : yes
Delete all files on camera       : no
File preview (thumbnail) support : yes
File upload support              : yes
`
But when I try to execute this command in order to take a picture with the camera:
`LD_LIBRARY_PATH=/usr/local/lib env LANG=C /usr/local/bin/gphoto2 --capture-image-and-download`
I get the following:
`*** Error ***              
PTP I/O Error

*** Error ***              
An error occurred in the io-library ('I/O problem'): No error description available
ERROR: Could not capture image.
ERROR: Could not capture.

*** Error ***              
PTP I/O Error

*** Error ***              
An error occurred in the io-library ('I/O problem'): No error description available`

So I created a log file which might be of help. I attach it to this issue.
[my-logfile.txt](https://github.com/gphoto/gphoto2/files/799991/my-logfile.txt)

I don't know, where to go from here. Any ideas?

**Comment by ttsoris** [comment]
I have also tried the solution described in issue 18: "Failed to capture a photo via Sony A7R II camera. #18".
Still not working. 
New log file: [db.log.txt](https://github.com/gphoto/gphoto2/files/800071/db.log.txt)
My ubuntu version follows:
`Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
`

**Comment by ttsoris** [comment]
OK. It finally worked. I have just executed the command `gphoto2 --list-all-config` and somehow the camera snapped out of the screen showing "Connecting..." and the "USB" icon and showed what the lens was actually capturing.
Subsequently, by executing a `gphoto2 --port usb: --capture-image-and-download`, it shot the picture and downloaded in my laptop. Great!

**Comment by msmeissn** [comment]
I hope this is persistent working now. (I have a SLT A58 too, it works nicely for me).
