### ISSUE TITLE
Canon M6 MkII suddenly stops working (after 2 years)

### ISSUE THREAD

**Issue by draupner1** [gphoto/gphoto2#593]
A week ago I lost connectivity to my Canon M6 MkII.

I have been using it as webcam with OBS for over a year.

The camera is connected in the USB tree, se lsusb.txt

I get some action in syslog, but can not make out what is missing for completion here?
See syslog.txt

Added a debug print from Auto-detect: autodetect.txt

Also did a log from /sys/debug/kernel/devices... :syskerndevices.txt

Any hint on what happened?

anders@xps13:$ gphoto2 --version
gphoto2 2.5.28

Copyright (c) 2000-2021 Marcus Meissner and others

gphoto2 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of gphoto2 under the terms of the GNU General Public
License. For more information about these matters, see the files named COPYING.

This version of gphoto2 is using the following software versions and options:
gphoto2         2.5.28         gcc, popt(m), exif, cdk, aa, jpeg, readline
libgphoto2      2.5.27         standard camlibs, gcc, ltdl, EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi, gcc, no ltdl, EXIF, USB, serial without locking

[syskerndevices.txt](https://github.com/gphoto/gphoto2/files/11866832/syskerndevices.txt)
[syslog.txt](https://github.com/gphoto/gphoto2/files/11866833/syslog.txt)
[lsusb.txt](https://github.com/gphoto/gphoto2/files/11866834/lsusb.txt)
[autodetect.txt](https://github.com/gphoto/gphoto2/files/11866836/autodetect.txt)

**Comment by draupner1** [comment]
Forgot platform:
Dell Laptop, Ubuntu 22.04.2 LTS

**Comment by msmeissn** [comment]
your lsusb.txt is not showing it directly.
if you just run "lsusb" does it list the Canon?

also your syslog.txt snippet has no reference to a Canon.

usually if something breaks after working for a long time I would check cabling.

**Comment by draupner1** [comment]
After some reboots, and resets and restarts, it is working again.

Never really found out the problem cause, sorry for that.

Thank you for the feedback!, lets close it!
