### ISSUE TITLE
What's the simplest way to get

### ISSUE THREAD

**Issue by aonghas** [gphoto/gphoto2#598]
```
gphoto2 --capture-movie --stdout

```

To stream to a web server like
http://localhost:3000/live

I have tried a few things with ffmpeg without success

**Comment by msmeissn** [comment]
I think ffmpeg is the right approach already. 

I tried some howtos on google (gphoto2 capture-movie ffmpeg), but have personally not succeeded yet.

**Comment by aonghas** [comment]
Ok I've managed to get something kind of working with a python server running Open CV on a different port looking at a the virtual camera I created with modprobe on /dev/video0.

I'm then streaming gphoto2 out to that virtual device with this command:

`gphoto2 --stdout --capture-movie | ffmpeg -i - -vf "hflip" -pix_fmt bgr24 -f v4l2 /dev/video0`

Now I can access a live stream with minimal delay in the browser.

**Comment by msmeissn** [comment]
good to hear it works now!
