### ISSUE TITLE
Capture Preview via Standard Out

### ISSUE THREAD

**Issue by SarenT** [gphoto/gphoto2#60]
Hi,

I am trying to make a Java based GUI for gphoto2. I would like to capture previews via standard output to be displayed on the program. Right now, I am having troubles to capture it via standard output.
gphoto2 --show-preview --stdout
gphoto2 --capture-preview --stdout
both create a file capture-preview.jpg
I would really like to avoid hard drive IO for this. Is there anything wrong with my approach or gphoto2 doesn't support this atm?
Or should I use libgphoto2 directly instead of invoking gphoto2 (which is going to be very time consuming)?

Best,
SarenT

**Comment by msmeissn** [comment]
i was thinking that --capture-preview --stdout  should work  ... but it might be bugygy.

what you can use instead as a bit of workaround:
gphoto2 --capture-movie=1 --stdout

this will capture 1 frame preview and write it to stdout.

**Comment by SarenT** [comment]
Yeap, that works great. Although while leaving stdout gphoto2 tells me that there are 2 frames captured.
Thanks a lot!

**Comment by SarenT** [comment]
I closed the issue, because --capture-movie=0 works as a workaround. gphoto2 capture 1 more frame than specified. =0 means therefore 1 frame to be captured.
