### ISSUE TITLE
Leica Q3

### ISSUE THREAD

**Issue by trevorski** [gphoto/gphoto2#601]
**Name of the camera**

Leica Q3

**USB IDs**

(serial number blanked out)

```
% sudo lsusb | grep -i leica
Bus 000 Device 002: ID 1a98:2376 Leica Camera AG LEICA Q3  Serial: 000000000XXXXXXX
Bus 000 Device 000: ID 1a98:2376 Leica Camera AG USB 3.1 Bus
```

**camera summary output**

(serial number blanked out)

[summary.txt](https://github.com/gphoto/gphoto2/files/12567816/summary.txt)

**camera configuration output**

[list-all-config.txt](https://github.com/gphoto/gphoto2/files/12567826/list-all-config.txt)

**test capture**

test if capture perhaps already works:

`gphoto2 --trigger-capture` works `gphoto2 --capture-image-and-download` takes a photo but fails to move past that and `gphoto2 --capture-preview` fails with `*** Error (-1: 'Unspecified error') ***`.

Let me know if you'd like debug logs, USB traffic captured or any more info.

Thanks!

**Comment by msmeissn** [comment]
can you get debug output from the failed capture+download?
and also from the capture preview?

**Comment by trevorski** [comment]
OK, I've attached the debug output for both failed commands. One thing probably work noting is that the capture preview fails *and* seems to terminate the PTP session as the camera resumes its untethered state after the command returns.

Thanks a bunch & I'm excited for `gphoto2` to support the Q3!

[capture-preview-failure.txt](https://github.com/gphoto/gphoto2/files/12710101/capture-preview-failure.txt)
[capture-and-download-failure.txt](https://github.com/gphoto/gphoto2/files/12710102/capture-and-download-failure.txt)

**Comment by msmeissn** [comment]
There is some weirdness, that the session is reported already open which led to the error.



0.059354 ptp_usb_getresp [usb.c:516] (0): PTP_OC 0x1015 receiving resp failed: PTP Session Not Open (0x2003)
0.059360 camera_capture_preview [library.c:3988](0): 'ptp_getdevicepropvalue (params, PTP_DPC_SupportedStreams, &propval, PTP_DTC_UINT32)' failed: PTP Sessio
n Not Open (0x2003)

Currently the code does not seem to take the Leica specific paths as it did not know the USB id. 

I have now added the USB id to libgphoto2, so one thing you can try is to update libgphoto2 to current GIT master, where I added the USB id?

**Comment by trevorski** [comment]
OK, I built `gphoto2` against `libgphoto2` built from master and it still seems to have the same (failing) behavior. Logs attached.

Thanks!

[capture-image-and-download-logfile.txt](https://github.com/gphoto/gphoto2/files/12773950/capture-image-and-download-logfile.txt)
[capture-preview-logfile.txt](https://github.com/gphoto/gphoto2/files/12773951/capture-preview-logfile.txt)

**Comment by msmeissn** [comment]
i added another fix, can you pull , rebuild and retest?

**Comment by trevorski** [comment]
`gphoto2 --capture-preview` works now! `gphoto2 --capture-image-and-download` still seems to fail/hang and I've attached the logs. Thanks!

[capture-image-and-download.txt](https://github.com/gphoto/gphoto2/files/12799381/capture-image-and-download.txt)

**Comment by msmeissn** [comment]
So it waits for the "Capture COmplete" event, which does not arrive.

1. can you try if it works better if you do not use Dual JPG+DNG capture? e.g. single image either JPG or DNG?

2. can you change the line in camlibs/ptp2/library.c:

        {"Leica:Q3",                            0x1a98, 0x2376, PTP_CAP|PTP_CAP_PREVIEW},
to
        {"Leica:Q3",                            0x1a98, 0x2376, PTP_CAP|PTP_CAP_PREVIEW|PTP_NO_CAPTURE_COMPLETE},
and rebuild, this should also fix it.

**Comment by trevorski** [comment]
1) My previous build was lost so I wasn't able to figure this out, but...

2) `gphoto2 --capture-image-and-download` now works with both dual DNG+JPG capture!

**Comment by msmeissn** [comment]
very good! :) 
I think we solved the issues :)
