### ISSUE TITLE
Support for Canon EOS R8

### ISSUE THREAD

**Issue by williamrehndell** [gphoto/gphoto2#607]
Could you kindly update to include support for the Canon EOS R8?
Thank you!

**Comment by msmeissn** [comment]
is now in current GIT, but likely has worked as-is with 2.5.31.

**Comment by wesmagyar** [comment]
I am using the latest version  of Stellarmate and according to them they have the latest release and I am having a similar issue. I am fairly new to Github so not sure if I should attach it to this one or create a new ticket this is the log output for the DSLR test feature in stellar mate
[dslrTest.txt](https://github.com/gphoto/gphoto2/files/14159946/dslrTest.txt)

**Comment by msmeissn** [comment]
@wesmagyar please check if your cameras shows up with "lsusb", it looks like it might not be connected to the host correctly

**Comment by wesmagyar** [comment]
it shows up on dmesg but not on lsusb
![Image 2-5-24 at 11 10 AM](https://github.com/gphoto/gphoto2/assets/95952786/b1bf49fe-23e8-4453-a223-61d81fbaae76)
![Image 2-5-24 at 11 09 AM](https://github.com/gphoto/gphoto2/assets/95952786/45d24738-4c93-4387-8efa-67920e717528)

**Comment by msmeissn** [comment]
it needs to show up on lsusb, otherwise libgphoto2 will not see it either. There is no visible issue in dmesg, only that you might have waited too long and the canon powered off?

**Comment by wesmagyar** [comment]
I had unplugged it and replugged it in 10 seconds or so before running both commands. Not sure what the issue is. Sent from my iPhoneOn Feb 28, 2024, at 10:40 AM, Marcus Meissner ***@***.***> wrote:﻿
it needs to show up on lsusb, otherwise libgphoto2 will not see it either. There is no visible issue in dmesg, only that you might have waited too long and the canon powered off?

**Comment by nachiket** [comment]
I do see it in dmesg and lsusb as a generic Canon camera, not the R8. Are there other steps to get it to work with gphoto2?
