### ISSUE TITLE
Camera won't capture after some time passes

### ISSUE THREAD

**Issue by musaulker** [gphoto/gphoto2#613]
First of all thank you for a great project and library!

I have Canon 650d camera. I connect using USB cable to the laptop. 

I am trying to capture photo from time to time while the camera is connected to the computer.
Photo capture works with gphoto2 on initial try. But after some moment passes, maybe the camera is going sleep or usb connection is closed, for some reason i cannot take a picture any more without closing and opening the camera.

```
gphoto2 --auto-detect                                                   
Model                          Port
----------------------------------------------------------
Canon EOS 650D                 usb:253,003
```

**libgphoto2 and gphoto2 version**
```
gphoto2 2.5.28

Copyright (c) 2000-2021 Marcus Meissner and others

gphoto2 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of gphoto2 under the terms of the GNU General Public
License. For more information about these matters, see the files named COPYING.

This version of gphoto2 is using the following software versions and options:
gphoto2         2.5.28         clang, popt(m), exif, no cdk, no aa, jpeg, readline
libgphoto2      2.5.31         standard camlibs, clang, no ltdl, EXIF
libgphoto2_port 0.12.2         iolibs: disk ptpip serial usb1, clang, no ltdl, EXIF, USB, serial without locking
```

**To Reproduce**

```
$>  env LANG=C gphoto2 --debug --debug-logfile=my-logfile.txt --capture-image-and-download
New file is in location /capt0000.jpg on the camera
Saving file as capt0000.jpg
Deleting file /capt0000.jpg on the camera

..... wait like 30 seconds

$>  env LANG=C gphoto2 --debug --debug-logfile=my-logfile.txt --capture-image-and-download
*** Error: No camera found. ***

```

Is there a configuration that I need to do on the camera or laptop to have a continuously connected camera where I can take picture any time?

Thanks

**Comment by msmeissn** [comment]
when gphoto2 is wiating for events we usually emit Keepalive messages. if gphoto2 is not running we cannot do that.
so perhaps add some gphoto2 --wait-event=10s or whatever delay you plan and see if this helps.

**Comment by musaulker** [comment]
If I understand correctly, I should run gphoto2 with --wait-event=30s in
separate terminal and run gphoto2 capture and download in different
terminal?

I want to have the camera ready to function anytime when I call from
gphoto2. Is there an option to keep the camera alive and ready until I
disconnect the cable or stop it?

Thanks

**Comment by msmeissn** [comment]
there cannopt be parallel instances accessing the same camera, as the camera only can understand 1 protocol data stream

What you could do:

gphoto2 --wait-event-and-download=1000s 

in one shell, and if you have the PID of the gphoto2 process (ps auxw|grep gphoto2)

if you then send a SIGUSR1 via  "kill -USR1 $PID"   the waiting gphoto2 process will take a picture and download it immediately.

**Comment by musaulker** [comment]
I think my problem could be related to autopoweroff setting which has 30 seconds value:

```
gphoto2 --get-config /main/settings/autopoweroff                    
Label: Auto Power Off
Readonly: 0
Type: TEXT
Current: 30
END
```

I tried to set autopoweroff to 60 seconds but unfortunately its not possible

```
env LANG=C gphoto2 --debug --debug-logfile=my-logfile.txt --set-config /main/settings/autopoweroff=60

*** Error ***
The property 'Auto Power Off' / 0xd114 was not set (0x2019: PTP Device Busy).

*** Error ***
Failed to set new configuration value 60 for configuration entry /main/settings/autopoweroff.
*** Error (-110: 'I/O in progress') ***
```

**Comment by msmeissn** [comment]
did you have any luck? i have currently not much more ideas

**Comment by musaulker** [comment]
I found the problem was related to autopower off settings which was set 30 seconds. After i change it to 0 seconds the problem is fixed. Thanks for the suggestion
