### ISSUE TITLE
Canon 700D Unspecified error 

### ISSUE THREAD

**Issue by Gafail** [gphoto/gphoto2#625]
**Describe the bug**

When  attempting to copy Data from the Camera's SD card to the MicroSD card in Raspberry Pi W 0 2 it errors for no explicable reason.

i have tried the Same Raspberry pi setup with a Canon 200D and have no issues at all, I have replace the Pi, i have replaced all the cabling involved, it doesn't work

the Raspberry pi is running headless, and i have checked all the recommendations around other tools looking the camera connectivity, but cannot find anything to indicate this is the issue

i can gather camera info, see photos on the camera without issues, but as soon as i attempt to copy files, it errors:

*** Error ***
PTP General Error

*** Error ***
An error occurred in the io-library ('Unspecified error'): No error description available
*** Error (-1: 'Unspecified error') ***

i have rebuilt the OS, using the default apt-get versions of Gphoto2, i have tried, the latest version and dev versions via:
wget https://raw.githubusercontent.com/gonzalo/gphoto2-updater/master/gphoto2-updater.sh && wget https://raw.githubusercontent.com/gonzalo/gphoto2-updater/master/.env && chmod +x gphoto2-updater.sh && sudo ./gphoto2-updater.sh

i have confirmed the Camera works correctly, i can plug it in to any Desktop and EOS utility can communicate without any issues

Camera has been tested on firmware 1.1.4 and 1.1.5 Magic lantern is not in use.

**Name the camera**
Model                          Port
----------------------------------------------------------
Canon EOS 700D                 usb:001,009

**libgphoto2 and gphoto2 version**
gphoto2 2.5.28.1

Copyright (c) 2000-2021 Marcus Meissner and others

gphoto2 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of gphoto2 under the terms of the GNU General Public
License. For more information about these matters, see the files named COPYING.

This version of gphoto2 is using the following software versions and options:
gphoto2         2.5.28.1       gcc, popt(m), exif, no cdk, no aa, no jpeg, no readline
libgphoto2      2.5.31.1       standard camlibs (SKIPPING docupen lumix), gcc, no ltdl, EXIF
libgphoto2_port 0.12.2         iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi, gcc, no ltdl, EXIF, USB, serial without locking

**To Reproduce**
Simply running Gphoto2 --get-all-files is all thats need to to trigger it every time.
[my-logfile.txt](https://github.com/gphoto/gphoto2/files/14227871/my-logfile.txt)

If its a camera misbehavior, attach debug output using  --debug --debug-logfile=debug.log   (if considered useful).

when runing gphoto2 --auto-detect --debug --debug-logfile=debug.log the log is below aswell
[debug.log](https://github.com/gphoto/gphoto2/files/14227897/debug.log)

any help would be apreciated, happy to blow away OS's and swap out firmwares as needed to help test.

**Comment by msmeissn** [comment]
0.132402 ptp_usb_sendreq             (2): Sending PTP_OC 0x9109 (EOS_GetObjectInfoEx) (0x20001,0xffffffff,0x100000) request...
0.132414 gp_port_write               (3): Writing 24 = 0x18 bytes to port...
0.135601 gp_port_write               (3): Wrote   24 = 0x18 bytes to port: (hexdump of 24 bytes)
0000  18 00 00 00 01 00 09 91-05 00 00 00 01 00 02 00  ................
0010  ff ff ff ff 00 00 10 00-                         ........        

0.135639 ptp_usb_getdata             (2): Reading PTP_OC 0x9109 (EOS_GetObjectInfoEx) data...
0.135653 gp_port_read                (3): Reading 1024 = 0x400 bytes from port...
0.135772 gp_libusb1_read [libusb1.c:697](0): 'libusb_bulk_transfer (port->pl->dh, port->settings.usb.inep, (unsigned char*)bytes, size, &curread, port->timeout)' failed: Input/Output error (-1)
0.135802 gp_port_read [gphoto2-port.c:441](0): Reading 1024 = 0x400 bytes from port failed: Error reading from the port (-34)


-34 is a read error. It tries again, still gets read error ... but then later on we get the data from the camera for this command after another read error.

So something with USB protocol handling is buggy.
If the camera works on another hardware, I would suspect the kernel or raspberry pi hardware here :/

Currently no idea how libgphoto2 this would differentiate from a real read error.

**Comment by Gafail** [comment]
The ambiguity of the issue is disappointing, your help is awesome, what I will try next (tomorrow evening) will be to pull up some old versions of Rasbian lite with older kernels and test, I will then report back what version I have tested and what the result are, hopefully I can find the issue.
I do not that I have been trying this on the latest version available to me currently, so maybe something new exists that had not previously been encountered.
I also agree that I can’t rule out the pi hardware, but this would be surprising too me at worst I have a much older pi 0w original I could test as well if everything else fails.
Many thanks k will report back

**Comment by Gafail** [comment]
Also sorry I did not mean to close this (mobile is great)

**Comment by Gafail** [comment]
ok Update Time, 
Issue is not with Gphoto2, Sorry for wasting time.

For those that may end up with a similar issue becasue i hate finding posts that say Fixed it (Closed) with no context:
i had an 18650 battery bank stepped up to 5V powering the Rpi
i had a cheap USB 2S charger charging the Canon Battery from the same 18650 bank
The cheap charger was not outputting 0-8.4V it was outputting -4.2 to 4.2V this was pulling down the cameras ground reference and making a ground imbalance between the Pi and the DSLR over the usb cable

This meant Gphoto2 could do short/quick things fine but anything long would fail as the grounds would be compleatly out and the longer Gphoto tried the worse the imbalance got (i cant explain this its just what i measured)

i will now close this.
