### ISSUE TITLE
Add support for Nikon Zf

### ISSUE THREAD

**Issue by HeadCase** [gphoto/gphoto2#630]
**Name of the camera*
Nikon Zf

**USB IDs**
Bus 002 Device 001: ID 04b0:0453 Nikon Corporation NIKON DSC Z f  Serial: 0000003010436

**camera summary output**

Attached [summary.txt](https://github.com/gphoto/gphoto2/files/14949547/summary.txt)

**camera configuration output**

Attached [list-all-config.txt](https://github.com/gphoto/gphoto2/files/14949548/list-all-config.txt)

**test capture**

test if capture perhaps already works:

RAW Capture seemed to work, though the JPEG preview appears not to. See attached. 
![capture_preview](https://github.com/gphoto/gphoto2/assets/5247821/4349128b-ea21-4c77-a87e-c12ce86c4402)

**Comment by msmeissn** [comment]
thanks for the report!
please check what happens if you take two previews, if the second is not black.

**Comment by msmeissn** [comment]
added via commit e78ebaa7d442876c3279c5525d7523c481dac695

**Comment by heyfordy** [comment]
I'm interested in this too, is there anything you need to help this get going? I have a ZF and can provide whatever information is necesssary
