### ISSUE TITLE
Nikon 1 J3 exposure time not correct

### ISSUE THREAD

**Issue by HaraldStauss** [gphoto/gphoto2#661]
**Describe the bug**

gphoto2 correctly detects the Nikon 1 J3 camera. It also sets the exposure time correctly using:
gphoto2 --set-config Shutterspeed=15 
This sets the exposure time to 15 seconds (confirmed on camera display)
After that:
gphoto2 --capture-image
takes an image but only with an exposure time of less than 1 second.

**Name the camera**
If this is camera specific, include the camera name as shown by gphoto2 --auto-detect or USB IDs
Model                          Port                                            
----------------------------------------------------------
Nikon J3                       usb:001,010     

**libgphoto2 and gphoto2 version**
output of: gphoto2 --version
gphoto2 2.5.28

Copyright (c) 2000-2021 Marcus Meissner and others

gphoto2 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of gphoto2 under the terms of the GNU General Public
License. For more information about these matters, see the files named COPYING.

This version of gphoto2 is using the following software versions and options:
gphoto2         2.5.28         gcc, popt(m), exif, cdk, aa, jpeg, readline
libgphoto2      2.5.30         standard camlibs, gcc, no ltdl, EXIF
libgphoto2_port 0.12.1         iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi, gcc, no ltdl, EXIF, USB, serial without locking

**To Reproduce**
1. connect camera to USB port
2. gphoto2 --set-config Shutterspeed=15 
3. gphoto2 --capture-image

If its a camera misbehavior, attach debug output using  --debug --debug-logfile=debug.log   (if considered useful).
[Nikon_J3_Debug.txt](https://github.com/user-attachments/files/17856738/Nikon_J3_Debug.txt)

Thank you for looking into this.

Harald Stauss

**Comment by msmeissn** [comment]
tracked in libgphoto2 space
