### ISSUE TITLE
Pentax K-5II not supported?

### ISSUE THREAD

**Issue by mccodesurfer** [gphoto/gphoto2#67]
gphoto2 could not autodetect Pentax K-5II on a mac OSX 10.11.6 (El Capitan). The camera showed as mounted.

[my-logfile.txt](https://github.com/gphoto/gphoto2/files/948489/my-logfile.txt)

**Comment by msmeissn** [comment]
For Pentax Cameras we need to have the USB id listed in camlibs/pentax/library.c 

can you attach the product/vendorid here?  ( run the lsusb tool ) 

if you want to try, you can add it in the camera_abilities() function in above file.

**Comment by mccodesurfer** [comment]
Here's the info!

#define kPentaxVendorID     0x25fb  //Vendor ID of the USB device
#define kK5iiProductID      0x148   //Product ID of device BEFORE it

Thanks, I'll give it a try!

**Comment by msmeissn** [comment]
I have added the ID to git.

hmm, we use a specific scsi generic pass through mode. This is currently just for Linux and not MacOS ... hmm.

**Comment by mccodesurfer** [comment]
Yeah, my guess is its not compatible with MacOS. I was trying to port pk-remote at one time and discovered MacOS is totally different, but I thought maybe you guys were doing some magic :-(  I tried adding the K-5II product ID to the library but it did not work. Maybe MacOS is a logo?

**Comment by mccodesurfer** [comment]
gphoto2 now supports Pentax on Linux. I've opened another issue about Mac support.

**Comment by FAb7D** [comment]
Can you add USB support for Pentax KP on linux? There is MSC e PTB mode of USB.
This is lsusb 
Bus 001 Device 009: ID 25fb:017f Pentax Ricoh Imaging Co., Ltd PENTAX KP
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
and there are this:
https://api.ricoh/downloads/
https://api.ricoh/docs/camera-usb-sdk-cpp/quick-start-linux/
