### ISSUE TITLE
-set-config...shutterspeed bug with Canon EOS 650 D

### ISSUE THREAD

**Issue by weeebber** [gphoto/gphoto2#69]
**Versions:**
gphoto2         2.5.11
libgphoto2      2.5.12
libgphoto2_port 0.12.0
(installed via macports on OS X Sierra)

**Camera:**
Canon EOS 650 D

**Explanation and Symptom:**
While tinkering with setting the shutterspeeds I have come across a bug/ incorrect driver or settings configs.

Choice 25 = 1/8th second shutter speed however the camera goes and sets itself to 25seconds.

NOTE: I have since gone through each of the 0-52 choices and the broken choices are:
(by broken I mean that when setting the choice it doesnt match what `gphoto2 --get-config /main/capturesettings/shutterspeed` reports)
broken choices: **1, 2, 4, 5, 6, 8, 10, 13, 15, 20, 25, 30**

**Troubleshooting:**
`gphoto2 --list-config`
`gphoto2 --get-config /main/capturesettings/shutterspeed`
"...Choice: 24 1/6
Choice: 25 1/8
Choice: 26 1/10..."

`gphoto2 --set-config /main/capturesettings/shutterspeed=24`
camera display shows: 1/6

`gphoto2 --set-config /main/capturesettings/shutterspeed=25`
camera display shows: 25"

`gphoto2 --set-config /main/capturesettings/shutterspeed=26`
camera display shows: 1/10

**Comment by msmeissn** [comment]
As there is "magic" detection in -set-config if the index or the value is used, this can lead to such issues.

Can you do --set-config-index=25   ... this would select entry 25 from the list and not 25 seconds.
Or --set-config-value="1/8"  .. for setting the value

**Comment by weeebber** [comment]
ah perfect I missed that reading through the docs!
Many thanks for your very quick response!
