### ISSUE TITLE
Upgrade of apt-get versions on Raspberry

### ISSUE THREAD

**Issue by NicHub** [gphoto/gphoto2#72]
Hello,

The `apt-get` versions of `gphoto2` and `libgphoto2` are quite old on Raspberry (Raspbian Jessie). Do you plan to upgrade them ?

Thank you in advance !

**Comment by msmeissn** [comment]
These are not under our control. Not sure who to report bugs or feature to Rasbian

**Comment by NicHub** [comment]
Thank you for your answer.

I issued the following command on my Raspberry :

	apt-cache show gphoto2

and it showed the following :

> Maintainer: Debian PhotoTools Maintainers <pkg-phototools-devel@lists.alioth.debian.org>

So I mailed them my question. I don’t know if it is the correct way to do it though. I’ll see.

**Comment by luzpaz** [comment]
These are the current gphoto versions on Raspbian distro. Looks like the Stable and Testing are good.

[![Raspbian Oldstable package](https://repology.org/badge/version-for-repo/raspbian_oldstable/gphoto2.svg)](https://repology.org/project/gphoto2/versions)[![Raspbian Stable package](https://repology.org/badge/version-for-repo/raspbian_stable/gphoto2.svg)](https://repology.org/project/gphoto2/versions)[![Raspbian Testing package](https://repology.org/badge/version-for-repo/raspbian_testing/gphoto2.svg)](https://repology.org/project/gphoto2/versions)

This ticket can be closed
