### ISSUE TITLE
[Featrure Request] --list-all-config should also include accesibility (read-only/readwrite)

### ISSUE THREAD

**Issue by SarenT** [gphoto/gphoto2#75]
Hi,

Currently, I am parsing the outputs of gphoto2 --list-all-config and --summary get the config list. --summary includes some of the configs with accessibility information, whereas --list-all-config includes detailed information of all configs without accessibility.
It would be great to include accessibility in --list-all-config for clean parsing without messy cross-ref.

I will have a look into the code to figure out this. But I am not very proficient in C/C++.

Best,
Saren

**Comment by SarenT** [comment]
I have solved the issue for my self by changing actions.c file and adding relevant lines. I would like to submit it. I have read HACKING file. I don't see any conflict other than the different --list-all-config output. Although, this may be an issue for other people parsing this text, if they did wisely, this should not be necessarily a compatibility issue. Additionally, the new line "Readonly: x" can be useful for everybody.
e.g.:

> Label: Active Pic Ctrl Item
> **Readonly: 0**
> Type: MENU
> Current: 1
> Choice: 0 1
> Choice: 1 2
> Choice: 2 3
> Choice: 3 4
> Choice: 4 5
> Choice: 5 6
> /main/other/d201
> Label: Change Pic Ctrl Item
> **Readonly: 1**
> Type: MENU
> Current: 0

Where should I submit this new code? git? svn? (I have downloaded the source code from sourceforge).

**Comment by msmeissn** [comment]
a github pull request against this project here would be welcome, but if this is too compilcated you can also attach your patch here

**Comment by SarenT** [comment]
I am new to git and github. So I forked, then pushed it to my branch. After that, I tried to send a push request. I hope it worked.

**Comment by msmeissn** [comment]
looks good, I merged it
