### ISSUE TITLE
Unspecified Error in io-library

### ISSUE THREAD

**Issue by 0io** [gphoto/gphoto2#79]
Hi. I have been using gphoto2 in combination with sony-pm-alt to wirelessly copy files from my Sony A6000 for about 6 months, but it suddenly stopped working. I tried compiling and installing libgphoto2 and gphoto2 2.5.14 from the Github repos, but it still has the same error:

```
0.468776 ptp_ptpip_init_command_request(3): ptpip/init_cmd data: (hexdump of 60 bytes)
0000  3c 00 00 00 01 00 00 00-35 66 ae 98 b2 f2 66 1b  <.......5f....f.
0010  57 25 e7 5d 53 60 66 a9-4d 00 65 00 72 00 63 00  W%.]S`f.M.e.r.c.
0020  75 00 72 00 79 00 2e 00-30 00 69 00 6f 00 2e 00  u.r.y...0.i.o...
0030  6f 00 72 00 67 00 00 00-00 00 01 00              o.r.g.......

0.468821 ptp_ptpip_init_command_request [ptpip.c:472](0): return 60 / len 60
0.471921 ptp_ptpip_generic_read      (3): ptpip/generic_read header: (hexdump of 8 bytes)
0000  0c 00 00 00 05 00 00 00-                         ........

0.471936 ptp_ptpip_generic_read      (3): ptpip/generic_read data: (hexdump of 4 bytes)
0000  01 00 00 00            -                         ....

0.471942 ptp_ptpip_init_command_ack [ptpip.c:497](0): bad type returned 5
0.471978 camera_init [library.c:7995](0): Failed to connect.
0.471985 gp_port_close               (2): Closing port...
0.472107 gp_context_error            (0): An error occurred in the io-library ('Unspecified error'): No error description available

*** Error ***
An error occurred in the io-library ('Unspecified error'): No error description available
*** Error (-1: 'Unspecified error') ***

```
Full debug output attached.

Since I don't know where it's getting ptpip.c from, I'm not sure where to start troubleshooting this. It could be a recent update, as I regularly do updates to my Ubuntu 14.04 box. Any suggestions? Thanks,

Jonathan
[gphoto2debug.txt](https://github.com/gphoto/gphoto2/files/1089187/gphoto2debug.txt)

**Comment by msmeissn** [comment]
The connection was not accepted by the camera. this might mean the UUID is not correct/ has changed.

ptpip.c is from libgphoto2 , camlibs/ptp2/ 

Basically the code is  working fine here, just the camera side does not like us anymore and does not want us to connect.

Did your hostname cjhange? or something with the camera?

**Comment by luzpaz** [comment]
@0io did this issue get resolved for you ?

**Comment by msmeissn** [comment]
long time without reaction
