### ISSUE TITLE
Interval Capturing Lags Behind

### ISSUE THREAD

**Issue by huaruiwu** [gphoto/gphoto2#8]
I've been trying to use interval of 1s to capture images on a nikon camera. If I use the camera's internal interval capturing, it can take images every second with no problems. However, with gphoto2, the capturing would lag behind sometimes to as much as 2s intervals. Where do you think this delay is coming from, and would it be difficult to speed it up?

**Comment by msmeissn** [comment]
is it downloading images? is the image format capt000x.jpg?

if yes, switch the capturetarget to card, this will leave the pictures on the card.

in sdram mode, the images are always downloaded, and that takes around 2 seconds.

**Comment by msmeissn** [comment]
no reply , if still an issue, reopen
