### ISSUE TITLE
Canon EOS M3 "does not suppot generic capture"

### ISSUE THREAD

**Issue by samedmonds** [gphoto/gphoto2#84]
Hi,
Despite updating to the latest release, it would appear that my Canon M3 is still unsupported. Any ideas as to what the problem might be?

I'm connecting my M3 to a RaspberryPi and executing gphoto commands via ssh.

Please see below for a screenshot of the error message when attempting to auto detect.

<img width="622" alt="screen shot 2017-07-15 at 1 19 44 pm" src="https://user-images.githubusercontent.com/29719179/28236165-02aaf760-6962-11e7-8415-2baf5bf35d0a.png">
<img width="540" alt="screen shot 2017-07-15 at 1 20 24 pm" src="https://user-images.githubusercontent.com/29719179/28236166-02b5e42c-6962-11e7-8d85-a661fa95e521.png">

**Comment by msmeissn** [comment]
what does   gphoto2 --version   report?

**Comment by msmeissn** [comment]
The EOS M support is new in libgphoto 2.5.14 , which is quite fresh.

**Comment by samedmonds** [comment]
![screen shot 2017-07-15 at 5 46 30 pm](https://user-images.githubusercontent.com/29719179/28237564-a7901292-6985-11e7-923c-91ce862647a8.png)

**Comment by msmeissn** [comment]
it needs libgphoto2 2.5.14
