### ISSUE TITLE
How keep my RAW file in camera's card ?

### ISSUE THREAD

**Issue by thymon13** [gphoto/gphoto2#90]
Hi all,

I've tested like this :

`gphoto2  --capture-image-and-download --keep-raw`
( tested with raspberry & Canon 7D RAW+JPEG).

JPEG added on my raspberry
But nothing keep on my camera's card. 

Thx in advance !

(sorry for my english)

**Comment by msmeissn** [comment]
You probably have "SDRAM" capture enabled. Change it to CARD capture via 

gphoto2 --set-config capturetarget=1

**Comment by thymon13** [comment]
Yes !
Perfect :) Thank's a lot.

**Comment by zahu69** [comment]
Hello
I have the same Problem with my Sony A99. I can only remote control the Camera when i make the setting in the menue "USB-Connection=PC-Remotecontrol". In this case the raspberry PI, from where i send the command gphoto2 --capture-image-and-donwload, downloads the jpg and the arw - file. capt0000.jpg and capt0000.arw. When i send the command the second time, then it ovwerwrite both of the files again with capt0000.jpg and capt0000.arw. the next problem When i send only the command --capture-image, then it says, that the Pictures are stored on the camera. But when i remove the SD-Card, the Card ist empty. This ist i think the reason that the command --Keep-Raw does not work with my camera. I found this thread, and hoped, that the command "gphoto2 --set-config capturetarget=1" would be the solutioon too for my Problem. But my A99 does not have the Parameter capturetarget. Does any Person has a hint for my, what kann i do, that it works with my camera too?
Many thanks at all! :-) zahu69
