### ISSUE TITLE
fix cross compilation - patch

### ISSUE THREAD

**Issue by hpfn** [gphoto/gphoto2#93]
Hi,

I received a patch[0] to "fix cross compilation" (Debian). Here is
what the author[1] says:

"gphoto2 fails to cross build from source, because it uses the build
architecture pkg-config when the host architecture one is needed. The
cause is on the GP_PKG_CONFIG macro, which fails to consider
$ac_tool_prefix. The upstream macro PKG_PROG_PKG_CONFIG does a better
job at solving the same problem and simply replacing the failing macro
fixes the cross build. Please consider applying the attached patch after
stretch is released."

[0] - https://anonscm.debian.org/cgit/pkg-phototools/gphoto2.git/commit/?id=b1ea49fbb1f23c4f8aa2249eb4b762ba1c3bda08
[1] - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=858097

The patch was applied ten days ago. Do you want to take a look at it?

Regards,
Herbert

**Comment by msmeissn** [comment]
I merged it into gphoto-m4 and gphoto2, thaanks!

i also merged the 00-support_now_timevalue.patch
