### ISSUE TITLE
OpenWRT drivers

### ISSUE THREAD

**Issue by nah0y** [gphoto/gphoto2#94]
Hello!

I installed gphoto2 on an OpenWRT device, using opkg install gphoto2, which has installed everything required to run gphoto2. But there was no driver at all, so no camera was recognized...

So I searched a little bit, and found out that I can install them manually from here: http://downloads.openwrt.org/snapshots/trunk/ar71xx/generic/packages/packages/

But there's a LOT of drivers (files starting with libgphoto2-drivers-X).
I'm currently using a Canon so I only had to download:
- libgphoto2-drivers-canon_2.5.14-2_ar71xx.ipk	
- libgphoto2-drivers-ptp2_2.5.14-2_ar71xx.ipk
to make things work.

But if I want to have something that works with every camera, should I install ALL the drivers? (there's more than 50 files I think...).

Thanks for the FANTASTIC tool!

**Comment by msmeissn** [comment]
canon and ptp2 will cover almost all remote controllable current cameras. You should also throw in pentax and sierra, then it would cover I think all serious (not toy) ones from the last years.

**Comment by nah0y** [comment]
Thanks for the answer!
- Canon also includes the Nikon ones?
- What about Sony?
- Finally, usually when we compile gphoto2, or install it on a Linux system via apt-get install gphoto2, does that automatically install ALL the drivers?

**Comment by msmeissn** [comment]
The ptp2 driver covers: current Canon, Nikon, Sony SLT/Alpha and also some Fuji cameras.  
The canon driver covers very old canon (canon moved to implement PTP).

**Comment by nah0y** [comment]
Oh okay!
Thanks for the answer :)

Well, if I execute --list-cameras, it would return the list of supported cameras based on the drivers I installed right?

**Comment by msmeissn** [comment]
yes, it will list all the cameras in the drivers installed

**Comment by nah0y** [comment]
Perfect!
Final question, is there an "easy" way to see what are the cameras supported by each driver?

For example, if someone is telling me it's not recognised, I could just search for the driver that support it, and add it.

**Comment by msmeissn** [comment]
hmm, I had hoped the website would list the the driver on http://gphoto.org/proj/libgphoto2/support.php , but it currently does not.

**Comment by nah0y** [comment]
Hehe no problem, thanks for all the answers!
