### ISSUE TITLE
"No camera found." when X-server is running, log included, root works

### ISSUE THREAD

**Issue by trashbytes** [gphoto/gphoto2#99]
Hi!

I am currently developing a photo booth with a Raspberry Pi and gphoto2. I have one big problem, however:

As long as the x-server (xinit) is running gphoto2 won't find a camera even though lsusb still lists the cam.
When the x-server is closed everything works perfectly fine.

I am using Debian Jessie.

Log WITHOUT X running: https://pastebin.com/J05yV6Dk
Log WITH X running: https://pastebin.com/5LPDLAm3

**Comment by trashbytes** [comment]
I solved it by adding a new rule to udev following this tip: https://stackoverflow.com/a/22723445

**Comment by msmeissn** [comment]
packages should contain such udev or hwdb rules already. If you are using a distribution package, report this as bug.

**Comment by trashbytes** [comment]
I think compiled gphoto2 myself. I use barebones Debian without any "bloat" whatsoever so I stumble upon missing things here and there every once in a while. So it may not even be a bug, just something I missed because I didn't know about it.

Thank you!
